/*
# Add Washington Food Banks in Smaller Communities

1. Data Insert
- Adds food banks in Grant County (Moses Lake, Ephrata, Quincy, Mattawa, Royal
  City, Othello, Soap Lake) and Tri-Cities (Kennewick, Benton City).
2. Source
- Verified via Big Bend Community College local food bank list, MLCHC food bank
  flyer, and Tri-Cities Food Bank website.
3. Notes
- All food banks cost_free=true.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Moses Lake Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community Services of Moses Lake food bank providing emergency supplemental food weekly for individuals and families in need. Never charges for food.', '9299 Beacon Rd NE', 'Moses Lake', 'Grant', 'WA', '98837', '509-765-8101', 'https://www.mlfood.org', '{"mon":"11:00-14:45","tue":"11:00-14:45","wed":"11:00-14:45","thu":"11:00-14:45","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Weekly Groceries}', '{Food Bank}', '{General Public,Low-Income,Homeless}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Ephrata Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank in Ephrata providing emergency food assistance to individuals and families in need in the Ephrata area.', '1010 A St SE', 'Ephrata', 'Grant', 'WA', '98823', '509-754-5772', 'https://granthealth.org', '{"mon":"14:00-16:00","tue":"Closed","wed":"Closed","thu":"14:00-16:00","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{General Public,Low-Income}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Quincy Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank in Quincy providing emergency food assistance to individuals and families in need in the Quincy area.', '210 1st Ave SE', 'Quincy', 'Grant', 'WA', '98848', '509-787-7963', 'https://granthealth.org', '{"mon":"Closed","tue":"9:30-12:00,16:30-18:00","wed":"Closed","thu":"Closed","fri":"9:30-12:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{General Public,Low-Income}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mattawa Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank in Mattawa serving the Wahluke area; open the 2nd and 4th Saturday of each month.', '23898 Rd 26.2', 'Mattawa', 'Grant', 'WA', '99349', '509-832-2331', 'https://granthealth.org', '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"Closed","fri":"Closed","sat":"13:00-16:00","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{General Public,Low-Income,Farmworkers}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Royal City Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank in Royal City providing emergency food assistance to individuals and families in the Royal Slope area.', '229 Balsam St NW', 'Royal City', 'Grant', 'WA', '99357', '509-346-2679', 'https://granthealth.org', '{"mon":"Closed","tue":"12:30-15:00","wed":"Closed","thu":"Closed","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{General Public,Low-Income,Farmworkers}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Othello Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank in Othello providing emergency food assistance to individuals and families in the Othello area.', '949 E Main St', 'Othello', 'Adams', 'WA', '99344', '509-488-6044', 'https://granthealth.org', '{"mon":"13:00-15:00","tue":"13:00-15:00","wed":"13:00-15:00","thu":"Closed","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{General Public,Low-Income,Farmworkers}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Soap Lake Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank in Soap Lake providing emergency food assistance to individuals and families in need in the Soap Lake area.', '325 Main Ave E', 'Soap Lake', 'Grant', 'WA', '98851', '509-246-0164', 'https://granthealth.org', '{"mon":"Closed","tue":"10:00-15:30","wed":"Closed","thu":"Closed","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{General Public,Low-Income}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Tri-Cities Food Bank - Kennewick', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Tri-Cities Food Bank Kennewick branch providing emergency groceries to individuals and families in need. Photo ID and proof of address requested; clients may visit every 14 days.', '424 W Deschutes Ave', 'Kennewick', 'Benton', 'WA', '99336', '509-547-9167', 'https://tcfoodbank.com', '{"mon":"9:00-11:30","tue":"9:00-11:30","wed":"9:00-11:30","thu":"9:00-11:30","fri":"9:00-11:30","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Groceries}', '{Food Bank}', '{General Public,Low-Income,Homeless}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Tri-Cities Food Bank - Benton City', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Tri-Cities Food Bank branch in Benton City providing emergency groceries to individuals and families in need in the Benton City area.', '712 N 10th St', 'Benton City', 'Benton', 'WA', '99320', '509-588-5454', 'https://tcfoodbank.com', '{"mon":"Closed","tue":"Closed","wed":"10:30-12:30","thu":"12:00-14:00,18:00-20:00","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Groceries}', '{Food Bank}', '{General Public,Low-Income}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Yakima Rotary Food Bank - Union Gospel Mission', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Union Gospel Mission Yakima food bank serving Yakima County individuals and families. Operates a large food distribution and meal program for people in need.', '8 South 6th Ave', 'Yakima', 'Yakima', 'WA', '98902', '509-575-3719', 'https://www.yakimauniongospel.org', '{"mon":"9:00-15:00","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"9:00-15:00","sat":"9:00-12:00","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Meal Program}', '{Food Bank}', '{General Public,Low-Income,Homeless}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;