/*
# Add More Washington Tribal Health Clinics (Batch 2)

1. Data Insert
- Adds Nisqually, Stillaguamish, and Port Gamble S'Klallam tribal health clinics.
2. Source
- Verified via tribe websites and HelpMeGrowWA listings.
3. Notes
- Tribal FQHCs; medicaid=true, sliding_scale=true.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Nisqually Health Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Nisqually Tribe Indian Health Service clinic providing family medicine, behavioral health, substance use counseling, dental and pharmacy services for tribal members and the community.', '4816 She-Nah-Num Dr SE', 'Olympia', 'Thurston', 'WA', '98513', '360-459-5312', 'https://www.nisqually-nsn.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Behavioral Health,Substance Use,Dental,Pharmacy}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Stillaguamish Tribal Health Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Stillaguamish Tribe wellness clinic providing medical, behavioral health, substance use treatment (MOUD), massage therapy and dental services.', '24205 James Dorsey Way, Ste A', 'Arlington', 'Snohomish', 'WA', '98223', '360-652-7362', 'https://www.stillaguamish.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Behavioral Health,Substance Use,Dental,Massage}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Port Gamble S Klallam Community Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Port Gamble S Klallam Tribe community health center providing primary care, pediatrics, women''s health, dental, behavioral health, pharmacy, chiropractic and acupuncture services.', '31912 Little Boston Rd NE', 'Kingston', 'Kitsap', 'WA', '98346', '360-297-2840', 'https://pgst.nsn.us/health-services', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Pediatrics,Womens Health,Dental,Behavioral Health,Pharmacy,Chiropractic,Acupuncture}', '{Tribal Health,Family Medicine,Pediatrics}', '{Tribal Members,Native Americans,Families}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;