-- Add additional mental health, crisis, and rural transportation services
INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  data.category_id,
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Additional Rural Mental Health Providers
  ('Cottage Grove Community Mental Health', (SELECT id FROM resource_categories WHERE slug = 'mental-health'), 'Outpatient Mental Health', 'Outpatient mental health services serving Chelan County.', '601 N Wenatchee Ave', 'Wenatchee', 'Chelan', '98801', '(509) 662-6765', 'https://www.cottagegrovemh.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatric Care', 'Case Management'], ARRAY['mental health', 'therapy', 'counseling', 'Wenatchee', 'Chelan County'], 'Cottage Grove Community Mental Health Wenatchee therapy counseling Chelan', 47.4321, -120.3214),
  ('North Central Behavioral Health - Omak', (SELECT id FROM resource_categories WHERE slug = 'mental-health'), 'Outpatient Mental Health', 'Mental health services for Okanogan County residents.', '624 N Main St', 'Omak', 'Okanogan', '98841', '(509) 826-4641', 'https://www.northcentralbh.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatric Care', 'Substance Abuse', 'Case Management'], ARRAY['mental health', 'therapy', 'Omak', 'Okanogan County', 'substance abuse'], 'North Central Behavioral Health Omak mental health therapy Okanogan County', 48.4184, -119.5471),
  ('Cascadia Behavioral Health - Moses Lake', (SELECT id FROM resource_categories WHERE slug = 'mental-health'), 'Outpatient Mental Health', 'Mental health and substance use services for Grant County.', '925 E Plaza Dr', 'Moses Lake', 'Grant', '98837', '(509) 764-6640', 'https://www.cascadiabh.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatric Care', 'Substance Abuse'], ARRAY['mental health', 'therapy', 'substance abuse', 'Moses Lake', 'Grant County'], 'Cascadia Behavioral Health Moses Lake mental health therapy Grant County', 47.1216, -119.2803),
  ('Peninsula Mental Health Services - Port Angeles', (SELECT id FROM resource_categories WHERE slug = 'mental-health'), 'Outpatient Mental Health', 'Outpatient mental health services for Clallam County.', '126 N Laurel St', 'Port Angeles', 'Clallam', '98362', '(360) 452-3875', 'https://www.peninsulamentalhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Individual Therapy', 'Family Therapy', 'Psychiatric Care', 'Substance Abuse'], ARRAY['mental health', 'therapy', 'Port Angeles', 'Clallam County', 'Olympic Peninsula'], 'Peninsula Mental Health Port Angeles therapy counseling Clallam County', 48.1153, -123.4298),
  ('Lower Columbia Community Action - Longview Mental Health', (SELECT id FROM resource_categories WHERE slug = 'mental-health'), 'Outpatient Mental Health', 'Mental health services for Cowlitz County.', '1857 Olympia Way', 'Longview', 'Cowlitz', '98632', '(360) 425-3460', 'https://www.lowercolumbia.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Crisis Intervention', 'Case Management'], ARRAY['mental health', 'therapy', 'Longview', 'Cowlitz County', 'crisis'], 'Lower Columbia Community Action Longview mental health therapy Cowlitz', 46.1345, -122.9402),
  -- Peer Support and Recovery Services
  ('Peer Kent - Peer Support Center', (SELECT id FROM resource_categories WHERE slug = 'mental-health'), 'Peer Support', 'Peer support and recovery services for mental health consumers.', '603 Stewart St Suite 202', 'Kent', 'King', '98030', '(253) 856-5241', 'https://www.peerkent.org', '{"monday": "10am-6pm", "tuesday": "10am-6pm", "wednesday": "10am-6pm", "thursday": "10am-6pm", "friday": "10am-4pm"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Peer Support', 'Recovery Support', 'Social Activities', 'Advocacy'], ARRAY['peer support', 'mental health recovery', 'Kent', 'consumer run', 'support groups'], 'Peer Kent peer support mental health recovery services support groups', 47.3892, -122.2327),
  ('Recovery Cafe - Seattle', (SELECT id FROM resource_categories WHERE slug = 'substance-use'), 'Recovery Support', 'Peer support community for people in recovery from mental health and substance use.', '2022 Boren Ave', 'Seattle', 'King', '98121', '(206) 373-9680', 'https://www.recoverycafe.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English'], ARRAY['Peer Support', 'Recovery Support', 'Meals', 'Resource Navigation'], ARRAY['recovery support', 'peer support', 'mental health', 'substance abuse', 'Seattle'], 'Recovery Cafe Seattle peer support recovery mental health substance abuse', 47.6160, -122.3194),
  ('Friends of Youth - Recovery Services', (SELECT id FROM resource_categories WHERE slug = 'substance-use'), 'Adolescent Treatment', 'Substance use treatment for adolescents and young adults.', '1312 NW Gilman Blvd', 'Issaquah', 'King', '98027', '(425) 392-6367', 'https://www.friendsofyouth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Adolescent Treatment', 'Outpatient Counseling', 'Family Therapy', 'Case Management'], ARRAY['substance abuse', 'adolescent treatment', 'Issaquah', 'young adult', 'teen'], 'Friends of Youth adolescent substance use treatment Issaquah teen recovery', 47.5434, -122.0651),
  -- Additional Crisis Lines
  ('King County Crisis Line', (SELECT id FROM resource_categories WHERE slug = 'crisis'), 'Crisis Hotline', '24/7 crisis support and suicide prevention for King County residents.', '3000 14th Ave S', 'Seattle', 'King', '98144', '(206) 461-3222', 'https://www.crisisconnections.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, false, false, false, true, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Crisis Support', 'Suicide Prevention', 'Mental Health Crisis', 'Referral'], ARRAY['crisis line', 'suicide prevention', '24/7', 'Seattle', 'King County', 'mental health crisis'], 'King County Crisis Line suicide prevention 24/7 mental health crisis Seattle', 47.5813, -122.3194),
  ('Snohomish County Crisis Line', (SELECT id FROM resource_categories WHERE slug = 'crisis'), 'Crisis Hotline', '24/7 crisis support hotline for Snohomish County.', '2601 Wetmore Ave', 'Everett', 'Snohomish', '98201', '(425) 258-4357', 'https://www.voaww.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, false, false, false, true, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Crisis Support', 'Suicide Prevention', 'Mental Health Crisis', 'Referral'], ARRAY['crisis line', 'suicide prevention', '24/7', 'Everett', 'Snohomish County'], 'Snohomish County Crisis Line suicide prevention 24/7 mental health crisis Everett', 47.9812, -122.2003),
  ('Okanogan County Crisis Line', (SELECT id FROM resource_categories WHERE slug = 'crisis'), 'Crisis Hotline', '24/7 crisis intervention for Okanogan County residents.', '624 N Main St', 'Omak', 'Okanogan', '98841', '(509) 422-5454', 'https://www.northcentralbh.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, false, false, false, true, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Crisis Support', 'Suicide Prevention', 'Mobile Crisis'], ARRAY['crisis line', 'suicide prevention', '24/7', 'Omak', 'Okanogan County'], 'Okanogan County Crisis Line suicide prevention 24/7 mental health crisis Omak', 48.4184, -119.5471),
  -- Transportation Services - Rural
  ('Grant County Transportation', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'Public Transit', 'Public transportation and paratransit for Grant County.', '100 W Broadway Ave', 'Moses Lake', 'Grant', '98837', '(509) 764-5787', 'https://www.granttransit.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, false, false, true, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Public Transit', 'Paratransit', 'Senior Transportation'], ARRAY['transportation', 'bus', 'paratransit', 'Moses Lake', 'Grant County', 'senior'], 'Grant County Transportation public transit paratransit Moses Lake senior', 47.1210, -119.2833),
  ('People for People Transportation - Ellensburg', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'Rural Transit', 'Transportation services for rural Kittitas County.', '110 E 3rd Ave', 'Ellensburg', 'Kittitas', '98926', '(509) 933-9900', 'https://www.peopleforpeoplewa.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-6pm"}'::jsonb, true, false, false, false, false, true, true, false, false, ARRAY['English'], ARRAY['Rural Transit', 'Senior Transportation', 'Medical Transportation'], ARRAY['transportation', 'rural transit', 'medical transportation', 'Ellensburg', 'Kittitas County', 'senior'], 'People for People Transportation rural transit Ellensburg Kittitas senior medical', 46.9970, -120.5462),
  ('Kitsap Transit', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'Public Transit', 'Public transportation including bus and ferry services for Kitsap County.', '300 Washington Ave', 'Bremerton', 'Kitsap', '98337', '(360) 479-4500', 'https://www.kitsaptransit.com', '{"monday": "5am-10pm", "tuesday": "5am-10pm", "wednesday": "5am-10pm", "thursday": "5am-10pm", "friday": "5am-10pm", "saturday": "6am-8pm", "sunday": "7am-8pm"}'::jsonb, true, false, false, false, false, true, true, false, false, ARRAY['English'], ARRAY['Public Transit', 'Paratransit', 'ACCESS', 'Ferry Service'], ARRAY['transportation', 'bus', 'paratransit', 'Bremerton', 'Kitsap County', 'ACCESS', 'ferry'], 'Kitsap Transit public transit bus ferry Bremerton Kitsap County ACCESS paratransit', 47.5640, -122.6219),
  ('Asotin County Public Transportation', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'Rural Transit', 'Dial-a-ride transit service for Asotin County.', '129 2nd St', 'Asotin', 'Asotin', '99402', '(509) 758-3936', 'https://www.asotincountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, false, false, true, true, false, false, ARRAY['English'], ARRAY['Dial-A-Ride', 'Medical Transportation', 'Senior Transportation'], ARRAY['transportation', 'dial-a-ride', 'Asotin County', 'senior', 'medical transportation'], 'Asotin County Public Transportation dial a ride Asotin senior medical transit', 46.3063, -117.0458),
  ('Southeast Washington Transportation - Dayton', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'Rural Transit', 'Transportation for Columbia, Garfield, and Whitman counties.', '350 E Main St', 'Dayton', 'Columbia', '99328', '(509) 382-2556', 'https://www.sewtransport.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, false, false, true, true, false, false, ARRAY['English'], ARRAY['Dial-A-Ride', 'Medical Transportation', 'Senior Transportation'], ARRAY['transportation', 'rural transit', 'Dayton', 'Columbia County', 'Garfield County', 'senior'], 'Southeast Washington Transportation rural transit Dayton Columbia Garfield senior', 46.3193, -117.9862),
  -- NEMT (Non-Emergency Medical Transportation)
  ('Northwest Medical Transportation', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'NEMT', 'Non-emergency medical transportation serving Washington state.', '1500 Fairview Ave E', 'Seattle', 'King', '98102', '(425) 658-2244', 'https://www.nwmedicaltrans.com', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Wheelchair Transport', 'Ambulatory Transport', 'Medical Appointments', 'Airport Medical'], ARRAY['NEMT', 'medical transportation', 'wheel chair', 'transportation', 'Seattle'], 'Northwest Medical Transportation NEMT wheelchair medical appointments Seattle', 47.6245, -122.3153),
  ('TranSouth Medical Transportation', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'NEMT', 'Non-emergency medical transportation for Southwest Washington.', '8015 NE 13th St', 'Vancouver', 'Clark', '98662', '(360) 635-8333', 'https://www.transouthmedical.com', '{"monday": "6am-8pm", "tuesday": "6am-8pm", "wednesday": "6am-8pm", "thursday": "6am-8pm", "friday": "6am-8pm"}'::jsonb, true, false, true, true, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Wheelchair Transport', 'Ambulatory Transport', 'Medical Appointments'], ARRAY['NEMT', 'medical transportation', 'wheelchair', 'Vancouver', 'Clark County'], 'TranSouth Medical Transportation NEMT wheelchair Vancouver Clark County', 45.6950, -122.5870),
  ('Eastern Washington Medical Transport - Spokane', (SELECT id FROM resource_categories WHERE slug = 'transportation'), 'NEMT', 'Non-emergency medical transportation for Eastern Washington.', '3604 N Nevada St', 'Spokane', 'Spokane', '99207', '(509) 723-3100', 'https://www.ewmedicaltrans.com', '{"monday": "6am-8pm", "tuesday": "6am-8pm", "wednesday": "6am-8pm", "thursday": "6am-8pm", "friday": "6am-8pm"}'::jsonb, true, false, true, true, false, false, true, false, false, ARRAY['English'], ARRAY['Wheelchair Transport', 'Ambulatory Transport', 'Medical Appointments'], ARRAY['NEMT', 'medical transportation', 'wheelchair', 'Spokane', 'Eastern Washington'], 'Eastern Washington Medical Transport NEMT wheelchair Spokane Eastern WA', 47.7153, -117.3782)
) AS data(name, category_id, subcategory, description, address, city, county, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, languages, services, tags, search_text, lat, lng);
