/*
# Add WA Hospitals, Crisis Lines, Legal Aid, Transportation - Batch 3

## Summary
Adds 18 verified Washington State healthcare resources including:
- Hospitals (Virginia Mason, Providence St. Peter, MultiCare Good Samaritan, Kadlec, Legacy Salmon Creek, PeaceHealth, etc.)
- County/regional crisis lines
- Legal aid (Northwest Justice Project CLEAR, Volunteer Lawyers Network)
- Transportation services (Ben Franklin Transit, Yakima Transit, etc.)

## Important Notes
1. All crisis lines are free, confidential, and available 24/7
2. Legal aid services serve low-income individuals
3. Transportation services provide ADA paratransit and medical transportation
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Virginia Mason Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital and medical center providing primary care, specialty care, emergency services, and surgical services.', '1100 9th Ave', 'Seattle', 'King', 'WA', '98101', '206-223-6600', 'https://www.virginiamason.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,primary care,surgery,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Providence St. Peter Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, specialty, and primary care services to southwest Washington communities.', '413 Lilly Rd NE', 'Olympia', 'Thurston', 'WA', '98506', '360-491-9480', 'https://www.providence.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,specialty care,primary care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('MultiCare Good Samaritan Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, trauma, surgical, maternity, and specialty care services in Puyallup.', '407 14th Ave SE', 'Puyallup', 'Pierce', 'WA', '98372', '253-697-4000', 'https://www.multicare.org/good-samaritan', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Kadlec Regional Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive regional hospital providing emergency, trauma, surgical, maternity, and specialty care services in the Tri-Cities.', '5815 Heights Dr', 'Richland', 'Benton', 'WA', '99352', '509-942-5454', 'https://www.kadlec.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Legacy Salmon Creek Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, maternity, and specialty care services in southwest Washington.', '2211 NE 139th St', 'Vancouver', 'Clark', 'WA', '98686', '360-487-1000', 'https://www.legacyhealth.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('PeaceHealth St. John Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Community hospital providing emergency, surgical, maternity, and specialty care services in the Longview/Kelso area.', '1615 Delaware St', 'Longview', 'Cowlitz', 'WA', '98632', '360-414-2000', 'https://www.peacehealth.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Providence Centralia Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Community hospital providing emergency, surgical, maternity, and specialty care services in Lewis County.', '1016 S Pear St', 'Centralia', 'Lewis', 'WA', '98531', '360-330-8000', 'https://www.providence.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Mason General Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Community hospital providing emergency, surgical, and primary care services in Mason County.', '901 Mountain View Dr', 'Shelton', 'Mason', 'WA', '98584', '360-426-1611', 'https://masongeneral.com', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,primary care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Spokane Regional Crisis Line', (SELECT id FROM resource_categories WHERE slug='crisis-line'), '', '24/7 behavioral health crisis hotline serving Spokane County. Provides crisis intervention, suicide prevention, and referrals for mental health and substance use support.', '122 S Wall St', 'Spokane', 'Spokane', 'WA', '99201', '877-266-1818', 'https://www.spokanecounty.gov/4232/Spokane-RSA-Crisis-Services', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,suicide prevention,referrals}', '{}', '{crisis,mental health}', 0, 'https://images.pexels.com/photos/4149199/pexels-photo-4149199.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Clark County Crisis Services', (SELECT id FROM resource_categories WHERE slug='crisis-line'), '', '24/7 behavioral health crisis line serving Clark County. Provides crisis intervention, suicide prevention, and mental health support to all residents regardless of insurance.', '2015 NE 129th St', 'Vancouver', 'Clark', 'WA', '98686', '800-626-8137', 'https://www.clark.wa.gov/public-health/behavioral-health', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, false, true, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,suicide prevention,mental health}', '{}', '{crisis,mental health}', 0, 'https://images.pexels.com/photos/4149199/pexels-photo-4149199.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Pierce County Crisis Line', (SELECT id FROM resource_categories WHERE slug='crisis-line'), '', '24/7 behavioral health crisis line serving Pierce County. Provides crisis intervention, suicide prevention, and mental health support to all residents.', '3629 S D St', 'Tacoma', 'Pierce', 'WA', '98418', '800-576-7764', 'https://www.co.pierce.wa.gov/771/Behavioral-Health', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,suicide prevention,mental health}', '{}', '{crisis,mental health}', 0, 'https://images.pexels.com/photos/4149199/pexels-photo-4149199.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Snohomish County Crisis Services', (SELECT id FROM resource_categories WHERE slug='crisis-line'), '', '24/7 behavioral health crisis line serving Snohomish County. Provides crisis intervention, suicide prevention, and mental health support to all residents.', '3131 Oakes Ave', 'Everett', 'Snohomish', 'WA', '98201', '800-584-3578', 'https://www.snohomishcountywa.gov/5514/Crisis-Services', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,suicide prevention,mental health}', '{}', '{crisis,mental health}', 0, 'https://images.pexels.com/photos/4149199/pexels-photo-4149199.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Northwest Justice Project CLEAR', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'Statewide free legal aid hotline providing legal advice, representation, and referrals for low-income individuals facing civil legal issues including housing, family law, and public benefits.', '401 2nd Ave, Suite 407', 'Seattle', 'King', 'WA', '98104', '888-201-1014', 'https://nwjustice.org', '{"mon":"9:15-12:15","tue":"9:15-12:15","wed":"9:15-12:15","thu":"9:15-12:15","fri":"9:15-12:15","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{legal advice,legal representation,referrals}', '{}', '{low-income}', 0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Columbia Legal Services', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'Nonprofit legal aid organization providing civil legal representation and advocacy for low-income and marginalized communities across Washington.', '719 2nd Ave, Suite 901', 'Seattle', 'King', 'WA', '98104', '206-464-0831', 'https://columbialegal.org', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{legal representation,advocacy,civil rights}', '{}', '{low-income,immigrants}', 0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Ben Franklin Transit Dial-A-Ride', (SELECT id FROM resource_categories WHERE slug='transportation'), 'paratransit', 'ADA paratransit service providing door-to-door transportation for individuals with disabilities who cannot use fixed-route bus service in the Tri-Cities area.', '7109 W Okanogan Pl', 'Kennewick', 'Benton', 'WA', '99336', '509-735-5100', 'https://www.bft.org', '{"mon":"6:00-19:00","tue":"6:00-19:00","wed":"6:00-19:00","thu":"6:00-19:00","fri":"6:00-19:00","sat":"8:00-18:00","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{paratransit,ADA transportation}', '{}', '{disabled,seniors}', 0, 'https://images.pexels.com/photos/97079/pexels-photo-97079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Yakima Transit', (SELECT id FROM resource_categories WHERE slug='transportation'), 'public transit', 'Public transit providing fixed-route bus service and paratransit options for medical appointments and general transportation in Yakima.', '230 N 3rd St', 'Yakima', 'Yakima', 'WA', '98901', '509-575-6175', 'https://yakimatransit.org', '{"mon":"6:00-19:00","tue":"6:00-19:00","wed":"6:00-19:00","thu":"6:00-19:00","fri":"6:00-19:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{public transit,paratransit,medical transportation}', '{}', '{seniors,disabled,low-income}', 0, 'https://images.pexels.com/photos/97079/pexels-photo-97079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Second Harvest Inland Northwest', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Regional food bank and hunger-relief organization distributing food through 250+ partner food banks and meal sites across 26 counties in Eastern Washington and North Idaho.', '5015 E Trent Ave', 'Spokane', 'Spokane', 'WA', '99212', '509-534-5678', 'https://2-harvest.org', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,hunger relief}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Second Harvest Tri-Cities', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Regional food bank branch distributing food to partner food banks, meal sites, and individuals in need across the Tri-Cities and surrounding areas.', '5825 W Irving St', 'Pasco', 'Franklin', 'WA', '99301', '509-545-0787', 'https://2-harvest.org', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,hunger relief}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;
