/*
# Add WIC (Women, Infants & Children) Nutrition Program Clinics

1. Data Insert
- Adds WIC program clinic sites across WA: Grant County (Moses Lake, Quincy,
  Ephrata, Warden, Mattawa), Yakima Valley (Granger, Toppenish, Sunnyside),
  and Pierce County (Mary Bridge WIC sites: Bonney Lake, Eatonville, Gig
  Harbor, Spanaway, Tacoma East).
2. Source
- Verified via Moses Lake Community Health Center, Yakima Valley Farm Workers
  Clinic, and Mary Bridge Children's WIC program websites.
3. Notes
- WIC is a free nutrition program. cost_free=true. community-org category.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Moses Lake Community Health Center - WIC (Moses Lake)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'WIC nutrition program at Moses Lake Community Health Center providing healthy food, nutrition education, breastfeeding support and referrals for pregnant women, new moms, infants and children under 5.', '605 S Coolidge St', 'Moses Lake', 'Grant', 'WA', '98837', '509-766-9815', 'https://www.mlchc.org/service/women-infant-and-children-wic-nutrition', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Moses Lake Community Health Center - WIC (Quincy)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'WIC nutrition program satellite office in Quincy providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children in the Quincy area.', '203 N Quincy Ave', 'Quincy', 'Grant', 'WA', '98848', '509-787-1796', 'https://www.mlchc.org/service/women-infant-and-children-wic-nutrition', '{"mon":"8:30-17:30","tue":"8:30-17:30","wed":"8:30-17:30","thu":"8:30-17:30","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Moses Lake Community Health Center - WIC (Ephrata)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'WIC nutrition program satellite office at Ephrata Community Dental Clinic providing healthy food, nutrition education, and breastfeeding support for Grant County families.', '457 1st Ave NW', 'Ephrata', 'Grant', 'WA', '98823', '509-760-1486', 'https://www.mlchc.org/service/women-infant-and-children-wic-nutrition', '{"mon":"8:00-17:00","tue":"Closed","wed":"8:00-17:00","thu":"Closed","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Moses Lake Community Health Center - WIC (Warden)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'WIC nutrition program satellite office in Warden providing healthy food assistance, nutrition education, breastfeeding support and referrals for southern Grant County families.', '200 S Main St', 'Warden', 'Grant', 'WA', '98857', '509-349-7311', 'https://www.mlchc.org/location/warden-wic', '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"8:30-16:30","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Yakima Valley Farm Workers Clinic - WIC (Yakima)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'YVFWC WIC program providing healthy food, nutrition education, breastfeeding support, and referrals for women, infants, and children under 5 in the Yakima area.', '602 E Nob Hill Blvd', 'Yakima', 'Yakima', 'WA', '98901', '855-942-4622', 'https://www.yvfwc.com/wic/washington', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish,Native languages}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Yakima Valley Farm Workers Clinic - WIC (Toppenish)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'YVFWC WIC program in Toppenish providing healthy food, nutrition education, breastfeeding support, and referrals for Lower Valley women, infants, and children.', '510 W 1st Ave', 'Toppenish', 'Yakima', 'WA', '98948', '509-865-6677', 'https://www.yvfwc.com/wic/washington', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish,Native languages}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Yakima Valley Farm Workers Clinic - WIC (Granger)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'YVFWC WIC program in Granger providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children in the Granger area.', '121 Sunnyside Ave, Ste A', 'Granger', 'Yakima', 'WA', '98932', '509-854-1069', 'https://www.yvfwc.com/wic/washington', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Yakima Neighborhood Health Services - WIC (Sunnyside)', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'YNHS WIC program in Sunnyside providing nutrition education, healthy food assistance, breastfeeding support and referrals for women, infants, and children under 5 in the Lower Yakima Valley.', '617 Scoon Rd', 'Sunnyside', 'Yakima', 'WA', '98944', '509-837-8200', 'https://ynhs.org', '{"mon":"8:00-18:30","tue":"8:00-18:30","wed":"8:00-18:30","thu":"8:00-18:30","fri":"8:00-18:30","sat":"8:00-13:00","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mary Bridge Children''s WIC - Tacoma East', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'Mary Bridge Children''s WIC program site in east Tacoma providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children under 5 in Pierce County.', '248 S Yakima Ave', 'Tacoma', 'Pierce', 'WA', '98404', '253-403-1507', 'https://www.marybridge.org/patients-visitors/patient-family-support-services/wic-nutrition-services', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish,Korean,Russian,Vietnamese}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mary Bridge Children''s WIC - Spanaway', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'Mary Bridge Children''s WIC program site in Spanaway providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children under 5 in central Pierce County.', '264 Pacific Ave S', 'Spanaway', 'Pierce', 'WA', '98387', '253-403-1507', 'https://www.marybridge.org/patients-visitors/patient-family-support-services/wic-nutrition-services', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mary Bridge Children''s WIC - Gig Harbor', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'Mary Bridge Children''s WIC program site in Gig Harbor providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children under 5 on the Key Peninsula.', '4417 Point Fosdick Dr NW, Ste 220', 'Gig Harbor', 'Pierce', 'WA', '98335', '253-403-1507', 'https://www.marybridge.org/patients-visitors/patient-family-support-services/wic-nutrition-services', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mary Bridge Children''s WIC - Eatonville', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'Mary Bridge Children''s WIC program site in Eatonville providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children in eastern Pierce County / Mt Rainier foothills.', '305 Center St E', 'Eatonville', 'Pierce', 'WA', '98328', '253-403-1507', 'https://www.marybridge.org/patients-visitors/patient-family-support-services/wic-nutrition-services', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mary Bridge Children''s WIC - Bonney Lake', (SELECT id FROM resource_categories WHERE slug='community-org'), 'WIC', 'Mary Bridge Children''s WIC program site in Bonney Lake providing healthy food, nutrition education, breastfeeding support and referrals for women, infants and children under 5 in eastern Pierce County.', '10120 State Route 410 E, Ste 101', 'Bonney Lake', 'Pierce', 'WA', '98391', '253-403-1507', 'https://www.marybridge.org/patients-visitors/patient-family-support-services/wic-nutrition-services', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Nutrition Education,Healthy Food Assistance,Breastfeeding Support,Referrals}', '{WIC Nutrition}', '{Women,Infants,Children,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;