-- Add physical therapy, chiropractic, and rehabilitation services
INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  data.category_id,
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Physical Therapy
  ('Physiotherapy Associates Seattle', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Outpatient physical therapy and rehabilitation services.', '200 Broadway E', 'Seattle', 'King', '98102', '(206) 329-3900', 'https://www.physiotherapyassociates.com', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Physical Therapy', 'Sports Medicine', 'Rehabilitation'], ARRAY['physical therapy', 'rehabilitation', 'sports medicine', 'Seattle'], 'Physiotherapy Associates Seattle physical therapy rehabilitation sports medicine', 47.6190, -122.3155),
  ('Providence Physical Therapy Spokane', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Comprehensive physical therapy and rehabilitation.', '16528 E Desmet Ct', 'Spokane', 'Spokane', '99208', '(509) 472-2700', 'https://www.providence.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Physical Therapy', 'Occupational Therapy', 'Speech Therapy'], ARRAY['physical therapy', 'occupational therapy', 'rehabilitation', 'Spokane'], 'Providence Physical Therapy Spokane rehabilitation occupational therapy', 47.7392, -117.3918),
  ('Confluence Health Physical Therapy Wenatchee', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Physical therapy and rehabilitation services for Chelan County.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-8711', 'https://www.confluencehealth.org', '{"monday": "7am-5pm", "tuesday": "7am-5pm", "wednesday": "7am-5pm", "thursday": "7am-5pm", "friday": "7am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Hand Therapy', 'Vestibular Therapy'], ARRAY['physical therapy', 'rehabilitation', 'Wenatchee', 'Chelan County'], 'Confluence Health Physical Therapy Wenatchee rehabilitation Chelan County', 47.4321, -120.3214),
  ('MultiCare Physical Therapy Puyallup', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Physical therapy and sports medicine rehabilitation.', '400 15th Ave SE', 'Puyallup', 'Pierce', '98372', '(253) 792-6680', 'https://www.multicare.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Physical Therapy', 'Sports Medicine', 'Post-Surgical Rehab'], ARRAY['physical therapy', 'rehabilitation', 'Puyallup', 'sports medicine'], 'MultiCare Physical Therapy Puyallup rehabilitation sports medicine', 47.1860, -122.2820),
  ('PeaceHealth Physical Therapy Bellingham', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Outpatient physical therapy and rehabilitation.', '2900 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 738-6650', 'https://www.peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Physical Therapy', 'Occupational Therapy', 'Speech Therapy'], ARRAY['physical therapy', 'rehabilitation', 'Bellingham', 'Whatcom County'], 'PeaceHealth Physical Therapy Bellingham rehabilitation Whatcom County', 48.7564, -122.4743),
  -- Chiropractic Services
  ('Community Chiropractic Center Seattle', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Chiropractic', 'Affordable chiropractic care for pain relief and wellness.', '1200 Western Ave Suite 300', 'Seattle', 'King', '98101', '(206) 623-2225', 'https://www.communitychiropracticwa.com', '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-5pm", "saturday": "10am-2pm"}'::jsonb, true, true, true, true, true, true, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Chiropractic Care', 'Massage Therapy', 'Spinal Adjustment'], ARRAY['chiropractic', 'back pain', 'spine', 'Seattle', 'wellness'], 'Community Chiropractic Center Seattle back pain spinal adjustment', 47.6089, -122.3391),
  ('Spokane Chiropractic and Wellness', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Chiropractic', 'Chiropractic care for back pain, neck pain, and sports injuries.', '1402 N Washington St', 'Spokane', 'Spokane', '99201', '(509) 325-1122', 'https://www.spokanechiropracticwa.com', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-5pm"}'::jsonb, true, false, true, true, true, true, true, false, false, ARRAY['English'], ARRAY['Chiropractic Care', 'Massage Therapy', 'Physical Rehab'], ARRAY['chiropractic', 'back pain', 'neck pain', 'Spokane', 'sports injury'], 'Spokane Chiropractic Wellness back pain neck pain sports injury', 47.6650, -117.4152),
  ('Bellevue Family Chiropractic', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Chiropractic', 'Family-friendly chiropractic services for all ages.', '124 106th Ave NE Suite 100', 'Bellevue', 'King', '98004', '(425) 454-4440', 'https://www.bellevuefamilychiro.com', '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-5pm"}'::jsonb, false, false, true, true, true, true, true, false, false, ARRAY['English'], ARRAY['Chiropractic Care', 'Pediatric Chiropractic', 'Prenatal Chiropractic'], ARRAY['chiropractic', 'family chiropractic', 'Bellevue', 'pediatric', 'prenatal'], 'Bellevue Family Chiropractic pediatric prenatal chiropractic Bellevue', 47.6053, -122.2048),
  -- Occupational Therapy and Rehabilitation
  ('Valley Medical Center Rehabilitation', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Rehabilitation', 'Inpatient and outpatient rehabilitation services.', '4011 Talbot Rd S', 'Renton', 'King', '98055', '(425) 690-3520', 'https://www.valleymed.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Occupational Therapy', 'Speech Therapy', 'Cardiac Rehab'], ARRAY['rehabilitation', 'physical therapy', 'occupational therapy', 'Renton', 'Valley Medical'], 'Valley Medical Center Rehabilitation physical therapy occupational therapy Renton', 47.4729, -122.1833),
  ('Harborview Medical Center Rehabilitation', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Rehabilitation', 'Comprehensive rehabilitation including trauma recovery and brain injury.', '325 9th Ave', 'Seattle', 'King', '98104', '(206) 744-3321', 'https://www.uwmedicine.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Physical Therapy', 'Occupational Therapy', 'Trauma Recovery', 'Brain Injury Rehab'], ARRAY['rehabilitation', 'trauma recovery', 'brain injury', 'Seattle', 'Harborview'], 'Harborview Medical Center Rehabilitation trauma recovery brain injury Seattle', 47.6026, -122.3180),
  ('Swedish Rehabilitation Institute', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Rehabilitation', 'Inpatient and outpatient rehabilitation programs.', '747 Broadway', 'Seattle', 'King', '98122', '(206) 320-2000', 'https://www.swedish.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Inpatient Rehab', 'Outpatient Rehab', 'Stroke Recovery', 'Brain Injury Rehab'], ARRAY['rehabilitation', 'stroke recovery', 'inpatient rehab', 'Seattle', 'Swedish'], 'Swedish Rehabilitation Institute inpatient outpatient stroke recovery Seattle', 47.6128, -122.3144),
  -- Pediatric Therapy Services
  ('Seattle Childrens Therapy Services', (SELECT id FROM resource_categories WHERE slug = 'pediatrics'), 'Pediatric Therapy', 'Physical, occupational, and speech therapy for children.', '4800 Sand Point Way NE', 'Seattle', 'King', '98105', '(206) 987-5200', 'https://www.seattlechildrens.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Pediatric Physical Therapy', 'Pediatric Occupational Therapy', 'Speech Therapy'], ARRAY['pediatric therapy', 'children therapy', 'Seattle', 'speech therapy', 'occupational therapy'], 'Seattle Childrens Therapy Services pediatric physical occupational speech therapy', 47.6628, -122.2842),
  ('Northwest Center Kids', (SELECT id FROM resource_categories WHERE slug = 'pediatrics'), 'Pediatric Therapy', 'Early intervention and therapy services for children with disabilities.', '5808 Airport Way S', 'Seattle', 'King', '98108', '(206) 285-9110', 'https://www.nwcenter.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Early Intervention', 'Pediatric Therapy', 'Developmental Services'], ARRAY['pediatric therapy', 'early intervention', 'developmental disability', 'Seattle', 'children'], 'Northwest Center Kids early intervention pediatric therapy developmental Seattle', 47.5517, -122.3198),
  ('Boyds Academy Pediatric Therapy', (SELECT id FROM resource_categories WHERE slug = 'pediatrics'), 'Pediatric Therapy', 'Specialized pediatric therapy for developmental delays and disabilities.', '12828 Bel Red Rd', 'Bellevue', 'King', '98005', '(425) 641-4400', 'https://www.boydsacademy.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-5pm"}'::jsonb, false, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Pediatric Physical Therapy', 'Pediatric Occupational Therapy', 'Speech Therapy', 'ABA Therapy'], ARRAY['pediatric therapy', 'ABA therapy', 'autism', 'Bellevue', 'developmental'], 'Boyds Academy Pediatric Therapy ABA autism developmental Bellevue', 47.6195, -122.1536),
  -- Additional Rural Physical Therapy
  ('Yakima Valley Physical Therapy', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Outpatient physical therapy for Yakima Valley residents.', '806 N 40th Ave', 'Yakima', 'Yakima', '98902', '(509) 248-3373', 'https://www.yakimapluspt.com', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Orthopedic Rehab', 'Sports Medicine'], ARRAY['physical therapy', 'rehabilitation', 'Yakima', 'Yakima Valley'], 'Yakima Valley Physical Therapy rehabilitation orthopedic sports medicine', 46.6041, -120.5468),
  ('Tri-Cities Physical Therapy Kennewick', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Comprehensive physical therapy and rehabilitation services.', '522 W Kennewick Ave', 'Kennewick', 'Benton', '99336', '(509) 586-3322', 'https://www.tricities-pt.com', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Sports Rehab', 'Post-Surgical Rehab'], ARRAY['physical therapy', 'rehabilitation', 'Kennewick', 'Tri-Cities', 'sports'], 'Tri Cities Physical Therapy Kennewick rehabilitation sports medicine', 46.2094, -119.1282),
  ('Olympic Peninsula Physical Therapy Port Angeles', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Physical therapy and rehabilitation for Olympic Peninsula residents.', '624 N Lincoln St', 'Port Angeles', 'Clallam', '98362', '(360) 452-8850', 'https://www.olympicptw.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Physical Therapy', 'Orthopedic Rehab', 'Balance Therapy'], ARRAY['physical therapy', 'rehabilitation', 'Port Angeles', 'Olympic Peninsula', 'Clallam County'], 'Olympic Peninsula Physical Therapy Port Angeles rehabilitation Clallam', 48.1153, -123.4298),
  ('Lewis County Physical Therapy Chehalis', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Outpatient physical therapy for Lewis County.', '1424 Market St', 'Chehalis', 'Lewis', '98532', '(360) 748-2225', 'https://www.lewiscountypt.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Physical Therapy', 'Sports Rehab', 'Work Injury Rehab'], ARRAY['physical therapy', 'rehabilitation', 'Chehalis', 'Lewis County', 'work injury'], 'Lewis County Physical Therapy Chehalis rehabilitation work injury sports', 46.6635, -122.9618)
) AS data(name, category_id, subcategory, description, address, city, county, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, languages, services, tags, search_text, lat, lng);
