/*
# Add Substance Use Treatment Providers

1. Purpose
   - Add substance use treatment and recovery services across Washington state
   - Focus on inpatient, outpatient, and medication-assisted treatment

2. Coverage
   - All major Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'substance-use'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Crawford Recovery Center - Seattle', 'Outpatient Treatment', 'Substance use treatment with MAT, counseling, and case management services.', '2711 Eastlake Ave E', 'Seattle', 'King', '98102', '(206) 324-2400', 'https://crs.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['MAT', 'Suboxone', 'Counseling', 'Case Management'], ARRAY['substance use', 'addiction', 'MAT', 'medication assisted treatment', 'opioid'], 'substance use treatment Crawford Recovery Seattle MAT opioid addiction', 47.6466, -122.3202),
  ('Valley Cities Behavioral Health SUD - Des Moines', 'Outpatient Treatment', 'Substance use treatment with outpatient counseling and medication services.', '22000 17th Ave S', 'Des Moines', 'King', '98198', '(206) 870-4500', 'https://valleycities.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Counseling', 'Group Therapy', 'MAT'], ARRAY['substance use', 'addiction', 'MAT'], 'substance use treatment Valley Cities Des Moines MAT', 47.3966, -122.3250),
  ('Nueva Vida Counseling Services - Yakima', 'Outpatient Treatment', 'Bilingual substance use treatment with counseling and case management.', '102 S Naches Ave', 'Yakima', 'Yakima', '98901', '(509) 248-1500', 'https://saludmuralhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Counseling', 'Group Therapy'], ARRAY['substance use', 'addiction', 'Spanish'], 'substance use treatment Nueva Vida Yakima Spanish bilingual', 46.6030, -120.5067),
  ('Sundown M Ranch - Selah', 'Residential Treatment', 'Residential substance use treatment facility serving adults.', '508 N Wenas Rd', 'Selah', 'Yakima', '98942', '(509) 966-4646', 'https://sundown.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7", "saturday": "24/7", "sunday": "24/7"}'::jsonb, true, true, true, true, true, true, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Residential Treatment', 'Detox', 'Counseling'], ARRAY['substance use', 'addiction', 'residential', 'detox'], 'substance use treatment Sundown M Ranch Selah residential detox', 46.6664, -120.1174),
  ('Daybreak Youth Services - Spokane', 'Residential Treatment', 'Youth substance use treatment with residential and outpatient programs.', '317 W 2nd Ave', 'Spokane', 'Spokane', '99201', '(509) 624-2590', 'https://daybreakyouthservices.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Youth Treatment', 'Counseling', 'Family Therapy'], ARRAY['substance use', 'addiction', 'youth', 'adolescent'], 'substance use treatment Daybreak Youth Services Spokane adolescent', 47.6572, -117.4304),
  ('Frontier Behavioral Health - Spokane', 'Outpatient Treatment', 'Community mental health with substance use treatment services.', '707 N Cochran St', 'Spokane', 'Spokane', '99201', '(509) 838-4655', 'https://frontierbhs.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Russian'], ARRAY['MAT', 'Counseling', 'Psychiatry'], ARRAY['substance use', 'addiction', 'MAT', 'mental health'], 'substance use treatment Frontier Behavioral Health Spokane MAT', 47.6612, -117.4234),
  ('Spokane Treatment Services - Spokane', 'Outpatient Treatment', 'Medication-assisted treatment for opioid use disorder.', '222 E Mission Ave', 'Spokane', 'Spokane', '99207', '(509) 327-9831', 'https://spokanetreatmentservices.com', '{"monday": "6am-2pm", "tuesday": "6am-2pm", "wednesday": "6am-2pm", "thursday": "6am-2pm", "friday": "6am-2pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Russian'], ARRAY['Methadone', 'Suboxone', 'Counseling'], ARRAY['substance use', 'addiction', 'MAT', 'methadone', 'opioid'], 'substance use treatment Spokane Treatment Services MAT methadone opioid', 47.6761, -117.3997),
  ('Ideal Option - Tacoma', 'Outpatient Treatment', 'Outpatient medication-assisted treatment for opioid and alcohol use disorder.', '1104 N 14th St', 'Tacoma', 'Pierce', '98403', '(253) 627-4400', 'https://idealoption.com', '{"monday": "7am-5pm", "tuesday": "7am-5pm", "wednesday": "7am-5pm", "thursday": "7am-5pm", "friday": "7am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, false, false, ARRAY['English', 'Spanish'], ARRAY['MAT', 'Suboxone', 'Vivitrol', 'Counseling'], ARRAY['substance use', 'addiction', 'MAT', 'opioid'], 'substance use treatment Ideal Option Tacoma MAT Suboxone Vivitrol', 47.2668, -122.4507),
  ('Elevate Addiction Services - Everett', 'Outpatient Treatment', 'Substance use treatment with evidence-based approaches.', '2827 Rucker Ave', 'Everett', 'Snohomish', '98201', '(360) 428-5910', 'https://elevateaddiction.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Counseling', 'Group Therapy', 'Case Management'], ARRAY['substance use', 'addiction'], 'substance use treatment Elevate Addiction Services Everett', 47.9693, -122.1981),
  ('Cocoon House SUD Services - Everett', 'Outpatient Treatment', 'Youth substance use treatment and housing support.', '3530 Colby Ave', 'Everett', 'Snohomish', '98201', '(425) 259-6111', 'https://cocoonhouse.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Youth Treatment', 'Counseling', 'Housing Support'], ARRAY['substance use', 'addiction', 'youth', 'homeless'], 'substance use treatment Cocoon House SUD Everett youth homeless', 47.9691, -122.2004),
  ('BHG Everett Treatment Center', 'Outpatient Treatment', 'Medication-assisted treatment and counseling.', '1508 Broadway', 'Everett', 'Snohomish', '98201', '(425) 317-9810', 'https://bhgrecovery.com', '{"monday": "6am-2pm", "tuesday": "6am-2pm", "wednesday": "6am-2pm", "thursday": "6am-2pm", "friday": "6am-2pm", "saturday": "8am-12pm", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Methadone', 'Suboxone', 'Counseling'], ARRAY['substance use', 'addiction', 'MAT', 'methadone'], 'substance use treatment BHG Everett methadone MAT', 47.9755, -122.2017),
  ('Comprehensive Healthcare SUD - Walla Walla', 'Outpatient Treatment', 'Substance use treatment serving Walla Walla Valley.', '1103 Poplar St', 'Walla Walla', 'Walla Walla', '99362', '(509) 525-0570', 'https://comprehensivehealthcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Counseling', 'MAT', 'Group Therapy'], ARRAY['substance use', 'addiction', 'MAT'], 'substance use treatment Comprehensive Healthcare Walla Walla MAT', 46.0715, -118.3386),
  ('Tri-Cities Treatment Services - Kennewick', 'Outpatient Treatment', 'Medication-assisted treatment for opioid use disorder.', '4427 W Deschutes Ave', 'Kennewick', 'Benton', '99336', '(509) 783-1000', 'https://tricitiestreatment.com', '{"monday": "6am-2pm", "tuesday": "6am-2pm", "wednesday": "6am-2pm", "thursday": "6am-2pm", "friday": "6am-2pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Methadone', 'Suboxone', 'Counseling'], ARRAY['substance use', 'addiction', 'MAT', 'methadone', 'Tri-Cities'], 'substance use treatment Tri-Cities Treatment Services Kennewick methadone MAT', 46.2066, -119.1792),
  ('Ideal Option - Vancouver', 'Outpatient Treatment', 'Medication-assisted treatment for opioid and alcohol disorders.', '2500 NE 78th St', 'Vancouver', 'Clark', '98665', '(360) 524-8400', 'https://idealoption.com', '{"monday": "7am-5pm", "tuesday": "7am-5pm", "wednesday": "7am-5pm", "thursday": "7am-5pm", "friday": "7am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, false, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['MAT', 'Suboxone', 'Vivitrol', 'Counseling'], ARRAY['substance use', 'addiction', 'MAT', 'opioid'], 'substance use treatment Ideal Option Vancouver MAT Suboxone', 45.6802, -122.6010),
  ('Daybreak Outpatient - Vancouver', 'Outpatient Treatment', 'Outpatient substance use treatment for adults and adolescents.', '3600 Main St', 'Vancouver', 'Clark', '98663', '(360) 696-4620', 'https://daybreakinfo.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Counseling', 'Group Therapy'], ARRAY['substance use', 'addiction'], 'substance use treatment Daybreak Outpatient Vancouver', 45.6258, -122.6658),
  ('Willapa Behavioral Health SUD - Aberdeen', 'Outpatient Treatment', 'Substance use treatment serving Grays Harbor County.', '300 Pomeroy St', 'Aberdeen', 'Grays Harbor', '98520', '(360) 533-3200', 'https://willapabehavioralhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Counseling', 'MAT', 'Group Therapy'], ARRAY['substance use', 'addiction', 'MAT'], 'substance use treatment Willapa Behavioral Health Aberdeen MAT', 46.9778, -123.8178),
  ('Olympic Community Action Programs SUD - Port Angeles', 'Outpatient Treatment', 'Substance use treatment serving Olympic Peninsula.', '2409 E 18th St', 'Port Angeles', 'Clallam', '98362', '(360) 417-2100', 'https://olycap.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Counseling', 'Case Management'], ARRAY['substance use', 'addiction'], 'substance use treatment Olycap Port Angeles Clallam', 48.1152, -123.3981),
  ('Whatcom Counseling Center SUD - Bellingham', 'Outpatient Treatment', 'County substance use services with sliding scale.', '503 W Bakerview Rd', 'Bellingham', 'Whatcom', '98226', '(360) 676-6160', 'https://whatcomcounty.us', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Individual Counseling', 'Group Therapy', 'MAT'], ARRAY['substance use', 'addiction', 'MAT', 'sliding scale'], 'substance use treatment Whatcom Counseling Bellingham MAT sliding scale', 48.7692, -122.4576),
  ('Rainbow Recovery Services - Olympia', 'Outpatient Treatment', 'LGBTQ+ affirming substance use treatment services.', '110 Broadway Ave E', 'Olympia', 'Thurston', '98501', '(360) 489-0650', 'https://rainbowrecovery.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Individual Counseling', 'Group Therapy', 'LGBTQ+ Affirming'], ARRAY['substance use', 'addiction', 'LGBTQ'], 'substance use treatment Rainbow Recovery Services Olympia LGBTQ affirming', 47.0468, -122.8914)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
