/*
# Add Additional Community Resources and Services

1. Purpose
   - Add disability services, legal aid, senior services, and other community resources
   - Fill gaps in underserved areas

2. Coverage
   - All Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'community-org'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Disability Rights Washington - Seattle', 'Disability Services', 'Advocacy and legal services for people with disabilities statewide.', '390 7th Ave N', 'Seattle', 'King', '98109', '(800) 562-2702', 'https://disabilityrightswa.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Disability Advocacy', 'Legal Services', 'Rights Information'], ARRAY['disability', 'advocacy', 'legal', 'rights', 'ADA'], 'disability services Disability Rights Washington Seattle advocacy legal', 47.6241, -122.3420),
  ('Washington ADAPT - Seattle', 'Disability Services', 'Grassroots disability rights organization promoting community living.', '1414 24th Ave S', 'Seattle', 'King', '98144', '(206) 323-2891', 'https://adaptwa.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English'], ARRAY ['Disability Advocacy', 'Community Living'], ARRAY['disability', 'advocacy', 'community living'], 'disability services Washington ADAPT Seattle advocacy', 47.5968, -122.3003),
  ('Northwest Independence Associates - Spokane', 'Disability Services', 'Independent living center serving Eastern Washington.', '1202 N Maple St', 'Spokane', 'Spokane', '99208', '(509) 326-5261', 'https://niainc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Russian'], ARRAY['Independent Living Skills', 'Peer Support', 'Advocacy'], ARRAY['disability', 'independent living', 'Eastern Washington'], 'disability services Northwest Independence Associates Spokane independent living', 47.7258, -117.4247),
  ('Allies in Advocacy - Tacoma', 'Disability Services', 'Self-advocacy group for people with developmental disabilities.', '6207 6th Ave', 'Tacoma', 'Pierce', '98406', '(253) 564-6279', 'https://alliesinadvocacy.org', '{"monday": "9am-4pm", "tuesday": "9am-4pm", "wednesday": "9am-4pm", "thursday": "9am-4pm", "friday": "9am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Self-Advocacy', 'Peer Support'], ARRAY['disability', 'advocacy', 'developmental disabilities'], 'disability services Allies in Advocacy Tacoma developmental disabilities', 47.2606, -122.4853),
  ('WestCOP Disability Resource Center - Bellingham', 'Disability Services', 'Independent living center serving Whatcom, Skagit, Island, San Juan.', '115 W Magnolia St', 'Bellingham', 'Whatcom', '98225', '(360) 671-3172', 'https://wcdr.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Independent Living', 'Advocacy', 'Peer Support'], ARRAY['disability', 'independent living', 'Whatcom', 'Skagit', 'Island', 'San Juan'], 'disability services WestCOP Bellingham independent living Whatcom Skagit', 48.7507, -122.4781),
  ('Wenatchee Valley Disability Resource Center', 'Disability Services', 'Independent living center serving North Central Washington.', '201 S Wenatchee Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-5433', 'https://liferc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Independent Living', 'Advocacy', 'Peer Support'], ARRAY['disability', 'independent living', 'Chelan', 'Douglas', 'Okanogan'], 'disability services Wenatchee Valley Disability Resource Center', 47.4224, -120.3190),
  ('Senior Legal Assistance - Seattle', 'Legal Aid', 'Free legal services for seniors 60 and over in King County.', '915 2nd Ave #500', 'Seattle', 'King', '98104', '(206) 263-2801', 'https://kcsls.org', '{"monday": "9am-4pm", "tuesday": "9am-4pm", "wednesday": "9am-4pm", "thursday": "9am-4pm", "friday": "9am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Legal Advice', 'Elder Law', 'Housing', 'Benefits'], ARRAY['legal aid', 'senior', 'elder law', 'free legal'], 'legal aid Senior Legal Assistance Seattle King County elder law', 47.6054, -122.3337),
  ('Northwest Justice Project - Seattle', 'Legal Aid', 'Statewide civil legal aid for low-income individuals.', '401 2nd Ave N #400', 'Seattle', 'King', '98109', '(206) 464-1519', 'https://nwjustice.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Civil Legal Aid', 'Housing', 'Family Law', 'Public Benefits'], ARRAY['legal aid', 'civil legal', 'low income', 'free legal'], 'legal aid Northwest Justice Project Seattle civil legal aid', 47.6230, -122.3411),
  ('Columbia Legal Services - Seattle', 'Legal Aid', 'Civil legal aid for marginalized communities statewide.', '101 Yesler Way #200', 'Seattle', 'King', '98104', '(206) 464-1122', 'https://columbialegal.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Civil Legal Aid', 'Immigration', 'Housing', 'Workers Rights'], ARRAY['legal aid', 'civil legal', 'immigration', 'housing'], 'legal aid Columbia Legal Services Seattle immigration housing', 47.6017, -122.3313),
  ('TeamChild - Seattle', 'Legal Aid', 'Civil legal aid for youth in King, Pierce, Snohomish, Spokane.', '509 2nd Ave #400', 'Seattle', 'King', '98104', '(206) 322-2444', 'https://teamchild.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Youth Legal Aid', 'Education', 'Housing'], ARRAY['legal aid', 'youth', 'education', 'juvenile'], 'legal aid TeamChild Seattle youth juvenile legal', 47.6015, -122.3330),
  ('Northwest Justice Project - Spokane', 'Legal Aid', 'Civil legal aid for low-income individuals in Eastern Washington.', '322 W 2nd Ave', 'Spokane', 'Spokane', '99201', '(509) 328-2112', 'https://nwjustice.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Russian'], ARRAY['Civil Legal Aid', 'Housing', 'Family Law'], ARRAY['legal aid', 'civil legal', 'Eastern Washington'], 'legal aid Northwest Justice Project Spokane Eastern Washington', 47.6581, -117.4289),
  ('Skagit County Legal Aid - Mount Vernon', 'Legal Aid', 'Free legal services for low-income Skagit County residents.', '120 W Kincaid St', 'Mount Vernon', 'Skagit', '98273', '(360) 336-3670', 'https://lawcenternw.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Civil Legal Aid', 'Housing', 'Family Law'], ARRAY['legal aid', 'civil legal', 'Skagit County'], 'legal aid Skagit County Legal Aid Mount Vernon', 48.4213, -122.3353),
  ('Whatcom County Legal Aid - Bellingham', 'Legal Aid', 'Free legal services for low-income Whatcom County residents.', '103 E Holly St', 'Bellingham', 'Whatcom', '98225', '(360) 647-8833', 'https://lawcenternw.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Civil Legal Aid', 'Housing', 'Family Law'], ARRAY['legal aid', 'civil legal', 'Whatcom County'], 'legal aid Whatcom County Legal Aid Bellingham', 48.7516, -122.4828),
  ('Olympic Community Action Programs - Port Angeles', 'Senior Center', 'Multipurpose senior center serving Olympic Peninsula.', '825 Georgianna St', 'Port Angeles', 'Clallam', '98362', '(360) 452-8601', 'https://olycap.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English'], ARRAY['Senior Center', 'Meal Programs', 'Transportation', 'Case Management'], ARRAY['senior center', 'aging services', 'Olympic Peninsula'], 'senior center Olympic Community Action Programs Port Angeles aging services', 48.1240, -123.4102),
  ('Senior Services of Snohomish County - Everett', 'Senior Center', 'Multipurpose senior center providing meals and transportation.', '2806 Lombard Ave', 'Everett', 'Snohomish', '98201', '(425) 347-1229', 'https://sssc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Senior Center', 'Meal Programs', 'Transportation', 'Case Management'], ARRAY['senior center', 'aging services', 'Snohomish County'], 'senior center Senior Services Snohomish County Everett aging services', 47.9691, -122.2004),
  ('Area Agency on Aging - Tacoma', 'Senior Center', 'AAA serving Pierce County seniors.', '3607 Pacific Ave', 'Tacoma', 'Pierce', '98418', '(253) 922-6345', 'https://seniorservicespierce.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Senior Center', 'Meal Programs', 'Case Management'], ARRAY['senior center', 'aging services', 'Pierce County', 'AAA'], 'senior center Area Agency on Aging Tacoma Pierce', 47.2196, -122.4370),
  ('Aging and Long Term Care - Spokane', 'Senior Center', 'AAA serving aging adults in Eastern Washington.', '1222 W 2nd Ave', 'Spokane', 'Spokane', '99201', '(509) 458-2500', 'https://altcew.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Russian'], ARRAY['Senior Center', 'Long Term Care', 'Case Management'], ARRAY['senior center', 'aging services', 'Eastern Washington', 'AAA'], 'senior center Aging Long Term Care Spokane Eastern Washington', 47.6567, -117.4308),
  ('Thurston County Senior Services - Olympia', 'Senior Center', 'AAA serving Thurston County seniors.', '2240 Martin Way E', 'Olympia', 'Thurston', '98506', '(360) 664-2161', 'https://co.thurston.wa.us', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Senior Center', 'Meal Programs', 'Transportation'], ARRAY['senior center', 'aging services', 'Thurston County', 'AAA'], 'senior center Thurston County Senior Services Olympia AAA', 47.0420, -122.8780),
  ('Tri-Cities Cancer Center - Kennewick', 'Cancer Support', 'Cancer treatment and support services for Tri-Cities.', '7350 W Deschutes Ave', 'Kennewick', 'Benton', '99336', '(509) 737-3400', 'https://tri-citiescancer.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Cancer Treatment', 'Support Groups', 'Navigation'], ARRAY['cancer', 'oncology', 'Tri-Cities'], 'cancer support Tri-Cities Cancer Center Kennewick oncology', 46.2066, -119.1792),
  ('Cancer Care Northwest - Spokane', 'Cancer Support', 'Comprehensive cancer care services.', '501 N Riverpoint Blvd', 'Spokane', 'Spokane', '99202', '(509) 228-1000', 'https://cancercarenorthwest.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Russian'], ARRAY['Cancer Treatment', 'Support Groups', 'Navigation'], ARRAY['cancer', 'oncology', 'Spokane'], 'cancer support Cancer Care Northwest Spokane oncology', 47.6562, -117.4188),
  ('Washington Poison Center', 'Crisis Line', '24/7 poison emergency and information hotline statewide.', '155 NE 100th St', 'Seattle', 'King', '98125', '(800) 222-1222', 'https://wapc.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7", "saturday": "24/7", "sunday": "24/7"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Poison Emergency', 'Information Hotline'], ARRAY['poison', 'crisis', 'hotline', 'statewide', 'emergency'], 'poison center Washington Poison Center Seattle emergency hotline statewide', 47.7023, -122.3276),
  ('Health Care Authority Customer Service', 'Insurance Assistance', 'State agency helping with Apple Health (Medicaid) and Public Employees Benefits.', '626 8th Ave SE', 'Olympia', 'Thurston', '98504', '(800) 562-3022', 'https://hca.wa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, false, false, false, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Insurance Enrollment', 'Apple Health', 'Medicaid', 'Coverage Questions'], ARRAY['insurance', 'Medicaid', 'Apple Health', 'enrollment', 'state agency'], 'insurance assistance Health Care Authority Apple Health Medicaid enrollment', 47.0379, -122.8949),
  ('Washington Healthplanfinder', 'Insurance Assistance', 'State health insurance marketplace for ACA plans.', '300 Queen Anne Ave N #400', 'Seattle', 'King', '98109', '(855) 923-4633', 'https://wahealthplanfinder.org', '{"monday": "8am-7pm", "tuesday": "8am-7pm", "wednesday": "8am-7pm", "thursday": "8am-7pm", "friday": "8am-7pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, true, true, ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese'], ARRAY['Insurance Enrollment', 'ACA Plans', 'Subsidy Help'], ARRAY['insurance', 'ACA', 'marketplace', 'enrollment'], 'insurance assistance Washington Healthplanfinder ACA marketplace enrollment', 47.6231, -122.3571)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
