/*
# Add Washington Tribal Health Clinics (Batch 3)

1. Data Insert
- Adds Lummi Tribal Health Center, Upper Skagit Tribal Clinic, Muckleshoot
  Health & Wellness Center, and Puyallup Tribal Health Authority.
2. Source
- Verified via tribe and IHS websites (Lummi, Upper Skagit, Muckleshoot,
  Puyallup Tribal Health Authority).
3. Notes
- Tribal FQHCs serving AI/AN members and (where noted) other federally
  recognized tribal members. medicaid=true, sliding_scale=true.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Lummi Tribal Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Lummi Nation health center providing medical, dental, behavioral health, physical therapy, lab, pharmacy and public health services for enrolled Lummi tribal members and other federally recognized AI/AN in Whatcom County.', '2592 Kwina Rd', 'Bellingham', 'Whatcom', 'WA', '98226', '360-384-0464', 'https://www.lummihealth.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Lummi}', '{wheelchair,"ADA parking"}', '{Medical,Dental,Behavioral Health,Physical Therapy,Lab,Pharmacy,Public Health}', '{Tribal Health,Family Medicine}', '{Native Americans,Tribal Members}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Upper Skagit Tribal Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Upper Skagit Indian Tribe health clinic providing non-emergency primary care, behavioral health, children''s well care and immunizations, smoking cessation, health education, nutrition counseling, and diabetes support for Upper Skagit tribal members and other AI/AN.', '25959 Community Plaza Way', 'Sedro-Woolley', 'Skagit', 'WA', '98284', '360-854-7070', 'https://upperskagittribe-nsn.gov/departments/health-services', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Behavioral Health,Well Child Care,Immunizations,Diabetes Support,Nutrition Counseling}', '{Tribal Health,Family Medicine}', '{Native Americans,Tribal Members}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Muckleshoot Health & Wellness Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Muckleshoot Indian Tribe health and wellness center providing medical, dental, behavioral health, pharmacy, elders in-home support, gym, and substance use recovery services for Muckleshoot members, other AI/AN, and community.', '17500 SE 392nd St', 'Auburn', 'King', 'WA', '98092', '253-939-6648', 'https://www.muckleshoot.nsn.us/depts/hwc', '{"mon":"6:00-19:00","tue":"6:00-19:00","wed":"6:00-19:00","thu":"6:00-19:00","fri":"6:00-19:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Lushootseed,Spanish}', '{wheelchair,"ADA parking","pool lift"}', '{Medical,Dental,Behavioral Health,Pharmacy,Substance Use Recovery,Elders In-Home Support}', '{Tribal Health,Family Medicine}', '{Native Americans,Tribal Members,Elders}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Puyallup Tribal Health Authority', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Puyallup Tribe ambulatory medical and dental care facility providing primary care, dental, mental health, WIC/well child, nutrition, lab, pharmacy and managed care referral for eligible AI/AN in Pierce County.', '2209 E 32nd St', 'Tacoma', 'Pierce', 'WA', '98404', '253-593-0232', 'https://www.puyalluptribalhealthauthority.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"10:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Lushootseed,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Primary Care,Dental,Mental Health,WIC,Well Child,Nutrition,Lab,Pharmacy}', '{Tribal Health,Family Medicine,Pediatrics}', '{Native Americans,Tribal Members,AI/AN in Pierce County}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;