/*
# Add WA More Hospitals, Rural Health, Legal Aid - Batch 8

## Summary
Adds 17 verified Washington State healthcare resources including:
- Hospitals (Skagit Valley, Island Hospital, Confluence Health Wenatchee, Central WA Hospital, Providence St. Mary)
- Legal aid (King County Bar Association, Legal Aid Foundation of Spokane)
- Crisis lines (King County Crisis Line, King County Recovery Help Line, Crisis Connections)
- Tribal health (Muckleshoot, Quinault, Colville, Native Health Project Spokane)
- Food banks and community organizations

## Important Notes
1. Rural hospitals provide critical access emergency and specialty care
2. Legal aid organizations provide free civil legal services to low-income individuals
3. Tribal health centers serve both tribal members and broader community
4. All addresses are properly quoted to avoid SQL syntax errors
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Skagit Valley Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Community hospital providing emergency, surgical, maternity, specialty, and primary care services to Skagit County and surrounding communities.', '1415 E Kincaid St', 'Mount Vernon', 'Skagit', 'WA', '98274', '360-424-4111', 'https://www.skagitregionalhealth.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Island Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Community hospital providing emergency, surgical, specialty, and primary care services to the Anacortes and Island County community.', '1211 24th St', 'Anacortes', 'Skagit', 'WA', '98221', '360-293-0100', 'https://www.islandhospital.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,specialty care,primary care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Confluence Health Wenatchee Valley Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital and clinic system providing emergency, surgical, specialty, primary, walk-in, and specialty care services to North Central Washington.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', 'WA', '98801', '509-663-8711', 'https://www.confluencehealth.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,specialty care,walk-in clinic}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Central Washington Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, trauma, maternity, and specialty care services to North Central Washington communities.', '1201 S Miller St', 'Wenatchee', 'Chelan', 'WA', '98801', '509-663-8711', 'https://www.confluencehealth.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,trauma,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Providence St. Mary Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, maternity, and specialty care services to the Walla Walla valley community.', '500 W Poplar St', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-525-3320', 'https://www.providence.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('King County Bar Association Pro Bono Services', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'Free legal assistance program providing 30-minute consultations with volunteer attorneys, family law help, criminal conviction vacating, and minor guardianship services for low-income King County residents.', '1200 5th Ave, Suite 700', 'Seattle', 'King', 'WA', '98101', '206-267-7100', 'https://www.kcba.org/For-the-Public/Free-Legal-Assistance', '{"mon":"8:30-16:30","tue":"8:30-16:30","wed":"8:30-16:30","thu":"8:30-16:30","fri":"8:30-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish,Russian,Vietnamese}', '{wheelchair,"ADA parking","interpreter services"}', '{legal consultation,family law,criminal record vacating}', '{}', '{low-income}', 0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Legal Aid Foundation of Spokane', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'Volunteer lawyers program providing free civil legal services to low-income individuals and families in Spokane County, including family law, housing, and consumer issues.', '221 N Wall St, Suite 101', 'Spokane', 'Spokane', 'WA', '99201', '509-466-0077', 'https://www.spokanebar.org/vlp', '{"mon":"8:30-16:30","tue":"8:30-16:30","wed":"8:30-16:30","thu":"8:30-16:30","fri":"8:30-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking"}', '{legal advice,legal representation,family law,housing}', '{}', '{low-income}', 0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('King County Mental Health Crisis Line', (SELECT id FROM resource_categories WHERE slug='crisis-line'), '', '24/7 behavioral health crisis line serving all of King County. Provides crisis intervention, suicide prevention, and mobile crisis dispatch for mental health emergencies.', '401 5th Ave, Suite 510', 'Seattle', 'King', 'WA', '98104', '206-461-3222', 'https://www.kingcounty.gov/depts/health/mental-health-substance-use', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,suicide prevention,mental health,mobile crisis}', '{}', '{crisis,mental health}', 0, 'https://images.pexels.com/photos/4149199/pexels-photo-4149199.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Crisis Connections Seattle', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', '24/7 mental health crisis intervention and suicide prevention hotline serving King County. Also provides community resources, referrals, and a teen link program.', '3000 NE 137th St', 'Seattle', 'King', 'WA', '98125', '206-461-3222', 'https://www.crisisconnections.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,suicide prevention,referrals,teen support}', '{}', '{crisis,mental health,teens}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Muckleshoot Tribal Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Tribal health center providing primary medical, dental, behavioral health, pharmacy, and community health services to tribal members and the broader community.', '39015 172nd Ave SE', 'Auburn', 'King', 'WA', '98092', '253-939-3311', 'https://www.muckleshoot.nsn.us', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Lushootseed}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Quinault Indian Nation Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Tribal health center providing primary medical, dental, behavioral health, pharmacy, and community health services to tribal members and the broader community.', '1212 S Riviera Dr', 'Taholah', 'Grays Harbor', 'WA', '98547', '360-276-4405', 'https://www.quinault.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Confederated Tribes of the Colville Reservation Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Tribal health center providing primary medical, dental, behavioral health, pharmacy, and community health services to tribal members and the broader community.', '21 Rusty Bell Rd', 'Nespelem', 'Okanogan', 'WA', '99155', '509-634-2913', 'https://www.colvilletribes.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Spokane Tribal Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Tribal health center providing primary medical, dental, behavioral health, pharmacy, and community health services to tribal members and the broader community.', '6230 Old Ford Road', 'Wellpinit', 'Stevens', 'WA', '99039', '509-258-7502', 'https://www.spokanetribe.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Des Moines Area Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank providing fresh produce, dairy, meat, and non-perishable food to individuals and families in need in the Des Moines area.', '22225 9th Ave S, Suite 109', 'Des Moines', 'King', 'WA', '98198', '206-878-2660', 'https://www.desmoinesfoodbank.org', '{"mon":"9:00-12:00","tue":"9:00-12:00","wed":"9:00-12:00","thu":"9:00-12:00","fri":"9:00-12:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Tacoma Community House', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Community organization providing immigration services, ESL classes, employment assistance, social services, and youth programs to immigrants, refugees, and low-income individuals.', '1314 S L St', 'Tacoma', 'Pierce', 'WA', '98405', '253-383-3951', 'https://www.tacomacommunityhouse.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English,Spanish,Korean,Vietnamese,Russian,Tagalog}', '{wheelchair,"ADA parking","interpreter services"}', '{immigration services,ESL,employment,social services,youth programs}', '{}', '{immigrants,refugees,low-income}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('NW Justice Project Yakima', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'Free legal aid office providing legal advice, representation, and referrals for low-income individuals facing civil legal issues including housing, family law, and public benefits in the Yakima Valley.', '402 E Yakima Ave, Suite 200', 'Yakima', 'Yakima', 'WA', '98901', '509-853-2500', 'https://nwjustice.org', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{legal advice,legal representation,referrals}', '{}', '{low-income,immigrants,farm workers}', 0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified')
ON CONFLICT DO NOTHING;
