/*
# Add Transportation Services

1. Purpose
   - Add medical transportation and dial-a-ride services across Washington state
   - Focus on non-emergency medical transportation
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'transportation'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Hopelink Transportation - Bellevue', 'Paratransit', 'Non-emergency medical transportation for Medicaid eligible individuals in King County.', '14812 NE 21st St', 'Bellevue', 'King', '98007', '(425) 943-6750', 'https://hopelink.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, false, false, true, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Medical Transportation', 'Dialysis Transportation', 'Pharmacy Trips'], ARRAY['transportation', 'medical transport', 'Medicaid', 'paratransit', 'Hopelink'], 'transportation Hopelink medical Medicaid paratransit King County', 47.6276, -122.1441),
  ('King County Metro Access - Seattle', 'Paratransit', 'ADA paratransit service for people with disabilities in King County.', '821 2nd Ave', 'Seattle', 'King', '98104', '(206) 205-5000', 'https://kingcounty.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, false, ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese'], ARRAY['ADA Paratransit', 'Medical Appointments'], ARRAY['transportation', 'paratransit', 'ADA', 'disability', 'King County Metro'], 'transportation King County Metro Access ADA paratransit disability Seattle', 47.6023, -122.3320),
  ('MTS (Medical Transportation Service) - Pierce County', 'Paratransit', 'Non-emergency medical transportation for Pierce County Medicaid recipients.', '8001 E 32nd St', 'Tacoma', 'Pierce', '98404', '(800) 848-3897', 'https://mts.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, false, false, true, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Medical Transportation', 'Wheelchair Accessible'], ARRAY['transportation', 'medical transport', 'Medicaid', 'Pierce County'], 'transportation MTS Pierce County Medicaid medical transport', 47.2302, -122.4153),
  ('Pierce Transit SHUTTLE - Tacoma', 'Paratransit', 'ADA paratransit service for people with disabilities in Pierce County.', '3721 14th Ave SW', 'Puyallup', 'Pierce', '98373', '(253) 581-8000', 'https://piercetransit.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Pierce Transit', 'SHUTTLE'], 'transportation Pierce Transit SHUTTLE ADA paratransit Tacoma', 47.1307, -122.3914),
  ('Spokane Transit Authority Paratransit', 'Paratransit', 'ADA paratransit service for people with disabilities in Spokane.', '1229 E Broadway Ave', 'Spokane', 'Spokane', '99207', '(509) 328-1552', 'https://spokanetransit.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Russian'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Spokane Transit'], 'transportation Spokane Transit Authority paratransit ADA', 47.6740, -117.3954),
  ('Community Transit DART - Snohomish County', 'Paratransit', 'Demand-response transit service for people with disabilities.', '7100 Hardeson Rd', 'Everett', 'Snohomish', '98203', '(425) 347-5912', 'https://communitytransit.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Snohomish', 'DART'], 'transportation Community Transit DART Snohomish paratransit', 47.9509, -122.2132),
  ('C-Tran Paratransit - Vancouver', 'Paratransit', 'ADA paratransit service for Clark County residents with disabilities.', '5100 NE 82nd Ave', 'Vancouver', 'Clark', '98662', '(360) 695-0123', 'https://ctran.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Clark County', 'C-Tran'], 'transportation C-Tran paratransit Clark County Vancouver', 45.6821, -122.5718),
  ('Ben Franklin Transit Dial-A-Ride - Tri-Cities', 'Paratransit', 'Demand-response transit for people with disabilities in Tri-Cities.', '5825 W Umatilla Ave', 'Kennewick', 'Benton', '99336', '(509) 735-5100', 'https://bft.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Tri-Cities', 'Ben Franklin Transit'], 'transportation Ben Franklin Transit Dial-A-Ride Tri-Cities paratransit', 46.2066, -119.1093),
  ('Intercity Transit Dial-A-Lift - Olympia', 'Paratransit', 'ADA paratransit service for Thurston County residents.', '526 Patterson St SW', 'Olympia', 'Thurston', '98502', '(360) 705-5811', 'https://intercitytransit.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Thurston County', 'Intercity Transit'], 'transportation Intercity Transit Dial-A-Lift Olympia Thurston paratransit', 47.0396, -122.9330),
  ('Whatcom Transportation Authority Specialized Transportation', 'Paratransit', 'ADA paratransit service for Whatcom County.', '4101 Bakerview Spinks Rd', 'Bellingham', 'Whatcom', '98226', '(360) 676-7433', 'https://ridewta.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Whatcom County', 'WTA'], 'transportation WTA Whatcom Transportation Authority paratransit Bellingham', 48.7734, -122.4570),
  ('Skagit Transit Paratransit - Mount Vernon', 'Paratransit', 'ADA paratransit service for Skagit County.', '105 E College Way', 'Mount Vernon', 'Skagit', '98273', '(360) 416-2733', 'https://skagittransit.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Skagit County'], 'transportation Skagit Transit paratransit Mount Vernon', 48.4205, -122.3511),
  ('RiverCities Transit Paratransit - Longview', 'Paratransit', 'ADA paratransit service for Cowlitz County.', '1000 14th Ave', 'Longview', 'Cowlitz', '98632', '(360) 442-5610', 'https://rctransit.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Cowlitz County'], 'transportation RiverCities Transit paratransit Longview Cowlitz', 46.1410, -122.9344),
  ('Grays Harbor Transit Paratransit - Aberdeen', 'Paratransit', 'ADA paratransit for Grays Harbor County residents.', '105 N G St', 'Aberdeen', 'Grays Harbor', '98520', '(360) 532-2770', 'https://ghtransit.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Grays Harbor'], 'transportation Grays Harbor Transit paratransit Aberdeen', 46.9738, -123.8233),
  ('Yakima Transit Paratransit', 'Paratransit', 'ADA paratransit service for Yakima area.', '106 S 1st St', 'Yakima', 'Yakima', '98901', '(509) 575-6265', 'https://yakimatransit.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Yakima'], 'transportation Yakima Transit paratransit', 46.6034, -120.5061),
  ('Medivan - Wenatchee', 'Paratransit', 'Medical transportation for rural Chelan and Douglas Counties.', '270 5th St N', 'Wenatchee', 'Chelan', '98801', '(509) 664-7246', 'https://linktransit.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Medical Transportation', 'Rural Transportation'], ARRAY['transportation', 'medical transport', 'rural', 'Chelan', 'Medivan', 'Link Transit'], 'transportation Medivan Link Transit Wenatchee medical rural Chelan Douglas', 47.4354, -120.3195),
  ('Volunteer Driver Programs - Lewis County', 'Paratransit', 'Volunteer driver program for medical transportation.', '2420 SW 267th St', 'Rochester', 'Lewis', '98579', '(360) 785-3722', 'https://lccountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Medical Transportation', 'Volunteer Drivers'], ARRAY['transportation', 'medical transport', 'volunteer', 'Lewis County'], 'transportation Volunteer Driver Programs Lewis County medical transport', 46.8255, -123.0698),
  ('Clallam Transit Paratransit - Port Angeles', 'Paratransit', 'ADA paratransit service for Clallam County.', '830 E Lauridsen Blvd', 'Port Angeles', 'Clallam', '98362', '(360) 417-2425', 'https://clallamtransit.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['ADA Paratransit', 'Medical Transportation'], ARRAY['transportation', 'paratransit', 'ADA', 'Clallam County', 'Olympic Peninsula'], 'transportation Clallam Transit paratransit Port Angeles', 48.1190, -123.4333),
  ('Washington State Medical Transportation - Statewide', 'Paratransit', 'Non-emergency medical transportation for Medicaid recipients statewide.', 'PO Box 42700', 'Olympia', 'Thurston', '98504', '(800) 786-4366', 'https://hca.wa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, false, false, true, false, false, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Medical Transportation', 'Statewide Service'], ARRAY['transportation', 'medical transport', 'Medicaid', 'statewide'], 'transportation statewide Medicaid medical transport Washington', 47.0355, -122.9055)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
