/*
# Add Independent Rural Primary Care Clinics

1. Data Insert
- Adds rural primary care clinics across WA: KVH Ellensburg, Confluence Health
  Moses Lake & East Wenatchee, Astria Toppenish & Sunnyside, Olympic Medical
  Port Angeles (OMP), North Olympic Health Care Network, WhidbeyHealth Oak Harbor.
2. Source
- Verified via KVH, Confluence Health, Astria, Olympic Medical, WhidbeyHealth
  websites.
3. Notes
- primary-care category. medicaid / medicare / private_insurance = true.
- ON CONFLICT DO NOTHING.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('KVH Family Medicine - Ellensburg', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'Kittitas Valley Healthcare rural health clinic providing family medicine for all ages including MOUD (medication for opioid use disorder). Affiliated with Kittitas Valley Healthcare hospital.', '502 N Main St', 'Ellensburg', 'Kittitas', 'WA', '98926', '509-933-2600', 'https://www.kvhealthcare.org/clinics-and-specialty-services/family-medicine-ellensburg', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 80, 150, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Primary Care,MOUD,Chronic Disease Management,Wellness Visits,Immunizations}', '{Family Medicine}', '{Families,Adults,Seniors,Children}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Confluence Health - Moses Lake Campus', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'Confluence Health Moses Lake campus providing primary care, walk-in care, women''s health, behavioral health, anticoagulation, radiation oncology and specialty care services.', '840 E Hill Ave', 'Moses Lake', 'Grant', 'WA', '98837', '509-764-6400', 'https://www.confluencehealth.org/locations/moses-lake-campus', '{"mon":"7:30-17:00","tue":"7:30-17:00","wed":"7:30-17:00","thu":"7:30-17:00","fri":"7:30-17:00","sat":"Closed","sun":"7:30-15:30"}'::jsonb, true, true, true, true, true, true, true, true, false, 90, 200, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Primary Care,Walk-In,Women''s Health,Behavioral Health,Oncology}', '{Family Medicine,Internal Medicine}', '{Families,Adults,Seniors}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Confluence Health - East Wenatchee Clinic', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'Confluence Health East Wenatchee clinic providing primary care, DirectCare walk-in, and specialty services for the East Wenatchee/Douglas County community.', '100 Highline Dr', 'East Wenatchee', 'Douglas', 'WA', '98802', '509-663-8711', 'https://www.confluencehealth.org/locations/east-wenatchee-clinic', '{"mon":"7:00-17:00","tue":"7:00-17:00","wed":"7:00-17:00","thu":"7:00-17:00","fri":"7:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 90, 200, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Primary Care,DirectCare Walk-In,Specialty Services}', '{Family Medicine,Internal Medicine}', '{Families,Adults,Seniors}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Astria Health Center Sunnyside', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'Astria Health Center primary care and behavioral health clinic in Sunnyside serving the Lower Yakima Valley with family medicine and behavioral health services.', '2705 E Lincoln Ave', 'Sunnyside', 'Yakima', 'WA', '98944', '509-837-2602', 'https://astria.health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 80, 150, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Primary Care,Behavioral Health,Chronic Disease Management}', '{Family Medicine}', '{Families,Adults,Seniors}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Astria Health Center Toppenish', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'Astria Health Center primary care clinic in Toppenish providing family medicine and behavioral health services for the Lower Yakima Valley community, affiliated with Astria Toppenish Hospital.', '1016 Tacoma Ave', 'Toppenish', 'Yakima', 'WA', '98948', '509-865-5660', 'https://astria.health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 80, 150, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Primary Care,Behavioral Health,Chronic Disease Management}', '{Family Medicine}', '{Families,Adults,Seniors}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('OMP Primary Care Clinic - Port Angeles', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'Olympic Medical Physicians primary care clinic in Port Angeles providing family medicine and behavioral health services, affiliated with Olympic Medical Center.', '939 E 1st St', 'Port Angeles', 'Clallam', 'WA', '98362', '360-565-0999', 'https://www.olympicmedical.org/services/primary-care', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 90, 180, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Behavioral Health,Family Medicine}', '{Family Medicine}', '{Families,Adults,Seniors}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('WhidbeyHealth Primary Care - Oak Harbor', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'WhidbeyHealth primary care clinic in Oak Harbor providing family medicine, chronic disease management, preventive care, and pediatric care for Whidbey Island residents.', '275 SE Cabot Dr, Ste B101', 'Oak Harbor', 'Island', 'WA', '98277', '360-675-6648', 'https://whidbeyhealth.org/locations/primary-care-oak-harbor', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 90, 180, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Chronic Disease Management,Preventive Care,Pediatrics}', '{Family Medicine,Pediatrics}', '{Families,Adults,Seniors,Children}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('North Olympic Health Care Network', (SELECT id FROM resource_categories WHERE slug='primary-care'), '', 'North Olympic Health Care Network independent primary care clinic in Port Angeles providing family medicine, internal medicine, behavioral health and chronic disease management for Clallam County.', '240 W Front St, Ste A', 'Port Angeles', 'Clallam', 'WA', '98362', '360-452-7891', 'https://www.nohcn.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 90, 180, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Behavioral Health,Chronic Disease Management,Family Medicine,Internal Medicine}', '{Family Medicine,Internal Medicine}', '{Families,Adults,Seniors}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;