/*
# Add Specialty Services - Vision, Hearing, Women's Health, and More

1. Purpose
   - Add specialty healthcare services across Washington state
   - Include vision clinics, hearing services, and women's health

2. Coverage
   - All Washington counties with specialty care
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'community-org'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Vision Services
  ('Sight Connection - Seattle', 'Vision Services', 'Low vision services and adaptive equipment for people with vision impairments.', '1105 E Pike St', 'Seattle', 'King', '98122', '(206) 325-2937', 'https://sightconnection.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Low Vision Services', 'Adaptive Equipment', 'Counseling'], ARRAY['vision', 'low vision', 'blindness', 'adaptive equipment', 'Seattle'], 'vision Sight Connection Seattle low vision adaptive equipment blindness services', 47.6148, -122.3210),
  ('Vision USA - Seattle', 'Vision Services', 'Free eye exams for low-income uninsured individuals.', '222 E Thomas St', 'Seattle', 'King', '98102', '(206) 323-4000', 'https://visionusa.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Free Eye Exams', 'Glasses Programs'], ARRAY['vision', 'free eye exam', 'glasses', 'low income', 'Seattle'], 'vision Vision USA Seattle free eye exam glasses low income uninsured', 47.6199, -122.3215),
  ('Lions Club Vision Screening - Statewide', 'Vision Services', 'Free vision screening and eyeglass assistance through Lions Clubs statewide.', 'PO Box 9000', 'Seattle', 'King', '98109', '(800) 283-7263', 'https://lionsclubs.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Vision Screening', 'Eyeglass Assistance'], ARRAY['vision', 'Lions Club', 'free glasses', 'screening', 'statewide'], 'vision Lions Club statewide free glasses vision screening', 47.6230, -122.3370),
  ('Puget Sound Lions Eye Bank', 'Vision Services', 'Eye tissue recovery and distribution for corneal transplants.', '550 17th Ave', 'Seattle', 'King', '98122', '(206) 682-8500', 'https://psleb.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Corneal Transplants', 'Eye Tissue Services'], ARRAY['vision', 'eye bank', 'corneal transplant', 'Seattle'], 'vision Puget Sound Lions Eye Bank corneal transplant eye tissue', 47.6047, -122.3144),
  -- Hearing Services
  ('Hearing Speech and Deafness Center - Seattle', 'Hearing Services', 'Comprehensive hearing services including audiometry, hearing aids, and speech therapy.', '1620 18th Ave', 'Seattle', 'King', '98122', '(206) 632-8600', 'https://hsdc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'ASL'], ARRAY['Hearing Tests', 'Hearing Aids', 'Speech Therapy', 'Sign Language'], ARRAY['hearing', 'deaf', 'speech', 'ASL', 'hearing aids', 'Seattle'], 'hearing Hearing Speech Deafness Center Seattle audiometry hearing aids speech therapy ASL', 47.6147, -122.3130),
  ('Washington Hearing and Speech Agency - Spokane', 'Hearing Services', 'Hearing and speech services for Eastern Washington.', '426 W Francis Ave', 'Spokane', 'Spokane', '99205', '(509) 328-6023', 'https://whsa.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Russian'], ARRAY['Hearing Tests', 'Hearing Aids', 'Speech Therapy'], ARRAY['hearing', 'speech', 'Spokane', 'Eastern Washington'], 'hearing Washington Hearing Speech Agency Spokane audiometry speech therapy', 47.7091, -117.4271),
  ('Communication Center for Deaf and Hard of Hearing - Tacoma', 'Hearing Services', 'Communication services for deaf and hard of hearing individuals.', '3806 W Yakima Ave', 'Tacoma', 'Pierce', '98466', '(253) 564-0444', 'https://ccdhh.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'ASL'], ARRAY['Interpreting Services', 'Advocacy', 'Communication Support'], ARRAY['hearing', 'deaf', 'ASL', 'interpreting', 'Tacoma'], 'hearing Communication Center Deaf Hard Hearing Tacoma ASL interpreting', 47.2617, -122.4935),
  -- Women's Health
  ('Planned Parenthood - Capitol Hill', 'Womens Health', 'Reproductive health services including contraception, STI testing, and cancer screenings.', '2200 E Madison St', 'Seattle', 'King', '98112', '(206) 328-7700', 'https://plannedparenthood.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Family Planning', 'STI Testing', 'Cancer Screening', 'Contraception'], ARRAY['womens health', 'Planned Parenthood', 'reproductive health', 'STI testing', 'Seattle'], 'womens health Planned Parenthood Capitol Hill Seattle family planning contraception STI testing', 47.6217, -122.3006),
  ('Planned Parenthood - Everett', 'Womens Health', 'Reproductive health services for Snohomish County.', '2730 Rucker Ave', 'Everett', 'Snohomish', '98201', '(425) 339-8288', 'https://plannedparenthood.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Family Planning', 'STI Testing', 'Cancer Screening'], ARRAY['womens health', 'Planned Parenthood', 'Everett', 'Snohomish'], 'womens health Planned Parenthood Everett Snohomish reproductive health', 47.9693, -122.1981),
  ('Planned Parenthood - Spokane', 'Womens Health', 'Reproductive health services for Eastern Washington.', '123 E Indiana Ave', 'Spokane', 'Spokane', '99207', '(509) 328-2838', 'https://plannedparenthood.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Russian'], ARRAY['Family Planning', 'STI Testing', 'Cancer Screening'], ARRAY['womens health', 'Planned Parenthood', 'Spokane', 'Eastern Washington'], 'womens health Planned Parenthood Spokane reproductive health Eastern Washington', 47.6740, -117.3954),
  ('Planned Parenthood - Tacoma', 'Womens Health', 'Reproductive health services for Pierce County.', '4222 Pacific Ave', 'Tacoma', 'Pierce', '98418', '(253) 474-7031', 'https://plannedparenthood.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Family Planning', 'STI Testing', 'Cancer Screening'], ARRAY['womens health', 'Planned Parenthood', 'Tacoma', 'Pierce County'], 'womens health Planned Parenthood Tacoma Pierce County reproductive health', 47.2201, -122.4263),
  ('First Step Family Support Center - Bremerton', 'Womens Health', 'Pregnancy support and parenting education for Kitsap County.', '1118 Harlow Dr', 'Bremerton', 'Kitsap', '98312', '(360) 479-9244', 'https://firststepfamily.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Pregnancy Support', 'Parenting Education', 'Baby Supplies'], ARRAY['womens health', 'pregnancy', 'parenting', 'Bremerton', 'Kitsap'], 'womens health First Step Family Support Bremerton pregnancy parenting education', 47.5700, -122.6750),
  -- HIV/AIDS Services
  ('Lifelong AIDS Alliance - Seattle', 'HIV Services', 'Comprehensive HIV/AIDS services including case management, housing, and food programs.', '1000 E Union St', 'Seattle', 'King', '98122', '(206) 957-1600', 'https://lifelong.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Case Management', 'Housing Assistance', 'Food Programs', 'Medical Care'], ARRAY['HIV', 'AIDS', 'case management', 'housing', 'Seattle'], 'HIV AIDS Lifelong AIDS Alliance Seattle case management housing food programs', 47.6112, -122.3115),
  ('Evergreen Health - Seattle', 'HIV Services', 'HIV/AIDS care and prevention services.', '4317 Rainier Ave S', 'Seattle', 'King', '98118', '(206) 850-1550', 'https://evergreenhealth.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['HIV Care', 'Testing', 'Prevention'], ARRAY['HIV', 'AIDS', 'testing', 'prevention', 'Seattle'], 'HIV AIDS Evergreen Health Seattle care testing prevention', 47.5490, -122.2922),
  ('Spokane AIDS Network', 'HIV Services', 'HIV/AIDS services for Eastern Washington.', '200 W Mission Ave', 'Spokane', 'Spokane', '99201', '(509) 455-8700', 'https://spokaneaidsnetwork.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, true, ARRAY['English'], ARRAY['HIV Care', 'Case Management', 'Support Groups'], ARRAY['HIV', 'AIDS', 'Spokane', 'Eastern Washington'], 'HIV AIDS Spokane AIDS Network Eastern Washington case management support', 47.6548, -117.4272),
  -- Kidney/Dialysis Centers
  ('DaVita Dialysis Center - Seattle', 'Dialysis', 'Dialysis services for patients with kidney disease.', '1800 12th Ave S', 'Seattle', 'King', '98144', '(206) 329-6337', 'https://davita.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Peritoneal Dialysis', 'Kidney Care Education'], ARRAY['dialysis', 'kidney', 'DaVita', 'Seattle', 'hemodialysis'], 'dialysis DaVita Seattle hemodialysis peritoneal kidney care', 47.5856, -122.3147),
  ('Fresenius Kidney Care - Tacoma', 'Dialysis', 'Dialysis center serving Pierce County.', '1902 E 64th St', 'Tacoma', 'Pierce', '98404', '(253) 473-5235', 'https://freseniuskidneycare.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Kidney Care Education'], ARRAY['dialysis', 'kidney', 'Fresenius', 'Tacoma'], 'dialysis Fresenius Kidney Care Tacoma hemodialysis Pierce County', 47.2440, -122.3987),
  ('DaVita Dialysis Center - Spokane', 'Dialysis', 'Dialysis services for Eastern Washington.', '1919 E 29th Ave', 'Spokane', 'Spokane', '99203', '(509) 535-5990', 'https://davita.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Russian'], ARRAY['Hemodialysis', 'Peritoneal Dialysis'], ARRAY['dialysis', 'kidney', 'DaVita', 'Spokane'], 'dialysis DaVita Spokane hemodialysis Eastern Washington kidney', 47.6290, -117.3965),
  -- Physical/Occupational Therapy
  ('Physiotherapy Associates - Seattle', 'Physical Therapy', 'Physical therapy and rehabilitation services.', '1300 140th Ave NE', 'Bellevue', 'King', '98005', '(425) 644-2400', 'https://physiotherapy.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Occupational Therapy', 'Sports Medicine'], ARRAY['physical therapy', 'rehabilitation', 'occupational therapy', 'Bellevue'], 'physical therapy Physiotherapy Associates Bellevue rehabilitation sports medicine', 47.6132, -122.1540),
  ('Providence Physical Therapy - Olympia', 'Physical Therapy', 'Physical therapy and rehabilitation services.', '411 Lilly Rd NE', 'Olympia', 'Thurston', '98506', '(360) 493-4444', 'https://providence.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Occupational Therapy'], ARRAY['physical therapy', 'rehabilitation', 'Olympia', 'Thurston'], 'physical therapy Providence Physical Therapy Olympia rehabilitation Thurston', 47.0504, -122.8643),
  ('Confluence Health Physical Therapy - Wenatchee', 'Physical Therapy', 'Physical therapy and rehabilitation for North Central Washington.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-8711', 'https://confluencehealth.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Physical Therapy', 'Occupational Therapy'], ARRAY['physical therapy', 'rehabilitation', 'Wenatchee', 'Chelan'], 'physical therapy Confluence Health Wenatchee rehabilitation North Central Washington', 47.4261, -120.3136),
  -- Home Health Services
  ('Providence Home Health - Seattle', 'Home Health', 'In-home nursing and therapy services for homebound patients.', '1717 114th Ave SE', 'Bellevue', 'King', '98004', '(206) 329-5444', 'https://providence.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Skilled Nursing', 'Physical Therapy', 'Occupational Therapy', 'Home Health Aide'], ARRAY['home health', 'skilled nursing', 'in-home care', 'Bellevue', 'Seattle'], 'home health Providence Home Health Seattle Bellevue skilled nursing therapy in-home care', 47.5936, -122.1819),
  ('MultiCare Home Health - Tacoma', 'Home Health', 'In-home health services for Pierce County.', '315 Martin Luther King Jr Way', 'Tacoma', 'Pierce', '98405', '(253) 403-2000', 'https://multicare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Skilled Nursing', 'Physical Therapy', 'Occupational Therapy'], ARRAY['home health', 'skilled nursing', 'in-home care', 'Tacoma', 'Pierce'], 'home health MultiCare Home Health Tacoma Pierce County skilled nursing in-home', 47.2533, -122.4496),
  ('PeaceHealth Home Health - Bellingham', 'Home Health', 'In-home health services for Whatcom County.', '2940 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 734-5400', 'https://peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Skilled Nursing', 'Physical Therapy', 'Occupational Therapy'], ARRAY['home health', 'skilled nursing', 'in-home care', 'Bellingham', 'Whatcom'], 'home health PeaceHealth Home Health Bellingham Whatcom skilled nursing in-home', 48.7690, -122.4850)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
