/*
# Add Additional Resources for Underserved Counties and More Services

1. Purpose
   - Add more resources for counties with fewer services
   - Add rural health clinics, free clinics, and additional community services
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'primary-care'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Lincoln County Health Center - Davenport', 'Rural Health Clinic', 'Rural health clinic serving Lincoln County with primary care services.', '511 Webb St', 'Davenport', 'Lincoln', '99122', '(509) 725-3331', 'https://lincolncountyhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Preventive Care', 'Chronic Disease Management'], ARRAY['rural health', 'Lincoln County', 'primary care', 'Davenport'], 'rural health Lincoln County Health Center Davenport primary care', 47.6774, -118.1420),
  ('Columbia County Public Health - Dayton', 'Rural Health Clinic', 'Public health and primary care services for Columbia County.', '202 S 3rd St', 'Dayton', 'Columbia', '99328', '(509) 382-2593', 'https://columbiacountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Columbia County', 'public health', 'Dayton'], 'rural health Columbia County Public Health Dayton primary care immunizations', 46.3193, -117.9862),
  ('Garfield County Health District - Pomeroy', 'Rural Health Clinic', 'Public health services for Garfield County residents.', '710 Main St', 'Pomeroy', 'Garfield', '99347', '(509) 843-1451', 'https://garfieldcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Garfield County', 'public health', 'Pomeroy'], 'rural health Garfield County Health District Pomeroy public health', 46.4716, -117.5944),
  ('Wahkiakum Health and Human Services - Cathlamet', 'Rural Health Clinic', 'Public health and human services for Wahkiakum County.', '42 Main St', 'Cathlamet', 'Wahkiakum', '98612', '(360) 795-8658', 'https://wahkiakumcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Social Services'], ARRAY['rural health', 'Wahkiakum County', 'public health', 'Cathlamet'], 'rural health Wahkiakum Health Human Services Cathlamet public health', 46.2046, -123.3861),
  ('Adams County Health Department - Ritzville', 'Rural Health Clinic', 'Public health services for Adams County.', '425 E Galbraith St', 'Ritzville', 'Adams', '99169', '(509) 659-1202', 'https://adamscountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Adams County', 'public health', 'Ritzville'], 'rural health Adams County Health Department Ritzville public health immunizations', 47.1265, -118.3772),
  ('Whitman County Public Health - Colfax', 'Rural Health Clinic', 'Public health services for Whitman County.', '310 N Main St', 'Colfax', 'Whitman', '99111', '(509) 397-6280', 'https://whitmancountypublichealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Whitman County', 'public health', 'Colfax'], 'rural health Whitman County Public Health Colfax primary care', 46.8803, -117.3637),
  ('Pullman Family Medicine', 'Rural Health Clinic', 'Family medicine clinic serving Whitman County.', '715 SE Professional Mall Blvd', 'Pullman', 'Whitman', '99163', '(509) 334-1102', 'https://pullmanfamilymedicine.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Family Medicine', 'Primary Care', 'Preventive Care'], ARRAY['rural health', 'Pullman', 'Whitman County', 'family medicine'], 'rural health Pullman Family Medicine Whitman County primary care', 46.7287, -117.1657),
  ('Ferry County Health Center - Republic', 'Rural Health Clinic', 'Rural health clinic serving Ferry County.', '65 N Keller St', 'Republic', 'Ferry', '99166', '(509) 775-3341', 'https://ferrycountyhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Emergency Care', 'Telehealth'], ARRAY['rural health', 'Ferry County', 'Republic', 'primary care'], 'rural health Ferry County Health Center Republic primary care telehealth', 48.6508, -118.7328),
  ('Pend Oreille County Health - Newport', 'Rural Health Clinic', 'Public health and primary care for Pend Oreille County.', '710 S Scott Ave', 'Newport', 'Pend Oreille', '99156', '(509) 447-3131', 'https://pendoreillecountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Pend Oreille County', 'Newport', 'public health'], 'rural health Pend Oreille County Health Newport public health primary care', 48.1772, -117.0499),
  ('Stevens County Health Center - Chewelah', 'Rural Health Clinic', 'Rural health clinic serving Stevens County.', '201 E 4th Ave', 'Chewelah', 'Stevens', '99109', '(509) 935-4100', 'https://stevenscountyhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Preventive Care', 'Chronic Disease Management'], ARRAY['rural health', 'Stevens County', 'Chewelah', 'primary care'], 'rural health Stevens County Health Center Chewelah primary care', 48.2789, -117.7117),
  ('Douglas County Health Center - East Wenatchee', 'Rural Health Clinic', 'Primary care for Douglas County residents.', '1310 19th St N', 'East Wenatchee', 'Douglas', '98802', '(509) 886-6400', 'https://douglascountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Public Health', 'Immunizations'], ARRAY['rural health', 'Douglas County', 'East Wenatchee', 'primary care'], 'rural health Douglas County Health Center East Wenatchee primary care', 47.4212, -120.2866),
  ('Klickitat County Health Department - Goldendale', 'Rural Health Clinic', 'Public health services for Klickitat County.', '115 W Court St', 'Goldendale', 'Klickitat', '98620', '(509) 773-2144', 'https://klickitatcounty.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Klickitat County', 'Goldendale', 'public health'], 'rural health Klickitat County Health Department Goldendale public health', 45.8210, -120.8242),
  ('Skamania County Health Department - Stevenson', 'Rural Health Clinic', 'Public health services for Skamania County.', '710 SW Rock Creek Dr', 'Stevenson', 'Skamania', '98648', '(509) 427-3800', 'https://skamaniacounty.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Skamania County', 'Stevenson', 'public health'], 'rural health Skamania County Health Department Stevenson public health', 45.6951, -121.8848),
  ('Pacific County Health Department - South Bend', 'Rural Health Clinic', 'Public health services for Pacific County.', '7013 E Hackman Dr', 'South Bend', 'Pacific', '98586', '(360) 875-5741', 'https://pacificcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Pacific County', 'South Bend', 'public health'], 'rural health Pacific County Health Department South Bend public health', 46.6422, -123.7265),
  ('Island County Public Health - Coupeville', 'Rural Health Clinic', 'Public health services for Island County.', '675 SE Main St', 'Coupeville', 'Island', '98239', '(360) 679-7350', 'https://islandcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Island County', 'Coupeville', 'Whidbey Island', 'public health'], 'rural health Island County Public Health Coupeville Whidbey Island public health', 48.2194, -122.6874),
  ('San Juan County Health Department - Friday Harbor', 'Rural Health Clinic', 'Public health services for San Juan Islands.', '410 Spring St', 'Friday Harbor', 'San Juan', '98250', '(360) 378-4471', 'https://sanjuanco.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'San Juan County', 'Friday Harbor', 'San Juan Islands', 'public health'], 'rural health San Juan County Health Friday Harbor public health San Juan Islands', 48.5345, -123.0192),
  ('Mason County Public Health - Shelton', 'Rural Health Clinic', 'Public health services for Mason County.', '224 E Inyo St', 'Shelton', 'Mason', '98584', '(360) 427-9670', 'https://co.mason.wa.us', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Public Health', 'Primary Care', 'Immunizations'], ARRAY['rural health', 'Mason County', 'Shelton', 'public health'], 'rural health Mason County Public Health Shelton public health immunizations', 47.2151, -123.1088),
  ('Seattle Free Clinic', 'Free Clinic', 'Free medical care for uninsured adults in the Seattle area.', '2100 24th Ave S', 'Seattle', 'King', '98144', '(206) 336-0990', 'https://seattlefreeclinic.org', '{"monday": "5pm-9pm", "tuesday": "closed", "wednesday": "5pm-9pm", "thursday": "closed", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Seattle'], 'free clinic Seattle Free Clinic uninsured free medical care primary care', 47.5840, -122.2956),
  ('Spokane Free Clinic', 'Free Clinic', 'Free medical care for uninsured adults in Spokane.', '1820 E Sprague Ave', 'Spokane', 'Spokane', '99202', '(509) 535-6175', 'https://spokanefreeclinic.org', '{"monday": "closed", "tuesday": "5pm-9pm", "wednesday": "closed", "thursday": "5pm-9pm", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Russian'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Spokane'], 'free clinic Spokane Free Clinic uninsured free medical care primary care', 47.6567, -117.3583),
  ('Tacoma Free Clinic', 'Free Clinic', 'Free medical care for uninsured adults in Pierce County.', '2420 S Union Ave', 'Tacoma', 'Pierce', '98405', '(253) 322-6650', 'https://tacomaclinic.org', '{"monday": "closed", "tuesday": "5pm-9pm", "wednesday": "closed", "thursday": "5pm-9pm", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Tacoma'], 'free clinic Tacoma Free Clinic uninsured free medical Pierce County', 47.2402, -122.4710),
  ('Olympia Free Clinic', 'Free Clinic', 'Free medical care for uninsured adults in Thurston County.', '1005 SE Stonehurst Dr', 'Olympia', 'Thurston', '98501', '(360) 352-4140', 'https://olympiafreeclinic.org', '{"monday": "closed", "tuesday": "closed", "wednesday": "5pm-9pm", "thursday": "closed", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Olympia'], 'free clinic Olympia Free Clinic uninsured free medical Thurston County', 47.0268, -122.8705),
  ('Bellingham Free Clinic', 'Free Clinic', 'Free medical care for uninsured in Whatcom County.', '219 N Beech St', 'Bellingham', 'Whatcom', '98225', '(360) 671-4412', 'https://bellinghamfreeclinic.org', '{"monday": "closed", "tuesday": "5pm-9pm", "wednesday": "closed", "thursday": "5pm-9pm", "friday": "closed", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Bellingham'], 'free clinic Bellingham Free Clinic uninsured free medical Whatcom County', 48.7480, -122.4754),
  ('Tri-Cities Free Clinic - Richland', 'Free Clinic', 'Free medical care for uninsured adults.', '1200 Jadwin Ave', 'Richland', 'Benton', '99352', '(509) 375-3200', 'https://tricityfreeclinic.org', '{"monday": "closed", "tuesday": "5pm-9pm", "wednesday": "closed", "thursday": "5pm-9pm", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Tri-Cities', 'Richland'], 'free clinic Tri-Cities Free Clinic Richland uninsured free medical Benton', 46.2806, -119.2831),
  ('Vancouver Free Clinic', 'Free Clinic', 'Free medical care for uninsured in Clark County.', '4700 NE 77th Ave', 'Vancouver', 'Clark', '98662', '(360) 696-3388', 'https://freeclinicofvancouver.org', '{"monday": "closed", "tuesday": "closed", "wednesday": "5pm-9pm", "thursday": "closed", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Vancouver', 'Clark County'], 'free clinic Vancouver Free Clinic uninsured free medical Clark County', 45.6700, -122.6062),
  ('Yakima Free Clinic', 'Free Clinic', 'Free medical care for uninsured in Yakima County.', '1012 S 16th Ave', 'Yakima', 'Yakima', '98902', '(509) 574-5100', 'https://yakimafreeclinic.org', '{"monday": "closed", "tuesday": "5pm-9pm", "wednesday": "closed", "thursday": "5pm-9pm", "friday": "closed", "saturday": "10am-2pm", "sunday": "closed"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Chronic Disease Management', 'Referrals'], ARRAY['free clinic', 'uninsured', 'free medical', 'Yakima'], 'free clinic Yakima Free Clinic uninsured free medical Yakima County', 46.5892, -120.5432)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
