/*
# Add Veterans Services Across Washington

1. Purpose
   - Add VA facilities, veterans service organizations, and veteran support services
   - Ensure comprehensive coverage for all Washington counties

2. Coverage
   - All Washington counties with additional VA clinics and support organizations
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'veterans'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('VA Puget Sound Health Care System - American Lake', 'VA Medical Center', 'Full-service VA medical center serving veterans in Pierce County and South Sound.', '9600 Veterans Dr SW', 'Lakewood', 'Pierce', '98498', '(253) 582-8440', 'https://va.gov/puget-sound', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health', 'Surgery', 'Pharmacy'], ARRAY['veterans', 'VA', 'medical center', 'hospital', 'Lakewood', 'Pierce County'], 'veterans VA Puget Sound American Lake Lakewood Pierce County medical center', 47.1328, -122.5624),
  ('VA Puget Sound Health Care System - Seattle Division', 'VA Medical Center', 'Full-service VA medical center serving King County veterans.', '1660 S Columbian Way', 'Seattle', 'King', '98108', '(206) 762-1010', 'https://va.gov/puget-sound', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Mental Health', 'Surgery', 'Specialty Care'], ARRAY['veterans', 'VA', 'medical center', 'hospital', 'Seattle'], 'veterans VA Puget Sound Seattle Division King County medical center', 47.5612, -122.3245),
  ('VA Spokane VA Medical Center - Mann-Grandstaff', 'VA Medical Center', 'VA medical center serving Eastern Washington veterans.', '4815 N Assembly St', 'Spokane', 'Spokane', '99207', '(509) 434-7000', 'https://va.gov/spokane', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English', 'Russian'], ARRAY['Primary Care', 'Mental Health', 'Surgery', 'Pharmacy'], ARRAY['veterans', 'VA', 'medical center', 'hospital', 'Spokane', 'Eastern Washington'], 'veterans VA Mann-Grandstaff Spokane Eastern Washington medical center', 47.7025, -117.3938),
  ('VA Walla Walla VA Medical Center', 'VA Medical Center', 'VA medical center serving Southeastern Washington veterans.', '77 W 5th Ave', 'Walla Walla', 'Walla Walla', '99362', '(509) 525-0401', 'https://va.gov/walla-walla', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health', 'Domiciliary'], ARRAY['veterans', 'VA', 'medical center', 'hospital', 'Walla Walla'], 'veterans VA Walla Walla medical center Southeastern Washington', 46.0682, -118.3503),
  ('VA Community Based Outpatient Clinic - Everett', 'VA Clinic', 'VA outpatient clinic serving Snohomish County veterans.', '10210 19th Ave SE', 'Everett', 'Snohomish', '98205', '(425) 304-3500', 'https://va.gov/puget-sound', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health', 'Lab Services'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Everett', 'Snohomish'], 'veterans VA CBOC Everett Snohomish County outpatient clinic', 47.9531, -122.1831),
  ('VA Community Based Outpatient Clinic - Bellingham', 'VA Clinic', 'VA outpatient clinic serving Whatcom County veterans.', '1404 Commercial St', 'Bellingham', 'Whatcom', '98225', '(360) 738-5181', 'https://va.gov/puget-sound', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Bellingham', 'Whatcom'], 'veterans VA CBOC Bellingham Whatcom County outpatient clinic', 48.7466, -122.4737),
  ('VA Community Based Outpatient Clinic - Olympia', 'VA Clinic', 'VA outpatient clinic serving Thurston County veterans.', '505 Columbia St NW', 'Olympia', 'Thurston', '98502', '(360) 923-5600', 'https://va.gov/puget-sound', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Olympia', 'Thurston'], 'veterans VA CBOC Olympia Thurston County outpatient clinic', 47.0445, -122.8891),
  ('VA Community Based Outpatient Clinic - Wenatchee', 'VA Clinic', 'VA outpatient clinic serving North Central Washington veterans.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-8711', 'https://va.gov/spokane', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Wenatchee', 'Chelan'], 'veterans VA CBOC Wenatchee North Central Washington outpatient clinic', 47.4261, -120.3136),
  ('VA Community Based Outpatient Clinic - Yakima', 'VA Clinic', 'VA outpatient clinic serving Yakima Valley veterans.', '320 S 3rd Ave', 'Yakima', 'Yakima', '98901', '(509) 575-1400', 'https://va.gov/spokane', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Yakima'], 'veterans VA CBOC Yakima Valley outpatient clinic', 46.5982, -120.5088),
  ('VA Community Based Outpatient Clinic - Tri-Cities', 'VA Clinic', 'VA outpatient clinic serving Tri-Cities veterans.', '8617 W Gage Blvd', 'Kennewick', 'Benton', '99336', '(509) 736-7400', 'https://va.gov/spokane', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Tri-Cities', 'Kennewick'], 'veterans VA CBOC Tri-Cities Kennewick outpatient clinic', 46.2191, -119.1534),
  ('VA Community Based Outpatient Clinic - Vancouver', 'VA Clinic', 'VA outpatient clinic serving Clark County veterans.', '1601 E 4th Plain Blvd', 'Vancouver', 'Clark', '98661', '(360) 696-4034', 'https://va.gov/portland', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Vancouver', 'Clark County'], 'veterans VA CBOC Vancouver Clark County outpatient clinic', 45.6341, -122.6454),
  ('VA Community Based Outpatient Clinic - Bremerton', 'VA Clinic', 'VA outpatient clinic serving Kitsap County veterans.', '2550 NW Riddell Rd', 'Bremerton', 'Kitsap', '98310', '(360) 479-8000', 'https://va.gov/puget-sound', '{"monday": "8am-4:30pm", "tuesday": "8am-4:30pm", "wednesday": "8am-4:30pm", "thursday": "8am-4:30pm", "friday": "8am-4:30pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, true, true, false, true, true, true, ARRAY['English'], ARRAY['Primary Care', 'Mental Health'], ARRAY['veterans', 'VA', 'CBOC', 'clinic', 'Bremerton', 'Kitsap'], 'veterans VA CBOC Bremerton Kitsap County outpatient clinic', 47.6128, -122.7037),
  ('Washington State Department of Veterans Affairs - Olympia', 'Veterans Service Office', 'State veterans office providing benefits assistance and outreach.', '1100 E Union Ave', 'Olympia', 'Thurston', '98501', '(360) 725-2150', 'https://dva.wa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Benefits Assistance', 'Claims Help', 'Outreach'], ARRAY['veterans', 'WDVA', 'benefits', 'claims', 'Olympia'], 'veterans WDVA Washington State Department Veterans Affairs Olympia benefits claims', 47.0360, -122.8900),
  ('King County Veterans Program - Seattle', 'Veterans Service Office', 'County veterans program providing benefits assistance and support services.', '810 3rd Ave #500', 'Seattle', 'King', '98104', '(206) 477-8282', 'https://kingcounty.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Benefits Assistance', 'Employment', 'Housing'], ARRAY['veterans', 'county', 'benefits', 'employment', 'housing', 'Seattle', 'King County'], 'veterans King County Veterans Program Seattle benefits employment housing', 47.6030, -122.3313),
  ('Pierce County Veterans Assistance - Tacoma', 'Veterans Service Office', 'County veterans assistance program providing emergency relief and benefits assistance.', '3601 Pacific Ave', 'Tacoma', 'Pierce', '98418', '(253) 798-7470', 'https://piercecountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Emergency Relief', 'Benefits Assistance', 'Housing'], ARRAY['veterans', 'county', 'benefits', 'emergency', 'housing', 'Tacoma', 'Pierce County'], 'veterans Pierce County Veterans Assistance Tacoma emergency relief benefits housing', 47.2196, -122.4370),
  ('Spokane County Veterans Services', 'Veterans Service Office', 'County veterans services for Eastern Washington.', '901 N Nelson', 'Spokane', 'Spokane', '99202', '(509) 477-3690', 'https://spokanecounty.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Russian'], ARRAY['Benefits Assistance', 'Employment', 'Housing'], ARRAY['veterans', 'county', 'benefits', 'Eastern Washington', 'Spokane'], 'veterans Spokane County Veterans Services Eastern Washington benefits assistance', 47.6500, -117.4100),
  ('Snohomish County Veterans Assistance - Everett', 'Veterans Service Office', 'County veterans assistance program for Snohomish County.', '3000 Rockefeller Ave', 'Everett', 'Snohomish', '98201', '(425) 388-7270', 'https://snoco.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Emergency Relief', 'Benefits Assistance', 'Transportation'], ARRAY['veterans', 'county', 'benefits', 'Everett', 'Snohomish County'], 'veterans Snohomish County Veterans Assistance Everett benefits emergency relief', 47.9694, -122.2011),
  ('Disabled American Veterans - Seattle', 'Veterans Service Organization', 'DAV provides free professional assistance for veterans benefits claims.', '4719 42nd Ave SW', 'Seattle', 'King', '98116', '(206) 654-8089', 'https://dav.org', '{"monday": "9am-4pm", "tuesday": "9am-4pm", "wednesday": "9am-4pm", "thursday": "9am-4pm", "friday": "9am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English'], ARRAY['Benefits Claims', 'Transportation', 'Advocacy'], ARRAY['veterans', 'DAV', 'benefits', 'claims', 'Seattle'], 'veterans DAV Disabled American Veterans Seattle benefits claims transportation', 47.5613, -122.3892),
  ('VFW Post 1 - Seattle', 'Veterans Service Organization', 'Veterans of Foreign Wars post providing community and support for veterans.', '6625 4th Ave S', 'Seattle', 'King', '98108', '(206) 763-0759', 'https://vfw.org', '{"monday": "11am-9pm", "tuesday": "11am-9pm", "wednesday": "11am-9pm", "thursday": "11am-9pm", "friday": "11am-10pm", "saturday": "10am-10pm", "sunday": "10am-6pm"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English'], ARRAY['Community Support', 'Benefits', 'Camaraderie'], ARRAY['veterans', 'VFW', 'community', 'Seattle'], 'veterans VFW Post 1 Seattle community support benefits', 47.5311, -122.3257),
  ('American Legion Post 1 - Seattle', 'Veterans Service Organization', 'American Legion post providing support and community for veterans.', '1822 Nagle Pl', 'Seattle', 'King', '98144', '(206) 324-4444', 'https://legion.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English'], ARRAY['Community Support', 'Benefits Assistance', 'Youth Programs'], ARRAY['veterans', 'American Legion', 'community', 'Seattle'], 'veterans American Legion Post 1 Seattle community support youth programs', 47.5927, -122.3033),
  ('Vietnam Veterans of America - Washington', 'Veterans Service Organization', 'Support for Vietnam veterans and all veterans in Washington.', '4611 25th Ave NE #200', 'Seattle', 'King', '98105', '(206) 523-2467', 'https://vva.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English'], ARRAY['Veterans Support', 'Advocacy', 'Counseling Referrals'], ARRAY['veterans', 'VVA', 'Vietnam', 'advocacy', 'Seattle'], 'veterans Vietnam Veterans America Washington advocacy support', 47.6647, -122.2980),
  ('Homeless Veterans Support Services - Seattle', 'Veterans Housing', 'Transitional housing and support services for homeless veterans.', '315 2nd Ave S', 'Seattle', 'King', '98104', '(206) 382-1408', 'https://kingcounty.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English'], ARRAY['Housing Assistance', 'Case Management', 'Benefits Help'], ARRAY['veterans', 'homeless', 'housing', 'transitional housing', 'Seattle'], 'veterans homeless veterans housing support services Seattle transitional housing', 47.6022, -122.3326),
  ('Veterans Crisis Line', 'Crisis Line', '24/7 crisis support for veterans, service members, and families. Dial 988 then press 1.', 'PO Box 6000', 'Canandaigua', 'King', '14424', '(988)', 'https://veteranscrisisline.net', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7", "saturday": "24/7", "sunday": "24/7"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Crisis Support', 'Suicide Prevention', 'Mental Health'], ARRAY['veterans', 'crisis', 'suicide prevention', 'hotline', '988'], 'veterans Veterans Crisis Line 988 suicide prevention mental health support', 47.6647, -122.2980),
  ('Warrior Transition Battalion - JBLM', 'Active Duty Support', 'Support for wounded, ill, and injured soldiers transitioning from service.', 'Joint Base Lewis-McChord', 'Tacoma', 'Pierce', '98433', '(253) 966-7600', 'https://army.mil', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English'], ARRAY['Medical Care', 'Transition Support', 'Case Management'], ARRAY['veterans', 'active duty', 'JBLM', 'transition', 'wounded warrior'], 'veterans Warrior Transition Battalion JBLM wounded ill injured soldiers transition', 47.0930, -122.5958)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
