/*
# Add Pharmacies Across Washington

1. Purpose
   - Add pharmacies including chain and independent locations
   - Focus on medication access for all communities

2. Coverage
   - All Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'pharmacy'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('CVS Pharmacy - Capitol Hill', 'Retail Pharmacy', 'Full-service pharmacy with prescription services and over-the-counter medications.', '333 15th Ave E', 'Seattle', 'King', '98102', '(206) 860-0925', 'https://cvs.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-6pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations', 'Over-the-Counter'], ARRAY['pharmacy', 'CVS', 'vaccinations'], 'pharmacy CVS Capitol Hill Seattle prescriptions vaccinations', 47.6194, -122.3138),
  ('Rite Aid Pharmacy - West Seattle', 'Retail Pharmacy', 'Pharmacy with prescription services and health products.', '4541 California Ave SW', 'Seattle', 'King', '98116', '(206) 935-0611', 'https://riteaid.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Rite Aid'], 'pharmacy Rite Aid West Seattle prescriptions', 47.5628, -122.3853),
  ('Walgreens Pharmacy - University District', 'Retail Pharmacy', '24-hour pharmacy with prescription and immunization services.', '4700 University Way NE', 'Seattle', 'King', '98105', '(206) 523-1115', 'https://walgreens.com', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7", "saturday": "24/7", "sunday": "24/7"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Prescriptions', 'Vaccinations', '24-Hour'], ARRAY['pharmacy', 'Walgreens', '24-hour'], 'pharmacy Walgreens University District Seattle 24-hour prescriptions', 47.6634, -122.3096),
  ('Costco Pharmacy - Seattle', 'Retail Pharmacy', 'Member pharmacy with low-cost prescriptions.', '4500 4th Ave S', 'Seattle', 'King', '98134', '(206) 587-0050', 'https://costco.com', '{"monday": "10am-7pm", "tuesday": "10am-7pm", "wednesday": "10am-7pm", "thursday": "10am-7pm", "friday": "10am-7pm", "saturday": "10am-6pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Low-Cost Meds'], ARRAY['pharmacy', 'Costco', 'low cost'], 'pharmacy Costco Seattle low-cost prescriptions', 47.5803, -122.3282),
  ('Bartell Drugs Pharmacy - Ballard', 'Retail Pharmacy', 'Local Washington pharmacy chain with personalized service.', '5300 15th Ave NW', 'Seattle', 'King', '98107', '(206) 789-1550', 'https://bartelldrugs.com', '{"monday": "9am-9pm", "tuesday": "9am-9pm", "wednesday": "9am-9pm", "thursday": "9am-9pm", "friday": "9am-9pm", "saturday": "10am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Bartell', 'local'], 'pharmacy Bartell Drugs Ballard Seattle', 47.6697, -122.3761),
  ('CVS Pharmacy - Everett', 'Retail Pharmacy', 'Full-service pharmacy serving Snohomish County.', '1010 SE Everett Mall Way', 'Everett', 'Snohomish', '98208', '(425) 355-1122', 'https://cvs.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-6pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'CVS', 'Snohomish'], 'pharmacy CVS Everett Snohomish prescriptions', 47.9634, -122.1998),
  ('Rite Aid Pharmacy - Spokane Valley', 'Retail Pharmacy', 'Full-service pharmacy serving Spokane Valley.', '15520 E Sprague Ave', 'Spokane Valley', 'Spokane', '99216', '(509) 924-3323', 'https://riteaid.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Russian'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Rite Aid', 'Spokane Valley'], 'pharmacy Rite Aid Spokane Valley prescriptions', 47.6574, -117.2477),
  ('Walgreens Pharmacy - Tacoma', 'Retail Pharmacy', 'Pharmacy serving Pierce County with prescription services.', '3802 Bridgeport Way W', 'University Place', 'Pierce', '98466', '(253) 566-5455', 'https://walgreens.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-9pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish', 'Korean'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Walgreens', 'Pierce County'], 'pharmacy Walgreens Tacoma University Place prescriptions', 47.1307, -122.5308),
  ('CVS Pharmacy - Olympia', 'Retail Pharmacy', 'Full-service pharmacy serving Thurston County.', '1425 E 4th Ave', 'Olympia', 'Thurston', '98506', '(360) 943-7755', 'https://cvs.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-6pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'CVS', 'Olympia'], 'pharmacy CVS Olympia Thurston prescriptions', 47.0413, -122.8858),
  ('Rite Aid Pharmacy - Yakima', 'Retail Pharmacy', 'Pharmacy serving Yakima Valley with bilingual services.', '2400 W Nob Hill Blvd', 'Yakima', 'Yakima', '98902', '(509) 966-2101', 'https://riteaid.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Rite Aid', 'Yakima'], 'pharmacy Rite Aid Yakima Valley prescriptions', 46.5919, -120.5500),
  ('Walgreens Pharmacy - Tri-Cities - Kennewick', 'Retail Pharmacy', 'Pharmacy serving Benton County.', '3915 W Clearwater Ave', 'Kennewick', 'Benton', '99336', '(509) 783-4421', 'https://walgreens.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-9pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Walgreens', 'Tri-Cities'], 'pharmacy Walgreens Kennewick Tri-Cities prescriptions', 46.2170, -119.1777),
  ('CVS Pharmacy - Vancouver', 'Retail Pharmacy', 'Pharmacy serving Clark County.', '500 E Mill Plain Blvd', 'Vancouver', 'Clark', '98663', '(360) 693-3388', 'https://cvs.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-6pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'CVS', 'Vancouver', 'Clark County'], 'pharmacy CVS Vancouver Clark County prescriptions', 45.6255, -122.6640),
  ('Rite Aid Pharmacy - Bellingham', 'Retail Pharmacy', 'Pharmacy serving Whatcom County.', '1230 N State St', 'Bellingham', 'Whatcom', '98225', '(360) 733-1612', 'https://riteaid.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Rite Aid', 'Bellingham'], 'pharmacy Rite Aid Bellingham Whatcom prescriptions', 48.7509, -122.4839),
  ('Walgreens Pharmacy - Wenatchee', 'Retail Pharmacy', 'Pharmacy serving Chelan County.', '1201 N Miller St', 'Wenatchee', 'Chelan', '98801', '(509) 662-2470', 'https://walgreens.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-6pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Walgreens', 'Wenatchee'], 'pharmacy Walgreens Wenatchee Chelan prescriptions', 47.4354, -120.3401),
  ('CVS Pharmacy - Port Angeles', 'Retail Pharmacy', 'Pharmacy serving Olympic Peninsula.', '110 E 1st St', 'Port Angeles', 'Clallam', '98362', '(360) 452-8301', 'https://cvs.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'CVS', 'Olympic Peninsula', 'Port Angeles'], 'pharmacy CVS Port Angeles Olympic Peninsula prescriptions', 48.1240, -123.4314),
  ('Rite Aid Pharmacy - Moses Lake', 'Retail Pharmacy', 'Pharmacy serving Grant County.', '922 E Broadway Ave', 'Moses Lake', 'Grant', '98837', '(509) 765-4188', 'https://riteaid.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Rite Aid', 'Moses Lake', 'Grant County'], 'pharmacy Rite Aid Moses Lake Grant County prescriptions', 47.1289, -119.2778),
  ('Walgreens Pharmacy - Aberdeen', 'Retail Pharmacy', 'Pharmacy serving Grays Harbor County.', '1200 Simpson Ave', 'Aberdeen', 'Grays Harbor', '98520', '(360) 532-0441', 'https://walgreens.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Walgreens', 'Aberdeen', 'Grays Harbor'], 'pharmacy Walgreens Aberdeen Grays Harbor prescriptions', 46.9738, -123.8222),
  ('CVS Pharmacy - Longview', 'Retail Pharmacy', 'Pharmacy serving Cowlitz County.', '1330 15th Ave', 'Longview', 'Cowlitz', '98632', '(360) 577-0712', 'https://cvs.com', '{"monday": "8am-10pm", "tuesday": "8am-10pm", "wednesday": "8am-10pm", "thursday": "8am-10pm", "friday": "8am-10pm", "saturday": "9am-6pm", "sunday": "9am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'CVS', 'Longview', 'Cowlitz'], 'pharmacy CVS Longview Cowlitz County prescriptions', 46.1430, -122.9387),
  ('Rite Aid Pharmacy - Walla Walla', 'Retail Pharmacy', 'Pharmacy serving Walla Walla County.', '880 S 2nd Ave', 'Walla Walla', 'Walla Walla', '99362', '(509) 529-1110', 'https://riteaid.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-6pm", "sunday": "10am-5pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Rite Aid', 'Walla Walla'], 'pharmacy Rite Aid Walla Walla prescriptions', 46.0657, -118.3510),
  ('Community Pharmacy - Bellevue', 'Independent Pharmacy', 'Independent community pharmacy with personalized care.', '14603 NE 20th St', 'Bellevue', 'King', '98007', '(425) 644-1194', 'https://communitypharmacybellevue.com', '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Chinese', 'Mandarin'], ARRAY['Prescriptions', 'Compounding', 'Consultations'], ARRAY['pharmacy', 'independent', 'compounding', 'Bellevue'], 'pharmacy independent Community Pharmacy Bellevue compounding Eastside', 47.6276, -122.1420),
  ('Kelley-Ross Pharmacy - Seattle', 'Independent Pharmacy', 'Compounding pharmacy specializing in customized medications.', '535 4th Ave E', 'Seattle', 'King', '98102', '(206) 322-3528', 'https://kelley-ross.com', '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English'], ARRAY['Prescriptions', 'Compounding', 'Specialty Medications'], ARRAY['pharmacy', 'independent', 'compounding', 'specialty'], 'pharmacy independent Kelley-Ross Seattle compounding specialty Capitol Hill', 47.6198, -122.3208),
  ('Pioneer Community Pharmacy - Tacoma', 'Independent Pharmacy', 'Community pharmacy with personalized medication management.', '915 Pacific Ave', 'Tacoma', 'Pierce', '98402', '(253) 396-0891', 'https://pioneerpharmacy.com', '{"monday": "9am-6pm", "tuesday": "9am-6pm", "wednesday": "9am-6pm", "thursday": "9am-6pm", "friday": "9am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English'], ARRAY['Prescriptions', 'Medication Management', 'Consultations'], ARRAY['pharmacy', 'independent', 'Tacoma', 'Pierce County'], 'pharmacy independent Pioneer Community Pharmacy Tacoma medication management', 47.2522, -122.4381),
  ('QFC Pharmacy - Seattle', 'Grocery Pharmacy', 'Grocery store pharmacy with convenient hours.', '4500 Stone Way N', 'Seattle', 'King', '98103', '(206) 632-0345', 'https://qfc.com', '{"monday": "8am-9pm", "tuesday": "8am-9pm", "wednesday": "8am-9pm", "thursday": "8am-9pm", "friday": "8am-9pm", "saturday": "9am-7pm", "sunday": "10am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'QFC', 'grocery'], 'pharmacy QFC Seattle Wallingford prescriptions grocery', 47.6503, -122.3237),
  ('Fred Meyer Pharmacy - Bellingham', 'Grocery Pharmacy', 'Grocery store pharmacy serving Whatcom County.', '4500 Meridian St', 'Bellingham', 'Whatcom', '98226', '(360) 738-0500', 'https://fredmeyer.com', '{"monday": "9am-9pm", "tuesday": "9am-9pm", "wednesday": "9am-9pm", "thursday": "9am-9pm", "friday": "9am-9pm", "saturday": "9am-7pm", "sunday": "10am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Spanish'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Fred Meyer', 'grocery', 'Bellingham'], 'pharmacy Fred Meyer Bellingham grocery Whatcom prescriptions', 48.7567, -122.4615),
  ('Safeway Pharmacy - Spokane', 'Grocery Pharmacy', 'Grocery store pharmacy serving Spokane.', '2925 E 57th Ave', 'Spokane', 'Spokane', '99223', '(509) 448-2311', 'https://safeway.com', '{"monday": "9am-9pm", "tuesday": "9am-9pm", "wednesday": "9am-9pm", "thursday": "9am-9pm", "friday": "9am-9pm", "saturday": "9am-7pm", "sunday": "10am-6pm"}'::jsonb, true, false, true, true, true, true, false, false, false, ARRAY['English', 'Russian'], ARRAY['Prescriptions', 'Vaccinations'], ARRAY['pharmacy', 'Safeway', 'grocery', 'Spokane'], 'pharmacy Safeway Spokane grocery prescriptions South Hill', 47.5990, -117.3814)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
