/*
# Add Urgent Care Centers Batch 2 - Eastern WA, Peninsula, Southwest WA

1. Coverage
   - Tri-Cities, Wenatchee, Bellingham, Skagit, Thurston, Clark, Walla Walla, Grays Harbor, Cowlitz
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'primary-care'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Providence Urgent Care - Mill Creek', 'Urgent Care', 'Walk-in care for minor injuries and illness.', '12820 35th Ave SE', 'Mill Creek', 'Snohomish', '98012', '(425) 337-3100', 'https://providence.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'providence'], 'urgent care Providence Mill Creek', 47.8570, -122.1967),
  ('MultiCare Indigo Urgent Care - Marysville', 'Urgent Care', 'Walk-in urgent care serving Marysville and surrounding communities.', '3425 172nd St NE', 'Marysville', 'Snohomish', '98271', '(253) 344-4852', 'https://indigourgentcare.com', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "8am-8pm", "sunday": "8am-8pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'indigo'], 'urgent care Indigo Marysville', 48.0546, -122.1572),
  ('PeaceHealth Urgent Care - Vancouver', 'Urgent Care', 'Walk-in care for minor injuries and illness. Part of PeaceHealth system.', '3400 Main St', 'Vancouver', 'Clark', '98663', '(360) 696-5000', 'https://peacehealth.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'peacehealth'], 'urgent care PeaceHealth Vancouver', 45.6387, -122.6615),
  ('The Vancouver Clinic Urgent Care', 'Urgent Care', 'Full-service urgent care with on-site imaging and lab.', '2211 NE 139th St', 'Vancouver', 'Clark', '98686', '(360) 882-2778', 'https://tvc.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "8am-6pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'Vancouver Clinic'], 'urgent care Vancouver Clinic Clark', 45.7208, -122.5690),
  ('Providence Urgent Care - Olympia', 'Urgent Care', 'Walk-in care for non-emergency conditions.', '411 Lilly Rd NE', 'Olympia', 'Thurston', '98506', '(360) 493-4444', 'https://providence.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'providence'], 'urgent care Providence Olympia', 47.0504, -122.8643),
  ('MultiCare Indigo Urgent Care - Lacey', 'Urgent Care', 'Walk-in urgent care serving Thurston County.', '4520 Martin Way E', 'Lacey', 'Thurston', '98516', '(253) 344-4852', 'https://indigourgentcare.com', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "8am-8pm", "sunday": "8am-8pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'indigo'], 'urgent care Indigo Lacey', 47.0529, -122.7846),
  ('Yakima Valley Farm Workers Clinic Urgent Care', 'Urgent Care', 'Community health urgent care with sliding scale. Bilingual services.', '700 W 4th Ave', 'Toppenish', 'Yakima', '98948', '(509) 865-2100', 'https://yvfwc.com', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "9am-1pm", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Lab', 'Pharmacy', 'Primary Care'], ARRAY['urgent care', 'FQHC', 'sliding scale', 'YVFWC'], 'urgent care YVFWC Toppenish sliding scale FQHC', 46.3776, -120.3162),
  ('Astria Health Urgent Care - Yakima', 'Urgent Care', 'Walk-in care for minor injuries and illness.', '2900 S 16th Ave', 'Yakima', 'Yakima', '98903', '(509) 965-2100', 'https://astria.health', '{"monday": "9am-7pm", "tuesday": "9am-7pm", "wednesday": "9am-7pm", "thursday": "9am-7pm", "friday": "9am-7pm", "saturday": "10am-4pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'astria'], 'urgent care Astria Yakima', 46.5822, -120.5425),
  ('Kadlec Urgent Care - Richland', 'Urgent Care', 'Walk-in urgent care with X-ray and lab services.', '1268 Lee Blvd', 'Richland', 'Benton', '99352', '(509) 946-1651', 'https://kadlec.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "8am-6pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'kadlec'], 'urgent care Kadlec Richland', 46.2856, -119.2706),
  ('Kadlec Urgent Care - Kennewick', 'Urgent Care', 'Full-service urgent care serving Tri-Cities.', '4003 W 27th Ave', 'Kennewick', 'Benton', '99337', '(509) 946-1651', 'https://kadlec.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'kadlec'], 'urgent care Kadlec Kennewick', 46.1891, -119.1583),
  ('Lourdes Urgent Care - Pasco', 'Urgent Care', 'Walk-in care for minor injuries and illness.', '8515 W Gage Blvd', 'Pasco', 'Franklin', '99301', '(509) 547-8811', 'https://lourdesps.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'lourdes'], 'urgent care Lourdes Pasco', 46.2547, -119.1364),
  ('PeaceHealth Urgent Care - Bellingham', 'Urgent Care', 'Walk-in care for non-emergency conditions.', '2940 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 734-5400', 'https://peacehealth.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'peacehealth'], 'urgent care PeaceHealth Bellingham', 48.7691, -122.4850),
  ('Unity Care NW Urgent Care - Bellingham', 'Urgent Care', 'Community health center with sliding scale. Full primary care services.', '220 Unity St', 'Bellingham', 'Whatcom', '98225', '(360) 676-6177', 'https://unitycarenw.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "9am-1pm", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Primary Care', 'Lab', 'Pharmacy'], ARRAY['urgent care', 'FQHC', 'sliding scale'], 'urgent care Unity Care NW Bellingham FQHC sliding scale', 48.7544, -122.4745),
  ('PeaceHealth Urgent Care - Burlington', 'Urgent Care', 'Walk-in care for minor injuries and illness serving Skagit County.', '100 Hospital Dr', 'Burlington', 'Skagit', '98233', '(360) 428-2500', 'https://peacehealth.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'peacehealth'], 'urgent care PeaceHealth Burlington Skagit', 48.4691, -122.4142),
  ('Confluence Health Urgent Care - Wenatchee', 'Urgent Care', 'Walk-in care serving Wenatchee Valley.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-8711', 'https://confluencehealth.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'confluence'], 'urgent care Confluence Wenatchee', 47.4261, -120.3136),
  ('Columbia Valley Community Health Urgent Care', 'Urgent Care', 'FQHC with sliding scale fees. Bilingual services available.', '600 Orondo Ave', 'Wenatchee', 'Chelan', '98801', '(509) 662-6000', 'https://cvch.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "9am-1pm", "sunday": "closed"}'::jsonb, true, true, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['urgent care', 'FQHC', 'sliding scale', 'CVCH'], 'urgent care Columbia Valley Community Health Wenatchee FQHC', 47.4340, -120.3316),
  ('Providence Urgent Care - Walla Walla', 'Urgent Care', 'Walk-in care for non-emergency conditions.', '1025 S 2nd Ave', 'Walla Walla', 'Walla Walla', '99362', '(509) 529-5200', 'https://providence.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'providence'], 'urgent care Providence Walla Walla', 46.0620, -118.3370),
  ('Summit Urgent Care - Aberdeen', 'Urgent Care', 'Walk-in care serving Grays Harbor County.', '915 Anderson Dr NW', 'Aberdeen', 'Grays Harbor', '98520', '(360) 537-2500', 'https://summitmedical.com', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "9am-3pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'summit'], 'urgent care Summit Aberdeen Grays Harbor', 46.9745, -123.8165),
  ('PeaceHealth Urgent Care - Longview', 'Urgent Care', 'Walk-in care for minor injuries and illness.', '1615 Delaware St', 'Longview', 'Cowlitz', '98632', '(360) 414-2000', 'https://peacehealth.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'peacehealth'], 'urgent care PeaceHealth Longview Cowlitz', 46.1415, -122.9401),
  ('Olympic Medical Urgent Care - Port Angeles', 'Urgent Care', 'Walk-in care serving the Olympic Peninsula.', '844 N 5th Ave', 'Port Angeles', 'Clallam', '98362', '(360) 417-7150', 'https://olympicmedical.org', '{"monday": "8am-8pm", "tuesday": "8am-8pm", "wednesday": "8am-8pm", "thursday": "8am-8pm", "friday": "8am-8pm", "saturday": "9am-5pm", "sunday": "9am-5pm"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English', 'Spanish'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'olympic medical'], 'urgent care Olympic Medical Port Angeles Clallam', 48.1162, -123.4333),
  ('Jefferson Healthcare Urgent Care - Port Townsend', 'Urgent Care', 'Walk-in urgent care serving East Jefferson County.', '834 Sheridan St', 'Port Townsend', 'Jefferson', '98368', '(360) 385-2200', 'https://jeffersonhealthcare.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "9am-3pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care', 'jefferson healthcare'], 'urgent care Jefferson Healthcare Port Townsend', 48.1163, -122.7755),
  ('Island Health Urgent Care - Oak Harbor', 'Urgent Care', 'Walk-in care serving Whidbey Island.', '101 N Main St', 'Oak Harbor', 'Island', '98277', '(360) 679-6500', 'https://islandhealth.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "9am-3pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, true, true, true, false, ARRAY['English'], ARRAY['X-ray', 'Lab'], ARRAY['urgent care'], 'urgent care Island Health Oak Harbor Whidbey', 48.2948, -122.6584)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
