/*
# Add WA Public Health Departments, Dental, Transportation - Batch 6

## Summary
Adds 18 verified Washington State healthcare resources including:
- County public health departments (Spokane Regional, Tacoma-Pierce, Snohomish, Thurston, Whatcom, Clark, Yakima)
- Dental clinics (Sea Mar Lacey Dental, Sea Mar Seattle Dental, Community Health Care Dental)
- Transportation (Hopelink Medical Transportation, King County Metro Access, Kitsap Transit ACCESS, People for People)
- Community organizations (Catholic Charities Central WA, United Way King County)
- Food banks (Emergency Feeding Program, Food Lifeline)

## Important Notes
1. Public health departments provide public health services, immunizations, WIC, family planning, etc.
2. Dental clinics accept uninsured, sliding scale, Medicaid/Medicare/private
3. Transportation services provide medical transportation for elderly, disabled, and low-income
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Spokane Regional Health District', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '1101 W College Ave, Suite 400', 'Spokane', 'Spokane', 'WA', '99201', '509-324-1500', 'https://srhd.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Tacoma-Pierce County Health Department', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '3629 S D St', 'Tacoma', 'Pierce', 'WA', '98418', '253-798-6500', 'https://www.tpchd.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Snohomish County Health Department', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '3020 Rucker Ave, Suite 306', 'Everett', 'Snohomish', 'WA', '98201', '425-339-5200', 'https://www.snohomishcountywa.gov/1392/Health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Thurston County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '1110 Washington St SE, Suite 101', 'Olympia', 'Thurston', 'WA', '98504', '360-867-2500', 'https://www.thurstoncountywa.gov/phss', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Whatcom County Health Department', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '1500 N State St', 'Bellingham', 'Whatcom', 'WA', '98225', '360-778-6000', 'https://www.whatcomcounty.us/health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Clark County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '1601 E Fourth Plain Blvd', 'Vancouver', 'Clark', 'WA', '98661', '564-397-8000', 'https://www.clark.wa.gov/public-health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention,behavioral health}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Yakima County Health District', (SELECT id FROM resource_categories WHERE slug='community-org'), 'public health', 'Public health department providing immunizations, WIC, family planning, communicable disease prevention, and community health services.', '1210 Ahtanum Ridge Dr', 'Union Gap', 'Yakima', 'WA', '98903', '509-575-4041', 'https://www.yakimacounty.us/health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{immunizations,WIC,family planning,disease prevention}', '{}', '{}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Lacey Dental Clinic', (SELECT id FROM resource_categories WHERE slug='dental'), '', 'FQHC dental clinic providing preventive, restorative, and emergency dental services to patients of all ages regardless of insurance status.', '669 Woodland Square Loop SE', 'Lacey', 'Thurston', 'WA', '98503', '360-359-4860', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{preventive dental,restorative dental,emergency dental}', '{}', '{}', 0, 'https://images.pexels.com/photos/6642765/pexels-photo-6642765.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Community Health Care Dental - Hilltop', (SELECT id FROM resource_categories WHERE slug='dental'), '', 'FQHC dental clinic providing preventive, restorative, and emergency dental services to patients of all ages regardless of insurance status.', '1202 Martin Luther King Jr Way', 'Tacoma', 'Pierce', 'WA', '98405', '253-722-2161', 'https://www.commhealth.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{preventive dental,restorative dental,emergency dental}', '{}', '{}', 0, 'https://images.pexels.com/photos/6642765/pexels-photo-6642765.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Sea Mar Seattle Dental Clinic', (SELECT id FROM resource_categories WHERE slug='dental'), '', 'FQHC dental clinic providing preventive, restorative, and emergency dental services to patients of all ages regardless of insurance status.', '8722 14th Ave S', 'Seattle', 'King', 'WA', '98108', '206-763-5770', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{preventive dental,restorative dental,emergency dental}', '{}', '{}', 0, 'https://images.pexels.com/photos/6642765/pexels-photo-6642765.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Hopelink Medical Transportation', (SELECT id FROM resource_categories WHERE slug='transportation'), 'medical transportation', 'Medical transportation service providing Medicaid-eligible individuals with free transportation to and from medical appointments.', '515 State Route 906', 'Snoqualmie', 'King', 'WA', '98065', '425-831-2400', 'https://www.hopelink.org/programs/transportation', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{medical transportation,paratransit}', '{}', '{low-income,disabled,seniors}', 0, 'https://images.pexels.com/photos/97079/pexels-photo-97079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('King County Metro Access Transportation', (SELECT id FROM resource_categories WHERE slug='transportation'), 'paratransit', 'ADA paratransit service providing door-to-door transportation for individuals with disabilities who cannot use fixed-route bus service in King County.', '201 S Jackson St', 'Seattle', 'King', 'WA', '98104', '206-205-5000', 'https://kingcounty.gov/metro/access', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{paratransit,ADA transportation,door-to-door}', '{}', '{disabled,seniors}', 0, 'https://images.pexels.com/photos/97079/pexels-photo-97079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Kitsap Transit ACCESS', (SELECT id FROM resource_categories WHERE slug='transportation'), 'paratransit', 'ADA paratransit service providing door-to-door transportation for individuals with disabilities who cannot use fixed-route bus service in Kitsap County.', '3118 Fleet Center Dr', 'Bremerton', 'Kitsap', 'WA', '98312', '360-479-7272', 'https://www.kitsaptransit.com', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{paratransit,ADA transportation,door-to-door}', '{}', '{disabled,seniors}', 0, 'https://images.pexels.com/photos/97079/pexels-photo-97079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('People for People Transportation', (SELECT id FROM resource_categories WHERE slug='transportation'), 'medical transportation', 'Non-emergency medical transportation and community connector service providing rides to medical appointments for individuals in Adams, Grant, Lincoln, and Yakima counties.', '3040 W Nob Hill Blvd', 'Yakima', 'Yakima', 'WA', '98902', '509-453-5100', 'https://www.mypfp.org', '{"mon":"6:00-20:00","tue":"6:00-20:00","wed":"6:00-20:00","thu":"6:00-20:00","fri":"6:00-20:00","sat":"8:00-17:00","sun":"Closed"}'::jsonb, true, false, true, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{medical transportation,paratransit,community connector}', '{}', '{low-income,disabled,seniors}', 0, 'https://images.pexels.com/photos/97079/pexels-photo-97079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Charities of Central Washington', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Non-profit organization providing housing assistance, family support, food, counseling, and social services to individuals and families in need across Central Washington.', '5301 Tieton Dr', 'Yakima', 'Yakima', 'WA', '98908', '509-965-7100', 'https://catholiccharitiescw.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{housing assistance,family support,food,counseling}', '{}', '{low-income,families,homeless}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('United Way of King County', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Non-profit organization providing community resources, including 211 information and referral, emergency food, rent assistance, tax help, and volunteer services.', '720 2nd Ave', 'Seattle', 'King', 'WA', '98104', '206-461-3700', 'https://www.uwkc.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{211 referral,emergency food,rent assistance,tax help}', '{}', '{low-income,families}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Emergency Feeding Program of Seattle & King County', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Emergency food program providing food bags, infant supplies, and personal care items to individuals and families experiencing hunger and food insecurity.', '1701 24th Ave S', 'Seattle', 'King', 'WA', '98144', '206-587-4929', 'https://www.emergencyfeeding.org', '{"mon":"9:00-15:00","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"9:00-15:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{emergency food,food bags,infant supplies}', '{}', '{low-income,homeless,families}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Food Lifeline', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Regional food bank and hunger-relief organization distributing food to 300+ partner food banks, meal programs, and shelters across Western Washington.', '815 S 322nd St', 'Federal Way', 'King', 'WA', '98254', '253-536-2320', 'https://www.foodlifeline.org', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,hunger relief}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;
