-- Add missing major hospitals and medical centers in Washington State
-- These are major healthcare facilities that were missing from the database

INSERT INTO resources (
  id, name, category_id, subcategory, description, address, city, county, state, zip_code,
  lat, lng, phone, website, domain, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance,
  walk_ins_welcome, appointments, telehealth, cost_free,
  cost_estimate_min, cost_estimate_max, languages, accessibility,
  services, specialties, audiences, tags, search_text
) VALUES
-- Overlake Medical Center - Bellevue (Major Eastside Hospital)
(
  gen_random_uuid(),
  'Overlake Medical Center',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Overlake Medical Center is a nonprofit, independently operated regional health system serving the Eastside since 1960. Features a Level III Trauma Center, comprehensive cancer care, cardiac care, surgery, family birth center, and intensive care units. Part of MultiCare Health System since 2024.',
  '1035 116th Ave NE',
  'Bellevue',
  'King',
  'WA',
  '98004',
  47.6247,
  -122.1853,
  '(425) 688-5000',
  'https://www.overlakehospital.org',
  'overlakehospital.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  false,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Free parking'],
  ARRAY['Emergency Room', 'Surgery', 'Cancer Care', 'Cardiac Care', 'Maternity', 'ICU', 'Laboratory', 'Radiology', 'Urgent Care'],
  ARRAY['Trauma Care', 'Cardiology', 'Oncology', 'Orthopedics', 'Neurology', 'Obstetrics'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'trauma center', 'emergency', 'surgery', 'cancer care', 'cardiac', 'maternity', 'bellevue', 'eastside', 'multicare'],
  'Overlake Medical Center Bellevue hospital trauma center emergency surgery cancer cardiac maternity ICU eastside King County Washington'
),

-- Kaiser Permanente Bellevue Medical Center
(
  gen_random_uuid(),
  'Kaiser Permanente Bellevue Medical Center',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Kaiser Permanente Bellevue Medical Center provides comprehensive integrated healthcare services including primary care, specialty care, urgent care, and 24-hour emergency services. Part of Kaiser Permanente, one of the nations leading nonprofit health plans and healthcare providers.',
  '11511 NE 10th St',
  'Bellevue',
  'King',
  'WA',
  '98004',
  47.6185,
  -122.1758,
  '(425) 502-3000',
  'https://healthy.kaiserpermanente.org/washington/facilities/bellevue-medical-center-338927',
  'kaiserpermanente.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  false,
  false,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  100,
  3000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean', 'Tagalog'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Pharmacy on-site'],
  ARRAY['Emergency Room', 'Primary Care', 'Specialty Care', 'Urgent Care', 'Laboratory', 'Radiology', 'Pharmacy'],
  ARRAY['Internal Medicine', 'Family Medicine', 'Cardiology', 'Orthopedics', 'Pediatrics', 'OB/GYN'],
  ARRAY['Kaiser members', 'Adults', 'Children', 'Families'],
  ARRAY['hospital', 'kaiser', 'integrated care', 'emergency', 'primary care', 'bellevue', 'urgent care'],
  'Kaiser Permanente Bellevue Medical Center hospital emergency primary care specialty urgent care King County Washington'
),

-- Seattle Childrens Hospital (Main Campus)
(
  gen_random_uuid(),
  'Seattle Childrens Hospital',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Pediatric Hospital',
  'Seattle Childrens Hospital is the premier pediatric medical center in the Pacific Northwest, providing comprehensive care for children from infancy through young adulthood. Features specialized programs in cancer, cardiac care, neurosciences, orthopedics, and mental health. Nationally ranked by U.S. News & World Report.',
  '4800 Sand Point Way NE',
  'Seattle',
  'King',
  'WA',
  '98105',
  47.6618,
  -122.2835,
  '(206) 987-2000',
  'https://www.seattlechildrens.org',
  'seattlechildrens.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  0,
  5000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Chinese', 'Somali', 'Russian', 'Korean', 'Tagalog'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Family housing', 'Child life specialists'],
  ARRAY['Emergency Room', 'Surgery', 'Cancer Care', 'Cardiac Care', 'Neurology', 'Orthopedics', 'Mental Health', 'ICU', 'NICU'],
  ARRAY['Pediatrics', 'Pediatric Oncology', 'Pediatric Cardiology', 'Pediatric Neurosurgery', 'Pediatric Surgery', 'Developmental Behavioral'],
  ARRAY['Children', 'Teens', 'Young Adults', 'Families'],
  ARRAY['hospital', 'pediatric', 'children', 'cancer', 'cardiac', 'neurology', 'mental health', 'seattle', 'specialty'],
  'Seattle Childrens Hospital pediatric hospital cancer cardiac neurology orthopedics mental health emergency King County Washington'
),

-- Swedish Medical Center First Hill (Seattle)
(
  gen_random_uuid(),
  'Swedish Medical Center - First Hill Campus',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Swedish Medical Center First Hill is the flagship campus of Swedish Health Services, a nonprofit healthcare system founded in 1910. Features Level II Trauma Center, comprehensive cancer care, cardiac services, neuroscience, high-risk obstetrics, organ transplantation, and family medicine residency program. Part of Providence Swedish.',
  '747 Broadway',
  'Seattle',
  'King',
  'WA',
  '98122',
  47.6132,
  -122.3217,
  '(206) 386-6000',
  'https://www.swedish.org/locations/first-hill-campus',
  'swedish.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean', 'Russian', 'Somali'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Chapel', 'Patient housing'],
  ARRAY['Emergency Room', 'Trauma Center', 'Surgery', 'Cancer Care', 'Cardiac Care', 'NICU', 'ICU', 'Organ Transplant', 'Neuroscience'],
  ARRAY['Cardiology', 'Oncology', 'Neuroscience', 'Orthopedics', 'Obstetrics', 'Transplant Surgery', 'Family Medicine'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'trauma center', 'emergency', 'cancer', 'cardiac', 'neuroscience', 'transplant', 'first hill', 'providence swedish'],
  'Swedish Medical Center First Hill hospital trauma center emergency cancer cardiac neuroscience transplant Seattle King County Washington'
),

-- Swedish Medical Center Cherry Hill (Seattle)
(
  gen_random_uuid(),
  'Swedish Medical Center - Cherry Hill Campus',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Swedish Cherry Hill Campus specializes in neuroscience, orthopedics, and rehabilitation. Nationally ranked by U.S. News for Neurology, Neurosurgery, and Spinal Fusion. Part of Providence Swedish health system.',
  '500 17th Ave',
  'Seattle',
  'King',
  'WA',
  '98122',
  47.6061,
  -122.3162,
  '(206) 386-6000',
  'https://www.swedish.org/locations/cherry-hill-campus',
  'swedish.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Rehabilitation gym'],
  ARRAY['Surgery', 'Neuroscience', 'Orthopedics', 'Rehabilitation', 'Spine Care', 'Stroke Care'],
  ARRAY['Neurology', 'Neurosurgery', 'Orthopedics', 'Spine Surgery', 'Physical Medicine', 'Rehabilitation Medicine'],
  ARRAY['Adults', 'Seniors', 'Stroke patients', 'Spine patients'],
  ARRAY['hospital', 'neuroscience', 'orthopedics', 'rehabilitation', 'spine', 'stroke', 'cherry hill', 'providence swedish'],
  'Swedish Medical Center Cherry Hill hospital neuroscience neurology orthopedics spine rehabilitation stroke Seattle King County Washington'
),

-- Swedish Medical Center Ballard
(
  gen_random_uuid(),
  'Swedish Medical Center - Ballard Campus',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Swedish Ballard Campus provides community hospital services including 24-hour emergency care, surgery, maternity services, and comprehensive diagnostic services. Part of Providence Swedish health system.',
  '5300 Tallman Ave NW',
  'Seattle',
  'King',
  'WA',
  '98107',
  47.6675,
  -122.3795,
  '(206) 782-2700',
  'https://www.swedish.org',
  'swedish.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  3000,
  ARRAY['English', 'Spanish'],
  ARRAY['Wheelchair accessible', 'Free parking', 'Interpreter services'],
  ARRAY['Emergency Room', 'Surgery', 'Maternity', 'Laboratory', 'Radiology'],
  ARRAY['Family Medicine', 'Obstetrics', 'General Surgery'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'emergency', 'maternity', 'surgery', 'ballard', 'community hospital', 'providence swedish'],
  'Swedish Medical Center Ballard hospital emergency maternity surgery community hospital Seattle King County Washington'
),

-- Swedish Medical Center Issaquah
(
  gen_random_uuid(),
  'Swedish Medical Center - Issaquah Campus',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Swedish Issaquah Campus provides comprehensive hospital services to the Eastside community including 24-hour emergency care, maternity, surgery, cancer care, and primary care. Named among nations best for maternity care. Part of Providence Swedish.',
  '751 NE Blakely Dr',
  'Issaquah',
  'King',
  'WA',
  '98029',
  47.5447,
  -122.0365,
  '(425) 313-7000',
  'https://www.swedish.org',
  'swedish.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  4000,
  ARRAY['English', 'Spanish', 'Chinese'],
  ARRAY['Wheelchair accessible', 'Free parking', 'Interpreter services'],
  ARRAY['Emergency Room', 'Surgery', 'Maternity', 'Cancer Care', 'Primary Care', 'Laboratory'],
  ARRAY['Family Medicine', 'Obstetrics', 'Oncology', 'General Surgery'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'emergency', 'maternity', 'cancer', 'surgery', 'issaquah', 'eastside', 'providence swedish'],
  'Swedish Medical Center Issaquah hospital emergency maternity cancer surgery King County Washington eastside'
),

-- EvergreenHealth Kirkland
(
  gen_random_uuid(),
  'EvergreenHealth Kirkland',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'EvergreenHealth Kirkland is a full-service public hospital district serving East King County. Features the Halvorson Cancer Center, comprehensive cardiac care, family birth center, and primary/specialty care. Partnership with Fred Hutch Cancer Center for world-class oncology services.',
  '12040 NE 128th St',
  'Kirkland',
  'King',
  'WA',
  '98034',
  47.7167,
  -122.1815,
  '(425) 899-1000',
  'https://www.evergreenhealth.com',
  'evergreenhealth.com',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean', 'Russian'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Free parking'],
  ARRAY['Emergency Room', 'Surgery', 'Cancer Care', 'Cardiac Care', 'Maternity', 'ICU', 'Primary Care', 'Laboratory', 'Radiology'],
  ARRAY['Oncology', 'Cardiology', 'Orthopedics', 'Obstetrics', 'General Surgery', 'Family Medicine'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'cancer', 'cardiac', 'maternity', 'surgery', 'kirkland', 'fred hutch', 'public hospital'],
  'EvergreenHealth Kirkland hospital cancer cardiac maternity surgery emergency King County Washington public hospital'
),

-- St. Joseph Medical Center Tacoma
(
  gen_random_uuid(),
  'St. Joseph Medical Center - Tacoma',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'St. Joseph Medical Center is consistently ranked among the top hospitals in Washington by U.S. News & World Report. Features Level II Trauma Center, Level III NICU, comprehensive cardiac care, family birth center with midwifery services, and 24-hour emergency care. Part of Virginia Mason Franciscan Health.',
  '1717 S J St',
  'Tacoma',
  'Pierce',
  'WA',
  '98405',
  47.2489,
  -122.4467,
  '(253) 426-4101',
  'https://www.vmfh.org/our-hospitals/st-joseph-medical-center',
  'vmfh.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Korean', 'Russian', 'Tagalog'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Chapel'],
  ARRAY['Emergency Room', 'Trauma Center', 'Surgery', 'Cardiac Care', 'Maternity', 'NICU', 'ICU', 'Cancer Care'],
  ARRAY['Cardiology', 'Oncology', 'Orthopedics', 'Obstetrics', 'Trauma Surgery', 'Neurology'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'trauma center', 'emergency', 'cardiac', 'maternity', 'NICU', 'tacoma', 'virginia mason franciscan'],
  'St Joseph Medical Center Tacoma hospital trauma center emergency cardiac maternity NICU Pierce County Washington Virginia Mason Franciscan'
),

-- MultiCare Tacoma General Hospital
(
  gen_random_uuid(),
  'MultiCare Tacoma General Hospital',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'MultiCare Tacoma General Hospital is a Level I Stroke Center and comprehensive tertiary medical center. Nationally recognized for stroke care and accredited as a Center of Excellence in Robotic and Colorectal Surgery. Features advanced cardiac care, cancer treatment, and neuroscience services.',
  '315 Martin Luther King Jr Way',
  'Tacoma',
  'Pierce',
  'WA',
  '98405',
  47.2533,
  -122.4418,
  '(253) 403-1000',
  'https://www.multicare.org/location/tacoma-general-hospital',
  'multicare.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Korean', 'Russian', 'Tagalog'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services'],
  ARRAY['Emergency Room', 'Stroke Center', 'Surgery', 'Cardiac Care', 'Cancer Care', 'ICU', 'Robotic Surgery', 'Laboratory'],
  ARRAY['Cardiology', 'Oncology', 'Neurology', 'Colorectal Surgery', 'Robotic Surgery', 'Stroke Medicine'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'stroke center', 'cardiac', 'cancer', 'robotic surgery', 'tacoma', 'multicare', 'tertiary'],
  'MultiCare Tacoma General Hospital stroke center cardiac cancer robotic surgery emergency tertiary Pierce County Washington'
),

-- MultiCare Auburn Medical Center
(
  gen_random_uuid(),
  'MultiCare Auburn Medical Center',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'MultiCare Auburn Medical Center is a Level II Stroke Center providing comprehensive hospital services to South King County and North Pierce County. Features 24-hour emergency care, birth center, stroke care, and primary/specialty services. DNV Certified Primary Stroke Center.',
  '202 N Division St',
  'Auburn',
  'King',
  'WA',
  '98001',
  47.3072,
  -122.2268,
  '(253) 833-7711',
  'https://www.multicare.org/location/auburn-medical-center',
  'multicare.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  4000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Korean', 'Russian'],
  ARRAY['Wheelchair accessible', 'Free parking', 'Interpreter services'],
  ARRAY['Emergency Room', 'Birth Center', 'Stroke Care', 'Surgery', 'Primary Care', 'Laboratory'],
  ARRAY['Stroke Medicine', 'Family Medicine', 'General Surgery', 'Obstetrics'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'stroke center', 'birth center', 'emergency', 'auburn', 'multicare', 'south king county'],
  'MultiCare Auburn Medical Center stroke center birth center emergency hospital Auburn South King County Washington'
),

-- MultiCare Good Samaritan Hospital (Puyallup)
(
  gen_random_uuid(),
  'MultiCare Good Samaritan Hospital',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'MultiCare Good Samaritan Hospital serves the Puyallup Valley and surrounding communities with comprehensive hospital services. Features 24-hour emergency care, family birth center, cancer care, cardiac services, and primary care.',
  '407 14th Ave SE',
  'Puyallup',
  'Pierce',
  'WA',
  '98372',
  47.1908,
  -122.2893,
  '(253) 848-3636',
  'https://www.multicare.org/location/multicare-good-samaritan-hospital',
  'multicare.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  4000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Korean', 'Russian'],
  ARRAY['Wheelchair accessible', 'Free parking', 'Interpreter services'],
  ARRAY['Emergency Room', 'Birth Center', 'Cancer Care', 'Cardiac Care', 'Surgery', 'Primary Care'],
  ARRAY['Oncology', 'Cardiology', 'Family Medicine', 'Obstetrics', 'General Surgery'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'birth center', 'cancer', 'cardiac', 'emergency', 'puyallup', 'multicare', 'pierce county'],
  'MultiCare Good Samaritan Hospital Puyallup birth center cancer cardiac emergency Pierce County Washington'
),

-- Providence Regional Medical Center Everett
(
  gen_random_uuid(),
  'Providence Regional Medical Center - Everett',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Providence Regional Medical Center Everett is a nationally recognized hospital and Level II Trauma Center serving Snohomish County. Features comprehensive cardiac care, cancer treatment, neuroscience, maternity services, and primary care. Part of Providence Swedish.',
  '1700 13th St',
  'Everett',
  'Snohomish',
  'WA',
  '98201',
  47.9809,
  -122.2043,
  '(425) 261-2000',
  'https://www.providence.org/locations/wa/providence-regional-medical-center-everett',
  'providence.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Korean', 'Russian', 'Chinese'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Family housing'],
  ARRAY['Emergency Room', 'Trauma Center', 'Surgery', 'Cancer Care', 'Cardiac Care', 'Maternity', 'ICU', 'Neuroscience'],
  ARRAY['Cardiology', 'Oncology', 'Neurology', 'Trauma Surgery', 'Obstetrics', 'Orthopedics'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'trauma center', 'emergency', 'cancer', 'cardiac', 'maternity', 'everett', 'providence swedish', 'snohomish'],
  'Providence Regional Medical Center Everett hospital trauma center emergency cancer cardiac maternity Snohomish County Washington'
),

-- Virginia Mason Medical Center (Seattle)
(
  gen_random_uuid(),
  'Virginia Mason Medical Center',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'General Hospital',
  'Virginia Mason Medical Center is one of the premier healthcare facilities in the Pacific Northwest, consistently ranked among the best hospitals in Washington by Healthgrades and U.S. News & World Report. Known for innovative Virginia Mason Production System for quality and safety. Features comprehensive specialty care, cancer treatment, and research programs.',
  '1100 9th Ave',
  'Seattle',
  'King',
  'WA',
  '98101',
  47.6088,
  -122.3253,
  '(206) 223-6600',
  'https://www.vmfh.org/our-hospitals/virginia-mason-medical-center',
  'vmfh.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services'],
  ARRAY['Emergency Room', 'Surgery', 'Cancer Care', 'Primary Care', 'Specialty Care', 'ICU', 'Laboratory', 'Radiology'],
  ARRAY['Oncology', 'Cardiology', 'Orthopedics', 'Neurology', 'General Surgery', 'Internal Medicine'],
  ARRAY['Adults', 'Families', 'Seniors'],
  ARRAY['hospital', 'cancer', 'cardiac', 'specialty', 'research', 'downtown seattle', 'virginia mason franciscan'],
  'Virginia Mason Medical Center hospital cancer cardiac specialty care research downtown Seattle King County Washington'
);