-- Fix phone numbers for urgent care facilities
UPDATE resources SET phone = '(425) 845-5500' WHERE name = 'UW Medicine Urgent Care - Kirkland';

-- Standardize phone number formats for hospitals to be consistent (xxx) xxx-xxxx format
UPDATE resources SET phone = '(509) 837-7581' WHERE name = 'Astria Sunnyside Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 435-2133' WHERE name = 'Cascade Valley Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 663-8711' WHERE name = 'Central Washington Hospital';
UPDATE resources SET phone = '(509) 754-3661' WHERE name = 'Columbia Basin Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 382-2511' WHERE name = 'Dayton General Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 775-3333' WHERE name = 'Ferry County Memorial Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 374-6271' WHERE name = 'Forks Community Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 843-1531' WHERE name = 'Garfield County Memorial Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(206) 744-3000' WHERE name = 'UW Medicine - Harborview Medical Center';
UPDATE resources SET phone = '(360) 293-0100' WHERE name = 'Island Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 385-2200' WHERE name = 'Jefferson Healthcare Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 942-5454' WHERE name = 'Kadlec Regional Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 962-7241' WHERE name = 'Kittitas Valley Healthcare' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 773-4017' WHERE name = 'Klickitat Valley Health' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 682-6121' WHERE name = 'Lake Chelan Community Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 487-1000' WHERE name = 'Legacy Salmon Creek Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 725-7101' WHERE name = 'Lincoln Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 546-2100' WHERE name = 'Lourdes Medical Center Pasco' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 426-1611' WHERE name = 'Mason General Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 826-1731' WHERE name = 'Mid-Valley Hospital Omak' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 447-3131' WHERE name = 'Newport Hospital & Health Services' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 486-2131' WHERE name = 'North Valley Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 642-6311' WHERE name = 'Ocean Beach Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 488-3105' WHERE name = 'Othello Community Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 378-4191' WHERE name = 'PeaceHealth Peace Island Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 414-2000' WHERE name = 'PeaceHealth St. John Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 734-5400' WHERE name = 'PeaceHealth St. Joseph Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 856-7000' WHERE name = 'PeaceHealth United General Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 786-6661' WHERE name = 'Prosser Memorial Health' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 330-8888' WHERE name = 'Providence Centralia Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 684-3401' WHERE name = 'Providence Mount Carmel Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 474-3000' WHERE name = 'Providence Sacred Heart Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 825-2508' WHERE name = 'Providence St. Elizabeth Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 935-8300' WHERE name = 'Providence St. Joseph Hospital Chewelah' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 525-3320' WHERE name = 'Providence St. Mary Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 491-9480' WHERE name = 'Providence St. Peter Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 332-2541' WHERE name = 'Pullman Regional Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 787-3531' WHERE name = 'Quincy Valley Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 424-4111' WHERE name = 'Skagit Valley Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 637-2600' WHERE name = 'Skyline Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(425) 831-2300' WHERE name = 'Snoqualmie Valley Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 482-7000' WHERE name = 'Summit Pacific Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 689-2515' WHERE name = 'Three Rivers Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 758-1111' WHERE name = 'Tri-State Memorial Hospital' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(206) 368-1500' WHERE name = 'UW Medicine - UW Medical Center Northwest' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(425) 656-4000' WHERE name = 'UW Medicine - Valley Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 678-7651' WHERE name = 'WhidbeyHealth Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(509) 397-3331' WHERE name = 'Whitman Hospital & Medical Center' AND phone NOT LIKE '%(%';
UPDATE resources SET phone = '(360) 875-9340' WHERE name = 'Willapa Harbor Hospital' AND phone NOT LIKE '%(%';