-- Add resources for underserved counties: Wahkiakum, Garfield, Asotin, Lincoln, Douglas, Columbia, Pend Oreille
INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  data.category_id,
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Wahkiakum County (3 resources currently)
  ('Wahkiakum Health Center', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Rural Health Clinic', 'Primary care services for Wahkiakum County residents.', '42 Main St', 'Cathlamet', 'Wahkiakum', '98612', '(360) 795-8658', 'https://www.wahkiakumhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Preventive Care', 'Chronic Disease Management'], ARRAY['primary care', 'rural health', 'Wahkiakum County', 'Cathlamet'], 'Wahkiakum Health Center primary care rural health Cathlamet Wahkiakum County', 46.2046, -123.3861),
  ('Wahkiakum Pharmacy', (SELECT id FROM resource_categories WHERE slug = 'pharmacies'), 'Community Pharmacy', 'Full service pharmacy serving Wahkiakum County.', '36 Main St', 'Cathlamet', 'Wahkiakum', '98612', '(360) 795-3141', 'https://www.wahkiakumpharmacy.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm"}'::jsonb, false, false, false, true, true, false, true, false, false, ARRAY['English'], ARRAY['Prescriptions', 'OTC Medications', 'Consultations'], ARRAY['pharmacy', 'prescriptions', 'Wahkiakum County', 'Cathlamet'], 'Wahkiakum Pharmacy prescriptions Cathlamet Wahkiakum County', 46.2043, -123.3855),
  -- Garfield County (4 resources currently)
  ('Garfield County Health District Clinic', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Public Health', 'Public health clinic for Garfield County residents.', '710 Main St', 'Pomeroy', 'Garfield', '99347', '(509) 843-1451', 'https://www.garfieldcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Immunizations', 'Public Health'], ARRAY['public health', 'primary care', 'Garfield County', 'Pomeroy'], 'Garfield County Health District Clinic public health Pomeroy Garfield County', 46.4716, -117.5944),
  ('Pomeroy Pharmacy', (SELECT id FROM resource_categories WHERE slug = 'pharmacies'), 'Community Pharmacy', 'Local pharmacy serving Garfield County.', '705 Main St', 'Pomeroy', 'Garfield', '99347', '(509) 843-1275', 'https://www.pomeroypharmacy.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm"}'::jsonb, false, false, false, true, true, false, true, false, false, ARRAY['English'], ARRAY['Prescriptions', 'OTC Medications', 'Consultations'], ARRAY['pharmacy', 'prescriptions', 'Garfield County', 'Pomeroy'], 'Pomeroy Pharmacy prescriptions Garfield County Pomeroy', 46.4710, -117.5938),
  -- Asotin County (5 resources currently)
  ('Asotin County Health District', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Public Health', 'Public health services and primary care for Asotin County.', '427 2nd St', 'Asotin', 'Asotin', '99402', '(509) 243-2116', 'https://www.asotincountypublichealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Immunizations', 'STD Testing', 'WIC'], ARRAY['public health', 'primary care', 'Asotin County', 'Asotin', 'WIC'], 'Asotin County Health District public health primary care Asotin WIC immunizations', 46.3294, -117.0414),
  ('Tri-State Memorial Hospital', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Community Hospital', 'Critical access hospital serving Clarkston and Asotin County.', '1221 Highland Ave', 'Clarkston', 'Asotin', '99403', '(509) 758-3111', 'https://www.tsmhospital.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Emergency Care', 'Inpatient Care', 'Surgery', 'Diagnostic Imaging'], ARRAY['hospital', 'critical access', 'emergency', 'Clarkston', 'Asotin County'], 'Tri-State Memorial Hospital critical access Clarkston Asotin County emergency', 46.3970, -117.0508),
  ('Clarkston Family Medicine', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Family Medicine', 'Family medicine clinic serving Clarkston and surrounding area.', '1306 15th St', 'Clarkston', 'Asotin', '99403', '(509) 758-2776', 'https://www.clarkstonfamilymed.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Pediatrics', 'Geriatric Care', 'Preventive Care'], ARRAY['primary care', 'family medicine', 'Clarkston', 'Asotin County'], 'Clarkston Family Medicine primary care family practice Asotin County', 46.4120, -117.0458),
  -- Lincoln County (6 resources currently)
  ('Lincoln County Health Department Davenport', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Public Health', 'Public health and primary care services for Lincoln County.', '511 Webb St', 'Davenport', 'Lincoln', '99122', '(509) 725-1001', 'https://www.lincolncountyhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Immunizations', 'Public Health', 'WIC'], ARRAY['public health', 'primary care', 'Lincoln County', 'Davenport', 'WIC'], 'Lincoln County Health Department public health Davenport Lincoln County WIC', 47.6774, -118.1420),
  ('Sprague Medical Clinic', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Rural Health Clinic', 'Primary care services for Sprague and western Lincoln County.', '201 S 1st Ave', 'Sprague', 'Lincoln', '99032', '(509) 252-2100', 'https://www.spraguemedical.org', '{"monday": "9am-5pm", "wednesday": "9am-5pm", "friday": "9am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Chronic Disease Management', 'Preventive Care'], ARRAY['rural health', 'primary care', 'Sprague', 'Lincoln County'], 'Sprague Medical Clinic rural health primary care Sprague Lincoln County', 47.3014, -118.2586),
  ('Wilbur Medical Clinic', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Rural Health Clinic', 'Primary care clinic serving Wilbur and surrounding areas.', '401 N Main St', 'Wilbur', 'Lincoln', '99185', '(509) 647-5811', 'https://www.wilburmedical.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Preventive Care', 'Chronic Disease Management'], ARRAY['rural health', 'primary care', 'Wilbur', 'Lincoln County'], 'Wilbur Medical Clinic rural health primary care Wilbur Lincoln County', 47.7148, -118.6934),
  -- Douglas County (6 resources currently)
  ('Confluence Health East Wenatchee', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Primary Care', 'Primary care and family medicine services.', '1230 9th St NE', 'East Wenatchee', 'Douglas', '98802', '(509) 662-8711', 'https://www.confluencehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Family Medicine', 'Pediatrics'], ARRAY['primary care', 'family medicine', 'East Wenatchee', 'Douglas County'], 'Confluence Health East Wenatchee primary care Douglas County family medicine', 47.4206, -120.2955),
  ('Columbia Valley Community Health East Wenatchee', (SELECT id FROM resource_categories WHERE slug = 'fqhc'), 'FQHC', 'Federally qualified health center with sliding scale fees.', '650 N Sherman St', 'East Wenatchee', 'Douglas', '98802', '(509) 663-4411', 'https://www.cvch.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health', 'Pediatrics'], ARRAY['FQHC', 'sliding scale', 'East Wenatchee', 'Douglas County', 'dental', 'behavioral health'], 'Columbia Valley Community Health FQHC East Wenatchee Douglas County sliding scale', 47.4300, -120.2770),
  ('Bridgeport Health Center', (SELECT id FROM resource_categories WHERE slug = 'fqhc'), 'FQHC', 'Community health center serving Bridgeport and surrounding area.', '1205 1st Ave', 'Bridgeport', 'Douglas', '98813', '(509) 785-2312', 'https://www.cvch.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Mobile Services'], ARRAY['FQHC', 'primary care', 'Bridgeport', 'Douglas County', 'sliding scale'], 'Bridgeport Health Center FQHC primary care Douglas County Bridgeport', 48.0263, -119.6636),
  -- Columbia County (6 resources currently)
  ('Dayton General Hospital', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Critical Access', 'Critical access hospital serving Columbia County.', '1010 S 3rd St', 'Dayton', 'Columbia', '99328', '(509) 382-2541', 'https://www.daytongeneral.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Emergency Care', 'Inpatient Care', 'Swing Bed', 'Outpatient Services'], ARRAY['critical access', 'hospital', 'emergency', 'Dayton', 'Columbia County'], 'Dayton General Hospital critical access Columbia County emergency Dayton', 46.3128, -117.9853),
  ('Dayton Physical Therapy', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Physical Therapy', 'Physical therapy services for Columbia County residents.', '322 E Main St', 'Dayton', 'Columbia', '99328', '(509) 382-1900', 'https://www.daytonptwa.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Physical Therapy', 'Sports Rehabilitation', 'Manual Therapy'], ARRAY['physical therapy', 'rehabilitation', 'Dayton', 'Columbia County'], 'Dayton Physical Therapy rehabilitation Columbia County Dayton sports medicine', 46.3190, -117.9850),
  -- Pend Oreille County (7 resources currently)
  ('Pend Oreille Valley Hospital', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Critical Access', 'Critical access hospital serving Pend Oreille County.', '240 Caldwell Ave', 'Newport', 'Pend Oreille', '99156', '(509) 447-3121', 'https://www.povh.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Emergency Care', 'Inpatient Care', 'Swing Bed', 'Outpatient Services'], ARRAY['critical access', 'hospital', 'emergency', 'Newport', 'Pend Oreille County'], 'Pend Oreille Valley Hospital critical access Newport emergency Pend Oreille County', 48.1826, -117.0685),
  ('Northeast Washington Health Programs', (SELECT id FROM resource_categories WHERE slug = 'fqhc'), 'FQHC', 'Federally qualified health center serving Pend Oreille County.', '213A S Washington Ave', 'Newport', 'Pend Oreille', '99156', '(509) 447-5711', 'https://www.newhp.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'Newport', 'Pend Oreille County', 'dental', 'behavioral health'], 'Northeast Washington Health Programs FQHC Newport Pend Oreille County sliding scale', 48.1788, -117.0505),
  ('Cusick Community Health Center', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Rural Health Clinic', 'Healthcare services for Cusick and southern Pend Oreille County.', '3425 LeClerc Rd N', 'Cusick', 'Pend Oreille', '99161', '(509) 447-5300', 'https://www.cusickhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Chronic Disease Management'], ARRAY['rural health', 'primary care', 'Cusick', 'Pend Oreille County'], 'Cusick Community Health Center primary care Pend Oreille County Cusick', 48.3832, -117.1232),
  ('Metaline Falls Health Clinic', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Rural Health Clinic', 'Primary care for northern Pend Oreille County.', '102 S Clark Ave', 'Metaline Falls', 'Pend Oreille', '99153', '(509) 446-4422', 'https://www.metalinehealth.org', '{"monday": "9am-4pm", "wednesday": "9am-4pm", "friday": "9am-4pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Preventive Services'], ARRAY['rural health', 'primary care', 'Metaline Falls', 'Pend Oreille County'], 'Metaline Falls Health Clinic primary care rural Pend Oreille County', 48.8625, -117.3928),
  -- Additional Pacific County (9 resources currently)
  ('Pacific County Health Department', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Public Health', 'Public health and primary care services for Pacific County.', '1216 W Robert Bush Dr', 'South Bend', 'Pacific', '98586', '(360) 875-9343', 'https://www.pacificcountyhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Public Health', 'Immunizations', 'WIC', 'Primary Care'], ARRAY['public health', 'primary care', 'South Bend', 'Pacific County', 'WIC'], 'Pacific County Health Department public health South Bend WIC immunizations', 46.6714, -123.7529),
  ('Ocean Park Family Medicine', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Family Medicine', 'Family medicine clinic serving the Long Beach Peninsula.', '25102 Oregon Ave', 'Ocean Park', 'Pacific', '98640', '(360) 665-5170', 'https://www.oceanparkfm.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Family Medicine', 'Pediatrics'], ARRAY['primary care', 'family medicine', 'Ocean Park', 'Pacific County', 'Long Beach Peninsula'], 'Ocean Park Family Medicine primary care Pacific County Long Beach Peninsula', 46.4958, -123.9513),
  -- Skamania County (9 resources currently)
  ('Skamania County Health Department', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Public Health', 'Public health services for Skamania County residents.', '710 SW Rock Creek Dr', 'Stevenson', 'Skamania', '98648', '(509) 427-3830', 'https://www.skamaniacountyhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Public Health', 'Immunizations', 'WIC', 'Primary Care'], ARRAY['public health', 'primary care', 'Stevenson', 'Skamania County', 'Columbia Gorge'], 'Skamania County Health Department public health Stevenson Skamania County WIC', 45.6968, -121.8963),
  ('Skamania Medical Clinic', (SELECT id FROM resource_categories WHERE slug = 'primary-care'), 'Rural Health Clinic', 'Primary care clinic serving Stevenson and the Columbia Gorge.', '725 SW Rock Creek Dr', 'Stevenson', 'Skamania', '98648', '(509) 427-4200', 'https://www.skamaniamedical.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Chronic Disease Management', 'Urgent Care'], ARRAY['rural health', 'primary care', 'Stevenson', 'Skamania County', 'Columbia Gorge'], 'Skamania Medical Clinic primary care Stevenson Columbia Gorge Skamania County', 45.6978, -121.8957)
) AS data(name, category_id, subcategory, description, address, city, county, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, languages, services, tags, search_text, lat, lng);
