/*
# Add Pediatric Clinics Across Washington

1. Purpose
   - Add pediatric healthcare providers across Washington state
   - Focus on accessible child healthcare in all regions

2. Coverage
   - All Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'pediatrics'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Seattle Childrens Hospital Outpatient - Bellevue', 'Pediatric Clinic', 'Pediatric specialty care including cardiology, neurology, and developmental pediatrics.', '1500 116th Ave NE', 'Bellevue', 'King', '98004', '(425) 526-2555', 'https://seattlechildrens.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Pediatric Specialty', 'Cardiology', 'Neurology', 'Developmental'], ARRAY['pediatric', 'children', 'specialty', 'Seattle Childrens', 'Bellevue'], 'pediatric Seattle Childrens Hospital Bellevue specialty children cardiology neurology', 47.6277, -122.1975),
  ('Seattle Childrens Hospital Outpatient - Federal Way', 'Pediatric Clinic', 'Pediatric specialty care serving South King County.', '31120 Pacific Hwy S', 'Federal Way', 'King', '98003', '(253) 941-2530', 'https://seattlechildrens.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Korean'], ARRAY['Pediatric Specialty', 'Orthopedics', 'Gastroenterology'], ARRAY['pediatric', 'children', 'specialty', 'Seattle Childrens', 'Federal Way'], 'pediatric Seattle Childrens Hospital Federal Way South King County children', 47.3111, -122.3202),
  ('Mary Bridge Childrens Hospital - Tacoma', 'Pediatric Clinic', 'MultiCare pediatric specialty clinic serving Pierce County.', '317 Martin Luther King Jr Way', 'Tacoma', 'Pierce', '98405', '(253) 403-1400', 'https://multicare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Pediatric Specialty', 'General Pediatrics'], ARRAY['pediatric', 'children', 'specialty', 'Mary Bridge', 'MultiCare', 'Tacoma'], 'pediatric Mary Bridge Childrens Hospital Tacoma Pierce County children MultiCare', 47.2533, -122.4496),
  ('Providence Childrens Health - Spokane', 'Pediatric Clinic', 'Providence pediatric services for Eastern Washington.', '123 W 7th Ave', 'Spokane', 'Spokane', '99204', '(509) 474-4400', 'https://providence.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Russian'], ARRAY['Pediatric Specialty', 'General Pediatrics'], ARRAY['pediatric', 'children', 'specialty', 'Providence', 'Spokane'], 'pediatric Providence Childrens Health Spokane Eastern Washington children', 47.6556, -117.4277),
  ('Pediatric Associates - North Seattle', 'Pediatric Clinic', 'General pediatric care for children from newborn to age 18.', '1200 NW 80th St', 'Seattle', 'King', '98117', '(206) 783-9000', 'https://pediatricassociates.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "9am-12pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'general pediatric', 'North Seattle'], 'pediatric Pediatric Associates North Seattle children well-child immunizations', 47.6867, -122.3822),
  ('Pediatric Associates - Everett', 'Pediatric Clinic', 'General pediatric care serving Snohomish County.', '1200 Everett Ave', 'Everett', 'Snohomish', '98201', '(425) 258-4900', 'https://pediatricassociates.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "9am-12pm", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'general pediatric', 'Everett', 'Snohomish'], 'pediatric Pediatric Associates Everett Snohomish children well-child immunizations', 47.9775, -122.2033),
  ('Kids Clinic Pediatrics - Spokane Valley', 'Pediatric Clinic', 'General pediatric care for Eastern Washington children.', '15720 E Indiana Ave', 'Spokane Valley', 'Spokane', '99216', '(509) 892-1450', 'https://kidsclinicpeds.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Russian'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'general pediatric', 'Spokane Valley'], 'pediatric Kids Clinic Spokane Valley children Eastern Washington', 47.6704, -117.2432),
  ('Valley Childrens Clinic - Yakima', 'Pediatric Clinic', 'Bilingual pediatric care serving Yakima Valley families.', '2000 W Lincoln Ave', 'Yakima', 'Yakima', '98902', '(509) 453-3100', 'https://valleychildrensclinic.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Spanish', 'bilingual', 'Yakima Valley'], 'pediatric Valley Childrens Clinic Yakima Valley children bilingual Spanish', 46.5948, -120.5490),
  ('PeaceHealth Pediatric Center - Bellingham', 'Pediatric Clinic', 'Comprehensive pediatric care for Whatcom County.', '2900 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 734-5400', 'https://peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'PeaceHealth', 'Bellingham', 'Whatcom'], 'pediatric PeaceHealth Pediatric Center Bellingham Whatcom County children', 48.7690, -122.4850),
  ('Benton Franklin Pediatric Clinic - Richland', 'Pediatric Clinic', 'Pediatric care for Tri-Cities area children.', '9570 Gage Blvd', 'Richland', 'Benton', '99354', '(509) 943-4150', 'https://bfpeds.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Tri-Cities', 'Richland', 'Benton'], 'pediatric Benton Franklin Pediatric Clinic Richland Tri-Cities children', 46.2835, -119.3012),
  ('South Sound Pediatrics - Puyallup', 'Pediatric Clinic', 'General pediatric care for Pierce County children.', '9605 7th Ave SW', 'Puyallup', 'Pierce', '98373', '(253) 445-5150', 'https://southsoundpeds.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Pierce County', 'Puyallup'], 'pediatric South Sound Pediatrics Puyallup Pierce County children', 47.1644, -122.4885),
  ('Olympia Pediatric Clinic', 'Pediatric Clinic', 'General pediatric care serving Thurston County.', '3430 Martin Way E', 'Olympia', 'Thurston', '98506', '(360) 491-4004', 'https://olympiapediatrics.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Olympia', 'Thurston County'], 'pediatric Olympia Pediatric Clinic Thurston County children', 47.0420, -122.8780),
  ('Vancouver Pediatric Center', 'Pediatric Clinic', 'Pediatric care for Clark County children.', '720 NE 139th St', 'Vancouver', 'Clark', '98686', '(360) 885-5900', 'https://vancouverpediatrics.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Vancouver', 'Clark County'], 'pediatric Vancouver Pediatric Center Clark County children', 45.7187, -122.5690),
  ('Pediatric Care Center - Wenatchee', 'Pediatric Clinic', 'Pediatric care for North Central Washington children.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-8711', 'https://confluencehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Wenatchee', 'Chelan', 'Confluence'], 'pediatric Pediatric Care Center Wenatchee Chelan children Confluence Health', 47.4261, -120.3136),
  ('Northwest Pediatrics - Bellingham', 'Pediatric Clinic', 'General pediatric care for Whatcom County.', '115 W Magnolia St', 'Bellingham', 'Whatcom', '98225', '(360) 671-3324', 'https://nwpeds.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Bellingham', 'Whatcom'], 'pediatric Northwest Pediatrics Bellingham Whatcom children', 48.7507, -122.4781),
  ('Pediatric Health Center - Aberdeen', 'Pediatric Clinic', 'Pediatric care for Grays Harbor County children.', '1300 Sumner Ave', 'Aberdeen', 'Grays Harbor', '98520', '(360) 532-8700', 'https://familyhealthcenter.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Aberdeen', 'Grays Harbor'], 'pediatric Pediatric Health Center Aberdeen Grays Harbor children', 46.9735, -123.8147),
  ('Moses Lake Pediatric Clinic', 'Pediatric Clinic', 'Pediatric care for Grant County children.', '605 S Sherman St', 'Moses Lake', 'Grant', '98837', '(509) 765-0674', 'https://nwchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Moses Lake', 'Grant County'], 'pediatric Moses Lake Pediatric Clinic Grant County children', 47.1231, -119.2787),
  ('Pediatric Associates of Walla Walla', 'Pediatric Clinic', 'General pediatric care serving Walla Walla County.', '327 W Poplar St', 'Walla Walla', 'Walla Walla', '99362', '(509) 529-6300', 'https://pediatric associateswallawalla.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Walla Walla'], 'pediatric Pediatric Associates Walla Walla children', 46.0697, -118.3418),
  ('Port Angeles Pediatrics', 'Pediatric Clinic', 'Pediatric care for Olympic Peninsula children.', '2415 E 8th St', 'Port Angeles', 'Clallam', '98362', '(360) 417-3395', 'https://olympicmedical.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Port Angeles', 'Olympic Peninsula', 'Clallam'], 'pediatric Port Angeles Pediatrics Olympic Peninsula children', 48.1145, -123.3920),
  ('Northwest Washington Pediatrics - Bellingham', 'Pediatric Clinic', 'Comprehensive pediatric services for Whatcom County.', '2940 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 734-3900', 'https://peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits', 'Newborn Care'], ARRAY['pediatric', 'children', 'Bellingham', 'PeaceHealth', 'Whatcom'], 'pediatric Northwest Washington Pediatrics Bellingham PeaceHealth children newborn', 48.7690, -122.4850),
  ('Pediatric Specialty Center - Tri-Cities', 'Pediatric Clinic', 'Pediatric specialty care for Tri-Cities area.', '1268 Lee Blvd', 'Richland', 'Benton', '99352', '(509) 946-1651', 'https://kadlec.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Pediatric Specialty', 'General Pediatrics'], ARRAY['pediatric', 'children', 'specialty', 'Kadlec', 'Tri-Cities', 'Richland'], 'pediatric Pediatric Specialty Center Tri-Cities Richland Kadlec children specialty', 46.2856, -119.2706),
  ('Childrens Clinic of Skagit - Mount Vernon', 'Pediatric Clinic', 'Pediatric care for Skagit County children.', '1450 Commercial Ave', 'Mount Vernon', 'Skagit', '98273', '(360) 424-3700', 'https://childrensclinicoFSkagit.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Mount Vernon', 'Skagit County'], 'pediatric Childrens Clinic Skagit Mount Vernon children', 48.4213, -122.3353),
  ('Cowlitz Pediatric Clinic - Longview', 'Pediatric Clinic', 'Pediatric care for Cowlitz County children.', '1200 14th Ave', 'Longview', 'Cowlitz', '98632', '(360) 423-0400', 'https://cowlitzpeds.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Longview', 'Cowlitz County'], 'pediatric Cowlitz Pediatric Clinic Longview children', 46.1410, -122.9344),
  ('Jefferson Healthcare Pediatrics - Port Townsend', 'Pediatric Clinic', 'Pediatric care for East Jefferson County children.', '834 Sheridan St', 'Port Townsend', 'Jefferson', '98368', '(360) 385-2200', 'https://jeffersonhealthcare.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Port Townsend', 'Jefferson County'], 'pediatric Jefferson Healthcare Pediatrics Port Townsend children', 48.1163, -122.7755),
  ('Okanogan Pediatric Services - Omak', 'Pediatric Clinic', 'Pediatric care for Okanogan County children.', '918 E Main Ave', 'Omak', 'Okanogan', '98841', '(509) 826-7200', 'https://ncwchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Omak', 'Okanogan County'], 'pediatric Okanogan Pediatric Services Omak children', 48.4106, -119.5256),
  ('Lewis County Pediatrics - Chehalis', 'Pediatric Clinic', 'Pediatric care for Lewis County children.', '1040 NW Liberty Ave', 'Chehalis', 'Lewis', '98532', '(360) 736-8800', 'https://lewiscountypeds.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Well-Child Visits', 'Immunizations', 'Sick Visits'], ARRAY['pediatric', 'children', 'Chehalis', 'Lewis County'], 'pediatric Lewis County Pediatrics Chehalis children', 46.6630, -122.9663)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
