/*
# Add WA Substance Use, YVFWC, Sea Mar - Batch 7

## Summary
Adds 17 verified Washington State healthcare resources including:
- Substance use treatment centers (Sundown M Ranch, Pioneer Human Services)
- Washington Recovery Help Line and NAMI HelpLine
- Yakima Valley Farm Workers Clinic locations (Yakima, Walla Walla, Wapato, Granger, Prosser, Toppenish, Sunnyside, Wenatchee, Pasco, Othello)
- Sea Mar additional clinics (Marysville, Everett, Tacoma)
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Sundown M Ranch', (SELECT id FROM resource_categories WHERE slug='substance-use'), 'residential treatment', 'Substance use treatment center providing medically supervised detoxification, residential treatment, outpatient counseling, and family programs for adolescents, adults, and older adults.', '2280 State Route 821', 'Yakima', 'Yakima', 'WA', '98901', '509-457-0990', 'https://sundown.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{detoxification,residential treatment,outpatient counseling,family programs,medication-assisted treatment}', '{substance use,dual diagnosis}', '{adolescents,adults,families}', 0, 'https://images.pexels.com/photos/3759079/pexels-photo-3759079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Pioneer Human Services', (SELECT id FROM resource_categories WHERE slug='substance-use'), '', 'Non-profit organization providing substance use treatment, mental health services, housing, employment, and reentry services to individuals in need across Washington.', '1444 NW 52nd St', 'Seattle', 'King', 'WA', '98107', '206-957-4500', 'https://pioneerhumanservices.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{substance use treatment,mental health,housing,employment,reentry}', '{}', '{uninsured,low-income,formerly incarcerated}', 0, 'https://images.pexels.com/photos/3759079/pexels-photo-3759079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Washington Recovery Help Line', (SELECT id FROM resource_categories WHERE slug='crisis-line'), '', '24/7 statewide helpline providing substance use, problem gambling, and mental health support, crisis intervention, and referrals to treatment services.', '4516 Union Bay Pl NE, Suite 200', 'Seattle', 'King', 'WA', '98105', '866-789-1511', 'https://www.warecoveryhelpline.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{crisis intervention,referrals,substance use,mental health}', '{}', '{crisis,substance use,mental health}', 0, 'https://images.pexels.com/photos/4149199/pexels-photo-4149199.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('NAMI HelpLine Washington', (SELECT id FROM resource_categories WHERE slug='mental-health'), 'support line', 'Peer support helpline providing information, resource referrals, and compassionate support to individuals and families affected by mental health conditions.', '4252 23rd Ave W', 'Seattle', 'King', 'WA', '98199', '800-950-6264', 'https://namiwa.org', '{"mon":"10:00-18:00","tue":"10:00-18:00","wed":"10:00-18:00","thu":"10:00-18:00","fri":"10:00-18:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, true, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{peer support,resource referrals,mental health information}', '{}', '{mental health,families}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC 11th Avenue Family Medicine', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, dental, and pharmacy services to patients of all ages regardless of insurance status.', '314 S 11th Ave, Suite A', 'Yakima', 'Yakima', 'WA', '98902', '509-902-8585', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-14:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,dental,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Family Medical Center Walla Walla', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, dental, and pharmacy services to patients of all ages regardless of insurance status.', '1120 W Rose St', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-525-6650', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-14:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,dental,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Mid-Valley Family Medicine', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing comprehensive family medicine, behavioral health, and preventive care services to patients of all ages.', '620 W 1st St', 'Wapato', 'Yakima', 'WA', '98951', '509-877-3236', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,family medicine}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Granger Family Medicine', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing comprehensive family medicine, behavioral health, and immediate care services to patients of all ages.', '115 Sunnyside Ave', 'Granger', 'Yakima', 'WA', '98932', '509-854-2400', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,immediate care}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Valley Vista Medical Group', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, WIC, and pharmacy services to patients of all ages regardless of insurance status.', '820 Memorial St, Suite 1', 'Prosser', 'Benton', 'WA', '99350', '509-786-2010', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,WIC,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Toppenish Medical Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, dental, behavioral health, pharmacy, and specialty services to patients of all ages.', '509 Washington Ave', 'Toppenish', 'Yakima', 'WA', '98948', '509-865-5600', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-14:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Sunnyside Medical Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, dental, behavioral health, and pharmacy services to patients of all ages regardless of insurance status.', '1800 Yakima Valley Hwy', 'Sunnyside', 'Yakima', 'WA', '98944', '509-837-8150', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-14:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Wenatchee Medical Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, dental, behavioral health, pharmacy, and specialty services to patients of all ages regardless of insurance status.', '815 N Chelan Ave', 'Wenatchee', 'Chelan', 'WA', '98801', '509-662-6000', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-14:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Pasco Medical Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, dental, behavioral health, and pharmacy services to patients of all ages regardless of insurance status.', '1105 W Court St', 'Pasco', 'Franklin', 'WA', '99301', '509-546-2922', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-14:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('YVFWC Othello Medical Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, dental, behavioral health, and pharmacy services to patients of all ages regardless of insurance status.', '660 S 10th Ave', 'Othello', 'Adams', 'WA', '99344', '509-331-1400', 'https://www.yvfwc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{farm workers,families,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Marysville Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, and preventive services to patients of all ages regardless of insurance status.', '9710 State Ave', 'Marysville', 'Snohomish', 'WA', '98270', '360-653-1742', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Everett Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, and preventive services to patients of all ages regardless of insurance status.', '909 W Main St', 'Everett', 'Snohomish', 'WA', '98201', '425-789-2000', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Tacoma Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, and health care for the homeless to patients of all ages regardless of insurance status.', '3712 S Cedar St', 'Tacoma', 'Pierce', 'WA', '98409', '253-682-2190', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,homeless health care}', '{}', '{low-income,homeless,farm workers}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified')
ON CONFLICT DO NOTHING;
