-- Add more major missing hospitals and urgent care locations
INSERT INTO resources (
  id, name, category_id, subcategory, description, address, city, county, state, zip_code,
  lat, lng, phone, website, domain, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance,
  walk_ins_welcome, appointments, telehealth, cost_free,
  cost_estimate_min, cost_estimate_max, languages, accessibility,
  services, specialties, audiences, tags, search_text
) VALUES
-- UW Medical Center - Montlake (Top ranked hospital in WA)
(
  gen_random_uuid(),
  'UW Medical Center - Montlake',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Academic Medical Center',
  'UW Medical Center - Montlake is Washington States top-ranked hospital and one of the worlds foremost academic health centers. Nationally ranked in cancer, diabetes, GI, neurosurgery, obstetrics, orthopedics, urology, and rehabilitation medicine. Over 600 beds and the largest teaching hospital in UW Medicine system.',
  '1959 NE Pacific St',
  'Seattle',
  'King',
  'WA',
  '98195',
  47.6505,
  -122.3117,
  '(206) 598-3300',
  'https://www.uwmedicine.org/locations/uw-medical-center-montlake',
  'uwmedicine.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  500,
  5000,
  ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese', 'Korean', 'Russian', 'Somali'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Valet parking'],
  ARRAY['Emergency Room', 'Surgery', 'Cancer Care', 'Cardiac Care', 'Maternity', 'ICU', 'Transplant', 'Neuroscience', 'Rehabilitation'],
  ARRAY['Oncology', 'Cardiology', 'Neurology', 'Orthopedics', 'Transplant Surgery', 'Obstetrics', 'Rehabilitation Medicine'],
  ARRAY['Adults', 'Children', 'Families', 'Seniors'],
  ARRAY['hospital', 'academic medical center', 'cancer', 'cardiac', 'transplant', 'neuroscience', 'teaching hospital', 'uw medicine'],
  'UW Medical Center Montlake hospital academic cancer cardiac transplant neuroscience emergency teaching Seattle King County Washington'
),

-- Mary Bridge Childrens Hospital - Tacoma
(
  gen_random_uuid(),
  'Mary Bridge Childrens Hospital',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Pediatric Hospital',
  'Mary Bridge Childrens Hospital is Western Washingtons only state-designated Level II Pediatric Trauma Center and the only hospital in the South Sound dedicated to children. New state-of-the-art pediatric campus opened in 2025. Recognized as a Top Childrens Hospital by The Leapfrog Group. Part of MultiCare.',
  '305 S L St',
  'Tacoma',
  'Pierce',
  'WA',
  '98405',
  47.2511,
  -122.4395,
  '(253) 403-1400',
  'https://www.marybridge.org',
  'marybridge.org',
  '{"monday": "Open 24 hours", "tuesday": "Open 24 hours", "wednesday": "Open 24 hours", "thursday": "Open 24 hours", "friday": "Open 24 hours", "saturday": "Open 24 hours", "sunday": "Open 24 hours"}',
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  0,
  5000,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Korean', 'Russian', 'Tagalog'],
  ARRAY['Wheelchair accessible', 'TTY available', 'Interpreter services', 'Family housing', 'Playrooms'],
  ARRAY['Emergency Room', 'Pediatric Trauma Center', 'Surgery', 'PICU', 'Cancer Care', 'Cardiac Care', 'NICU'],
  ARRAY['Pediatrics', 'Pediatric Oncology', 'Pediatric Cardiology', 'Pediatric Surgery', 'Pediatric Critical Care'],
  ARRAY['Children', 'Teens', 'Families'],
  ARRAY['hospital', 'pediatric', 'children', 'trauma center', 'cancer', 'cardiac', 'tacoma', 'multicare', 'south sound'],
  'Mary Bridge Childrens Hospital pediatric trauma center cancer cardiac emergency Tacoma Pierce County Washington South Sound MultiCare'
),

-- MultiCare Indigo Urgent Care - Bellevue
(
  gen_random_uuid(),
  'MultiCare Indigo Urgent Care - Bellevue',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Urgent Care',
  'MultiCare Indigo Urgent Care provides same-day treatment for non-life-threatening illnesses and injuries. Walk-ins welcome. On-site lab and X-ray services available. Open 7 days a week with evening and weekend hours.',
  '15600 NE 8th St Suite A4',
  'Bellevue',
  'King',
  'WA',
  '98008',
  47.6175,
  -122.1324,
  '(425) 643-3331',
  'https://www.indigohealth.com/locations/urgent-care-bellevue',
  'indigohealth.com',
  '{"monday": "8:00 AM - 8:00 PM", "tuesday": "8:00 AM - 8:00 PM", "wednesday": "8:00 AM - 8:00 PM", "thursday": "8:00 AM - 8:00 PM", "friday": "8:00 AM - 8:00 PM", "saturday": "8:00 AM - 8:00 PM", "sunday": "8:00 AM - 8:00 PM"}',
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  100,
  300,
  ARRAY['English', 'Spanish'],
  ARRAY['Wheelchair accessible', 'Free parking', 'X-ray on-site', 'Lab on-site'],
  ARRAY['Urgent Care', 'X-ray', 'Lab Services', 'Vaccinations', 'Physical Exams', 'Sports Physicals'],
  ARRAY['Family Medicine', 'Urgent Care Medicine'],
  ARRAY['Adults', 'Children', 'Families'],
  ARRAY['urgent care', 'walk-in clinic', 'x-ray', 'lab', 'bellevue', 'indigo', 'multicare'],
  'MultiCare Indigo Urgent Care Bellevue walk-in clinic x-ray lab same-day care King County Washington'
),

-- Overlake Downtown Bellevue Urgent Care
(
  gen_random_uuid(),
  'Overlake Clinics - Downtown Bellevue Urgent Care',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Urgent Care',
  'Overlake Downtown Bellevue Urgent Care provides same-day treatment for non-emergency conditions. Reserve your spot online to reduce wait times. Walk-ins welcome. Evening and weekend hours available.',
  '10223 NE 10th St',
  'Bellevue',
  'King',
  'WA',
  '98004',
  47.6192,
  -122.1868,
  '(425) 688-5000',
  'https://www.overlakehospital.org/locations/overlake-clinics-urgent-care-bellevue-downtown',
  'overlakehospital.org',
  '{"monday": "8:00 AM - 8:00 PM", "tuesday": "8:00 AM - 8:00 PM", "wednesday": "8:00 AM - 8:00 PM", "thursday": "8:00 AM - 8:00 PM", "friday": "8:00 AM - 8:00 PM", "saturday": "9:00 AM - 5:00 PM", "sunday": "9:00 AM - 5:00 PM"}',
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  100,
  300,
  ARRAY['English', 'Spanish'],
  ARRAY['Wheelchair accessible', 'Parking available'],
  ARRAY['Urgent Care', 'Lab Services', 'Physical Exams', 'Vaccinations'],
  ARRAY['Family Medicine', 'Urgent Care Medicine'],
  ARRAY['Adults', 'Children', 'Families'],
  ARRAY['urgent care', 'walk-in clinic', 'downtown bellevue', 'overlake', 'multicare'],
  'Overlake Downtown Bellevue Urgent Care walk-in clinic same-day care King County Washington'
),

-- UW Medicine Urgent Care - Kirkland
(
  gen_random_uuid(),
  'UW Medicine Urgent Care - Kirkland',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Urgent Care',
  'UW Medicine Urgent Care Kirkland provides same-day care for non-life-threatening conditions. Part of UW Medicine, affiliated with the University of Washington. Walk-ins welcome, online scheduling available.',
  '620 Kirkland Way Suite 100',
  'Kirkland',
  'King',
  'WA',
  '98033',
  47.6782,
  -122.1935,
  '(425) 899-5000',
  'https://www.uwmedicine.org/locations/kirkland/urgent-care',
  'uwmedicine.org',
  '{"monday": "8:00 AM - 8:00 PM", "tuesday": "8:00 AM - 8:00 PM", "wednesday": "8:00 AM - 8:00 PM", "thursday": "8:00 AM - 8:00 PM", "friday": "8:00 AM - 8:00 PM", "saturday": "9:00 AM - 5:00 PM", "sunday": "9:00 AM - 5:00 PM"}',
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  100,
  300,
  ARRAY['English', 'Spanish'],
  ARRAY['Wheelchair accessible', 'Free parking'],
  ARRAY['Urgent Care', 'Lab Services', 'X-ray'],
  ARRAY['Family Medicine', 'Urgent Care Medicine'],
  ARRAY['Adults', 'Children', 'Families'],
  ARRAY['urgent care', 'walk-in clinic', 'kirkland', 'uw medicine'],
  'UW Medicine Urgent Care Kirkland walk-in clinic same-day care King County Washington'
),

-- UW Medicine Urgent Care - Issaquah
(
  gen_random_uuid(),
  'UW Medicine Urgent Care - Issaquah',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Urgent Care',
  'UW Medicine Urgent Care Issaquah provides same-day care for non-emergency conditions on the Eastside. Part of UW Medicine. Walk-ins welcome with online scheduling available.',
  '2008 NW Sammamish Rd',
  'Issaquah',
  'King',
  'WA',
  '98027',
  47.5423,
  -122.0678,
  '(425) 313-7000',
  'https://www.uwmedicine.org/locations/issaquah/urgent-care',
  'uwmedicine.org',
  '{"monday": "8:00 AM - 8:00 PM", "tuesday": "8:00 AM - 8:00 PM", "wednesday": "8:00 AM - 8:00 PM", "thursday": "8:00 AM - 8:00 PM", "friday": "8:00 AM - 8:00 PM", "saturday": "9:00 AM - 5:00 PM", "sunday": "9:00 AM - 5:00 PM"}',
  true,
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  100,
  300,
  ARRAY['English', 'Spanish'],
  ARRAY['Wheelchair accessible', 'Free parking'],
  ARRAY['Urgent Care', 'Lab Services'],
  ARRAY['Family Medicine', 'Urgent Care Medicine'],
  ARRAY['Adults', 'Children', 'Families'],
  ARRAY['urgent care', 'walk-in clinic', 'issaquah', 'uw medicine', 'eastside'],
  'UW Medicine Urgent Care Issaquah walk-in clinic same-day care King County Washington eastside'
),

-- Seattle Childrens Urgent Care - Bellevue
(
  gen_random_uuid(),
  'Seattle Childrens Urgent Care - Bellevue',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Pediatric Urgent Care',
  'Seattle Childrens Urgent Care Bellevue offers same-day care for children and teens up to their 21st birthday. Pediatric specialists available 365 days a year including holidays. Virtual care also available.',
  '1500 116th Ave NE Suite 100',
  'Bellevue',
  'King',
  'WA',
  '98004',
  47.6208,
  -122.1783,
  '(866) 987-2000',
  'https://www.seattlechildrens.org/clinics/urgent-care-clinic',
  'seattlechildrens.org',
  '{"monday": "12:00 PM - 10:00 PM", "tuesday": "12:00 PM - 10:00 PM", "wednesday": "12:00 PM - 10:00 PM", "thursday": "12:00 PM - 10:00 PM", "friday": "12:00 PM - 10:00 PM", "saturday": "10:00 AM - 8:00 PM", "sunday": "10:00 AM - 8:00 PM"}',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false,
  100,
  300,
  ARRAY['English', 'Spanish', 'Vietnamese', 'Chinese', 'Somali'],
  ARRAY['Wheelchair accessible', 'Interpreter services', 'Child-friendly environment'],
  ARRAY['Pediatric Urgent Care', 'Virtual Care', 'Sports Medicine'],
  ARRAY['Pediatrics', 'Urgent Care Medicine'],
  ARRAY['Children', 'Teens', 'Young Adults'],
  ARRAY['urgent care', 'pediatric', 'children', 'bellevue', 'seattle childrens', 'virtual care'],
  'Seattle Childrens Urgent Care Bellevue pediatric same-day care children teens King County Washington'
),

-- ZoomCare Bellevue
(
  gen_random_uuid(),
  'ZoomCare - Bellevue 4th Street',
  'd62b804c-edb4-4a80-ae97-06106d2f7573',
  'Urgent Care',
  'ZoomCare Bellevue provides on-demand urgent care and primary care services. Open 7 days a week with same-day appointments. No appointment necessary for most services.',
  '10541 NE 4th St',
  'Bellevue',
  'King',
  'WA',
  '98004',
  47.6189,
  -122.1924,
  '(503) 928-2273',
  'https://www.zoomcare.com/clinic/zoomcare-bellevue-4th',
  'zoomcare.com',
  '{"monday": "8:00 AM - 8:00 PM", "tuesday": "8:00 AM - 8:00 PM", "wednesday": "8:00 AM - 8:00 PM", "thursday": "8:00 AM - 8:00 PM", "friday": "8:00 AM - 8:00 PM", "saturday": "8:00 AM - 6:00 PM", "sunday": "8:00 AM - 6:00 PM"}',
  true,
  false,
  false,
  true,
  true,
  true,
  true,
  false,
  false,
  99,
  250,
  ARRAY['English', 'Spanish'],
  ARRAY['Wheelchair accessible', 'Parking available'],
  ARRAY['Urgent Care', 'Primary Care', 'Lab Services', 'X-ray', 'Vaccinations'],
  ARRAY['Family Medicine', 'Urgent Care Medicine'],
  ARRAY['Adults', 'Children', 'Families'],
  ARRAY['urgent care', 'primary care', 'walk-in clinic', 'zoomcare', 'bellevue'],
  'ZoomCare Bellevue urgent care primary care walk-in clinic same-day appointments King County Washington'
);