/*
# Expand symptom catalog with 40+ additional symptoms

Adds 40 more symptoms covering a wide range of common conditions across
cardiac, respiratory, digestive, neurological, musculoskeletal, dermatologic,
mental health, women's health, pediatric, ENT, and general primary care areas.
Each has keywords, specialties, urgency, recommended care types, and category
slugs. A subset also gets FAQs and trusted sources.

No emergency icons or panic-inducing labels are used. The red_flag column is
set to false on all new rows; the UI shows a neutral concern note instead.

## Symptoms added (40):
Allergy Symptoms, Ankle Sprain, Arthritis, Asthma, Back Pain, Bronchitis,
Burns (Minor), Calf Pain, Common Cold, Constipation, Cough (Chronic),
Dizziness, Dry Eyes, Fatigue, Foot Pain, Hand Numbness, Headache (Tension),
Headache (Migraine), Hearing Loss, Hemorrhoids, High Blood Pressure,
Hip Pain, Insomnia, Irritable Bowel Syndrome, Joint Pain, Knee Pain,
Menstrual Cramps, Migraine, Neck Pain, Nosebleed, Pink Eye (duplicate check skipped),
Pinkeye Allergic, Ringworm, Sciatica, Sinus Infection, Skin Infection,
Sprain, Stomach Pain, Sunburn, Swollen Lymph Nodes, UTI, Vertigo, Wrist Pain
*/

INSERT INTO symptoms (name, slug, description, keywords, specialties, urgency, recommended_care_types, category_slugs, red_flag, sort_order) VALUES
-- A
('Allergy Symptoms','allergy-symptoms','Allergies occur when the immune system reacts to a foreign substance such as pollen, pet dander, dust mites, or certain foods. Symptoms include sneezing, runny or stuffy nose, itchy or watery eyes, skin rashes, and sometimes coughing or wheezing. Most allergies are manageable with over-the-counter medications and avoidance of triggers.',
 ARRAY['allergies','allergy','sneezing','hay fever','seasonal allergies','pollen allergy','dust allergy','pet allergy','allergic reaction','stuffy nose','runny nose'],
 ARRAY['primary care','allergy and immunology'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 13),
('Ankle Sprain','ankle-sprain','An ankle sprain is an injury to the ligaments that support the ankle, usually caused by rolling or twisting the ankle. Symptoms include pain, swelling, bruising, and difficulty bearing weight. Most sprains heal with rest, ice, compression, and elevation (RICE), but severe sprains may need imaging and professional treatment.',
 ARRAY['ankle sprain','sprained ankle','rolled ankle','twisted ankle','ankle pain','ankle swelling','ankle injury'],
 ARRAY['orthopedics','primary care','sports medicine'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 14),
('Arthritis','arthritis','Arthritis is inflammation of one or more joints causing pain, stiffness, and reduced range of motion. The two most common types are osteoarthritis (wear-and-tear) and rheumatoid arthritis (autoimmune). Symptoms often worsen with age and can affect daily activities. Treatment includes medication, physical therapy, lifestyle changes, and in some cases surgery.',
 ARRAY['arthritis','joint pain','joint stiffness','osteoarthritis','rheumatoid arthritis','inflamed joints','stiff joints','achy joints'],
 ARRAY['rheumatology','orthopedics','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 15),
('Asthma','asthma','Asthma is a chronic condition where the airways become inflamed and narrowed, causing episodes of wheezing, coughing, chest tightness, and shortness of breath. Triggers include allergens, exercise, cold air, and respiratory infections. Asthma is managed with controller and rescue inhalers and an asthma action plan.',
 ARRAY['asthma','wheezing','asthma attack','breathing problem','inhaler','airway','asthma flare','coughing at night'],
 ARRAY['pulmonology','primary care','allergy and immunology'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 16),
-- B
('Back Pain','back-pain','Back pain is one of the most common reasons people visit a doctor. It can range from a dull, constant ache to sudden, sharp pain. Most back pain is mechanical, related to muscles, ligaments, or discs. It often improves with rest, gentle movement, and over-the-counter pain relievers. Seek care if pain is severe, lasts more than a few weeks, or is accompanied by numbness, weakness, or bowel/bladder changes.',
 ARRAY['back pain','lower back pain','upper back pain','backache','spine pain','lumbar pain','back strain','slipped disc','herniated disc','sciatica pain'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 17),
('Bronchitis','bronchitis','Bronchitis is inflammation of the bronchial tubes, which carry air to the lungs. Acute bronchitis is usually caused by a viral infection and causes a cough that may produce mucus, chest discomfort, mild fever, and fatigue. It typically resolves on its own within 1-3 weeks. Chronic bronchitis is a form of COPD and requires ongoing management.',
 ARRAY['bronchitis','chest cold','cough with mucus','productive cough','acute bronchitis','chronic bronchitis','airway inflammation'],
 ARRAY['primary care','pulmonology'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 18),
('Burns (Minor)','minor-burns','Minor burns are first-degree or small second-degree burns affecting the outer layer of skin. They cause redness, pain, and sometimes blistering. Common causes include hot water, steam, sun exposure, and brief contact with hot objects. Treatment includes cooling the burn with running water, applying aloe or moisturizer, and covering with a clean bandage.',
 ARRAY['burn','burns','minor burn','first degree burn','second degree burn','sunburn','scald','hot water burn','blister','skin burn'],
 ARRAY['primary care','urgent care'],
 'low', ARRAY['urgent-care','primary-care'], ARRAY['primary-care'], false, 19),
-- C
('Common Cold','common-cold','The common cold is a viral infection of the upper respiratory tract. Symptoms include a runny or stuffy nose, sore throat, cough, mild headache, sneezing, and mild body aches. Colds usually resolve within 7-10 days without medical treatment. Rest, fluids, and over-the-counter symptom relievers can help.',
 ARRAY['cold','common cold','runny nose','stuffy nose','sneezing','head cold','nasal congestion','cold symptoms'],
 ARRAY['primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 20),
('Constipation','constipation','Constipation is having fewer than three bowel movements a week, hard or dry stools, or difficulty passing stool. It can be caused by low fiber intake, dehydration, lack of exercise, certain medications, or medical conditions. Most cases improve with dietary changes, increased water intake, and over-the-counter remedies.',
 ARRAY['constipation','hard stool','difficult bowel movement','no bowel movement','blocked up','constipated','infrequent stools'],
 ARRAY['primary care','gastroenterology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 21),
('Cough (Chronic)','chronic-cough','A chronic cough is a cough that lasts eight weeks or longer in adults. Common causes include postnasal drip, asthma, gastroesophageal reflux disease (GERD), medications (such as ACE inhibitors), and infections. A persistent cough should be evaluated by a healthcare provider to identify and treat the underlying cause.',
 ARRAY['chronic cough','persistent cough','cough for weeks','dry cough','cough that wont go away','lingering cough'],
 ARRAY['primary care','pulmonology'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 22),
-- D
('Dizziness','dizziness','Dizziness is a term used to describe a range of sensations, including feeling faint, woozy, weak, or unsteady. It can result from dehydration, low blood sugar, inner ear problems, medication side effects, or more serious conditions. Seek care if dizziness is recurrent, severe, or accompanied by chest pain, fainting, or difficulty speaking.',
 ARRAY['dizziness','dizzy','lightheaded','woozy','unsteady','off balance','fainting feeling','vertigo'],
 ARRAY['primary care','neurology','ent'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 23),
('Dry Eyes','dry-eyes','Dry eye syndrome occurs when the eyes do not produce enough tears or the tears are of poor quality. Symptoms include a stinging or burning sensation, redness, sensitivity to light, blurred vision, and a feeling of something in the eye. Treatment includes artificial tears, lifestyle changes, and in some cases prescription eye drops.',
 ARRAY['dry eyes','dry eye','eye irritation','burning eyes','scratchy eyes','eye drops','tear production',' gritty eyes'],
 ARRAY['ophthalmology','optometry','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 24),
-- F
('Fatigue','fatigue','Fatigue is a feeling of constant tiredness or exhaustion that is not relieved by rest. It can be caused by lifestyle factors (poor sleep, stress, diet), medical conditions (anemia, thyroid disorders, infections, depression), or medications. If fatigue persists for weeks or interferes with daily life, a medical evaluation can help identify the cause.',
 ARRAY['fatigue','tired','exhausted','no energy','always tired','weakness','lethargy','chronic fatigue','worn out'],
 ARRAY['primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 25),
('Foot Pain','foot-pain','Foot pain can result from plantar fasciitis, bunions, heel spurs, stress fractures, tendonitis, or poorly fitting shoes. The location and type of pain help determine the cause. Most foot pain improves with rest, proper footwear, stretching, and over-the-counter pain relievers. Persistent or severe pain should be evaluated.',
 ARRAY['foot pain','heel pain','plantar fasciitis','arch pain','bunions','foot ache','sole pain','ankle foot pain'],
 ARRAY['podiatry','orthopedics','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 26),
-- H
('Hand Numbness','hand-numbness','Hand numbness or tingling can be caused by nerve compression (such as carpal tunnel syndrome), peripheral neuropathy, poor circulation, or cervical spine issues. Carpal tunnel syndrome causes numbness, tingling, and weakness in the hand due to pressure on the median nerve. Persistent symptoms should be evaluated by a provider.',
 ARRAY['hand numbness','numb hands','tingling hands','carpal tunnel','pins and needles','hand tingling','wrist numbness','nerve compression'],
 ARRAY['neurology','orthopedics','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 27),
('Headache (Tension)','tension-headache','Tension headaches are the most common type of headache, causing a dull, aching pain on both sides of the head. They are often triggered by stress, poor posture, eye strain, or dehydration. Most tension headaches respond to rest, hydration, over-the-counter pain relievers, and stress management.',
 ARRAY['tension headache','headache','head pain','stress headache','dull headache','tight head','head pressure'],
 ARRAY['primary care','neurology'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 28),
('Hearing Loss','hearing-loss','Hearing loss can be gradual or sudden and may affect one or both ears. Causes include aging, noise exposure, earwax buildup, infections, and certain medications. Sudden hearing loss should be evaluated promptly. Hearing aids, medical treatment, or surgery can help depending on the cause.',
 ARRAY['hearing loss','cant hear','deaf','hard of hearing','muffled hearing','ear problem','sudden hearing loss'],
 ARRAY['ent','audiology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 29),
('Hemorrhoids','hemorrhoids','Hemorrhoids are swollen veins in the lower rectum or anus. They can cause itching, pain, discomfort, and bleeding during bowel movements. Common causes include straining, pregnancy, and chronic constipation. Most hemorrhoids improve with dietary changes, topical treatments, and warm baths.',
 ARRAY['hemorrhoids','piles','rectal bleeding','anal pain','rectal pain','itchy anus','bleeding during bowel movement'],
 ARRAY['primary care','gastroenterology','general surgery'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 30),
('High Blood Pressure','high-blood-pressure','High blood pressure (hypertension) is a common condition where the force of blood against artery walls is consistently too high. It often has no symptoms but can lead to serious health problems if untreated, including heart disease, stroke, and kidney damage. Regular monitoring and lifestyle changes are key to management.',
 ARRAY['high blood pressure','hypertension','blood pressure','elevated bp','hbp','pressure'],
 ARRAY['cardiology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 31),
('Hip Pain','hip-pain','Hip pain can result from arthritis, bursitis, tendonitis, muscle strain, or hip fractures. The pain may be felt in the hip joint, groin, thigh, or buttock. Most hip pain improves with rest, ice, stretching, and over-the-counter pain relievers. Severe pain or pain after a fall should be evaluated promptly.',
 ARRAY['hip pain','hip ache','groin pain','hip joint pain','bursitis hip','hip stiffness','lateral hip pain'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 32),
-- I
('Insomnia','insomnia','Insomnia is difficulty falling asleep, staying asleep, or both, despite having the opportunity to sleep. It can be acute (short-term) or chronic (lasting a month or more). Causes include stress, anxiety, depression, medications, caffeine, and medical conditions. Treatment includes sleep hygiene improvements, therapy (CBT-I), and sometimes medication.',
 ARRAY['insomnia','cant sleep','trouble sleeping','sleeplessness','no sleep','awake at night','sleep problem','poor sleep'],
 ARRAY['primary care','psychiatry','sleep medicine'],
 'low', ARRAY['primary-care','telehealth'], ARRAY['mental-health','primary-care'], false, 33),
('Irritable Bowel Syndrome','irritable-bowel-syndrome','Irritable bowel syndrome (IBS) is a common disorder affecting the large intestine. Symptoms include cramping, abdominal pain, bloating, gas, diarrhea, and constipation. IBS is a chronic condition that requires long-term management through diet, lifestyle changes, and stress management. It does not damage the bowel but can significantly affect quality of life.',
 ARRAY['ibs','irritable bowel','stomach cramps','bloating','gas','alternating diarrhea constipation','abdominal cramps','spastic colon'],
 ARRAY['gastroenterology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 34),
-- J
('Joint Pain','joint-pain','Joint pain can affect one or multiple joints and may result from arthritis, injury, infection, or overuse. The pain may be accompanied by swelling, stiffness, warmth, or reduced range of motion. Treatment depends on the cause and may include rest, medication, physical therapy, or other interventions.',
 ARRAY['joint pain','aching joints','stiff joints','arthralgia','joint swelling','joint stiffness','sore joints'],
 ARRAY['rheumatology','orthopedics','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 35),
-- K
('Knee Pain','knee-pain','Knee pain can result from injury (ligament tears, meniscus damage), mechanical problems, or arthritis. Symptoms include pain, swelling, stiffness, weakness, popping or clicking sounds. Many minor knee problems improve with rest, ice, compression, and elevation. Persistent or severe pain, or pain after an injury, should be evaluated.',
 ARRAY['knee pain','knee ache','knee swelling','knee injury','runner knee','knee stiffness','pain behind knee','knee popping'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 36),
-- M
('Menstrual Cramps','menstrual-cramps','Menstrual cramps (dysmenorrhea) are throbbing or cramping pains in the lower abdomen before and during menstrual periods. They can range from mild to severe and may be accompanied by back pain, nausea, and fatigue. Over-the-counter pain relievers, heat therapy, and lifestyle changes can help. Severe cramps that interfere with daily life should be evaluated.',
 ARRAY['menstrual cramps','period pain','cramps','dysmenorrhea','period cramps','pelvic pain during period','menstrual pain'],
 ARRAY['primary care','obstetrics and gynecology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 37),
('Migraine','migraine','A migraine is a neurological condition causing intense, throbbing headaches, often on one side of the head. Migraines can last hours to days and may be accompanied by nausea, vomiting, and sensitivity to light and sound. Some people experience an aura (visual disturbances) before the headache. Treatment includes medications to prevent and stop migraines.',
 ARRAY['migraine','migraine headache','severe headache','throbbing headache','headache with nausea','aura','light sensitivity','sound sensitivity'],
 ARRAY['neurology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 38),
-- N
('Neck Pain','neck-pain','Neck pain can result from poor posture, muscle strain, worn joints, injuries (such as whiplash), or nerve compression. Symptoms include stiffness, pain when turning the head, and sometimes numbness or tingling in the arms. Most neck pain improves with rest, gentle stretching, heat or ice, and over-the-counter pain relievers.',
 ARRAY['neck pain','stiff neck','neck ache','neck strain','whiplash','cervical pain','crick in neck'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 39),
('Nosebleed','nosebleed','A nosebleed (epistaxis) is bleeding from the nose, usually from the front part. Common causes include dry air, nose-picking, allergies, colds, and minor injuries. Most nosebleeds stop on their own within 10-20 minutes by pinching the soft part of the nose and leaning forward. Seek care if bleeding is heavy, lasts more than 20 minutes, or follows a head injury.',
 ARRAY['nosebleed','nose bleed','epistaxis','bleeding nose','blood from nose','nose bleeding'],
 ARRAY['ent','primary care','urgent care'],
 'low', ARRAY['urgent-care','primary-care'], ARRAY['primary-care'], false, 40),
-- P
('Pinkeye Allergic','allergic-conjunctivitis','Allergic conjunctivitis is eye inflammation caused by allergens such as pollen, dust, or pet dander. It causes redness, itching, tearing, and swollen eyelids. Unlike bacterial or viral conjunctivitis, it is not contagious. Treatment includes avoiding triggers, antihistamine eye drops, and cool compresses.',
 ARRAY['allergic conjunctivitis','allergy eyes','red itchy eyes','eye allergy','allergic pink eye','watery itchy eyes'],
 ARRAY['ophthalmology','optometry','allergy and immunology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 41),
-- R
('Ringworm','ringworm','Ringworm (tinea corporis) is a fungal skin infection that causes a red, itchy, circular rash with clearer skin in the middle. Despite the name, it is not caused by a worm. It is contagious and can spread through skin contact and contaminated items. Most cases respond to over-the-counter or prescription antifungal creams.',
 ARRAY['ringworm','tinea','fungal rash','circular rash','red ring rash','itchy ring','tinea corporis','fungal infection'],
 ARRAY['dermatology','primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 42),
-- S
('Sciatica','sciatica','Sciatica is pain that radiates along the path of the sciatic nerve, which branches from the lower back through the hips and buttocks and down each leg. It usually affects only one side and is caused by a herniated disc or bone spur compressing the nerve. Most cases improve with time, physical therapy, and pain management.',
 ARRAY['sciatica','sciatic nerve pain','leg pain from back','shooting leg pain','back leg pain','pinched nerve','nerve pain leg'],
 ARRAY['orthopedics','neurology','primary care','physical therapy'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 43),
('Sinus Infection','sinus-infection','Sinusitis is inflammation of the sinuses, often caused by a viral or bacterial infection. Symptoms include facial pressure, nasal congestion, thick nasal discharge, reduced sense of smell, and sometimes headache or tooth pain. Most cases are viral and resolve within 7-10 days. Bacterial sinusitis may need antibiotics.',
 ARRAY['sinus infection','sinusitis','sinus pressure','sinus pain','sinus congestion','sinus headache','blocked sinuses','nasal congestion'],
 ARRAY['ent','primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 44),
('Skin Infection','skin-infection','Skin infections can be caused by bacteria, fungi, viruses, or parasites. Common types include cellulitis (bacterial), impetigo, and fungal infections. Symptoms include redness, swelling, warmth, pain, pus, or fever. Minor infections may respond to topical treatments, but spreading or painful infections need medical evaluation.',
 ARRAY['skin infection','cellulitis','impetigo','infected skin','red swollen skin','skin abscess','pus','warm skin','skin redness'],
 ARRAY['dermatology','primary care','urgent care'],
 'moderate', ARRAY['urgent-care','primary-care'], ARRAY['primary-care'], false, 45),
('Stomach Pain','stomach-pain','Stomach pain (abdominal pain) can range from mild to severe and has many possible causes, including indigestion, gas, food poisoning, stomach viruses, appendicitis, gallstones, or ulcers. The location, type, and severity of pain help determine the cause. Seek care if pain is severe, sudden, or accompanied by fever, vomiting blood, or persistent vomiting.',
 ARRAY['stomach pain','abdominal pain','belly pain','stomach ache','tummy ache','gut pain','cramps','abdominal cramps'],
 ARRAY['primary care','gastroenterology'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 46),
('Sunburn','sunburn','Sunburn is skin damage from ultraviolet (UV) radiation, usually from sun exposure. Symptoms include red, painful, warm skin that may blister in severe cases. Repeated sunburns increase the risk of skin cancer. Treatment includes cool compresses, aloe vera, moisturizers, and over-the-counter pain relievers. Prevention with sunscreen is key.',
 ARRAY['sunburn','sun burned','red skin from sun','peeling skin','sun exposure','uv burn','burned skin'],
 ARRAY['dermatology','primary care'],
 'low', ARRAY['urgent-care','primary-care'], ARRAY['primary-care'], false, 47),
('Swollen Lymph Nodes','swollen-lymph-nodes','Swollen lymph nodes are a sign that the body is fighting an infection or, less commonly, another condition. They often occur in the neck, armpits, or groin and feel like tender lumps under the skin. Most swelling is caused by minor infections and resolves on its own. Seek care if nodes are hard, growing, or persist for more than a few weeks.',
 ARRAY['swollen lymph nodes','swollen glands','lumps in neck','enlarged nodes','lymphadenopathy','tender nodes','neck lumps'],
 ARRAY['primary care','hematology'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 48),
-- U
('Urinary Tract Infection','urinary-tract-infection','A urinary tract infection (UTI) is an infection in any part of the urinary system — kidneys, ureters, bladder, or urethra. Most UTIs involve the bladder and urethra. Symptoms include a strong, frequent urge to urinate, burning during urination, cloudy or strong-smelling urine, and pelvic pain. UTIs are typically treated with antibiotics.',
 ARRAY['uti','urinary tract infection','bladder infection','burning urination','frequent urination','cloudy urine','urine pain','kidney infection'],
 ARRAY['primary care','urology'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 49),
-- V
('Vertigo','vertigo','Vertigo is a sensation of spinning or dizziness, often caused by inner ear problems such as benign paroxysmal positional vertigo (BPPV), Meniere''s disease, or vestibular neuritis. It can be triggered by changes in head position. Treatment depends on the cause and may include head maneuvers, medication, or vestibular therapy.',
 ARRAY['vertigo','spinning sensation','dizziness','room spinning','balance problem','vestibular','bppv','menieres'],
 ARRAY['ent','neurology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 50),
-- W
('Wrist Pain','wrist-pain','Wrist pain can result from sprains, strains, fractures, tendonitis, carpal tunnel syndrome, or arthritis. It may involve pain, swelling, stiffness, weakness, or clicking. Many minor wrist problems improve with rest, ice, splinting, and over-the-counter pain relievers. Persistent pain or pain after an injury should be evaluated.',
 ARRAY['wrist pain','wrist ache','wrist sprain','wrist injury','carpal tunnel','wrist stiffness','wrist swelling'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 51),
-- Additional high-value symptoms
('Abdominal Pain','abdominal-pain','Abdominal pain is pain anywhere between the chest and groin. It can be acute or chronic and has many possible causes, from indigestion and gas to appendicitis or gallstones. The nature, location, and severity of the pain help determine the cause. Seek care for severe, sudden, or persistent pain, especially with fever or vomiting.',
 ARRAY['abdominal pain','belly pain','stomach pain','gut pain','abdomen','tummy ache','pelvic pain','gut cramps'],
 ARRAY['primary care','gastroenterology','general surgery'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 52),
('Diarrhea','diarrhea','Diarrhea is loose, watery bowel movements that occur more frequently than usual. It is usually caused by a viral or bacterial infection, food poisoning, or a change in diet. Most cases resolve within a few days. Stay hydrated and eat bland foods. Seek care if diarrhea lasts more than two days, contains blood, or is accompanied by high fever or severe dehydration.',
 ARRAY['diarrhea','loose stools','watery stool','the runs','loose motion','frequent bowel movements','stomach bug'],
 ARRAY['primary care','gastroenterology'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 53),
('Heartburn','heartburn','Heartburn is a burning sensation in the chest, just behind the breastbone, often after eating. It is caused by stomach acid backing up into the esophagus (acid reflux). Occasional heartburn is common and manageable with lifestyle changes and over-the-counter antacids. Frequent heartburn (more than twice a week) may indicate GERD and should be evaluated.',
 ARRAY['heartburn','acid reflux','indigestion','gerd','burning chest','acid stomach','reflux','sour stomach'],
 ARRAY['primary care','gastroenterology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 54),
('Hives','hives','Hives (urticaria) are raised, itchy welts on the skin that can vary in size and appear anywhere on the body. They are usually caused by allergic reactions to food, medication, insect bites, or infections. Most hives are acute and resolve within 24 hours. Over-the-counter antihistamines can help. Seek care if hives are accompanied by swelling of the throat or difficulty breathing.',
 ARRAY['hives','urticaria','welts','itchy bumps','raised rash','allergic welts','skin bumps itchy'],
 ARRAY['dermatology','primary care','allergy and immunology'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 55),
('Ingrown Toenail','ingrown-toenail','An ingrown toenail occurs when the corner or edge of a toenail grows into the surrounding skin, causing pain, redness, swelling, and sometimes infection. It most commonly affects the big toe. Mild cases can be treated at home with warm soaks and proper nail trimming. Severe or infected cases may need a provider to trim or remove the nail.',
 ARRAY['ingrown toenail','ingrown nail','toenail pain','infected toenail','nail growing into skin','toe pain','ingrown toe'],
 ARRAY['podiatry','primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 56),
('Motion Sickness','motion-sickness','Motion sickness occurs when the brain receives conflicting signals from the eyes, inner ears, and body during movement. Symptoms include nausea, dizziness, sweating, and vomiting. It is common during car rides, boat trips, and flights. Prevention includes looking at the horizon, sitting in the front seat, and taking over-the-counter motion sickness medication before travel.',
 ARRAY['motion sickness','car sick','sea sick','travel sickness','nausea from movement','motion sickness','airsickness'],
 ARRAY['primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 57),
('Pinkeye Bacterial','bacterial-conjunctivitis','Bacterial conjunctivitis is an eye infection caused by bacteria, leading to redness, a thick yellow or green discharge, crusting of the eyelids (especially in the morning), and irritation. Unlike viral conjunctivitis, it often requires antibiotic eye drops or ointment. It is contagious, so good hygiene is important.',
 ARRAY['bacterial conjunctivitis','bacterial pink eye','eye discharge','crusty eyes','yellow eye discharge','green eye discharge','infected eye'],
 ARRAY['ophthalmology','optometry','primary care'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 58),
('Snoring','snoring','Snoring is the hoarse or harsh sound that occurs when air flows past relaxed tissues in the throat during sleep. Occasional snoring is common, but loud, chronic snoring may be a sign of sleep apnea, a condition where breathing repeatedly stops during sleep. If snoring is accompanied by daytime sleepiness or pauses in breathing, evaluation is recommended.',
 ARRAY['snoring','loud snoring','sleep apnea','snore','noisy breathing at night','breathing pauses','night breathing'],
 ARRAY['ent','sleep medicine','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 59),
('Vaginal Discharge','vaginal-discharge','Vaginal discharge is common and varies in amount and consistency throughout the menstrual cycle. However, changes in color, odor, or texture — especially with itching, burning, or irritation — may indicate an infection such as a yeast infection, bacterial vaginosis, or a sexually transmitted infection. Most causes are treatable with medication.',
 ARRAY['vaginal discharge','abnormal discharge','yeast infection','bv','bacterial vaginosis','vaginal itching','vaginal odor','std symptoms'],
 ARRAY['obstetrics and gynecology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 60),
('Warts','warts','Warts are small, rough growths on the skin caused by the human papillomavirus (HPV). They commonly appear on hands, feet, and other areas. Most warts are harmless and may go away on their own, but they can be unsightly or painful. Treatment options include over-the-counter salicylic acid, freezing, and prescription treatments.',
 ARRAY['warts','wart','skin growth','hpv wart','plantar wart','common wart','hand wart','foot wart'],
 ARRAY['dermatology','primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 61),
('Yeast Infection','yeast-infection','A vaginal yeast infection is a fungal infection that causes irritation, discharge, and intense itchiness of the vagina and vulva. It is caused by an overgrowth of the fungus Candida. Symptoms include thick white discharge, redness, swelling, and burning during urination or intercourse. Most yeast infections are treated with over-the-counter or prescription antifungal medications.',
 ARRAY['yeast infection','candida','vaginal yeast','vaginal itching','fungal infection','thrush','monistat','yeast'],
 ARRAY['obstetrics and gynecology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 62),
('Gout','gout','Gout is a form of arthritis caused by excess uric acid in the bloodstream, which forms sharp crystals in joints. It typically affects the big toe but can occur in other joints. Symptoms include sudden, severe pain, redness, swelling, and warmth in the affected joint. Attacks often happen at night. Treatment includes medication to reduce inflammation and lower uric acid levels.',
 ARRAY['gout','gout attack','big toe pain','uric acid','joint crystals','podagra','swollen big toe','gouty arthritis'],
 ARRAY['rheumatology','primary care'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 63),
('Anemia','anemia','Anemia is a condition where the blood does not have enough healthy red blood cells or hemoglobin to carry adequate oxygen to the body''s tissues. Common causes include iron deficiency, vitamin deficiency, blood loss, or chronic diseases. Symptoms include fatigue, weakness, pale skin, shortness of breath, dizziness, and cold hands and feet. Treatment depends on the underlying cause.',
 ARRAY['anemia','low iron','iron deficiency','tired all the time','pale','low blood count','fatigue','hemoglobin'],
 ARRAY['primary care','hematology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 64),
('Carpal Tunnel Syndrome','carpal-tunnel-syndrome','Carpal tunnel syndrome is a condition caused by compression of the median nerve as it travels through the wrist. Symptoms include numbness, tingling, and weakness in the hand and fingers, especially at night. It is often related to repetitive hand use, pregnancy, or medical conditions. Treatment includes wrist splinting, activity changes, and in some cases surgery.',
 ARRAY['carpal tunnel','carpal tunnel syndrome','wrist numbness','hand tingling','numb fingers','median nerve','wrist splint','hand weakness at night'],
 ARRAY['orthopedics','neurology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 65),
('Eczema','eczema','Eczema (atopic dermatitis) is a chronic skin condition that causes dry, itchy, red, and inflamed skin. It often begins in childhood and can flare periodically. Triggers include irritants, allergens, stress, and weather. While there is no cure, eczema is manageable with moisturizers, topical medications, and trigger avoidance.',
 ARRAY['eczema','atopic dermatitis','dry skin','itchy skin','skin inflammation','dermatitis','skin rash','scaly skin'],
 ARRAY['dermatology','primary care','allergy and immunology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 66),
('Gastroesophageal Reflux Disease','gastroesophageal-reflux-disease','Gastroesophageal reflux disease (GERD) is a chronic condition where stomach acid regularly flows back into the esophagus, causing heartburn, chest pain, difficulty swallowing, and a sour taste in the mouth. It can often be managed with lifestyle changes and medication. Untreated GERD can lead to complications such as esophagitis.',
 ARRAY['gerd','acid reflux','chronic heartburn','reflux disease','stomach acid','esophagus','regurgitation','indigestion chronic'],
 ARRAY['gastroenterology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 67),
('Sleep Apnea','sleep-apnea','Sleep apnea is a serious sleep disorder where breathing repeatedly stops and starts during sleep. The most common type is obstructive sleep apnea, caused by throat muscles relaxing. Symptoms include loud snoring, gasping during sleep, morning headaches, and daytime sleepiness. Untreated sleep apnea increases the risk of heart problems and other health issues.',
 ARRAY['sleep apnea','apnea','snoring','stop breathing in sleep','daytime sleepiness','cpap','breathing pauses','sleep disorder'],
 ARRAY['sleep medicine','ent','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 68),
('Thyroid Problems','thyroid-problems','Thyroid problems occur when the thyroid gland produces too much (hyperthyroidism) or too little (hypothyroidism) thyroid hormone. Symptoms of hypothyroidism include fatigue, weight gain, cold sensitivity, and dry skin. Hyperthyroidism causes weight loss, rapid heartbeat, anxiety, and heat sensitivity. Both are diagnosed with blood tests and treated with medication.',
 ARRAY['thyroid','hypothyroidism','hyperthyroidism','underactive thyroid','overactive thyroid','goiter','hashimotos','graves disease','thyroid hormone'],
 ARRAY['endocrinology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 69),
('Migraine with Aura','migraine-with-aura','Migraine with aura is a type of migraine that includes sensory disturbances (aura) before or during the headache. Auras may include visual changes like flashing lights, zigzag lines, or blind spots, as well as tingling in the face or hands. The headache that follows is often throbbing and one-sided. Treatment includes medications to prevent and stop attacks.',
 ARRAY['migraine with aura','aura migraine','visual aura','flashing lights','zigzag lines','migraine aura','classic migraine','visual disturbance before headache'],
 ARRAY['neurology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 70),
('Conjunctivitis Viral','viral-conjunctivitis','Viral conjunctivitis is an eye infection caused by a virus, often associated with a cold or respiratory infection. Symptoms include redness, watery discharge, itching, and a gritty feeling in the eye. It is highly contagious but usually resolves on its own within 1-2 weeks. Supportive care includes cool compresses and artificial tears.',
 ARRAY['viral conjunctivitis','viral pink eye','pink eye virus','watery red eye','eye cold','contagious eye infection'],
 ARRAY['ophthalmology','optometry','primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 71),
('Tendonitis','tendonitis','Tendonitis is inflammation or irritation of a tendon, the thick cord that attaches muscle to bone. It is most often caused by repetitive motion or sudden injury. Common areas include the shoulder, elbow, wrist, knee, and heel. Symptoms include pain, tenderness, and mild swelling near the affected joint. Treatment includes rest, ice, anti-inflammatory medication, and physical therapy.',
 ARRAY['tendonitis','tendinitis','tendon pain','inflamed tendon','tennis elbow','golfers elbow','rotator cuff tendonitis','achilles tendonitis'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 72),
('Bursitis','bursitis','Bursitis is inflammation of the bursae, small fluid-filled sacs that cushion bones, tendons, and muscles near joints. It commonly affects the shoulder, elbow, hip, and knee. Symptoms include pain, swelling, and stiffness in the affected joint, often worsening with movement. Treatment includes rest, ice, anti-inflammatory medication, and sometimes corticosteroid injections.',
 ARRAY['bursitis','joint inflammation','bursa','swollen joint','shoulder bursitis','hip bursitis','knee bursitis','joint pain swelling'],
 ARRAY['orthopedics','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 73),
('Osteoporosis','osteoporosis','Osteoporosis is a condition where bones become weak and brittle, making them more likely to fracture. It often develops silently over years and is most common in older adults, particularly postmenopausal women. Risk factors include family history, low calcium intake, smoking, and inactivity. Treatment includes calcium and vitamin D supplementation, medication, weight-bearing exercise, and fall prevention.',
 ARRAY['osteoporosis','bone loss','weak bones','brittle bones','low bone density','bone density','fractures','osteopenia'],
 ARRAY['endocrinology','rheumatology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 74),
('Gallstones','gallstones','Gallstones are hardened deposits of digestive fluid that form in the gallbladder. They may cause no symptoms, but when they block a bile duct, they can cause sudden, intense pain in the upper right abdomen, especially after eating fatty foods. Other symptoms include nausea, vomiting, and back pain. Treatment may include dietary changes, medication, or surgery to remove the gallbladder.',
 ARRAY['gallstones','gallstone','gallbladder pain','biliary colic','upper right abdominal pain','gallbladder attack','gallbladder stones'],
 ARRAY['gastroenterology','general surgery','primary care'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 75),
('Kidney Stones','kidney-stones','Kidney stones are hard deposits of minerals and salts that form inside the kidneys. They can cause severe pain in the back, side, lower abdomen, or groin, along with nausea, vomiting, and changes in urination. Small stones may pass on their own with hydration and pain management. Larger stones may need medical procedures to break up or remove them.',
 ARRAY['kidney stones','kidney stone','renal calculi','stone pain','back pain side pain','blood in urine','stone in kidney','urinary stone'],
 ARRAY['urology','primary care'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 76),
('Stroke Symptoms','stroke-symptoms','A stroke occurs when blood flow to part of the brain is interrupted or reduced, depriving brain tissue of oxygen. Signs include sudden numbness or weakness of the face, arm, or leg (especially on one side), confusion, trouble speaking, vision problems, dizziness, and severe headache. If you are concerned, you should consider emergency services.',
 ARRAY['stroke','stroke symptoms','face drooping','arm weakness','speech difficulty','sudden numbness','sudden confusion','trouble speaking','fast stroke test'],
 ARRAY['neurology','emergency medicine'],
 'high', ARRAY['urgent-care'], ARRAY['hospital'], false, 77),
('Allergic Reaction Severe','severe-allergic-reaction','A severe allergic reaction (anaphylaxis) is a rapid, whole-body allergic reaction that can be life-threatening. Symptoms may include hives, swelling of the throat or tongue, difficulty breathing, wheezing, rapid heartbeat, dizziness, and a drop in blood pressure. If you are concerned, you should consider emergency services.',
 ARRAY['anaphylaxis','severe allergic reaction','throat swelling','tongue swelling','allergy emergency','anaphylactic shock','epipen','allergic reaction severe'],
 ARRAY['allergy and immunology','emergency medicine'],
 'high', ARRAY['urgent-care'], ARRAY['hospital'], false, 78),
('Concussion','concussion','A concussion is a mild traumatic brain injury caused by a bump, blow, or jolt to the head. Symptoms may include headache, confusion, dizziness, nausea, sensitivity to light or noise, memory problems, and feeling foggy. Most concussions resolve with rest, but symptoms that worsen or persist need medical evaluation.',
 ARRAY['concussion','head injury','brain injury','bumped head','head trauma','post concussion','confusion after hit','headache after injury'],
 ARRAY['neurology','primary care','sports medicine'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 79),
('Dehydration','dehydration','Dehydration occurs when the body loses more fluids than it takes in, leading to insufficient water for normal body functions. Symptoms include thirst, dry mouth, decreased urination, dark urine, fatigue, dizziness, and confusion. Severe dehydration can be dangerous, especially in young children and older adults. Treatment involves fluid replacement, either oral or intravenous.',
 ARRAY['dehydration','dehydrated','dry mouth','thirst','dark urine','no urination','fluid loss','water loss'],
 ARRAY['primary care','urgent care'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 80),
('Hernia','hernia','A hernia occurs when an internal organ or tissue pushes through a weak spot in the surrounding muscle or connective tissue. Most hernias occur in the abdomen or groin. Symptoms include a visible bulge, discomfort or pain (especially when lifting, coughing, or standing), and a heavy or aching sensation. Some hernias need surgical repair.',
 ARRAY['hernia','inguinal hernia','abdominal bulge','groin bulge','hernia pain','ventral hernia','umbilical hernia','hiatal hernia'],
 ARRAY['general surgery','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 81),
('Shingles','shingles','Shingles (herpes zoster) is a viral infection that causes a painful rash with blisters, usually on one side of the body. It is caused by the varicella-zoster virus, the same virus that causes chickenpox. Anyone who has had chickenpox can develop shingles. Early treatment with antiviral medication can reduce severity and duration. A vaccine is available for prevention.',
 ARRAY['shingles','herpes zoster','shingles rash','painful rash','blister rash','nerve pain rash','zoster','shingles pain'],
 ARRAY['primary care','dermatology'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 82),
('Vitamin D Deficiency','vitamin-d-deficiency','Vitamin D deficiency occurs when the body does not have enough vitamin D, which is essential for bone health, immune function, and muscle function. Symptoms can include fatigue, bone pain, muscle weakness, and mood changes. Risk factors include limited sun exposure, darker skin, and certain medical conditions. Treatment typically involves vitamin D supplements.',
 ARRAY['vitamin d deficiency','low vitamin d','vitamin d','bone pain','muscle weakness','vitamin deficiency','sunshine vitamin','calcium absorption'],
 ARRAY['primary care','endocrinology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 83),
('Iron Deficiency','iron-deficiency','Iron deficiency is a common type of anemia where the body lacks enough iron to produce hemoglobin, the protein in red blood cells that carries oxygen. Symptoms include fatigue, pale skin, shortness of breath, dizziness, and cold hands and feet. It is more common in women due to menstruation and pregnancy. Treatment includes iron supplements and dietary changes.',
 ARRAY['iron deficiency','low iron','iron deficiency anemia','anemia','tired','pale skin','iron pills','ferritin low'],
 ARRAY['primary care','hematology'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 84),
('Tinnitus','tinnitus','Tinnitus is the perception of noise — such as ringing, buzzing, clicking, or hissing — in the ears without an external sound source. It can be caused by exposure to loud noise, age-related hearing loss, earwax blockage, or certain medications. While there is often no cure, treatments can help manage symptoms.',
 ARRAY['tinnitus','ringing in ears','ear ringing','ear noise','buzzing ears','clicking in ear','hissing in ear','ear sounds'],
 ARRAY['ent','audiology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 85),
('Cataracts','cataracts','A cataract is a clouding of the lens of the eye that affects vision. It is most commonly related to aging but can also result from injury, certain medications, or medical conditions. Symptoms include blurry vision, faded colors, glare, and difficulty seeing at night. Cataracts are treated with surgery to replace the cloudy lens with an artificial one.',
 ARRAY['cataracts','cataract','cloudy vision','blurry eyes','vision changes','lens clouding','eye clouding','cataract surgery'],
 ARRAY['ophthalmology','optometry','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 86),
('Glaucoma','glaucoma','Glaucoma is a group of eye conditions that damage the optic nerve, often caused by abnormally high pressure in the eye. It is a leading cause of blindness. In its early stages, glaucoma often has no symptoms, making regular eye exams important. Treatment includes eye drops, medication, or surgery to lower eye pressure.',
 ARRAY['glaucoma','eye pressure','optic nerve damage','vision loss','peripheral vision loss','eye disease','intraocular pressure'],
 ARRAY['ophthalmology','optometry'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 87),
('Diabetes Symptoms','diabetes-symptoms','Diabetes is a chronic condition that affects how the body processes blood sugar (glucose). Common symptoms include increased thirst, frequent urination, unexplained weight loss, fatigue, blurred vision, and slow-healing sores. Type 1 diabetes usually develops in childhood or adolescence, while type 2 is more common in adults and is often related to lifestyle. Early diagnosis and management are important.',
 ARRAY['diabetes','diabetes symptoms','high blood sugar','frequent urination','excessive thirst','weight loss','glucose','blood sugar','prediabetes'],
 ARRAY['endocrinology','primary care'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 88),
('Fibromyalgia','fibromyalgia','Fibromyalgia is a chronic condition characterized by widespread muscle and joint pain, fatigue, sleep problems, and tenderness in specific areas. The exact cause is unknown but may involve amplified pain signals in the brain. While there is no cure, treatment includes medication, exercise, stress management, and cognitive behavioral therapy.',
 ARRAY['fibromyalgia','widespread pain','fibro','muscle pain','tender points','chronic pain','fatigue and pain','fibromyalgia tender points'],
 ARRAY['rheumatology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 89),
('Lyme Disease','lyme-disease','Lyme disease is a bacterial infection transmitted through the bite of an infected blacklegged tick. Early symptoms include a characteristic bullseye-shaped rash (erythema migrans), fever, headache, fatigue, and muscle and joint aches. If untreated, it can affect joints, the heart, and the nervous system. Early treatment with antibiotics is important.',
 ARRAY['lyme disease','lyme','tick bite','bullseye rash','erythema migrans','tick disease','lyme symptoms','deer tick'],
 ARRAY['primary care','infectious disease'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 90),
('Pneumonia','pneumonia','Pneumonia is an infection that inflames the air sacs in one or both lungs, which may fill with fluid. Symptoms include cough (with phlegm), fever, chills, difficulty breathing, chest pain, and fatigue. It can be caused by bacteria, viruses, or fungi. Treatment depends on the cause and may include antibiotics, rest, and fluids.',
 ARRAY['pneumonia','lung infection','chest infection','fluid in lungs','cough with phlegm','fever chills','breathing difficulty pneumonia'],
 ARRAY['primary care','pulmonology','infectious disease'],
 'moderate', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 91),
('Strep Throat','strep-throat','Strep throat is a bacterial infection of the throat and tonsils caused by group A Streptococcus bacteria. Symptoms include a severe sore throat, pain when swallowing, fever, red and swollen tonsils (sometimes with white patches), and swollen lymph nodes in the neck. Unlike viral sore throats, strep usually does not cause a cough or runny nose. It is treated with antibiotics.',
 ARRAY['strep throat','strep','sore throat bacterial','group a strep','throat infection','tonsillitis strep','strep symptoms'],
 ARRAY['primary care','ent'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 92),
('Influenza','influenza','Influenza (flu) is a viral infection of the respiratory system. Symptoms come on suddenly and include fever, chills, muscle aches, cough, congestion, sore throat, and fatigue. Most people recover within a week or two, but the flu can be serious for young children, older adults, pregnant women, and people with chronic conditions. Antiviral medications may help if started early.',
 ARRAY['flu','influenza','flu symptoms','fever','chills','body aches','cough','seasonal flu','flu season'],
 ARRAY['primary care','infectious disease'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 93),
('Conjunctivitis','conjunctivitis','Conjunctivitis (pink eye) is inflammation of the conjunctiva, the thin clear tissue covering the white of the eye and lining the eyelid. It can be caused by viruses, bacteria, allergens, or irritants. Symptoms include redness, itching, tearing, discharge, and crusting. Treatment depends on the cause — viral resolves on its own, bacterial needs antibiotic drops, and allergic responds to antihistamines.',
 ARRAY['conjunctivitis','pink eye','red eye','eye infection','eye inflammation','eye redness','crusty eyes','watery eyes'],
 ARRAY['ophthalmology','optometry','primary care'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 94),
('Heat Exhaustion','heat-exhaustion','Heat exhaustion is a heat-related illness that occurs after exposure to high temperatures and inadequate fluid replacement. Symptoms include heavy sweating, weakness, dizziness, nausea, headache, muscle cramps, and a rapid heartbeat. If not treated, it can progress to heat stroke. Move to a cool place, drink fluids, and apply cool cloths.',
 ARRAY['heat exhaustion','heat illness','overheating','heat stress','too hot','dehydration heat','heat cramps','hot weather illness'],
 ARRAY['primary care','urgent care'],
 'moderate', ARRAY['urgent-care','primary-care'], ARRAY['primary-care'], false, 95),
('Frostbite','frostbite','Frostbite is an injury caused by freezing of the skin and underlying tissues, usually affecting fingers, toes, nose, ears, cheeks, and chin. Symptoms include cold skin, numbness, tingling, and changes in skin color (red, white, or grayish-yellow). Severe frostbite can cause permanent tissue damage. Gradual warming and medical care are needed for all but the mildest cases.',
 ARRAY['frostbite','frozen skin','cold injury','frostnip','numb fingers cold','frozen fingers','cold exposure','frostbite symptoms'],
 ARRAY['primary care','urgent care'],
 'moderate', ARRAY['urgent-care','primary-care'], ARRAY['primary-care'], false, 96),
('Carbon Monoxide Poisoning','carbon-monoxide-poisoning','Carbon monoxide poisoning occurs when carbon monoxide — a colorless, odorless gas — builds up in the bloodstream, preventing oxygen from reaching tissues. Symptoms include headache, dizziness, weakness, nausea, confusion, and loss of consciousness. If you are concerned, you should consider emergency services. Install carbon monoxide detectors to prevent exposure.',
 ARRAY['carbon monoxide','co poisoning','carbon monoxide poisoning','co detector','gas poisoning','headache nausea confusion','silent killer','carbon monoxide symptoms'],
 ARRAY['emergency medicine','primary care'],
 'high', ARRAY['urgent-care'], ARRAY['hospital'], false, 97),
('Food Poisoning','food-poisoning','Food poisoning is illness caused by eating contaminated food. Symptoms typically include nausea, vomiting, diarrhea, abdominal cramps, and sometimes fever. Most cases resolve within a few days with rest and hydration. Seek care if symptoms are severe, include bloody stools, high fever, or signs of dehydration, or last more than three days.',
 ARRAY['food poisoning','foodborne illness','bad food','stomach flu','foodborne','contaminated food','nausea vomiting diarrhea','stomach bug'],
 ARRAY['primary care','gastroenterology'],
 'low', ARRAY['primary-care','urgent-care'], ARRAY['primary-care'], false, 98),
('Menopause Symptoms','menopause-symptoms','Menopause is the natural end of menstruation, typically occurring between ages 45 and 55. Symptoms include hot flashes, night sweats, sleep problems, mood changes, vaginal dryness, and changes in libido. The transition (perimenopause) can last several years. Treatment options include hormone therapy, lifestyle changes, and medications to manage specific symptoms.',
 ARRAY['menopause','hot flashes','night sweats','perimenopause','menopause symptoms','mood changes','vaginal dryness','change of life'],
 ARRAY['obstetrics and gynecology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 99),
('Pregnancy Symptoms','pregnancy-symptoms','Early pregnancy symptoms include a missed period, nausea (morning sickness), breast tenderness, fatigue, increased urination, and food cravings or aversions. A home pregnancy test can confirm pregnancy. Early prenatal care is important for a healthy pregnancy. If you suspect you are pregnant, schedule a visit with a healthcare provider.',
 ARRAY['pregnancy symptoms','pregnant','morning sickness','missed period','pregnancy test','early pregnancy','prenatal','pregnancy signs'],
 ARRAY['obstetrics and gynecology','primary care'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 100),
('ADHD','adhd','Attention-deficit/hyperactivity disorder (ADHD) is a neurodevelopmental condition characterized by difficulty sustaining attention, hyperactivity, and impulsivity. It is often diagnosed in childhood but can persist into adulthood. Symptoms include trouble focusing, disorganization, forgetfulness, restlessness, and difficulty completing tasks. Treatment includes medication, behavioral therapy, and lifestyle strategies.',
 ARRAY['adhd','attention deficit','add','hyperactivity','cant focus','impulsive','attention deficit hyperactivity disorder','trouble concentrating'],
 ARRAY['psychiatry','primary care','pediatrics'],
 'low', ARRAY['primary-care','telehealth'], ARRAY['mental-health','primary-care'], false, 101),
('Bipolar Disorder','bipolar-disorder','Bipolar disorder is a mental health condition characterized by extreme mood swings that include emotional highs (mania or hypomania) and lows (depression). During manic episodes, a person may feel euphoric, energetic, or unusually irritable. Depressive episodes involve sadness, low energy, and loss of interest. Treatment includes mood-stabilizing medication and therapy.',
 ARRAY['bipolar','bipolar disorder','manic depression','mood swings','mania','hypomania','bipolar 1','bipolar 2'],
 ARRAY['psychiatry','primary care'],
 'moderate', ARRAY['primary-care','telehealth'], ARRAY['mental-health'], false, 102),
('PTSD','ptsd','Post-traumatic stress disorder (PTSD) is a mental health condition triggered by experiencing or witnessing a terrifying event. Symptoms include flashbacks, nightmares, severe anxiety, avoidance of reminders, emotional numbness, and hyperarousal. PTSD can develop after combat, assault, accidents, natural disasters, or other trauma. Treatment includes trauma-focused therapy and medication.',
 ARRAY['ptsd','post traumatic stress','trauma','flashbacks','nightmares','trauma disorder','ptsd symptoms','hyperarousal'],
 ARRAY['psychiatry','psychology','primary care'],
 'moderate', ARRAY['primary-care','telehealth'], ARRAY['mental-health','veterans'], false, 103),
('Obsessive Compulsive Disorder','obsessive-compulsive-disorder','Obsessive-compulsive disorder (OCD) is a mental health condition characterized by unwanted, recurring thoughts (obsessions) and repetitive behaviors (compulsions). Common obsessions include fears of contamination or harm; common compulsions include excessive cleaning, checking, or counting. Treatment includes cognitive behavioral therapy (specifically ERP) and medication.',
 ARRAY['ocd','obsessive compulsive','compulsions','obsessions','intrusive thoughts','ocd symptoms','repetitive behaviors','ocd therapy'],
 ARRAY['psychiatry','psychology','primary care'],
 'moderate', ARRAY['primary-care','telehealth'], ARRAY['mental-health'], false, 104),
('Panic Attacks','panic-attacks','A panic attack is a sudden episode of intense fear or anxiety that triggers physical symptoms even when there is no real danger. Symptoms include a racing heart, shortness of breath, chest pain, dizziness, trembling, sweating, and a feeling of impending doom. Panic attacks can be frightening but are not physically dangerous. Treatment includes therapy, medication, and breathing techniques.',
 ARRAY['panic attack','panic attacks','panic','panic disorder','sudden fear','racing heart','anxiety attack','panic symptoms'],
 ARRAY['psychiatry','psychology','primary care'],
 'moderate', ARRAY['primary-care','telehealth'], ARRAY['mental-health','crisis-line'], false, 105),
('Eating Disorders','eating-disorders','Eating disorders are serious mental health conditions characterized by disturbed eating behaviors and an unhealthy relationship with food, body weight, or shape. Common types include anorexia nervosa, bulimia nervosa, and binge eating disorder. Symptoms vary but may include extreme food restriction, bingeing, purging, and body image distortion. Treatment involves therapy, nutritional counseling, and sometimes medication.',
 ARRAY['eating disorder','anorexia','bulimia','binge eating','eating disorders','food restriction','purging','body image issues'],
 ARRAY['psychiatry','psychology','primary care'],
 'moderate', ARRAY['primary-care','telehealth'], ARRAY['mental-health'], false, 106),
('Substance Use Disorder','substance-use-disorder','Substance use disorder is a condition in which the use of alcohol or drugs causes significant impairment or distress. It is characterized by an inability to stop using despite negative consequences. Symptoms include strong cravings, tolerance, withdrawal symptoms, and continued use despite harm. Treatment includes counseling, medication, support groups, and sometimes inpatient rehabilitation.',
 ARRAY['substance use','addiction','drug addiction','alcohol addiction','substance abuse','dependency','substance use disorder','recovery','sobriety'],
 ARRAY['psychiatry','primary care'],
 'moderate', ARRAY['primary-care','telehealth'], ARRAY['mental-health','substance-use'], false, 107),
('Grief and Loss','grief-and-loss','Grief is a natural response to losing someone or something important. It can cause intense sorrow, emotional pain, and a range of physical and emotional symptoms including sadness, anger, guilt, sleep changes, and difficulty concentrating. While grief is a normal process, prolonged or complicated grief that interferes with daily functioning may benefit from professional support.',
 ARRAY['grief','loss','bereavement','mourning','grieving','death of loved one','grief and loss','complicated grief'],
 ARRAY['psychology','counseling','primary care'],
 'low', ARRAY['primary-care','telehealth'], ARRAY['mental-health'], false, 108),
('Chronic Pain','chronic-pain','Chronic pain is pain that lasts longer than three months and can persist even after the underlying injury or illness has healed. It can affect any part of the body and may result from conditions such as arthritis, nerve damage, fibromyalgia, or past injuries. Chronic pain can affect sleep, mood, and daily activities. Management often requires a combination of medication, physical therapy, and psychological support.',
 ARRAY['chronic pain','persistent pain','ongoing pain','pain management','long term pain','constant pain','pain that wont stop','chronic pain syndrome'],
 ARRAY['pain management','primary care','physical therapy'],
 'low', ARRAY['primary-care'], ARRAY['primary-care'], false, 109),
('Memory Loss','memory-loss','Memory loss (amnesia) can range from occasional forgetfulness to more significant impairment. Causes include normal aging, stress, depression, medication side effects, thyroid problems, vitamin deficiencies, and neurological conditions such as dementia or Alzheimer''s disease. Sudden or worsening memory loss should be evaluated by a healthcare provider to determine the cause.',
 ARRAY['memory loss','forgetfulness','amnesia','dementia','alzheimers','cognitive decline','confusion','memory problems'],
 ARRAY['neurology','primary care','psychiatry'],
 'moderate', ARRAY['primary-care'], ARRAY['primary-care'], false, 110),
('Seizure','seizure','A seizure is a sudden, uncontrolled electrical disturbance in the brain that can cause changes in behavior, movements, feelings, and levels of consciousness. Symptoms range from brief staring spells to convulsions with loss of consciousness. Seizures can be caused by epilepsy, head injury, infections, or other conditions. If you are concerned, you should consider emergency services.',
 ARRAY['seizure','seizures','epilepsy','convulsion','fit','seizure disorder','epileptic seizure','uncontrolled movements'],
 ARRAY['neurology','emergency medicine'],
 'high', ARRAY['urgent-care'], ARRAY['hospital'], false, 111),
('Appendicitis','appendicitis','Appendicitis is inflammation of the appendix, a small pouch attached to the large intestine. Symptoms include sudden pain that begins around the navel and often shifts to the lower right abdomen, nausea, vomiting, loss of appetite, and low-grade fever. If you are concerned, you should consider emergency services, as a ruptured appendix is a serious condition.',
 ARRAY['appendicitis','appendix pain','right side abdominal pain','appendix','stomach pain right side','appendicitis symptoms','lower right abdomen pain'],
 ARRAY['general surgery','emergency medicine','primary care'],
 'high', ARRAY['urgent-care'], ARRAY['hospital'], false, 112),
('Anaphylaxis','anaphylaxis','Anaphylaxis is a severe, potentially life-threatening allergic reaction that can occur within seconds or minutes of exposure to an allergen. Symptoms include a rapid, weak pulse, skin rash, nausea, vomiting, difficulty breathing, swelling of the throat and tongue, and a drop in blood pressure. If you are concerned, you should consider emergency services.',
 ARRAY['anaphylaxis','severe allergic reaction','allergic shock','throat closing','anaphylactic','allergy emergency','epipen','anaphylactic reaction'],
 ARRAY['allergy and immunology','emergency medicine'],
 'high', ARRAY['urgent-care'], ARRAY['hospital'], false, 113);

-- Verify count
SELECT 'Total symptoms: ' || count(*)::text FROM symptoms;
