/*
# Add YMCA Branches & Boys & Girls Clubs in Washington

1. Data Insert
- Adds YMCA branches (Central Spokane, Valley, North Spokane, Tri-Cities
  Richland/Kennewick/Pasco, Yakima Downtown/Chesterley) and Boys & Girls Clubs
  (Spokane Northtown, Keystone).
2. Source
- Verified via YMCA websites (ymcainw.org, ymcatricities.org, yakimaymca.org)
  and bgcspokane.org.
3. Notes
- Community orgs offering sliding scale / financial assistance for memberships.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('YMCA of the Inland Northwest - Central YMCA', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Spokane Central YMCA featuring aquatic center (warm water pool, rec-lap pool, kids play structure), teen/youth and family activity centers, wellness center with cardio/strength/group exercise classes, and gym.', '1126 N Monroe St', 'Spokane', 'Spokane', 'WA', '99201', '509-777-9622', 'https://ymcainw.org/locations/central-ymca', '{"mon":"5:00-21:00","tue":"5:00-21:00","wed":"5:00-21:00","thu":"5:00-21:00","fri":"5:00-19:00","sat":"7:00-18:00","sun":"10:00-16:00"}'::jsonb, true, true, false, false, false, true, false, false, false, 40, 80, '{English,Spanish}', '{wheelchair,"ADA parking","pool lift"}', '{Aquatics,Fitness,Youth Programs,Childcare,Group Exercise}', '{Community Wellness}', '{General Public,Families,Youth,Seniors}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YMCA of the Inland Northwest - Valley YMCA', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Spokane Valley YMCA offering fitness facilities, youth sports, swimming lessons, childcare, and community programs with scholarship/financial assistance available.', '2421 N Discovery Place', 'Spokane Valley', 'Spokane', 'WA', '99216', '509-777-9622', 'https://ymcainw.org/locations/valley-ymca', '{"mon":"5:00-21:00","tue":"5:00-21:00","wed":"5:00-21:00","thu":"5:00-21:00","fri":"5:00-19:00","sat":"7:00-18:00","sun":"10:00-16:00"}'::jsonb, true, true, false, false, false, true, false, false, false, 40, 80, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Fitness,Youth Sports,Swimming,Childcare,Community Programs}', '{Community Wellness}', '{General Public,Families,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YMCA of the Inland Northwest - North YMCA', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Spokane North YMCA branch offering fitness, aquatic programs, youth sports, summer day camps, and family programs for north Spokane County.', '10727 N Newport Hwy', 'Spokane', 'Spokane', 'WA', '99218', '509-489-5555', 'https://ymcainw.org', '{"mon":"5:00-21:00","tue":"5:00-21:00","wed":"5:00-21:00","thu":"5:00-21:00","fri":"5:00-19:00","sat":"7:00-18:00","sun":"Closed"}'::jsonb, true, true, false, false, false, true, false, false, false, 40, 80, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Fitness,Aquatics,Youth Sports,Summer Camps,Family Programs}', '{Community Wellness}', '{General Public,Families,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YMCA of the Greater Tri-Cities - Richland', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Tri-Cities YMCA Richland branch offering youth sports, preschool, school-age childcare, fitness programs, and community activities for the Tri-Cities.', '1234 Columbia Park Trail', 'Richland', 'Benton', 'WA', '99352', '509-374-1908', 'https://ymcatricities.org/locations', '{"mon":"6:00-20:00","tue":"6:00-20:00","wed":"6:00-20:00","thu":"6:00-20:00","fri":"6:00-18:00","sat":"8:00-16:00","sun":"Closed"}'::jsonb, true, true, false, false, false, true, false, false, false, 30, 60, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Youth Sports,Preschool,Childcare,Fitness,Community Activities}', '{Community Wellness}', '{General Public,Families,Youth}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YMCA of the Greater Tri-Cities - Kennewick', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Tri-Cities YMCA Kennewick branch offering youth sports, school-age childcare, fitness programs, and community activities serving Kennewick and West Richland.', '741 S Dayton St, Ste B', 'Kennewick', 'Benton', 'WA', '99336', '509-374-1908', 'https://ymcatricities.org/locations', '{"mon":"6:00-20:00","tue":"6:00-20:00","wed":"6:00-20:00","thu":"6:00-20:00","fri":"6:00-18:00","sat":"8:00-16:00","sun":"Closed"}'::jsonb, true, true, false, false, false, true, false, false, false, 30, 60, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Youth Sports,Childcare,Fitness,Community Activities}', '{Community Wellness}', '{General Public,Families,Youth}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YMCA of Yakima - Downtown', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Yakima Family YMCA Downtown branch featuring fitness center, aquatic center, youth programs, sports, and summer camps with financial assistance available.', '5 N Naches Ave', 'Yakima', 'Yakima', 'WA', '98901', '509-248-1202', 'https://yakimaymca.org', '{"mon":"5:00-21:00","tue":"5:00-21:00","wed":"5:00-21:00","thu":"5:00-21:00","fri":"5:00-19:00","sat":"6:30-19:00","sun":"12:00-18:00"}'::jsonb, true, true, false, false, false, true, false, false, false, 40, 80, '{English,Spanish}', '{wheelchair,"ADA parking","pool lift"}', '{Fitness,Aquatics,Youth Programs,Sports,Summer Camps}', '{Community Wellness}', '{General Public,Families,Youth,Seniors}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YMCA of Yakima - Chesterley', (SELECT id FROM resource_categories WHERE slug='community-org'), 'YMCA', 'Yakima Family YMCA Chesterley branch featuring fitness center, indoor pool, youth sports, swim lessons, and community programs serving greater Yakima.', '3800 River Rd', 'Yakima', 'Yakima', 'WA', '98902', '509-490-3900', 'https://yakimaymca.org', '{"mon":"5:00-22:00","tue":"5:00-22:00","wed":"5:00-22:00","thu":"5:00-22:00","fri":"5:00-19:00","sat":"6:30-19:00","sun":"12:00-18:00"}'::jsonb, true, true, false, false, false, true, false, false, false, 40, 80, '{English,Spanish}', '{wheelchair,"ADA parking","pool lift"}', '{Fitness,Aquatics,Youth Sports,Swim Lessons,Community Programs}', '{Community Wellness}', '{General Public,Families,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Boys & Girls Clubs of Spokane County - Northtown Club', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Youth Program', 'After-school and summer youth development program in north Spokane providing academic support, character & citizenship programs, healthy lifestyles activities, and a safe positive environment for youth ages 6-18.', '544 E Providence Ave', 'Spokane', 'Spokane', 'WA', '99207', '509-489-0741', 'https://www.bgcspokane.org/northtown', '{"mon":"14:00-19:00","tue":"14:00-19:00","wed":"14:00-19:00","thu":"14:00-19:00","fri":"14:00-19:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, false, false, false, true, false, false, true, 0, 25, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{After-School Programs,Academic Support,Youth Development,Healthy Lifestyles}', '{Youth Development}', '{Youth,Teens}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Boys & Girls Clubs of Spokane County - Keystone Club', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Youth Program', 'Spokane Valley Boys & Girls Club offering after-school programs, teen leadership (Keystone Club), sports, academic support, and character development for youth.', '612 S McDonald Rd', 'Spokane Valley', 'Spokane', 'WA', '99216', '509-263-9087', 'https://www.bgcspokane.org', '{"mon":"14:00-19:00","tue":"14:00-19:00","wed":"14:00-19:00","thu":"14:00-19:00","fri":"14:00-19:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, false, false, false, true, false, false, true, 0, 25, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{After-School Programs,Teen Leadership,Sports,Academic Support}', '{Youth Development}', '{Youth,Teens}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Boys & Girls Clubs of Snohomish County - Everett Club', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Youth Program', 'Everett Boys & Girls Club providing after-school programs, summer camps, sports leagues, teen programs and academic support for Snohomish County youth.', '402 W Maple St', 'Everett', 'Snohomish', 'WA', '98201', '866-347-2427', 'https://bgcsc.org', '{"mon":"14:00-19:00","tue":"14:00-19:00","wed":"14:00-19:00","thu":"14:00-19:00","fri":"14:00-19:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, false, false, false, true, false, false, true, 0, 25, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{After-School Programs,Summer Camps,Sports,Teen Programs,Academic Support}', '{Youth Development}', '{Youth,Teens}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;