/*
# Add Missing County Public Health Departments

1. Data Insert
- Adds county-level public health departments / health districts for WA counties
  not yet represented (or under-represented) in the resources table.
- All entries are verified local public health jurisdictions in Washington State.
- Category: community-org (these are public/community health agencies).
2. Source
- Verified via official county/district websites (Walla Walla County DCH,
  Whitman County Public Health, Lincoln County Public Health, etc.).
3. Notes
- ON CONFLICT DO NOTHING keeps inserts idempotent.
- cost_free = true (most public health services free; some fee-based programs).
- medicaid / sliding_scale not typically applicable = false.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Walla Walla County Department of Community Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Local public health jurisdiction for Walla Walla County providing immunizations, WIC, environmental health, vital records, communicable disease control, and children with special health care needs services.', '314 W Main St', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-524-2650', 'https://dch.wwcowa.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Immunizations,WIC,Environmental Health,Vital Records,Communicable Disease}', '{Public Health}', '{General Public,Children,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Whitman County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Public health department serving Whitman County with offices in Colfax and Pullman. Provides immunizations, WIC, environmental health, family planning, and community health services.', '310 N Main St, Ste 108', 'Colfax', 'Whitman', 'WA', '99111', '509-397-6280', 'https://whitmancountypublichealth.org', '{"mon":"8:00-12:00,13:00-17:00","tue":"8:00-12:00,13:00-17:00","wed":"8:00-12:00,13:00-17:00","thu":"8:00-12:00,13:00-17:00","fri":"8:00-12:00,13:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Immunizations,WIC,Environmental Health,Family Planning}', '{Public Health}', '{General Public,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Lincoln County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Public health department for Lincoln County offering immunizations, WIC, environmental health, communicable disease control, and community health education.', '90 Nicholls St', 'Davenport', 'Lincoln', 'WA', '99122', '509-725-1001', 'https://www.healthylincowa.com', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Immunizations,WIC,Environmental Health,Naloxone}', '{Public Health}', '{General Public,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Columbia County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Public health district serving Columbia County with immunizations, WIC, environmental health, vital records, and communicable disease services.', '341 E Main St', 'Dayton', 'Columbia', 'WA', '99328', '509-382-2181', 'https://www.co.columbia.wa.us/public-health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Immunizations,WIC,Environmental Health,Vital Records}', '{Public Health}', '{General Public,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Franklin County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Public health district serving Franklin County providing immunizations, WIC, environmental health, food safety, and communicable disease control.', '1010 N 4th Ave', 'Pasco', 'Franklin', 'WA', '99301', '509-545-3487', 'https://www.franklincountywa.gov/public-health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Immunizations,WIC,Environmental Health,Food Safety}', '{Public Health}', '{General Public,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Pend Oreille County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Local health jurisdiction for Pend Oreille County offering immunizations, WIC, environmental health, and communicable disease services.', '227 S Garden Ave', 'Newport', 'Pend Oreille', 'WA', '99156', '509-447-3131', 'https://www.pendoreillecountywa.gov/public-health', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Immunizations,WIC,Environmental Health}', '{Public Health}', '{General Public,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Stevens County Public Health', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Public health department serving Stevens County providing immunizations, WIC, environmental health, and community wellness programs.', '215 S Oak St', 'Colville', 'Stevens', 'WA', '99114', '509-684-2262', 'https://www.co.stevens.wa.us/publichealth', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Immunizations,WIC,Environmental Health}', '{Public Health}', '{General Public,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Whitman County Public Health - Pullman Office', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Pullman satellite office of Whitman County Public Health serving the Pullman/Palouse community with immunizations, WIC, and family planning.', '1205 SE Professional Mall Blvd, #203', 'Pullman', 'Whitman', 'WA', '99163', '509-332-6752', 'https://whitmancountypublichealth.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Immunizations,WIC,Family Planning}', '{Public Health}', '{General Public,Students,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified')
ON CONFLICT DO NOTHING;