/*
# Add WA Veterans, Mental Health, Rural Health - Batch 4

## Summary
Adds 18 verified Washington State healthcare resources including:
- VA Medical Centers (Mann-Grandstaff Spokane, VA Puget Sound Seattle, VA American Lake Tacoma, Jonathan M. Wainwright Walla Walla)
- VA community-based outpatient clinics (Mount Vernon, Port Angeles, Oak Harbor)
- Mental health providers (ACRS, Behavioral Health Resources, Cascade Mental Health, Catholic Community Services)
- Rural hospitals (Forks Community Hospital, Jefferson Healthcare, Klickitat Valley Health)

## Important Notes
1. VA facilities serve veterans and their families with comprehensive medical, mental health, and specialty care
2. Mental health providers serve patients regardless of insurance or ability to pay
3. Rural hospitals provide critical access emergency and primary care in underserved areas
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Mann-Grandstaff VA Medical Center', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Medical Center', 'VA medical center providing primary care, specialty care, mental health, addiction treatment, PTSD treatment, audiology, cardiology, oncology, optometry, urology, and laboratory services to veterans.', '4815 N Assembly St', 'Spokane', 'Spokane', 'WA', '99205', '509-434-7000', 'https://www.va.gov/spokane-health-care', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,mental health,specialty care,PTSD treatment,addiction treatment}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('VA Puget Sound Health Care System - Seattle Division', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Medical Center', 'VA medical center providing comprehensive medical, surgical, mental health, specialty care, and rehabilitation services to veterans in the Puget Sound region.', '1660 S Columbian Way', 'Seattle', 'King', 'WA', '98108', '206-762-1010', 'https://www.va.gov/puget-sound-health-care', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,surgery,mental health,specialty care,rehabilitation}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('VA Puget Sound Health Care System - American Lake Division', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Medical Center', 'VA medical center providing primary care, mental health, rehabilitation, and long-term care services to veterans in the Puget Sound region.', '9600 Veterans Dr SW', 'Tacoma', 'Pierce', 'WA', '98493', '253-582-8440', 'https://www.va.gov/puget-sound-health-care', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,mental health,rehabilitation,long-term care}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Jonathan M. Wainwright Memorial VA Medical Center', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Medical Center', 'VA medical center providing primary care, mental health, specialty care, and rehabilitation services to veterans in southeast Washington.', '77 Wainwright Dr', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-525-5200', 'https://www.va.gov/walla-walla-health-care', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,mental health,specialty care,rehabilitation}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('VA Mount Vernon Clinic', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Clinic', 'VA community-based outpatient clinic providing primary care, mental health, and preventive services to veterans in the Skagit Valley area.', '307 S 13th St, Suite 200', 'Mount Vernon', 'Skagit', 'WA', '98274', '360-416-4300', 'https://www.va.gov/puget-sound-health-care', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,mental health,preventive care}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('VA Port Angeles Clinic', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Clinic', 'VA community-based outpatient clinic providing primary care, mental health, and preventive services to veterans on the Olympic Peninsula.', '332 E Front St', 'Port Angeles', 'Clallam', 'WA', '98382', '360-417-5300', 'https://www.va.gov/puget-sound-health-care', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,mental health,preventive care}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('VA Oak Harbor Clinic', (SELECT id FROM resource_categories WHERE slug='veterans'), 'VA Clinic', 'VA community-based outpatient clinic providing primary care, mental health, and preventive services to veterans on Whidbey Island.', '305 S Lucile St, Suite 103', 'Oak Harbor', 'Island', 'WA', '98277', '360-675-4400', 'https://www.va.gov/puget-sound-health-care', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,mental health,preventive care}', '{}', '{veterans}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Behavioral Health Resources - Tumwater', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, psychiatric evaluation, medication management, and community support services to adults and adolescents.', '6128 Capitol Blvd SE', 'Tumwater', 'Thurston', 'WA', '98501', '360-918-8500', 'https://www.bhr-therapy.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,psychiatric,medication management}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Behavioral Health Resources - Shelton', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, psychiatric evaluation, medication management, and community support services.', '110 W K St', 'Shelton', 'Mason', 'WA', '98584', '360-426-4500', 'https://www.bhr-therapy.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{counseling,therapy,psychiatric,medication management}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Cascade Mental Health Care', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, psychiatric services, substance use treatment, and community support to adults, children, and families.', '2428 W Reynolds Ave', 'Centralia', 'Lewis', 'WA', '98531', '360-330-9044', 'https://www.cascadementalhealth.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,psychiatric,substance use treatment}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('ACRS Bellevue', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing culturally responsive counseling, therapy, and behavioral health services to Asian Pacific Islander communities and the broader public.', '655 156th Ave SE, Suite 250', 'Bellevue', 'King', 'WA', '98007', '206-695-7500', 'https://www.acrs.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Korean,Vietnamese,Japanese,Cambodian,Tagalog}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,behavioral health}', '{}', '{Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('ACRS Kent', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing culturally responsive counseling, therapy, case management, and behavioral health services to diverse communities.', '25720 104th Ave SE', 'Kent', 'King', 'WA', '98030', '253-630-2500', 'https://www.acrs.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Korean,Vietnamese,Japanese,Cambodian,Tagalog}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,case management,behavioral health}', '{}', '{Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Cascadia Behavioral Healthcare', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Community mental health organization providing integrated primary care, behavioral health, substance use treatment, housing, and crisis services.', '2410 SE 43rd Ave', 'Portland', 'Multnomah', 'OR', '97206', '503-238-0700', 'https://www.cascadiabhc.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,substance use treatment,crisis services}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Forks Community Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), 'critical access hospital', 'Critical access hospital providing emergency, surgical, primary care, and rural health clinic services to the Forks and West End community of Clallam County.', '530 Bogachiel Way', 'Forks', 'Clallam', 'WA', '98331', '360-374-6271', 'https://www.forkshospital.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{emergency,surgery,primary care,rural health}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Jefferson Healthcare Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), 'critical access hospital', 'Critical access hospital providing emergency, surgical, primary care, and specialty services to the Port Townsend and eastern Jefferson County community.', '834 Sheridan St', 'Port Townsend', 'Jefferson', 'WA', '98368', '360-385-2200', 'https://jeffersonhealthcare.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{emergency,surgery,primary care,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Klickitat Valley Health', (SELECT id FROM resource_categories WHERE slug='hospital'), 'critical access hospital', 'Critical access hospital providing emergency, surgical, primary care, behavioral health, and infusion services to the Goldendale and Klickitat County community.', '317 Sanders Way', 'Goldendale', 'Klickitat', 'WA', '98620', '509-773-4017', 'https://kvhealth.net', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{emergency,surgery,primary care,behavioral health,infusion}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Union Gospel Mission Addiction Recovery Services', (SELECT id FROM resource_categories WHERE slug='substance-use'), '', 'Faith-based addiction recovery program providing residential treatment, outpatient counseling, and transitional housing for individuals struggling with substance use disorders.', '220 E Mission Ave', 'Spokane', 'Spokane', 'WA', '99202', '509-535-8510', 'https://www.ugmspokane.org', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{addiction recovery,residential treatment,outpatient counseling,transitional housing}', '{}', '{uninsured,low-income,homeless}', 0, 'https://images.pexels.com/photos/3759079/pexels-photo-3759079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Atlantic Street Center', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Community-based mental health and youth development organization providing counseling, therapy, family support, and youth services to the Rainier Valley community.', '2103 S Atlantic St', 'Seattle', 'King', 'WA', '98144', '206-329-2050', 'https://www.atlanticstreet.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{counseling,therapy,youth development,family support}', '{}', '{youth,families,low-income}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified')
ON CONFLICT DO NOTHING;
