/*
# Add Mental Health Providers

1. Purpose
   - Add mental health providers across Washington state
   - Focus on community mental health centers and outpatient services

2. Coverage
   - All major Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'mental-health'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Kings Mental Health Services - Seattle', 'Outpatient Treatment', 'Community mental health center offering individual therapy, group therapy, and psychiatric services.', '1100 Olive Way', 'Seattle', 'King', '98101', '(206) 443-2600', 'https://kingsmentalhealth.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry', 'Case Management'], ARRAY['mental health', 'therapy', 'psychiatry'], 'mental health therapy psychiatry Seattle Kings', 47.6136, -122.3240),
  ('Valley Cities Behavioral Health - Auburn', 'Outpatient Treatment', 'Community mental health center serving South King County. Sliding scale fees.', '100 12th St NE', 'Auburn', 'King', '98002', '(253) 833-7444', 'https://valleycities.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy', 'sliding scale'], 'mental health Valley Cities Auburn therapy sliding scale', 47.3076, -122.2278),
  ('Valley Cities Behavioral Health - Renton', 'Outpatient Treatment', 'Mental health services including therapy and medication management.', '420 Lind Ave SW', 'Renton', 'King', '98057', '(425) 271-5500', 'https://valleycities.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Vietnamese'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Valley Cities Renton therapy', 47.4793, -122.2119),
  ('Navos Mental Health - Burien', 'Outpatient Treatment', 'Community mental health center with comprehensive services for adults and children.', '2600 SW 152nd St', 'Burien', 'King', '98166', '(206) 248-3262', 'https://navos.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry', 'Case Management'], ARRAY['mental health', 'therapy', 'Navos'], 'mental health Navos Burien therapy psychiatry', 47.4668, -122.3413),
  ('Sound Mental Health - Bellevue', 'Outpatient Treatment', 'Mental health services including therapy and medication management.', '1600 124th Ave NE', 'Bellevue', 'King', '98005', '(425) 453-5100', 'https://soundmentalhealth.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Mandarin'], ARRAY['Individual Therapy', 'Psychiatry', 'Telehealth'], ARRAY['mental health', 'therapy', 'Sound'], 'mental health Sound Bellevue therapy psychiatry', 47.6245, -122.1590),
  ('Comprehensive Healthcare - Yakima', 'Outpatient Treatment', 'Community mental health center serving Yakima Valley with bilingual services.', '402 S 4th Ave', 'Yakima', 'Yakima', '98902', '(509) 575-4200', 'https://comprehensivehealthcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry', 'Case Management'], ARRAY['mental health', 'therapy', 'Spanish'], 'mental health Comprehensive Healthcare Yakima therapy', 46.6002, -120.5077),
  ('Comprehensive Healthcare - Sunnyside', 'Outpatient Treatment', 'Mental health services for Lower Yakima Valley.', '703 Wine Country Rd', 'Sunnyside', 'Yakima', '98944', '(509) 837-8700', 'https://comprehensivehealthcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Comprehensive Healthcare Sunnyside therapy', 46.3243, -119.9911),
  ('Spokane Mental Health Center', 'Outpatient Treatment', 'Community mental health center serving Spokane area.', '107 S Washington St', 'Spokane', 'Spokane', '99204', '(509) 838-3000', 'https://smhca.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Russian'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Spokane therapy psychiatry', 47.6556, -117.4277),
  ('Excelsior Wellness Center - Spokane', 'Outpatient Treatment', 'Mental health and substance use treatment for youth and adults.', '918 N Napa St', 'Spokane', 'Spokane', '99202', '(509) 624-2382', 'https://excelsiorwellness.org', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Russian'], ARRAY['Individual Therapy', 'Group Therapy', 'Substance Use Treatment'], ARRAY['mental health', 'therapy', 'substance use'], 'mental health Excelsior Wellness Spokane therapy', 47.6592, -117.4025),
  ('Pioneer Human Services - Tacoma', 'Outpatient Treatment', 'Mental health and substance use treatment with sliding scale fees.', '3104 S 38th St', 'Tacoma', 'Pierce', '98409', '(253) 471-5800', 'https://pioneerhumanservices.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Substance Use Treatment'], ARRAY['mental health', 'therapy', 'substance use', 'sliding scale'], 'mental health Pioneer Human Services Tacoma therapy', 47.2354, -122.4676),
  ('Optum Pierce County Mental Health - Tacoma', 'Outpatient Treatment', 'Community mental health services for Pierce County.', '3610 S Parkland Dr', 'Tacoma', 'Pierce', '98405', '(253) 502-2330', 'https://optum.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry', 'Case Management'], ARRAY['mental health', 'therapy', 'Optum'], 'mental health Optum Pierce Tacoma therapy', 47.2550, -122.4567),
  ('Cascade Mental Health - Chehalis', 'Outpatient Treatment', 'Community mental health center serving Lewis County.', '425 NW Cheylan Ave', 'Chehalis', 'Lewis', '98532', '(360) 748-6696', 'https://cascadementalhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Cascade Chehalis Lewis therapy', 46.6623, -122.9641),
  ('Catholic Community Services Mental Health - Olympia', 'Outpatient Treatment', 'Mental health services for Thurston County residents.', '4606 Capitol Blvd', 'Olympia', 'Thurston', '98501', '(360) 357-4509', 'https://ccsww.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Case Management'], ARRAY['mental health', 'therapy', 'Catholic'], 'mental health Catholic Community Services Olympia therapy', 47.0333, -122.8940),
  ('Cedar River Clinic - Covington', 'Outpatient Treatment', 'Mental health services including therapy and medication management.', '27121 168th Ave SE', 'Covington', 'King', '98042', '(425) 413-8800', 'https://cedarriverclinic.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Cedar River Clinic Covington therapy', 47.3563, -122.1162),
  ('Benton County Counseling Services - Richland', 'Outpatient Treatment', 'County mental health services with sliding scale fees.', '2100 W Van Giesen St', 'Richland', 'Benton', '99354', '(509) 946-2400', 'https://bentoncountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy', 'sliding scale'], 'mental health Benton County Counseling Richland therapy', 46.2838, -119.3023),
  ('ARC Counseling Services - Kennewick', 'Outpatient Treatment', 'Mental health and substance use treatment services.', '3500 W Clearwater Ave', 'Kennewick', 'Benton', '99336', '(509) 735-9010', 'https://arccounseling.com', '{"monday": "8am-6pm", "tuesday": "8am-6pm", "wednesday": "8am-6pm", "thursday": "8am-6pm", "friday": "8am-6pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Substance Use Treatment'], ARRAY['mental health', 'therapy', 'substance use'], 'mental health ARC Counseling Kennewick therapy', 46.2113, -119.1772),
  ('Whatcom Community Mental Health - Bellingham', 'Outpatient Treatment', 'Community mental health center serving Whatcom County.', '5600 Airport Dr', 'Bellingham', 'Whatcom', '98226', '(360) 715-2800', 'https://nccc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry', 'Case Management'], ARRAY['mental health', 'therapy'], 'mental health Whatcom Community Bellingham therapy', 48.7890, -122.4900),
  ('Skagit County Mental Health - Mount Vernon', 'Outpatient Treatment', 'County mental health services with sliding scale.', '2005 E College Way', 'Mount Vernon', 'Skagit', '98273', '(360) 416-5200', 'https://skagitcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy', 'sliding scale'], 'mental health Skagit County Mount Vernon therapy', 48.4216, -122.3334),
  ('Clallam County Behavioral Health - Port Angeles', 'Outpatient Treatment', 'Mental health services for Olympic Peninsula.', '118 E 8th St', 'Port Angeles', 'Clallam', '98362', '(360) 417-2400', 'https://clallamcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Clallam County Port Angeles therapy', 48.1244, -123.4330),
  ('Jefferson County Mental Health - Port Townsend', 'Outpatient Treatment', 'Community mental health services.', '1400 San Juan Ave', 'Port Townsend', 'Jefferson', '98368', '(360) 385-0321', 'https://jeffersoncountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Jefferson County Port Townsend therapy', 48.1144, -122.7744),
  ('Grays Harbor County Mental Health - Aberdeen', 'Outpatient Treatment', 'Mental health services for Grays Harbor residents.', '1900 Sumner Ave', 'Aberdeen', 'Grays Harbor', '98520', '(360) 533-8010', 'https://ghc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Grays Harbor Aberdeen therapy', 46.9743, -123.8147),
  ('Cowlitz County Mental Health - Longview', 'Outpatient Treatment', 'Community mental health center with sliding scale.', '600 Broadway St', 'Longview', 'Cowlitz', '98632', '(360) 425-0415', 'https://cowlitzcountywa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy', 'sliding scale'], 'mental health Cowlitz County Longview therapy', 46.1410, -122.9344),
  ('Clark County Mental Health Services - Vancouver', 'Outpatient Treatment', 'Comprehensive mental health services for Clark County.', '700 NE 87th Ave', 'Vancouver', 'Clark', '98664', '(360) 397-2130', 'https://clark.wa.gov', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Individual Therapy', 'Group Therapy', 'Psychiatry'], ARRAY['mental health', 'therapy'], 'mental health Clark County Vancouver therapy', 45.6853, -122.5868),
  ('Recovery Center of Grays Harbor - Aberdeen', 'Outpatient Treatment', 'Mental health and substance use treatment with sliding scale.', '1001 W Heron St', 'Aberdeen', 'Grays Harbor', '98520', '(360) 532-8950', 'https://recoverygh.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Individual Therapy', 'Substance Use Treatment'], ARRAY['mental health', 'therapy', 'substance use', 'sliding scale'], 'mental health Recovery Center Grays Harbor Aberdeen', 46.9738, -123.8233),
  ('PeaceHealth Behavioral Health - Bellingham', 'Outpatient Treatment', 'Hospital-based mental health services.', '2900 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 734-5400', 'https://peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Psychiatry', 'Individual Therapy'], ARRAY['mental health', 'therapy', 'PeaceHealth'], 'mental health PeaceHealth Behavioral Health Bellingham', 48.7690, -122.4850)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
