/*
# Add Additional Food Banks and Community Services

1. Purpose
   - Add food banks, community centers, and social services across Washington state
   - Fill gaps in underserved counties

2. Coverage
   - All Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'food-bank'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Northwest Harvest - Seattle', 'Food Bank', 'Regional food bank providing food to partner agencies across Washington.', '2226 3rd Ave S', 'Seattle', 'King', '98134', '(206) 923-0919', 'https://northwestharvest.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Food Bank'], ARRAY['food bank', 'food pantry', 'hunger relief'], 'food bank Northwest Harvest Seattle food distribution', 47.5800, -122.3300),
  ('Chief Sealth Food Bank - West Seattle', 'Food Bank', 'Community food bank serving West Seattle.', '1800 SW Brandon St', 'Seattle', 'King', '98106', '(206) 933-0707', 'https://westseattlefoodbank.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Somali'], ARRAY['Food Distribution', 'Weekend Food'], ARRAY['food bank', 'food pantry', 'West Seattle'], 'food bank Chief Sealth West Seattle food pantry', 47.5466, -122.3566),
  ('North Helpline Food Bank - Lake City', 'Food Bank', 'Community food bank serving North Seattle and Lake City area.', '12736 33rd Ave NE', 'Seattle', 'King', '98125', '(206) 632-2445', 'https://northhelpline.org', '{"monday": "10am-2pm", "tuesday": "10am-2pm", "wednesday": "10am-2pm", "thursday": "10am-2pm", "friday": "10am-2pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Vietnamese'], ARRAY['Food Distribution', 'Emergency Services'], ARRAY['food bank', 'food pantry', 'Lake City'], 'food bank North Helpline Lake City food pantry', 47.7351, -122.2995),
  ('Ballard Food Bank', 'Food Bank', 'Community food bank serving Ballard and surrounding neighborhoods.', '5130 NW Leary Way', 'Seattle', 'King', '98107', '(206) 789-9210', 'https://ballardfoodbank.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Somali'], ARRAY['Food Distribution', 'Home Delivery'], ARRAY['food bank', 'food pantry', 'Ballard'], 'food bank Ballard food pantry Seattle', 47.6685, -122.3898),
  ('University District Food Bank', 'Food Bank', 'Food bank serving the University District and NE Seattle.', '5017 Roosevelt Way NE', 'Seattle', 'King', '98105', '(206) 523-7060', 'https://udistrictfoodbank.org', '{"monday": "10am-3pm", "tuesday": "10am-3pm", "wednesday": "10am-3pm", "thursday": "10am-3pm", "friday": "10am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Food Distribution', 'Youth Programs'], ARRAY['food bank', 'food pantry', 'University District'], 'food bank University District food pantry U-District', 47.6647, -122.3201),
  ('Renton Salvation Army Food Bank', 'Food Bank', 'Community food bank serving Renton area.', '1100 Bronson Way N', 'Renton', 'King', '98055', '(425) 255-5961', 'https://salvationarmy.org', '{"monday": "9am-4pm", "tuesday": "9am-4pm", "wednesday": "9am-4pm", "thursday": "9am-4pm", "friday": "9am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Emergency Assistance'], ARRAY['food bank', 'food pantry', 'Salvation Army', 'Renton'], 'food bank Salvation Army Renton food pantry', 47.4817, -122.2046),
  ('FISH Food Bank - Tacoma', 'Food Bank', 'Community food bank serving Pierce County.', '2717 20th Ave E', 'Tacoma', 'Pierce', '98404', '(253) 383-3164', 'https://fishtacoma.org', '{"monday": "9am-3pm", "tuesday": "9am-3pm", "wednesday": "9am-3pm", "thursday": "9am-3pm", "friday": "9am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Korean'], ARRAY['Food Distribution', 'Mobile Pantry'], ARRAY['food bank', 'food pantry', 'Pierce County', 'FISH'], 'food bank FISH Tacoma Pierce County food pantry', 47.2456, -122.4147),
  ('Emergency Food Network - Puyallup', 'Food Bank', 'Regional food distribution center for Pierce County.', '3315 92nd St S', 'Puyallup', 'Pierce', '98373', '(253) 584-8040', 'https://efood.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Food Bank Support'], ARRAY['food bank', 'food distribution', 'Pierce County'], 'food bank Emergency Food Network Puyallup Pierce', 47.1307, -122.3914),
  ('Spokane Food Bank - Second Harvest', 'Food Bank', 'Regional food bank serving Eastern Washington.', '1234 E Sprague Ave', 'Spokane', 'Spokane', '99202', '(509) 252-6272', 'https://2-harvest.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Food Distribution', 'Mobile Pantry', 'Food Bank'], ARRAY['food bank', 'food pantry', 'Eastern Washington', 'Spokane'], 'food bank Second Harvest Spokane food distribution Eastern Washington', 47.6574, -117.3495),
  ('Volunteers of America Food Bank - Everett', 'Food Bank', 'Community food bank serving Snohomish County.', '2710 Oakes Ave', 'Everett', 'Snohomish', '98201', '(425) 259-3191', 'https://voaww.org', '{"monday": "9am-3pm", "tuesday": "9am-3pm", "wednesday": "9am-3pm", "thursday": "9am-3pm", "friday": "9am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Emergency Services'], ARRAY['food bank', 'food pantry', 'Snohomish County', 'VOA'], 'food bank Volunteers of America Everett Snohomish', 47.9755, -122.2073),
  ('Community Food Bank - Clark County', 'Food Bank', 'Regional food bank serving Clark County.', '6502 NE 47th Ave', 'Vancouver', 'Clark', '98661', '(360) 694-2672', 'https://cfbclc.org', '{"monday": "9am-4pm", "tuesday": "9am-4pm", "wednesday": "9am-4pm", "thursday": "9am-4pm", "friday": "9am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Food Distribution', 'Mobile Pantry'], ARRAY['food bank', 'food pantry', 'Clark County', 'Vancouver'], 'food bank Community Food Bank Clark County Vancouver', 45.6549, -122.6066),
  ('Thurston County Food Bank - Olympia', 'Food Bank', 'Community food bank serving Thurston County.', '2356 Mottman Rd SW', 'Tumwater', 'Thurston', '98501', '(360) 352-0178', 'https://tcfoodbank.org', '{"monday": "10am-4pm", "tuesday": "10am-4pm", "wednesday": "10am-4pm", "thursday": "10am-4pm", "friday": "10am-4pm", "saturday": "9am-12pm", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Kids Cafes'], ARRAY['food bank', 'food pantry', 'Thurston County', 'Olympia'], 'food bank Thurston County Food Bank Olympia Tumwater', 47.0258, -122.9283),
  ('Yakima Food Bank - Northwest Harvest', 'Food Bank', 'Regional food bank serving Yakima Valley.', '1212 S 3rd St', 'Yakima', 'Yakima', '98901', '(509) 469-4321', 'https://northwestharvest.org', '{"monday": "9am-3pm", "tuesday": "9am-3pm", "wednesday": "9am-3pm", "thursday": "9am-3pm", "friday": "9am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Yakima Valley'], 'food bank Northwest Harvest Yakima food distribution', 46.5894, -120.5129),
  ('Tri-Cities Food Bank - Kennewick', 'Food Bank', 'Community food bank serving Tri-Cities.', '1020 S Ely St', 'Kennewick', 'Benton', '99336', '(509) 946-4653', 'https://tricityfoodbank.org', '{"monday": "9am-3pm", "tuesday": "9am-3pm", "wednesday": "9am-3pm", "thursday": "9am-3pm", "friday": "9am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Tri-Cities', 'Kennewick'], 'food bank Tri-Cities Food Bank Kennewick Benton', 46.2066, -119.1093),
  ('Bellingham Food Bank', 'Food Bank', 'Community food bank serving Whatcom County.', '1823 Ellis St', 'Bellingham', 'Whatcom', '98225', '(360) 676-1039', 'https://bellinghamfoodbank.org', '{"monday": "10am-5pm", "tuesday": "10am-5pm", "wednesday": "10am-5pm", "thursday": "10am-5pm", "friday": "10am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Gleaning Program'], ARRAY['food bank', 'food pantry', 'Whatcom County', 'Bellingham'], 'food bank Bellingham Food Bank Whatcom', 48.7582, -122.4822),
  ('Cowlitz County Food Bank - Longview', 'Food Bank', 'Community food bank serving Cowlitz County.', '2030 48th Ave', 'Longview', 'Cowlitz', '98632', '(360) 425-2261', 'https://cowlitzfoodbank.org', '{"monday": "9am-3pm", "tuesday": "9am-3pm", "wednesday": "9am-3pm", "thursday": "9am-3pm", "friday": "9am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Cowlitz County'], 'food bank Cowlitz County Food Bank Longview', 46.1976, -122.9407),
  ('Grays Harbor Food Bank - Aberdeen', 'Food Bank', 'Community food bank serving Grays Harbor County.', '302 W First St', 'Aberdeen', 'Grays Harbor', '98520', '(360) 532-8801', 'https://grayscountyfoodbank.org', '{"monday": "9am-2pm", "tuesday": "9am-2pm", "wednesday": "9am-2pm", "thursday": "9am-2pm", "friday": "9am-2pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Grays Harbor'], 'food bank Grays Harbor Food Bank Aberdeen', 46.9749, -123.8217),
  ('Moses Lake Food Bank', 'Food Bank', 'Community food bank serving Grant County.', '1408 N Stratford Rd', 'Moses Lake', 'Grant', '98837', '(509) 765-8041', 'https://moseslakefoodbank.org', '{"monday": "10am-3pm", "tuesday": "10am-3pm", "wednesday": "10am-3pm", "thursday": "10am-3pm", "friday": "10am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Grant County', 'Moses Lake'], 'food bank Moses Lake Food Bank Grant County', 47.1324, -119.2968),
  ('Wenatchee Food Bank', 'Food Bank', 'Community food bank serving Chelan County.', '504 S Michigan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-4621', 'https://wenatcheefoodbank.org', '{"monday": "10am-3pm", "tuesday": "10am-3pm", "wednesday": "10am-3pm", "thursday": "10am-3pm", "friday": "10am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Chelan County', 'Wenatchee'], 'food bank Wenatchee Food Bank Chelan', 47.4125, -120.3110),
  ('Port Angeles Food Bank', 'Food Bank', 'Community food bank serving Clallam County.', '1634 E 5th St', 'Port Angeles', 'Clallam', '98362', '(360) 457-4454', 'https://pafoodbank.org', '{"monday": "10am-3pm", "tuesday": "10am-3pm", "wednesday": "10am-3pm", "thursday": "10am-3pm", "friday": "10am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Clallam County', 'Olympic Peninsula'], 'food bank Port Angeles Food Bank Clallam', 48.1190, -123.4112),
  ('Lewis County Food Bank - Centralia', 'Food Bank', 'Community food bank serving Lewis County.', '1010 W Main St', 'Centralia', 'Lewis', '98531', '(360) 736-3927', 'https://lcfoodbank.org', '{"monday": "9am-2pm", "tuesday": "9am-2pm", "wednesday": "9am-2pm", "thursday": "9am-2pm", "friday": "9am-2pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Lewis County', 'Centralia'], 'food bank Lewis County Food Bank Centralia', 46.7181, -122.9539),
  ('Walla Walla Food Bank', 'Food Bank', 'Community food bank serving Walla Walla County.', '310 W Poplar St', 'Walla Walla', 'Walla Walla', '99362', '(509) 529-9777', 'https://bluevalleyfoodbank.org', '{"monday": "10am-3pm", "tuesday": "10am-3pm", "wednesday": "10am-3pm", "thursday": "10am-3pm", "friday": "10am-3pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution'], ARRAY['food bank', 'food pantry', 'Walla Walla County'], 'food bank Walla Walla Food Bank', 46.0688, -118.3466)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
