/*
# Add WA CHAS, ICHS, Pediatrics, Food Banks - Batch 5

## Summary
Adds 17 verified Washington State healthcare resources including:
- CHAS Health FQHC clinics (Maple Street, Market Street, Parkside, Lidgerwood) in Spokane
- International Community Health Services ICHS clinics (International District, Holly Park, Shoreline, Bellevue)
- Pediatric care (MultiCare Mary Bridge Children's Hospital, Seattle Children's)
- Food banks (Tri-Cities Food Bank, Clark County Food Bank, Des Moines Area Food Bank, Serve Wenatchee Valley)

## Important Notes
1. CHAS Health is FQHC serving regardless of insurance status
2. ICHS is FQHC focused on diverse/immigrant communities with multilingual staff
3. Pediatric hospitals provide specialized care for children
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('CHAS Health Maple Street Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing primary care, dental, behavioral health, and pharmacy services to patients of all ages regardless of insurance status.', '3919 N Maple St', 'Spokane', 'Spokane', 'WA', '99205', '509-444-8200', 'https://chas.org', '{"mon":"7:00-18:00","tue":"7:00-18:00","wed":"7:00-18:00","thu":"7:00-18:00","fri":"7:00-18:00","sat":"8:00-17:00","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('CHAS Health Market Street Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing primary care, pharmacy, behavioral health, women''s health, nutritional services, and telehealth to patients of all ages.', '5921 N Market St', 'Spokane', 'Spokane', 'WA', '99208', '509-444-8200', 'https://chas.org', '{"mon":"7:00-18:00","tue":"7:00-18:00","wed":"7:00-18:00","thu":"7:00-18:00","fri":"7:00-18:00","sat":"8:00-17:00","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,pharmacy,behavioral health,womens health}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('CHAS Health Parkside Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing primary care, dental, behavioral health, and pharmacy services to patients of all ages regardless of insurance status.', '3002 E Mission Ave', 'Spokane', 'Spokane', 'WA', '99202', '509-444-8200', 'https://chas.org', '{"mon":"7:00-18:00","tue":"7:00-18:00","wed":"7:00-18:00","thu":"7:00-18:00","fri":"7:00-18:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('CHAS Health Lidgerwood Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing primary care and behavioral health services to patients of all ages regardless of insurance status.', '4905 N Lidgerwood St', 'Spokane', 'Spokane', 'WA', '99208', '509-444-8200', 'https://chas.org', '{"mon":"7:00-18:00","tue":"7:00-18:00","wed":"7:00-18:00","thu":"7:00-18:00","fri":"7:00-18:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('ICHS International District Medical & Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing adult and pediatric medical and dental care to diverse communities with multilingual staff. Flagship clinic of ICHS.', '720 8th Ave S', 'Seattle', 'King', 'WA', '98104', '206-788-3700', 'https://www.ichs.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Vietnamese,Korean,Tagalog,Cambodian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health}', '{}', '{immigrants,Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('ICHS Holly Park Medical & Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing adult and pediatric medical and dental care with after-hours primary care. Serves diverse communities in South Seattle.', '3830 S Othello St', 'Seattle', 'King', 'WA', '98118', '206-788-3700', 'https://www.ichs.com/locations/holly-park-medical-and-dental-clinic', '{"mon":"8:00-20:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-20:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Vietnamese,Korean,Tagalog,Cambodian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,after-hours care}', '{}', '{immigrants,Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('ICHS Shoreline Medical & Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing adult and pediatric medical and dental care to diverse communities in the Shoreline area.', '1225 NE 145th St', 'Shoreline', 'King', 'WA', '98155', '206-788-3700', 'https://www.ichs.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Vietnamese,Korean,Tagalog,Cambodian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health}', '{}', '{immigrants,Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('ICHS Bellevue Medical & Dental Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC clinic providing adult and pediatric medical and dental care to diverse communities on the Eastside.', '13033 NE Bel-Red Rd', 'Bellevue', 'King', 'WA', '98005', '206-788-3700', 'https://www.ichs.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"8:00-17:00","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Vietnamese,Korean,Tagalog,Cambodian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health}', '{}', '{immigrants,Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('MultiCare Mary Bridge Children''s Hospital', (SELECT id FROM resource_categories WHERE slug='pediatrics'), 'childrens hospital', 'Children''s hospital providing specialized pediatric emergency, surgical, critical care, specialty clinics, and inpatient services for children and adolescents.', '317 Martin Luther King Jr Way', 'Tacoma', 'Pierce', 'WA', '98405', '253-403-1400', 'https://www.marybridge.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{pediatric emergency,surgery,critical care,specialty clinics}', '{}', '{children,adolescents}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Mary Bridge Children''s Outpatient Center', (SELECT id FROM resource_categories WHERE slug='pediatrics'), '', 'Pediatric outpatient center providing specialty clinics, therapy services, and specialty care for children and adolescents.', '311 S L St', 'Tacoma', 'Pierce', 'WA', '98405', '253-792-6630', 'https://www.marybridge.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{pediatric specialty,therapy,outpatient care}', '{}', '{children,adolescents}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Tri-Cities Food Bank - Richland', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Regional food bank providing free food, fresh produce, and dairy products to individuals and families in need in the Tri-Cities area.', '321 Wellsian Way', 'Richland', 'Benton', 'WA', '99352', '509-943-2795', 'https://tcfoodbank.com', '{"mon":"9:00-11:30","tue":"9:00-11:30","wed":"Closed","thu":"9:00-11:30","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Clark County Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Regional food bank distributing food to partner pantries, meal programs, and individuals in need throughout Clark County.', '6502 NE 47th Ave', 'Vancouver', 'Clark', 'WA', '98661', '360-693-0939', 'https://www.clarkcountyfoodbank.org', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Northwest Harvest Kent Distribution Center', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Regional food bank and distribution center providing free food to individuals and families in need. Also supplies partner food banks across the region.', '22220 68th Ave S', 'Kent', 'King', 'WA', '98032', '206-285-0237', 'https://www.northwestharvest.org', '{"mon":"9:00-15:00","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"9:00-15:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Serve Wenatchee Valley Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Food bank providing fresh produce, dairy, and non-perishable food to individuals and families in the greater Wenatchee Valley area.', '317 S Chelan Ave', 'Wenatchee', 'Chelan', 'WA', '98801', '509-888-6634', 'https://www.servewenatchee.org', '{"mon":"9:00-14:00","tue":"9:00-14:00","wed":"9:00-14:00","thu":"9:00-14:00","fri":"9:00-14:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Bellingham Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank providing fresh produce, dairy, meat, and non-perishable food to individuals and families in need in the Bellingham area.', '509 Victoria Point St', 'Bellingham', 'Whatcom', 'WA', '98225', '360-676-0392', 'https://www.bellinghamfoodbank.org', '{"mon":"9:00-15:00","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"9:00-15:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Community Services of Western Washington', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Non-profit organization providing social services, family support, housing assistance, mental health counseling, and youth services to individuals and families in need.', '100 23rd Ave S', 'Seattle', 'King', 'WA', '98144', '206-328-5914', 'https://www.ccsww.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{social services,housing assistance,counseling,youth services}', '{}', '{low-income,families,seniors,homeless}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Salvation Army Northwest Division', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Non-profit organization providing social services, emergency assistance, food, shelter, clothing, and rehabilitation programs to individuals and families in need across Washington.', '22024 11th Ave S', 'Des Moines', 'King', 'WA', '98198', '206-447-9944', 'https://www.salvationarmyusa.org/northwest', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{social services,emergency assistance,food,shelter,rehabilitation}', '{}', '{low-income,families,homeless}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified')
ON CONFLICT DO NOTHING;
