/*
# Add Olympic Peninsula Food Banks (Jefferson & Clallam Counties)

1. Data Insert
- Adds Port Townsend Food Bank, Sequim Food Bank, and Port Angeles Food Bank.
2. Source
- Verified via Jefferson County Food Bank Association (jcfba.org),
  Sequim Food Bank (sequimfoodbank.org), and Port Angeles Food Bank website.
3. Notes
- All food banks cost_free=true.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Port Townsend Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Jefferson County Food Bank Association main site in Port Townsend offering weekly groceries, fresh produce, and basic necessities. Senior-only hours Saturday morning.', '1925 Blaine St', 'Port Townsend', 'Jefferson', 'WA', '98368', '360-774-4680', 'https://www.jcfba.org', '{"mon":"Closed","tue":"Closed","wed":"8:30-15:00","thu":"Closed","fri":"Closed","sat":"11:00-13:30,15:00-17:00","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Tagalog}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Fresh Produce}', '{Food Bank}', '{Low-Income,Seniors,Families}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Sequim Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Sequim Food Bank serving the Sequim community and eastern Clallam County, offering weekly groceries, fresh produce, dairy, protein, and a Mobile Food Pantry to outlying neighborhoods.', '144 W Alder St', 'Sequim', 'Clallam', 'WA', '98382', '360-683-1205', 'https://www.sequimfoodbank.org', '{"mon":"Closed","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"9:00-15:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Fresh Produce,Mobile Food Pantry}', '{Food Bank}', '{Low-Income,Families,Seniors}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Port Angeles Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Port Angeles Food Bank weekly grocery distribution serving low-income individuals and families throughout the Port Angeles area. Provides groceries, fresh produce, dairy and protein.', '632 N Oakridge Dr', 'Port Angeles', 'Clallam', 'WA', '98362', '360-452-8568', 'https://www.portangelesfoodbank.org', '{"mon":"8:00-15:00","tue":"8:00-15:00","wed":"14:00-18:00","thu":"14:00-18:00","fri":"14:00-18:00","sat":"11:00-14:00","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food,Fresh Produce,Groceries}', '{Food Bank}', '{Low-Income,Families,Seniors,Homeless}', 4.5, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Quilcene Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Jefferson County Food Bank Association satellite site in Quilcene serving the Quilcene and Brinnon communities.', '170 Herbert St', 'Quilcene', 'Jefferson', 'WA', '98376', '360-774-4680', 'https://www.jcfba.org/locations', '{"mon":"11:00-14:00","tue":"Closed","wed":"Closed","thu":"Closed","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Food Assistance,Emergency Food}', '{Food Bank}', '{Low-Income,Families}', 4.0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;