/*
# Add Dental Clinics

1. Purpose
   - Add community dental clinics and low-cost dental care across Washington state
   - Focus on FQHC dental and sliding scale clinics

2. Coverage
   - All major Washington counties
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'dental'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('ARC Dentistry - Seattle', 'Community Dental Clinic', 'Community dental clinic with sliding scale fees. General dentistry, extractions, and dentures.', '3615 S Pawnee St', 'Seattle', 'King', '98118', '(206) 467-4800', 'https://arccentistry.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Khmer'], ARRAY['General Dentistry', 'Extractions', 'Dentures', 'Fillings'], ARRAY['dental', 'sliding scale', 'low cost'], 'dental clinic ARC Dentistry Seattle sliding scale', 47.5333, -122.2683),
  ('Seattle Christian Dental Clinic', 'Community Dental Clinic', 'Faith-based community dental clinic providing care to uninsured and underinsured adults.', '1930 9th Ave S', 'Seattle', 'King', '98144', '(206) 783-7300', 'https://seattlecdc.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Extractions', 'Root Canals'], ARRAY['dental', 'free clinic', 'Christian', 'sliding scale'], 'dental clinic Seattle Christian Dental free sliding scale', 47.5870, -122.3240),
  ('Country Doctor Community Health Centers Dental - Seattle', 'Community Dental Clinic', 'FQHC dental services with sliding scale for low-income patients.', '2012 21st Ave S', 'Seattle', 'King', '98144', '(206) 461-4500', 'https://cdchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Country Doctor Community Health Seattle FQHC', 47.5961, -122.3061),
  ('Neighborcare Health Dental - Ballard', 'Community Dental Clinic', 'Community dental clinic serving Ballard area with sliding scale fees.', '1801 NW 56th St', 'Seattle', 'King', '98107', '(206) 708-6200', 'https://neighborcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Somali'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Neighborcare Health Ballard Seattle', 47.6687, -122.3833),
  ('Neighborcare Health Dental - Rainier Beach', 'Community Dental Clinic', 'Community dental clinic serving South Seattle.', '9245 Rainier Ave S', 'Seattle', 'King', '98118', '(206) 772-7200', 'https://neighborcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Vietnamese'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Neighborcare Health Rainier Beach Seattle', 47.5175, -122.2618),
  ('Sea Mar Dental - Tacoma', 'Community Dental Clinic', 'Bilingual dental services with sliding scale for low-income patients.', '2201 E 28th St', 'Tacoma', 'Pierce', '98404', '(253) 475-0600', 'https://seamar.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions', 'Dentures'], ARRAY['dental', 'FQHC', 'sliding scale', 'Sea Mar', 'Spanish'], 'dental clinic Sea Mar Tacoma sliding scale FQHC', 47.2405, -122.4250),
  ('Community Health Care Dental - Lakewood', 'Community Dental Clinic', 'Community dental clinic serving Pierce County with sliding scale.', '7701 30th St W', 'Lakewood', 'Pierce', '98499', '(253) 983-6500', 'https://chcpierce.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Community Health Care Lakewood Pierce', 47.1715, -122.5336),
  ('CHAS Health Dental - Spokane', 'Community Dental Clinic', 'Community dental clinic with sliding scale. Accepts Apple Health.', '1403 N Washington St', 'Spokane', 'Spokane', '99207', '(509) 444-8200', 'https://chas.org', '{"monday": "7am-5pm", "tuesday": "7am-5pm", "wednesday": "7am-5pm", "thursday": "7am-5pm", "friday": "7am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Russian', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions', 'Dentures'], ARRAY['dental', 'FQHC', 'sliding scale', 'CHAS'], 'dental clinic CHAS Health Spokane sliding scale FQHC', 47.6715, -117.4026),
  ('Smile Spokane Dental Center', 'Community Dental Clinic', 'Community dental clinic offering affordable care with sliding scale.', '510 S McClellan St', 'Spokane', 'Spokane', '99204', '(509) 624-2600', 'https://smilespokane.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Russian'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale'], 'dental clinic Smile Spokane sliding scale', 47.6531, -117.4289),
  ('YVFWC Dental - Toppenish', 'Community Dental Clinic', 'Bilingual community dental clinic with sliding scale fees.', '700 W 4th Ave', 'Toppenish', 'Yakima', '98948', '(509) 865-2100', 'https://yvfwc.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale', 'YVFWC', 'Spanish'], 'dental clinic YVFWC Toppenish Yakima Valley sliding scale', 46.3776, -120.3162),
  ('YVFWC Dental - Yakima', 'Community Dental Clinic', 'Community dental care with Apple Health accepted.', '1705 W Nob Hill Blvd', 'Yakima', 'Yakima', '98902', '(509) 454-4140', 'https://yvfwc.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'FQHC', 'sliding scale', 'YVFWC'], 'dental clinic YVFWC Yakima sliding scale FQHC', 46.5948, -120.5490),
  ('Confluence Health Dental - Wenatchee', 'Community Dental Clinic', 'Community dental services with sliding scale available.', '820 N Chelan Ave', 'Wenatchee', 'Chelan', '98801', '(509) 663-8711', 'https://confluencehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale'], 'dental clinic Confluence Health Wenatchee', 47.4261, -120.3136),
  ('Unity Care NW Dental - Bellingham', 'Community Dental Clinic', 'FQHC dental clinic with sliding scale for Whatcom County.', '220 Unity St', 'Bellingham', 'Whatcom', '98225', '(360) 676-6177', 'https://unitycarenw.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Unity Care NW Bellingham FQHC sliding scale', 48.7544, -122.4745),
  ('PeaceHealth Dental Clinic - Longview', 'Community Dental Clinic', 'Community dental clinic serving Cowlitz County.', '1615 Delaware St', 'Longview', 'Cowlitz', '98632', '(360) 414-2000', 'https://peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale', 'PeaceHealth'], 'dental clinic PeaceHealth Dental Longview Cowlitz', 46.1415, -122.9401),
  ('Kadlec Dental Clinic - Richland', 'Community Dental Clinic', 'Community dental services with sliding scale available.', '1268 Lee Blvd', 'Richland', 'Benton', '99352', '(509) 946-1651', 'https://kadlec.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale'], 'dental clinic Kadlec Dental Richland Tri-Cities', 46.2856, -119.2706),
  ('Community Health Center Dental - Vancouver', 'Community Dental Clinic', 'FQHC dental clinic serving Clark County with sliding scale.', '311 NE 138th Ave', 'Vancouver', 'Clark', '98684', '(360) 944-8900', 'https://ccfhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions', 'Dentures'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Community Health Center Vancouver Clark', 45.6221, -122.5477),
  ('Family Health Center Dental - Aberdeen', 'Community Dental Clinic', 'Community dental clinic serving Grays Harbor.', '1300 Sumner Ave', 'Aberdeen', 'Grays Harbor', '98520', '(360) 533-2948', 'https://fhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Family Health Center Aberdeen Grays Harbor', 46.9735, -123.8147),
  ('Olympic Dental Clinic - Port Angeles', 'Community Dental Clinic', 'Community dental services for Olympic Peninsula.', '844 N 5th Ave', 'Port Angeles', 'Clallam', '98362', '(360) 417-7150', 'https://olympicmedical.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale'], 'dental clinic Olympic Dental Port Angeles Clallam', 48.1162, -123.4333),
  ('Northwest Community Health Dental - Moses Lake', 'Community Dental Clinic', 'Community dental clinic serving Grant County.', '605 S Sherman St', 'Moses Lake', 'Grant', '98837', '(509) 765-0674', 'https://nwchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale'], 'dental clinic Northwest Community Health Dental Moses Lake Grant', 47.1231, -119.2787),
  ('Sunnyside Community Dental', 'Community Dental Clinic', 'Bilingual dental services in Lower Yakima Valley.', '800 E Edison Ave', 'Sunnyside', 'Yakima', '98944', '(509) 837-4500', 'https://sunnysidedental.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale', 'Spanish'], 'dental clinic Sunnyside Community Dental Yakima Valley', 46.3238, -119.9918),
  ('Columbia Valley Community Health Dental', 'Community Dental Clinic', 'FQHC dental clinic with sliding scale.', '600 Orondo Ave', 'Wenatchee', 'Chelan', '98801', '(509) 662-6000', 'https://cvch.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['General Dentistry', 'Cleanings', 'Fillings', 'Extractions'], ARRAY['dental', 'FQHC', 'sliding scale', 'CVCH'], 'dental clinic Columbia Valley Community Health Dental Wenatchee', 47.4340, -120.3316),
  ('Jefferson Healthcare Dental Center - Port Townsend', 'Community Dental Clinic', 'Community dental clinic serving East Jefferson County.', '834 Sheridan St', 'Port Townsend', 'Jefferson', '98368', '(360) 385-2200', 'https://jeffersonhealthcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['General Dentistry', 'Cleanings', 'Fillings'], ARRAY['dental', 'sliding scale'], 'dental clinic Jefferson Healthcare Dental Port Townsend', 48.1163, -122.7755)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
