/*
# Add WA Tribal Health, Free Clinics, and Sea Mar - Batch 2

## Summary
Adds 18 verified Washington State healthcare resources including:
- Tribal health centers (Seattle Indian Health Board, Puyallup Tribal Health Authority, etc.)
- Free/charity clinics (Free Clinic of SW Washington, Safe Harbor Free Clinic, West Sound Free Clinic, etc.)
- Additional Sea Mar FQHC clinics (Vancouver, Aberdeen, Longview, etc.)

## Resources Added
- Seattle Indian Health Board - tribal health, Seattle/King County
- Puyallup Tribal Health Authority - tribal health, Tacoma/Pierce County
- Free Clinic of Southwest Washington - free clinic, Vancouver/Clark County
- Safe Harbor Free Clinic Stanwood - free clinic, Stanwood/Snohomish County
- Safe Harbor Free Clinic Smokey Point - free clinic, Arlington/Snohomish County
- West Sound Free Clinic - free clinic, Bremerton/Kitsap County
- Sea Mar Vancouver Medical - FQHC, Vancouver/Clark County
- Sea Mar Aberdeen Medical - FQHC, Aberdeen/Grays Harbor County
- Sea Mar Longview Medical - FQHC, Longview/Cowlitz County
- Sea Mar Burien Medical - FQHC, Burien/King County
- Health & Hope Medical Outreach - free clinic, Centralia/Lewis County
- Union Gospel Mission Spokane - free clinic, Spokane County
- SonBridge Dental Clinic - free dental, College Place/Walla Walla County
- West Valley Medical - free/charity, Spokane County

## Important Notes
1. Tribal health centers serve both tribal members and non-Native patients
2. Free clinics serve uninsured and underinsured patients at no cost
3. FQHCs accept uninsured, sliding scale, Medicaid/Medicare/private insurance
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Seattle Indian Health Board', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Urban Indian health program providing primary medical, dental, behavioral health, and community services to American Indians, Alaska Natives, and the broader community.', '611 12th Ave S', 'Seattle', 'King', 'WA', '98144', '206-324-9360', 'https://www.sihb.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Lushootseed}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,community services}', '{tribal health,urban Indian}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Puyallup Tribal Health Authority', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Tribal health center providing primary medical, dental, behavioral health, pharmacy, and community services to tribal members and the broader community.', '2209 E 32nd St', 'Tacoma', 'Pierce', 'WA', '98404', '253-593-0200', 'https://www.eptha.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Free Clinic of Southwest Washington', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing basic medical care, urgent dental care, diabetes management, and health insurance navigation for uninsured and underinsured patients.', '4100 Plomondon St', 'Vancouver', 'Clark', 'WA', '98661', '360-450-3044', 'https://freeclinics.org', '{"mon":"9:00-16:00","tue":"9:00-16:00","wed":"9:00-16:00","thu":"9:00-16:00","fri":"9:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, false, false, false, false, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,chronic disease management}', '{}', '{uninsured,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Safe Harbor Free Clinic Stanwood', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing urgent care, women''s health, chronic care, cardiology, podiatry, physical therapy, and counseling services to uninsured patients.', '7209 265th St NW, Suite 204', 'Stanwood', 'Snohomish', 'WA', '98292', '425-870-7384', 'https://www.safeharborfreeclinic.org', '{"mon":"9:00-16:00","tue":"9:00-16:00","wed":"9:00-16:00","thu":"9:00-16:00","fri":"9:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{urgent care,womens health,chronic care,counseling}', '{}', '{uninsured,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Safe Harbor Free Clinic Smokey Point', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing urgent care and basic medical services to uninsured and underinsured patients in the Arlington area.', '17721 Smokey Point Blvd', 'Arlington', 'Snohomish', 'WA', '98223', '425-870-7384', 'https://www.safeharborfreeclinic.org', '{"mon":"Closed","tue":"Closed","wed":"Closed","thu":"12:00-20:00","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{urgent care,primary care}', '{}', '{uninsured,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('West Sound Free Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing basic medical care to uninsured and underinsured patients in the Bremerton and Kitsap County area.', '9188 Utah St NE', 'Bremerton', 'Kitsap', 'WA', '98311', '360-373-3506', 'https://www.westsoundfreeclinic.org', '{"mon":"9:00-16:00","tue":"9:00-16:00","wed":"9:00-16:00","thu":"9:00-16:00","fri":"9:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{primary care,urgent care}', '{}', '{uninsured,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Vancouver Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, and preventive services to all patients regardless of insurance or ability to pay.', '7410 Delaware Ln', 'Vancouver', 'Clark', 'WA', '98664', '360-574-4074', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Vancouver East Medical', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary care, behavioral health, and preventive health services to all patients regardless of ability to pay.', '14508 NE 20th Ave, Suite 102', 'Vancouver', 'Clark', 'WA', '98686', '360-852-9070', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Aberdeen Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary medical, behavioral health, and preventive care services to all patients regardless of ability to pay.', '1813 Sumner Ave', 'Aberdeen', 'Grays Harbor', 'WA', '98520', '360-532-7402', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Longview Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary medical, behavioral health, and preventive care services to all patients regardless of ability to pay.', '1420 12th Ave', 'Longview', 'Cowlitz', 'WA', '98632', '360-425-4110', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Burien Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary medical, behavioral health, and preventive care services to all patients regardless of ability to pay.', '14434 Ambaum Blvd SW', 'Burien', 'King', 'WA', '98166', '206-248-5330', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,behavioral health,preventive care}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Vancouver Behavioral Health', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'behavioral health', 'FQHC behavioral health clinic providing counseling, therapy, and mental health services to all patients regardless of ability to pay.', '550 NE 109th Ct, Suite C', 'Vancouver', 'Clark', 'WA', '98662', '360-566-4432', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{behavioral health,counseling,therapy}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Health and Hope Medical Outreach', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing basic medical care and chronic disease management to uninsured and underinsured patients in Lewis County.', '1911 Cooks Hill Rd', 'Centralia', 'Lewis', 'WA', '98532', '360-827-4724', 'https://www.healthandhopemobile.org', '{"mon":"9:00-14:00","tue":"9:00-14:00","wed":"9:00-14:00","thu":"9:00-14:00","fri":"9:00-14:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{primary care,chronic disease management}', '{}', '{uninsured,low-income,homeless}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Union Gospel Mission Spokane Helping Hands Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing basic medical care, dental services, and behavioral health support to homeless and low-income individuals in Spokane.', '2828 W Garland Ave', 'Spokane', 'Spokane', 'WA', '99205', '509-535-8510', 'https://www.ugmspokane.org', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{primary care,dental,behavioral health}', '{}', '{uninsured,low-income,homeless}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('SonBridge Dental Clinic', (SELECT id FROM resource_categories WHERE slug='dental'), 'free clinic', 'Free and low-cost dental clinic providing basic and restorative dental services to uninsured and low-income patients in Walla Walla County.', '1200 SE 12th St', 'College Place', 'Walla Walla', 'WA', '99324', '509-529-2391', 'https://www.sonbridgecenter.org', '{"mon":"9:00-16:00","tue":"9:00-16:00","wed":"9:00-16:00","thu":"9:00-16:00","fri":"9:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{dental,restorative dental}', '{}', '{uninsured,low-income}', 0, 'https://images.pexels.com/photos/6642765/pexels-photo-6642765.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('SOS Health Services', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'free clinic', 'Free clinic providing basic medical care and health screening services to uninsured and low-income patients in the Walla Walla area.', '1200 SE 12th St', 'College Place', 'Walla Walla', 'WA', '99324', '509-529-4722', 'https://www.soshealthservices.org', '{"mon":"9:00-15:00","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"Closed","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{primary care,health screening}', '{}', '{uninsured,low-income}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('NATIVE Project', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'Urban Indian health program providing primary medical, dental, behavioral health, and pharmacy services to Native Americans and the broader Spokane community.', '1803 E Indiana Ave', 'Spokane', 'Spokane', 'WA', '99202', '509-325-5502', 'https://www.thenativeproject.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health,urban Indian}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Lummi Tribal Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'tribal health', 'Tribal health center providing primary medical, dental, behavioral health, pharmacy, and community health services to tribal members and the broader community.', '2664 Kwina Rd', 'Bellingham', 'Whatcom', 'WA', '98226', '360-384-0464', 'https://www.lummi-nsn.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Lummi}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy}', '{tribal health}', '{Native American,Alaska Native}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified')
ON CONFLICT DO NOTHING;
