/*
# Add Washington Homeless Shelters & Missions

1. Data Insert
- Adds homeless shelters / rescue missions across WA: Spokane (UGM, Women &
  Children Crisis Shelter), Wenatchee (Wenatchee Rescue Mission), Pasco (Tri-City
  UGM), Everett (Everett Gospel Mission Men's Shelter), Vancouver (Share House,
  Open House Ministries), Bellingham (Opportunity Council).
2. Source
- Verified via UGM locations, Wenatchee Rescue Mission, Share Vancouver,
  Providence WA shelters PDF, and Opportunity Council websites.
3. Notes
- Shelters: cost_free=true. community-org category.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Union Gospel Mission - Spokane Men''s Shelter', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'UGM Inland Northwest men''s shelter and recovery program in Spokane providing emergency shelter, meals, addiction recovery, job training and spiritual support for men experiencing homelessness.', '1224 E Trent Ave', 'Spokane', 'Spokane', 'WA', '99202', '509-535-8510', 'https://www.uniongospelmission.org', '{"mon":"8:30-16:30","tue":"8:30-16:30","wed":"8:30-16:30","thu":"8:30-16:30","fri":"8:30-16:30","sat":"8:30-16:30","sun":"8:30-16:30"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Emergency Shelter,Meals,Addiction Recovery,Job Training}', '{Homeless Services}', '{Homeless Individuals,Men}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('UGM Women & Children''s Crisis Shelter - Spokane', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Union Gospel Mission crisis shelter for women and children in Spokane providing emergency shelter, meals, advocacy, case management and recovery services.', '1515 E Illinois Ave', 'Spokane', 'Spokane', 'WA', '99207', '509-535-8510', 'https://www.uniongospelmission.org/locations', '{"mon":"8:30-16:30","tue":"8:30-16:30","wed":"8:30-16:30","thu":"8:30-16:30","fri":"8:30-16:30","sat":"8:30-16:30","sun":"8:30-16:30"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Emergency Shelter,Meals,Advocacy,Case Management,Recovery}', '{Homeless Services}', '{Homeless Individuals,Women,Children,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Wenatchee Rescue Mission', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Low-barrier homeless shelter in Wenatchee providing shelter, three meals daily, showers, laundry, coordinated entry, warming/cooling center, and 44 pallet shelters.', '1450 S Wenatchee Ave', 'Wenatchee', 'Chelan', 'WA', '98801', '509-663-4289', 'https://wrmchange.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"9:00-18:00","sun":"9:00-18:00"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Emergency Shelter,Meals,Showers,Laundry,Coordinated Entry}', '{Homeless Services}', '{Homeless Individuals}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Tri-City Union Gospel Mission', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Tri-City Union Gospel Mission in Pasco providing emergency shelter, meals, addiction recovery programs, and supportive services for homeless individuals in the Tri-Cities.', '110 N 2nd Ave', 'Pasco', 'Franklin', 'WA', '99301', '509-547-2112', 'https://www.tcugm.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"8:00-17:00","sun":"8:00-17:00"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Emergency Shelter,Meals,Addiction Recovery,Supportive Services}', '{Homeless Services}', '{Homeless Individuals}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Everett Gospel Mission Men''s Shelter', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Everett Gospel Mission men''s shelter providing emergency shelter, meals, recovery programs, and supportive services for homeless men in Snohomish County.', '3711 Smith Ave', 'Everett', 'Snohomish', 'WA', '98201', '425-252-1297', 'https://www.egm.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"8:00-17:00","sun":"8:00-17:00"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Emergency Shelter,Meals,Recovery Programs,Supportive Services}', '{Homeless Services}', '{Homeless Individuals,Men}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Share House - Shelter for Single Men', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Share Vancouver shelter for single men providing emergency shelter, engagement specialists, housing navigation, and connections to employment, health and education resources in Clark County.', '1115 W 13th St', 'Vancouver', 'Clark', 'WA', '98660', '360-695-7658', 'https://sharevancouver.org', '{"mon":"9:00-19:00","tue":"9:00-19:00","wed":"9:00-19:00","thu":"9:00-19:00","fri":"9:00-19:00","sat":"9:00-19:00","sun":"9:00-19:00"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{Emergency Shelter,Housing Navigation,Case Management,Outreach}', '{Homeless Services}', '{Homeless Individuals,Men}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Open House Ministries', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Christ-centered shelter in Vancouver, WA providing long-term housing, meals, case management, parenting support, financial literacy, addiction recovery support and life skills programs for homeless families with children.', '905 W 13th St', 'Vancouver', 'Clark', 'WA', '98660', '360-695-4116', 'https://www.sheltered.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Emergency Shelter,Transitional Housing,Meals,Case Management,Life Skills,Addiction Recovery Support}', '{Homeless Services}', '{Homeless Families,Women,Children}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Opportunity Council', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Homeless Shelter', 'Whatcom County Community Action Agency providing emergency shelter, housing assistance, energy assistance, food, early childhood education (Head Start/ECEAP), and homeless services across Whatcom, Island and San Juan Counties.', '1111 Cornwall Ave', 'Bellingham', 'Whatcom', 'WA', '98225', '360-734-5121', 'https://www.oppco.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{Emergency Shelter,Housing Assistance,Energy Assistance,Food,Head Start,ECEAP}', '{Homeless Services,Community Action}', '{Homeless Individuals,Families,Children}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;