-- Add more food banks, senior services, and additional community resources
INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  data.category_id,
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Additional Food Banks
  ('Columbia Basin Food Bank - Moses Lake', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Food distribution for Grant County residents in need.', '220 E Colonial Ave', 'Moses Lake', 'Grant', '98837', '(509) 765-8572', 'https://www.columbiabasinfoodbank.org', '{"monday": "9am-3pm", "tuesday": "9am-3pm", "wednesday": "9am-3pm", "thursday": "9am-3pm", "friday": "9am-12pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Emergency Food', 'USDA Commodities'], ARRAY['food bank', 'emergency food', 'Moses Lake', 'Grant County', 'free'], 'Columbia Basin Food Bank Moses Lake emergency food Grant County free', 47.1259, -119.2810),
  ('Okanogan Community Action Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Food assistance for Okanogan County families.', '712 N 2nd Ave', 'Okanogan', 'Okanogan', '98840', '(509) 422-4041', 'https://www.okanogancac.org', '{"monday": "10am-4pm", "tuesday": "10am-4pm", "wednesday": "10am-4pm", "thursday": "10am-4pm", "friday": "10am-2pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Emergency Food', 'Senior Nutrition'], ARRAY['food bank', 'emergency food', 'Okanogan', 'Okanogan County', 'free'], 'Okanogan Community Action Food Bank emergency food Okanogan County free', 48.3641, -119.5920),
  ('Tonasket Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Food distribution for Tonasket and north Okanogan County.', '217 S Whitcomb Ave', 'Tonasket', 'Okanogan', '98855', '(509) 486-2133', 'https://www.tonasketfoodbank.org', '{"monday": "10am-3pm", "wednesday": "10am-3pm", "friday": "10am-3pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Emergency Food'], ARRAY['food bank', 'emergency food', 'Tonasket', 'Okanogan County', 'free'], 'Tonasket Food Bank emergency food Okanogan County Tonasket free', 48.7083, -119.4390),
  ('Republic Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Serving Ferry County residents with emergency food assistance.', '83 N Madison Ave', 'Republic', 'Ferry', '99166', '(509) 775-3121', 'https://www.republicfoodbank.org', '{"tuesday": "10am-2pm", "thursday": "10am-2pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English'], ARRAY['Food Distribution', 'Emergency Food'], ARRAY['food bank', 'emergency food', 'Republic', 'Ferry County', 'free'], 'Republic Food Bank emergency food Ferry County Republic free', 48.6489, -118.7382),
  ('Davenport Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Emergency food for Lincoln County families.', '222 7th St', 'Davenport', 'Lincoln', '99122', '(509) 725-0551', 'https://www.davenportfoodbank.org', '{"monday": "10am-2pm", "wednesday": "10am-2pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English'], ARRAY['Food Distribution', 'Emergency Food'], ARRAY['food bank', 'emergency food', 'Davenport', 'Lincoln County', 'free'], 'Davenport Food Bank emergency food Lincoln County free', 47.6570, -118.1456),
  ('Ritzville Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Food assistance for Adams County residents.', '211 E Galbraith St', 'Ritzville', 'Adams', '99169', '(509) 659-0610', 'https://www.ritzvillefoodbank.org', '{"monday": "9am-12pm", "wednesday": "9am-12pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English'], ARRAY['Food Distribution', 'Emergency Food'], ARRAY['food bank', 'emergency food', 'Ritzville', 'Adams County', 'free'], 'Ritzville Food Bank emergency food Adams County free', 47.1265, -118.3772),
  ('Dayton Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Emergency food distribution for Columbia County.', '341 E Main St', 'Dayton', 'Columbia', '99328', '(509) 382-2556', 'https://www.daytonfoodbank.org', '{"tuesday": "10am-2pm", "thursday": "10am-2pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English', 'Spanish'], ARRAY['Food Distribution', 'Emergency Food'], ARRAY['food bank', 'emergency food', 'Dayton', 'Columbia County', 'free'], 'Dayton Food Bank emergency food Columbia County Dayton free', 46.3193, -117.9862),
  ('Pomeroy Food Bank', (SELECT id FROM resource_categories WHERE slug = 'food-bank'), 'Food Bank', 'Serving Garfield County with emergency food assistance.', '715 Main St', 'Pomeroy', 'Garfield', '99347', '(509) 843-1354', 'https://www.pomeroyfoodbank.org', '{"monday": "9am-12pm", "thursday": "9am-12pm"}'::jsonb, true, false, false, false, false, true, false, false, true, ARRAY['English'], ARRAY['Food Distribution', 'Emergency Food'], ARRAY['food bank', 'emergency food', 'Pomeroy', 'Garfield County', 'free'], 'Pomeroy Food Bank emergency food Garfield County Pomeroy free', 46.4716, -117.5944),
  -- Senior Services
  ('Senior Services of Snohomish County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Comprehensive services for seniors including meals, transportation, and case management.', '3020 Lombard Ave', 'Everett', 'Snohomish', '98201', '(425) 265-2222', 'https://www.sssc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English'], ARRAY['Senior Meals', 'Transportation', 'Case Management', 'Caregiver Support'], ARRAY['senior services', 'elder care', 'Snohomish County', 'meals', 'transportation'], 'Senior Services Snohomish County meals transportation case management Everett', 47.9819, -122.2007),
  ('Pierce County Aging and Long-Term Care', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Services for older adults including case management, caregiver support, and benefits counseling.', '2601 S 35th St', 'Tacoma', 'Pierce', '98409', '(253) 798-4600', 'https://www.piercecountywa.gov/altc', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Case Management', 'Caregiver Support', 'Benefits Counseling', 'Meals on Wheels'], ARRAY['senior services', 'aging', 'case management', 'Tacoma', 'Pierce County'], 'Pierce County Aging Long Term Care senior services Tacoma caregiver support', 47.2389, -122.4848),
  ('Spokane County Aging and Long-Term Care', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Comprehensive aging services including in-home care, meals, and caregiver support.', '1225 N Washington St', 'Spokane', 'Spokane', '99260', '(509) 477-4300', 'https://www.spokanecounty.org/altc', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Case Management', 'In-Home Care', 'Caregiver Support', 'Meals on Wheels'], ARRAY['senior services', 'aging', 'Spokane', 'caregiver support', 'meals'], 'Spokane County Aging Long Term Care senior services Spokane caregiver', 47.6684, -117.4048),
  ('Senior Centers of Walla Walla', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Adult day health, meals, social activities, and transportation for seniors.', '310 E Rose St', 'Walla Walla', 'Walla Walla', '99362', '(509) 527-3795', 'https://www.seniorcentersww.org', '{"monday": "8am-4pm", "tuesday": "8am-4pm", "wednesday": "8am-4pm", "thursday": "8am-4pm", "friday": "8am-4pm"}'::jsonb, true, false, false, true, false, true, true, false, true, ARRAY['English'], ARRAY['Adult Day Health', 'Meals', 'Social Activities', 'Transportation'], ARRAY['senior services', 'adult day health', 'Walla Walla', 'meals', 'social activities'], 'Senior Centers Walla Walla adult day health meals social activities', 46.0682, -118.3374),
  ('Benton-Franklin Area Agency on Aging', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Services for older adults in Benton and Franklin counties.', '5020 W Lincoln Ave', 'Kennewick', 'Benton', '99336', '(509) 735-0055', 'https://www.bfaging.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Case Management', 'Caregiver Support', 'Benefits Counseling', 'Medicare Help'], ARRAY['senior services', 'aging', 'Tri-Cities', 'Kennewick', 'Medicare'], 'Benton Franklin Area Agency Aging senior services Kennewick Medicare help', 46.2140, -119.1754),
  ('Lewis County Senior Services', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Senior centers, meals, transportation, and social services.', '1921 S Tower Ave', 'Centralia', 'Lewis', '98531', '(360) 736-4944', 'https://www.lcseniors.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English'], ARRAY['Senior Meals', 'Transportation', 'Case Management', 'Social Activities'], ARRAY['senior services', 'Centralia', 'Lewis County', 'meals', 'transportation'], 'Lewis County Senior Services Centralia meals transportation case management', 46.7346, -122.9788),
  ('Grays Harbor Senior Services', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Senior Services', 'Services for seniors including meals, transportation, and in-home care.', '110 W Cleveland', 'Aberdeen', 'Grays Harbor', '98520', '(360) 532-0571', 'https://www.ghseniors.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English'], ARRAY['Senior Meals', 'Transportation', 'Case Management', 'In-Home Care'], ARRAY['senior services', 'Aberdeen', 'Grays Harbor', 'meals', 'transportation'], 'Grays Harbor Senior Services Aberdeen meals transportation in-home care', 46.9751, -123.8302),
  -- Meals on Wheels Programs
  ('Meals on Wheels King County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Meals on Wheels', 'Home-delivered meals for homebound seniors.', '220 2nd Ave S', 'Seattle', 'King', '98104', '(206) 436-8800', 'https://www.seniorservices.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English', 'Spanish', 'Chinese', 'Vietnamese'], ARRAY['Home Delivered Meals', 'Senior Nutrition', 'Wellness Checks'], ARRAY['meals on wheels', 'senior meals', 'home delivery', 'Seattle', 'King County'], 'Meals on Wheels King County home delivered meals Seattle nutrition', 47.6205, -122.3272),
  ('Meals on Wheels Spokane', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Meals on Wheels', 'Home meal delivery for seniors in Spokane area.', '1225 N Washington St', 'Spokane', 'Spokane', '99260', '(509) 477-3420', 'https://www.spokanecounty.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, true, false, false, true, false, true, ARRAY['English'], ARRAY['Home Delivered Meals', 'Senior Nutrition', 'Wellness Checks'], ARRAY['meals on wheels', 'senior meals', 'home delivery', 'Spokane'], 'Meals on Wheels Spokane home delivered meals senior nutrition', 47.6684, -117.4048),
  -- Adult Day Programs
  ('Adult Day Health Seattle - Providence', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Adult Day Health', 'Adult day program for seniors and adults with disabilities.', '1801 S Watson St', 'Seattle', 'King', '98108', '(206) 777-7600', 'https://www.providence.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Adult Day Care', 'Memory Care', 'Social Activities', 'Nursing Care'], ARRAY['adult day health', 'adult day care', 'memory care', 'Seattle', 'senior care'], 'Providence Adult Day Health Seattle senior memory care adult day program', 47.5535, -122.3241),
  ('ElderHealth Northwest Adult Day', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Adult Day Health', 'Adult day program with nursing care and social activities.', '4226 Aurora Ave N', 'Seattle', 'King', '98103', '(206) 675-2490', 'https://www.elderhealthnw.org', '{"monday": "7am-6pm", "tuesday": "7am-6pm", "wednesday": "7am-6pm", "thursday": "7am-6pm", "friday": "7am-6pm"}'::jsonb, true, true, true, true, true, false, true, false, false, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Adult Day Care', 'Memory Care', 'Skilled Nursing', 'Social Activities'], ARRAY['adult day health', 'adult day care', 'memory care', 'Seattle', 'skilled nursing'], 'ElderHealth Northwest Adult Day Seattle senior memory care skilled nursing', 47.6570, -122.3345),
  -- Disability Services
  ('Disability Rights Washington', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Disability Services', 'Advocacy and legal services for people with disabilities.', '315 5th Ave S Suite 850', 'Seattle', 'King', '98104', '(206) 324-1521', 'https://www.disabilityrightswa.org', '{"monday": "8:30am-5pm", "tuesday": "8:30am-5pm", "wednesday": "8:30am-5pm", "thursday": "8:30am-5pm", "friday": "8:30am-5pm"}'::jsonb, true, false, false, false, false, false, true, true, true, ARRAY['English', 'Spanish'], ARRAY['Advocacy', 'Legal Services', 'Disability Rights', 'IPE Assistance'], ARRAY['disability rights', 'advocacy', 'legal services', 'Seattle', 'ADA', 'disability'], 'Disability Rights Washington advocacy legal services disability Seattle', 47.5942, -122.3242),
  ('Washington Assistive Technology Act Program', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Disability Services', 'Assistive technology services and device lending for people with disabilities.', '4535 Union Bay Pl NE Suite 100', 'Seattle', 'King', '98105', '(206) 685-4180', 'https://www.watat.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, false, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Assistive Technology', 'Device Lending', 'Training', 'Demonstrations'], ARRAY['assistive technology', 'disability services', 'adaptive technology', 'Seattle'], 'Washington Assistive Technology Act Program disability services device lending', 47.6606, -122.2850),
  ('Downtown Emergency Service Center DESC', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Homeless Services', 'Emergency shelter, housing, and support services for homeless adults.', '517 3rd Ave', 'Seattle', 'King', '98104', '(206) 464-1570', 'https://www.desc.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Emergency Shelter', 'Mental Health', 'Housing', 'Case Management'], ARRAY['homeless shelter', 'emergency shelter', 'housing', 'Seattle', 'mental health'], 'DESC Downtown Emergency Service Center homeless shelter Seattle housing', 47.6004, -122.3289),
  ('Union Gospel Mission Spokane', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Homeless Services', 'Emergency shelter, meals, and recovery programs.', '202 E Trent Ave', 'Spokane', 'Spokane', '99258', '(509) 535-8510', 'https://www.ugmspokane.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, false, false, false, true, true, false, true, ARRAY['English'], ARRAY['Emergency Shelter', 'Hot Meals', 'Recovery Programs', 'Case Management'], ARRAY['homeless shelter', 'emergency shelter', 'Spokane', 'meals', 'recovery'], 'Union Gospel Mission Spokane homeless shelter meals recovery', 47.6530, -117.4076)
) AS data(name, category_id, subcategory, description, address, city, county, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, languages, services, tags, search_text, lat, lng);
