/*
# Add Domestic Violence Shelters & Catholic Charities Offices

1. Data Insert
- Adds domestic violence shelters/programs across WA (Spokane, Yakima, Walla
  Walla, Pullman/Palouse, Stevens County) and Catholic Charities Eastern/Central
  WA regional offices (Spokane, Walla Walla, Wenatchee, Tri-Cities, Yakima).
2. Source
- Verified via WA Eastern District Court DV resources listing, YWCA websites,
  and Catholic Charities Eastern/Central WA websites.
3. Notes
- DV shelters: cost_free=true. Catholic Charities: cost_free=true (most services).
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('YWCA Spokane Domestic Violence Services', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'YWCA Spokane provides 24-hour domestic violence helpline, safe shelter, housing, counseling, legal advocacy, mental health therapy and case management for survivors.', '930 N Monroe St', 'Spokane', 'Spokane', 'WA', '99201', '509-326-2255', 'https://ywcaspokane.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{DV Shelter,Counseling,Legal Advocacy,Mental Health Therapy,Case Management}', '{Domestic Violence}', '{Survivors,Women,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YWCA Yakima Domestic Violence Services', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'Largest provider of domestic violence services in Yakima County. Provides 24-hour crisis hotline, emergency shelter, transitional housing, legal and medical advocacy, support groups and counseling.', '818 W Yakima Ave', 'Yakima', 'Yakima', 'WA', '98902', '509-248-7796', 'https://www.ywcayakima.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{DV Shelter,Counseling,Legal Advocacy,Medical Advocacy,Transitional Housing}', '{Domestic Violence}', '{Survivors,Women,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('YWCA Walla Walla', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'YWCA Walla Walla provides 24-hour crisis line, counseling, support groups, safe shelter, and medical/legal advocacy for survivors of domestic violence, with a Dayton satellite office.', '213 S First St', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-525-2570', 'https://www.ywcaww.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{DV Shelter,Counseling,Legal Advocacy,Medical Advocacy,Support Groups}', '{Domestic Violence}', '{Survivors,Women,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Alternatives to Violence of the Palouse', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'Provides 24-hour advocacy, emergency shelter, support groups and service referrals for survivors of domestic violence and sexual assault in Whitman County and the Palouse region.', '115 NW State St, Room 305A', 'Pullman', 'Whitman', 'WA', '99163', '509-332-4357', 'https://www.atvp.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{DV Shelter,Advocacy,Support Groups,Emergency Shelter}', '{Domestic Violence,Sexual Assault}', '{Survivors,Women,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Stevens Rural Resources Victim Services', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'Provides 24-hour crisis line, crisis intervention, emergency shelter, legal assistance, service referral and support groups for survivors of domestic violence in Stevens County.', '956 S Main St', 'Colville', 'Stevens', 'WA', '99114', '509-684-8421', 'https://www.ruralresources.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{DV Shelter,Crisis Intervention,Legal Assistance,Support Groups}', '{Domestic Violence}', '{Survivors,Women,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('DAWN - Domestic Abuse Women''s Network', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'DAWN provides 24-hour advocacy and support line, emergency shelter, housing, counseling, legal advocacy and community education for survivors of domestic abuse in South King County.', 'PO Box 848', 'Renton', 'King', 'WA', '98057', '425-656-7867', 'https://dawnrising.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{DV Shelter,Counseling,Legal Advocacy,Housing,Community Education}', '{Domestic Violence}', '{Survivors,Women,Families}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lighthouse Domestic Violence Services', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Domestic Violence', 'Provides 24-hour crisis line, medical and legal advocacy, therapy services and support groups for survivors of domestic violence in the Lower Yakima Valley.', 'PO Box 93', 'Sunnyside', 'Yakima', 'WA', '98944', '509-837-6689', 'https://www.thelighthousewa.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Counseling,Legal Advocacy,Medical Advocacy,Support Groups}', '{Domestic Violence}', '{Survivors,Women,Families}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Charities Eastern Washington - Spokane', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Catholic Charities Eastern Washington Family Services Center providing behavioral health, housing, family stabilization, immigration services, and basic needs assistance across Eastern WA.', '12 E 5th Ave', 'Spokane', 'Spokane', 'WA', '99202', '509-358-4250', 'https://www.cceasternwa.org', '{"mon":"9:00-16:00","tue":"9:00-16:00","wed":"9:00-16:00","thu":"9:00-16:00","fri":"9:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Behavioral Health,Housing,Immigration Services,Basic Needs,Family Services}', '{Social Services}', '{General Public,Families,Immigrants}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Charities Walla Walla', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Regional office of Catholic Charities Eastern Washington providing individual/family/group counseling, emergency diaper and layette assistance, volunteer chore services, housing for seniors/veterans, and youth shelter at The LOFT.', '408 W Poplar St', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-525-0572', 'https://www.cceasternwa.org/walla-walla', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Counseling,Housing,Youth Shelter,Basic Needs}', '{Social Services}', '{General Public,Seniors,Veterans,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Charities Serving Central Washington - Wenatchee', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Catholic Charities Central Washington Wenatchee office providing mental health counseling, basic needs assistance, youth independent living services, and family support across Chelan, Douglas, Grant and Okanogan Counties.', '145 S Worthen St', 'Wenatchee', 'Chelan', 'WA', '98801', '509-662-6761', 'https://catholiccharitiescw.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Mental Health Counseling,Basic Needs,Youth Services,Family Support}', '{Social Services}', '{General Public,Families,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Charities Serving Central Washington - Yakima', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Catholic Charities Central Washington Yakima office serving Kittitas, Klickitat and Yakima Counties with mental health counseling, youth and young adult programs, and basic needs services.', '221 S 3rd Ave', 'Yakima', 'Yakima', 'WA', '98902', '509-966-0579', 'https://catholiccharitiescw.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Mental Health Counseling,Youth Services,Basic Needs,Family Support}', '{Social Services}', '{General Public,Families,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Charities Serving Central Washington - Tri-Cities', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Catholic Charities Central Washington Tri-Cities office serving Benton and Franklin Counties with mental health counseling, youth independent living, basic needs, and family support services.', '7101 W Okanogan Pl, Suite A', 'Kennewick', 'Benton', 'WA', '99336', '509-783-3491', 'https://catholiccharitiescw.org/tri-cities', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Mental Health Counseling,Youth Services,Basic Needs,Family Support}', '{Social Services}', '{General Public,Families,Youth}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;