-- Add women's health and maternal care services
INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  data.category_id,
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Prenatal and Maternal Health Services
  ('Open Arms Perinatal Services', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Maternal Health', 'Free doula support, childbirth education, and breastfeeding help for low-income families.', '4001 19th Ave W Suite 200', 'Seattle', 'King', '98199', '(206) 453-8846', 'https://www.openarmsps.org', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Doula Support', 'Childbirth Education', 'Breastfeeding Support'], ARRAY['maternal health', 'doula', 'childbirth', 'breastfeeding', 'free'], 'Open Arms Perinatal Services doula childbirth Seattle free maternal health', 47.6503, -122.3975),
  ('Nurse-Family Partnership King County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'Maternal Health', 'Free home visiting program for first-time mothers. Prenatal support through age 2.', '400 Yesler Way Suite 100', 'Seattle', 'King', '98104', '(206) 263-9000', 'https://www.kingcounty.gov/nfp', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Home Visiting', 'Prenatal Support', 'Parenting Education'], ARRAY['maternal health', 'prenatal', 'home visiting', 'first-time mothers', 'free'], 'Nurse Family Partnership King County prenatal home visiting free maternal', 47.6001, -122.3168),
  ('PeaceHealth St. Joseph Birth Center', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Maternity', 'Family birth center with midwifery services and NICU.', '2901 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 734-5400', 'https://www.peacehealth.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Birth Center', 'Midwifery', 'NICU', 'Labor and Delivery'], ARRAY['birth center', 'maternity', 'Bellingham', 'NICU', 'PeaceHealth'], 'PeaceHealth St Joseph Birth Center maternity midwifery Bellingham NICU', 48.7564, -122.4743),
  ('Yakima Neighborhood Health Maternity', (SELECT id FROM resource_categories WHERE slug = 'fqhc'), 'OB/GYN', 'Prenatal care, OB services, and postpartum support. Sliding scale available.', '1210 S 4th St', 'Yakima', 'Yakima', '98901', '(509) 454-4143', 'https://ynhs.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Prenatal Care', 'OB Services', 'Postpartum Care', 'Womens Health'], ARRAY['prenatal', 'OB/GYN', 'Yakima', 'FQHC', 'sliding scale', 'maternity'], 'Yakima Neighborhood Health Maternity prenatal OB GYN sliding scale', 46.5791, -120.4963),
  ('Tri-Cities Community Health OB/GYN', (SELECT id FROM resource_categories WHERE slug = 'fqhc'), 'OB/GYN', 'Prenatal care, labor and delivery partnerships, womens health.', '5615 W Canal Dr', 'Kennewick', 'Benton', '99336', '(509) 735-3000', 'https://tcch.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Prenatal Care', 'Womens Health', 'OB/GYN'], ARRAY['prenatal', 'OB/GYN', 'Tri-Cities', 'Kennewick', 'FQHC', 'sliding scale'], 'Tri Cities Community Health OB GYN prenatal womens health Kennewick', 46.2116, -119.1863),
  ('Overlake Clinics Womens Health', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'OB/GYN', 'Obstetrics, gynecology, breast health, and midwifery.', '1135 116th Ave NE', 'Bellevue', 'King', '98004', '(425) 688-5000', 'https://www.overlakehospital.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Obstetrics', 'Gynecology', 'Breast Health', 'Midwifery'], ARRAY['OB/GYN', 'womens health', 'Bellevue', 'Overlake', 'maternity'], 'Overlake Clinics Womens Health OB GYN Bellevue maternity midwifery', 47.6267, -122.1862),
  ('EvergreenHealth Womens Health', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'OB/GYN', 'Womens health services including OB, gynecology and breast health.', '12040 Totem Lake Blvd NE', 'Kirkland', 'King', '98034', '(425) 899-4000', 'https://www.evergreenhealth.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['OB/GYN', 'Breast Health', 'Midwifery', 'Womens Health'], ARRAY['OB/GYN', 'womens health', 'Kirkland', 'EvergreenHealth', 'maternity'], 'EvergreenHealth Womens Health OB GYN Kirkland maternity breast health', 47.7065, -122.1879),
  ('MultiCare Womens Health Puyallup', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'OB/GYN', 'Comprehensive womens health and maternity services.', '11102 168th St E', 'Puyallup', 'Pierce', '98375', '(253) 792-6660', 'https://www.multicare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['OB/GYN', 'Maternity', 'Womens Health'], ARRAY['OB/GYN', 'womens health', 'Puyallup', 'MultiCare', 'maternity'], 'MultiCare Womens Health OB GYN Puyallup maternity', 47.1441, -122.2923),
  ('PeaceHealth Womens Health Vancouver', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'OB/GYN', 'Obstetrics and gynecology care.', '3400 Main St', 'Vancouver', 'Clark', '98663', '(360) 514-2229', 'https://www.peacehealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['OB/GYN', 'Maternity', 'Womens Health'], ARRAY['OB/GYN', 'womens health', 'Vancouver', 'PeaceHealth', 'maternity'], 'PeaceHealth Womens Health Vancouver OB GYN maternity', 45.6407, -122.6645),
  -- WIC Programs
  ('WIC Program Seattle - King County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Women, Infants, and Children nutrition program. Free healthy foods, nutrition education, breastfeeding support.', '401 5th Ave N Suite 300', 'Seattle', 'King', '98109', '(206) 263-9000', 'https://www.kingcounty.gov/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish', 'Somali', 'Vietnamese', 'Chinese'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Seattle'], 'WIC Program Seattle King County nutrition pregnancy infants children free', 47.6215, -122.3479),
  ('WIC Program Spokane', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition program for pregnant women and children under 5.', '1101 E College Ave', 'Spokane', 'Spokane', '99207', '(509) 324-1620', 'https://srhd.org/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Spokane'], 'WIC Program Spokane nutrition pregnancy infants children free', 47.7045, -117.4093),
  ('WIC Program Tacoma - Pierce County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition assistance for pregnant women, infants and children.', '3629 S D St', 'Tacoma', 'Pierce', '98408', '(253) 798-6450', 'https://www.tpchd.org/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, true, true, false, true, ARRAY['English', 'Spanish', 'Korean', 'Vietnamese'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Tacoma'], 'WIC Program Tacoma Pierce County nutrition pregnancy infants children free', 47.2441, -122.4396),
  ('WIC Program Yakima County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition support for women and young children.', '111 W Walnut St', 'Yakima', 'Yakima', '98902', '(509) 249-2141', 'https://www.yakimacounty.us/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Yakima'], 'WIC Program Yakima County nutrition pregnancy infants children free', 46.6021, -120.5058),
  ('WIC Program Snohomish County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition program for pregnant women, infants and children under 5.', '3020 Rucker Ave', 'Everett', 'Snohomish', '98201', '(425) 252-5312', 'https://www.snohd.org/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish', 'Russian', 'Chinese'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Everett'], 'WIC Program Snohomish County Everett nutrition pregnancy infants children free', 47.9685, -122.1986),
  ('WIC Program Clark County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition assistance for women, infants and children.', '1601 E Fourth Plain Blvd', 'Vancouver', 'Clark', '98661', '(564) 397-8080', 'https://www.clark.wa.gov/public-health/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Vancouver'], 'WIC Program Clark County Vancouver nutrition pregnancy infants children free', 45.6317, -122.6542),
  ('WIC Program Thurston County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition program for pregnant women and children.', '412 Lilly Rd NE', 'Olympia', 'Thurston', '98506', '(360) 867-2515', 'https://www.thurstoncountywa.gov/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Olympia'], 'WIC Program Thurston County Olympia nutrition pregnancy infants children free', 47.0457, -122.8258),
  ('WIC Program Benton-Franklin Counties', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition assistance for Benton and Franklin county families.', '4717 W Okanogan Pl', 'Kennewick', 'Benton', '99336', '(509) 460-4200', 'https://www.bfhd.wa.gov/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Kennewick', 'Tri-Cities'], 'WIC Program Benton Franklin Counties Kennewick nutrition pregnancy infants children free', 46.2241, -119.1826),
  ('WIC Program Whatcom County', (SELECT id FROM resource_categories WHERE slug = 'community-resources'), 'WIC', 'Nutrition program for pregnant women and children under 5.', '509 Girard St', 'Bellingham', 'Whatcom', '98225', '(360) 778-6000', 'https://www.whatcomcounty.us/wic', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Nutrition Assistance', 'Breastfeeding Support', 'Healthy Foods'], ARRAY['WIC', 'nutrition', 'pregnancy', 'infants', 'children', 'free', 'Bellingham'], 'WIC Program Whatcom County Bellingham nutrition pregnancy infants children free', 48.7465, -122.4780)
) AS data(name, category_id, subcategory, description, address, city, county, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, languages, services, tags, search_text, lat, lng);
