/*
# Add Washington Senior Centers

1. Data Insert
- Adds senior centers across Washington State counties (source: WSASC master list).
- Includes Bellingham, Kirkland, White Salmon (Klickitat), Lakewood, Leavenworth,
  Lewis County, Longview, Mount Vernon, Moses Lake, Lind, Lynden, Kingston, and
  others.
2. Source
- Verified via Washington State Association of Senior Centers directory and
  county senior services listings.
3. Notes
- Senior centers: cost_free=true (donation-based programs); community-org category.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Bellingham Senior Activity Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Whatcom County senior activity center providing meals, fitness classes, social activities, transportation assistance, Medicare counseling and wellness programs for adults 50+.', '315 Halleck St', 'Bellingham', 'Whatcom', 'WA', '98225', '360-733-4030', 'https://www.whatcomcounty.us/1023/Senior-Centers', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Fitness,Social Activities,Transportation,Medicare Counseling}', '{Senior Services}', '{Seniors}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Kirkland Senior Community Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Kirkland senior community center providing meals, classes, social events and supportive services for older adults on the Eastside.', '352 Kirkland Ave', 'Kirkland', 'King', 'WA', '98033', '425-828-1223', 'https://www.kirklandwa.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Classes,Social Events,Supportive Services}', '{Senior Services}', '{Seniors}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Klickitat County Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Klickitat County senior center in White Salmon providing meals, social activities, transportation, information and assistance for older adults.', '157 NE East Ave', 'White Salmon', 'Klickitat', 'WA', '98672', '509-493-3068', 'https://www.klickitatcounty.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Transportation,Information Assistance}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lakewood Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Lakewood senior center providing congregate meals, fitness and wellness programs, social activities, and information/referral services for Pierce County seniors.', '9112 Lakewood Dr SW', 'Tacoma', 'Pierce', 'WA', '98499', '253-589-5735', 'https://www.cityoflakewood.us', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Fitness,Wellness,Social Activities,Information Referral}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Leavenworth Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Leavenworth senior center serving upper Chelan County with meals, social activities, and community engagement for older adults.', '423 Evans St', 'Leavenworth', 'Chelan', 'WA', '98826', '509-548-6666', 'https://www.leavenworthseniorcenter.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Community Engagement}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lewis County Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Lewis County senior and recreation center providing meals, fitness, social activities, transportation and information assistance for older adults in Chehalis.', '360 NW North St', 'Chehalis', 'Lewis', 'WA', '98532', '360-748-9121', 'https://www.lewiscountywa.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Meals,Fitness,Social Activities,Transportation,Information Assistance}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Longview Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Longview senior center providing congregate meals, wellness programs, social activities, and information/referral services for older adults in Cowlitz County.', '1111 Commerce St', 'Longview', 'Cowlitz', 'WA', '98632', '360-636-0210', 'https://www.mylongview.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Wellness,Social Activities,Information Referral}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Mount Vernon Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Mount Vernon senior center providing meals, fitness classes, social activities, and supportive services for older adults in Skagit County.', '1401 Cleveland St', 'Mount Vernon', 'Skagit', 'WA', '98273', '360-336-5757', 'https://www.mountvernonwa.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Meals,Fitness,Social Activities,Supportive Services}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Moses Lake Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Moses Lake senior center providing meals, wellness programs, social activities, and information/referral services for older adults in Grant County.', '1800 S Beech St', 'Moses Lake', 'Grant', 'WA', '98837', '509-765-7809', 'https://www.cityofmoseslake.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Meals,Wellness,Social Activities,Information Referral}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Kingston Senior Community Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Kingston senior community center providing meals, social activities, and supportive services for older adults in north Kitsap County.', '11212 NE State Highway 104', 'Kingston', 'Kitsap', 'WA', '98346', '360-297-2150', 'https://www.kitsapgov.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Supportive Services}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lacey Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Lacey senior center providing congregate meals, fitness and wellness classes, social activities, and Medicare counseling for older adults in Thurston County.', '6757 Pacific Ave SE', 'Lacey', 'Thurston', 'WA', '98503', '360-407-3967', 'https://www.ci.lacey.wa.us', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Fitness,Wellness,Social Activities,Medicare Counseling}', '{Senior Services}', '{Seniors}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lynden Community Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Lynden community center for older adults providing meals, social activities, and community programs in northern Whatcom County.', '401 Grover St', 'Lynden', 'Whatcom', 'WA', '98264', '360-354-4501', 'https://www.ci.lynden.wa.us', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Community Programs}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lind Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Lind senior center serving older adults in rural Adams County with meals, social activities, and community programming.', '117 N I St', 'Lind', 'Adams', 'WA', '99341', '509-677-3620', 'https://www.lindwa.gov', '{"mon":"8:00-12:00","tue":"8:00-12:00","wed":"8:00-12:00","thu":"8:00-12:00","fri":"8:00-12:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Community Programs}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lopez Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Lopez Island senior center providing meals, social activities, and supportive services for older adults in the San Juan Islands.', '2228 Fisherman Bay Rd', 'Lopez Island', 'San Juan', 'WA', '98261', '360-468-2421', 'https://www.lopezislandlibrary.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Supportive Services}', '{Senior Services}', '{Seniors}', 4.5, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Greater Maple Valley Senior Center', (SELECT id FROM resource_categories WHERE slug='community-org'), 'Senior Center', 'Greater Maple Valley senior center providing meals, social activities, and supportive services for older adults in southeast King County.', '25700 SE 216th St', 'Maple Valley', 'King', 'WA', '98038', '425-432-1272', 'https://www.maplevalleywa.gov', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Meals,Social Activities,Supportive Services}', '{Senior Services}', '{Seniors}', 4.0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;