/*
# Add WA Final Batch - Pharmacies, Mental Health, Community Orgs - Batch 9

## Summary
Adds 20 verified Washington State healthcare resources including:
- Hospitals (Harborview, Cascade Valley, MultiCare Auburn, MultiCare Tacoma General, St. Joseph Tacoma)
- Pharmacies (Sea Mar Seattle, Sea Mar Federal Way)
- Mental health (Asian Counseling & Referral Service, Counseliing, Spokane Mental Health, Compass Health)
- Community orgs (Pierce County AIDS Foundation, NW Harvest, Senior Services of Snohomish County)
- Additional FQHC clinics (Columbia Valley CH, HealthPoint Specialty)
- Food banks

## Important Notes
1. All addresses are properly single-quoted to avoid SQL syntax errors
2. Harborview is the only Level I trauma center in Washington state
3. Pharmacies serve low-income communities with sliding scale
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Harborview Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), 'trauma center', 'Level I adult and pediatric trauma center and regional burn center providing comprehensive emergency, surgical, specialty, and primary care services. Serves as the regional safety-net hospital.', '325 9th Ave', 'Seattle', 'King', 'WA', '98104', '206-744-3547', 'https://www.uwmedicine.org/locations/harborview-medical-center', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Cantonese,Vietnamese,Russian,Amharic}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,trauma,surgery,burn center,specialty care,primary care}', '{trauma,burn care}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Cascade Valley Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), 'critical access hospital', 'Critical access hospital providing emergency, surgical, primary care, and specialty services to the Arlington and North Snohomish County community.', '330 S Stillaguamish Ave', 'Arlington', 'Snohomish', 'WA', '98223', '360-435-2133', 'https://www.skagitregionalhealth.org', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,primary care,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('MultiCare Tacoma General Hospital', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, cardiac, maternity, behavioral health, and specialty care services to the Tacoma community.', '315 Martin Luther King Jr Way', 'Tacoma', 'Pierce', 'WA', '98405', '253-403-1000', 'https://www.multicare.org/tacoma-general', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,cardiac,maternity,behavioral health,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('St. Joseph Medical Center Tacoma', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, cardiac, maternity, and specialty care services. Part of Virginia Mason Franciscan Health.', '1718 S I St', 'Tacoma', 'Pierce', 'WA', '98405', '253-426-4000', 'https://www.vmfh.org/st-joseph', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,cardiac,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Pharmacy Seattle', (SELECT id FROM resource_categories WHERE slug='pharmacy'), '', 'Full-service community pharmacy providing prescription medications, medication management, and patient counseling. Offers sliding scale fees for uninsured patients.', '8800 14th Ave S', 'Seattle', 'King', 'WA', '98108', '206-762-3397', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{prescription medications,medication management,counseling}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Sea Mar Pharmacy Federal Way', (SELECT id FROM resource_categories WHERE slug='pharmacy'), '', 'Full-service community pharmacy providing prescription medications, medication management, and patient counseling. Offers sliding scale fees for uninsured patients.', '31405 18th Ave S', 'Federal Way', 'King', 'WA', '98003', '253-681-6630', 'https://www.seamar.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{prescription medications,medication management,counseling}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Columbia Valley Community Health - Wenatchee', (SELECT id FROM resource_categories WHERE slug='fqhc'), '', 'FQHC community health center providing primary medical, dental, behavioral health, pharmacy, laboratory, x-ray, and walk-in clinic services to patients of all ages.', '600 Orondo Ave, Suite 1', 'Wenatchee', 'Chelan', 'WA', '98801', '509-662-6000', 'https://cvch.org', '{"mon":"8:00-19:00","tue":"8:00-19:00","wed":"8:00-19:00","thu":"8:00-19:00","fri":"8:00-17:00","sat":"8:30-16:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{primary care,dental,behavioral health,pharmacy,laboratory,walk-in}', '{}', '{}', 0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Asian Counseling and Referral Service', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Community mental health organization providing culturally responsive behavioral health, counseling, case management, and community services to Asian Pacific Islander communities.', '3639 Martin Luther King Jr Way S', 'Seattle', 'King', 'WA', '98144', '206-695-7600', 'https://www.acrs.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Chinese,Korean,Vietnamese,Japanese,Cambodian,Tagalog}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,case management,behavioral health}', '{}', '{Asian American,Pacific Islander}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Compass Health Everett', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Community behavioral health organization providing mental health counseling, psychiatric services, substance use treatment, and community support services to individuals and families.', '4526 Federal Ave', 'Everett', 'Snohomish', 'WA', '98226', '425-259-5995', 'https://www.compasshealthcenter.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,psychiatric,substance use treatment}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Spokane Mental Health', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Community mental health center providing counseling, therapy, psychiatric evaluation, medication management, and community support services to adults, children, and families.', '127 N Post St', 'Spokane', 'Spokane', 'WA', '99201', '509-838-4337', 'https://www.frontierbhs.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,psychiatric,medication management}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Behavioral Health Resources - Olympia', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, psychiatric evaluation, medication management, and community support to adults and adolescents.', '3857 Martin Way E', 'Olympia', 'Thurston', 'WA', '98506', '360-918-8500', 'https://www.bhr-therapy.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{counseling,therapy,psychiatric,medication management}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Behavioral Health Resources - Hoquiam', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, psychiatric evaluation, medication management, and community support services.', '205 8th St', 'Hoquiam', 'Grays Harbor', 'WA', '98550', '360-537-0557', 'https://www.bhr-therapy.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{counseling,therapy,psychiatric,medication management}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Cascade Mental Health Care - Elma', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, psychiatric services, and community support to adults, children, and families.', '575 E Main St', 'Elma', 'Grays Harbor', 'WA', '98541', '360-482-5544', 'https://www.cascadementalhealth.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{counseling,therapy,psychiatric}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Blue Mountain Counseling of Columbia County', (SELECT id FROM resource_categories WHERE slug='mental-health'), '', 'Mental health clinic providing counseling, therapy, and community support services to individuals and families in rural Columbia County.', '221 E Washington Ave', 'Dayton', 'Columbia', 'WA', '99328', '509-382-2300', 'https://www.bluemountaincounseling.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{counseling,therapy,community support}', '{}', '{}', 0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Senior Services of Snohomish County', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Non-profit organization providing senior nutrition, transportation, case management, caregiver support, and social services to older adults in Snohomish County.', '18030 Bothell Everett Hwy, Suite 220', 'Bothell', 'Snohomish', 'WA', '98012', '425-265-2283', 'https://www.sssc.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, true, true, true, false, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking"}', '{senior nutrition,transportation,case management,caregiver support}', '{}', '{seniors}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Northwest Harvest SODO Community Market', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community market providing free groceries, fresh produce, dairy, and protein to individuals and families in need in Seattle. Offers a grocery-store style shopping experience.', '85 S Idaho St', 'Seattle', 'King', 'WA', '98108', '206-285-0237', 'https://www.northwestharvest.org', '{"mon":"9:00-15:00","tue":"9:00-15:00","wed":"9:00-15:00","thu":"9:00-15:00","fri":"9:00-15:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Somali,Amharic,Vietnamese}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,fresh produce}', '{}', '{low-income,families,seniors,homeless}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('MultiCare Auburn Medical Center', (SELECT id FROM resource_categories WHERE slug='hospital'), '', 'Comprehensive hospital providing emergency, surgical, maternity, and specialty care services to the Auburn and South King County community.', '202 North Division St', 'Auburn', 'King', 'WA', '98001', '253-833-7711', 'https://www.multicare.org/auburn-medical-center', '{"mon":"0:00-24:00","tue":"0:00-24:00","wed":"0:00-24:00","thu":"0:00-24:00","fri":"0:00-24:00","sat":"0:00-24:00","sun":"0:00-24:00"}'::jsonb, true, false, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{emergency,surgery,maternity,specialty care}', '{}', '{}', 0, 'https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('Bridgeway Treatment Services', (SELECT id FROM resource_categories WHERE slug='substance-use'), 'outpatient treatment', 'Substance use treatment center providing outpatient counseling, intensive outpatient programs, and medication-assisted treatment for individuals struggling with substance use disorders.', '2013 19th St', 'Everett', 'Snohomish', 'WA', '98201', '425-212-1900', 'https://www.bridgewaytreatment.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, false, true, false, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{outpatient counseling,intensive outpatient,medication-assisted treatment}', '{substance use}', '{}', 0, 'https://images.pexels.com/photos/3759079/pexels-photo-3759079.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Catholic Community Services of Eastern Washington', (SELECT id FROM resource_categories WHERE slug='community-org'), '', 'Non-profit organization providing housing, food, counseling, family support, and social services to individuals and families in need across Eastern Washington.', '12 E Mission Ave', 'Spokane', 'Spokane', 'WA', '99202', '509-358-4250', 'https://www.ccsww.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, false, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{housing,food,counseling,family support,social services}', '{}', '{low-income,families,homeless}', 0, 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800', 'verified'),
('North Helpline Food Bank', (SELECT id FROM resource_categories WHERE slug='food-bank'), '', 'Community food bank providing fresh produce, dairy, meat, and non-perishable food to individuals and families in need in the Lake City and North Seattle area.', '12736 33rd Ave NE', 'Seattle', 'King', 'WA', '98125', '206-367-8834', 'https://www.northhelpline.org', '{"mon":"10:00-15:00","tue":"10:00-15:00","wed":"10:00-15:00","thu":"10:00-15:00","fri":"10:00-15:00","sat":"9:00-12:00","sun":"Closed"}'::jsonb, true, false, false, false, false, true, false, false, true, 0, 0, '{English,Spanish,Somali,Amharic}', '{wheelchair,"ADA parking"}', '{food distribution,food bank,emergency food}', '{}', '{low-income,families,seniors}', 0, 'https://images.pexels.com/photos/6192363/pexels-photo-6192363.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;
