/*
# Add Additional FQHCs and Community Health Centers Batch 1

1. Purpose
   - Add FQHCs and free/low-cost clinics across Washington
   - Focus on underserved areas and missing providers

2. Coverage
   - Additional Sea Mar locations, CHAS, YVFWC, and independent FQHCs
*/

INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  (SELECT id FROM resource_categories WHERE slug = 'fqhc'),
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  ('Sea Mar Community Health Center - Wenatchee', 'FQHC', 'Bilingual community health center with medical, dental, and behavioral health. Sliding scale fees available.', '1408 N Miller St', 'Wenatchee', 'Chelan', '98801', '(509) 663-2828', 'https://seamar.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health', 'Pharmacy'], ARRAY['FQHC', 'sliding scale', 'Sea Mar', 'Spanish', 'bilingual'], 'FQHC Sea Mar Wenatchee sliding scale bilingual', 47.4404, -120.3148),
  ('Sea Mar Community Health Center - Pasco', 'FQHC', 'Full service community health center serving Tri-Cities area. Medical, dental, behavioral health.', '1333 W Sylvester St', 'Pasco', 'Franklin', '99301', '(509) 547-2209', 'https://seamar.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'Sea Mar', 'Spanish'], 'FQHC Sea Mar Pasco Tri-Cities sliding scale', 46.2304, -119.1017),
  ('Sea Mar Community Health Center - South Sound', 'FQHC', 'Community health center serving Lacey and Olympia area with comprehensive services.', '4510 Intelco Loop SE', 'Lacey', 'Thurston', '98503', '(360) 923-1170', 'https://seamar.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'Sea Mar', 'Spanish'], 'FQHC Sea Mar South Sound Lacey Olympia', 47.0326, -122.8151),
  ('Sea Mar Community Health Center - Marysville', 'FQHC', 'Community health center serving Snohomish County with medical and dental care.', '8414 51st Ave NE', 'Marysville', 'Snohomish', '98270', '(360) 658-8800', 'https://seamar.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental'], ARRAY['FQHC', 'sliding scale', 'Sea Mar', 'Spanish'], 'FQHC Sea Mar Marysville Snohomish', 48.0512, -122.1689),
  ('Sea Mar Community Health Center - Walla Walla', 'FQHC', 'Community health center providing medical, dental, and behavioral health services.', '1334 W Alder St', 'Walla Walla', 'Walla Walla', '99362', '(509) 525-4900', 'https://seamar.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'Sea Mar', 'Spanish'], 'FQHC Sea Mar Walla Walla sliding scale', 46.0672, -118.3569),
  ('CHAS Health - Deer Park', 'FQHC', 'Community health center with medical, dental, and pharmacy services. Sliding scale available.', '110 S Colville St', 'Deer Park', 'Spokane', '99206', '(509) 474-4900', 'https://chas.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Russian'], ARRAY['Primary Care', 'Dental', 'Pharmacy'], ARRAY['FQHC', 'sliding scale', 'CHAS'], 'FQHC CHAS Health Deer Park Spokane sliding scale', 47.9596, -117.4799),
  ('CHAS Health - Pullman', 'FQHC', 'Community health center serving Whitman County with medical and behavioral health.', '950 NE Merman Dr', 'Pullman', 'Whitman', '99163', '(509) 334-3288', 'https://chas.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'CHAS'], 'FQHC CHAS Health Pullman Whitman', 46.7340, -117.1430),
  ('Yakima Valley Farm Workers Clinic - Grandview', 'FQHC', 'Bilingual community health center serving Lower Valley. Medical, dental, behavioral health.', '401 W Wine Country Rd', 'Grandview', 'Yakima', '98930', '(509) 882-2754', 'https://yvfwc.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health', 'Pharmacy'], ARRAY['FQHC', 'sliding scale', 'YVFWC', 'Spanish', 'bilingual'], 'FQHC YVFWC Grandview Yakima Valley sliding scale', 46.2559, -119.9054),
  ('Yakima Valley Farm Workers Clinic - Prosser', 'FQHC', 'Community health center with primary care, dental, and behavioral health.', '1320 Paterson Rd', 'Prosser', 'Benton', '99350', '(509) 786-2505', 'https://yvfwc.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'YVFWC', 'Spanish'], 'FQHC YVFWC Prosser Benton sliding scale', 46.2054, -119.7691),
  ('Yakima Valley Farm Workers Clinic - Pasco Community', 'FQHC', 'Community health center providing comprehensive services to Tri-Cities.', '5402 W Court St', 'Pasco', 'Franklin', '99301', '(509) 545-2233', 'https://yvfwc.com', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "8am-12pm", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health', 'Pharmacy'], ARRAY['FQHC', 'sliding scale', 'YVFWC', 'Spanish'], 'FQHC YVFWC Pasco Community Tri-Cities sliding scale', 46.2315, -119.1200),
  ('Community Health Center of the Valleys - Kennewick', 'FQHC', 'Community health center serving Tri-Cities with primary and behavioral health care.', '420 W Kennewick Ave', 'Kennewick', 'Benton', '99336', '(509) 735-8900', 'https://chcvalleys.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Community Health Center Valleys Kennewick', 46.2110, -119.1167),
  ('Kittitas Valley Community Health Center', 'FQHC', 'Community health center serving Ellensburg area with sliding scale fees.', '506 N Pine St', 'Ellensburg', 'Kittitas', '98926', '(509) 933-1800', 'https://kvch.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Kittitas Valley Community Health Ellensburg', 46.9953, -120.5370),
  ('Northwest Community Health Center - Moses Lake', 'FQHC', 'Community health center with medical, dental, and behavioral health services.', '605 S Sherman St', 'Moses Lake', 'Grant', '98837', '(509) 765-0674', 'https://nwchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Northwest Community Health Moses Lake Grant', 47.1231, -119.2787),
  ('Family Health Center - Aberdeen', 'FQHC', 'Community health center serving Grays Harbor with sliding scale fees.', '1300 Sumner Ave', 'Aberdeen', 'Grays Harbor', '98520', '(360) 533-2948', 'https://fhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Family Health Center Aberdeen Grays Harbor', 46.9735, -123.8147),
  ('Family Health Center - Elma', 'FQHC', 'Community health center serving East Grays Harbor County.', '508 W Wynochee Ave', 'Elma', 'Grays Harbor', '98541', '(360) 482-2700', 'https://fhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental'], ARRAY['FQHC', 'sliding scale'], 'FQHC Family Health Center Elma Grays Harbor', 47.0054, -123.4063),
  ('Cowlitz Family Health Center - Longview', 'FQHC', 'Community health center with sliding scale for Cowlitz County residents.', '1200 14th Ave', 'Longview', 'Cowlitz', '98632', '(360) 577-7924', 'https://cowlitzfhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Cowlitz Family Health Center Longview', 46.1378, -122.9312),
  ('Clark County Family Health Center - Vancouver', 'FQHC', 'Community health center with primary care, dental, and substance use treatment.', '311 NE 138th Ave', 'Vancouver', 'Clark', '98684', '(360) 944-8900', 'https://ccfhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Russian'], ARRAY['Primary Care', 'Dental', 'Substance Use Treatment'], ARRAY['FQHC', 'sliding scale'], 'FQHC Clark County Family Health Vancouver', 45.6221, -122.5477),
  ('Snohomish Community Health Center - Everett', 'FQHC', 'Community health center providing primary care, dental, and behavioral health.', '1124 SE Everett Mall Way', 'Everett', 'Snohomish', '98208', '(425) 227-2100', 'https://schc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Snohomish Community Health Everett', 47.9634, -122.1998),
  ('Moses Lake Community Health Center - Othello', 'FQHC', 'Community health center serving Adams County with bilingual services.', '725 E Larch St', 'Othello', 'Adams', '99344', '(509) 488-2600', 'https://mlchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale', 'Spanish'], 'FQHC Moses Lake Community Health Othello Adams', 46.8258, -119.1725),
  ('North Central Washington Community Health Center - Omak', 'FQHC', 'Community health center serving Okanogan County with primary care.', '918 E Main Ave', 'Omak', 'Okanogan', '98841', '(509) 826-7200', 'https://ncwchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC NCW Community Health Omak Okanogan', 48.4106, -119.5256),
  ('North Central Washington Community Health Center - Okanogan', 'FQHC', 'Community health center serving Okanogan Valley.', '1208 Hawthorne Ave', 'Okanogan', 'Okanogan', '98840', '(509) 422-5700', 'https://ncwchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Dental'], ARRAY['FQHC', 'sliding scale'], 'FQHC NCW Community Health Okanogan', 48.3659, -119.5839),
  ('Benton Franklin Community Health Center - Richland', 'FQHC', 'Community health center with primary care and family planning.', '730 Swift Blvd', 'Richland', 'Benton', '99352', '(509) 946-8632', 'https://bfhc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Family Planning'], ARRAY['FQHC', 'sliding scale'], 'FQHC Benton Franklin Community Health Richland', 46.2800, -119.2810),
  ('Whatcom Community Health Center - Ferndale', 'FQHC', 'Community health center serving northern Whatcom County.', '5620 2nd Ave', 'Ferndale', 'Whatcom', '98248', '(360) 384-5500', 'https://wchc.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Primary Care', 'Behavioral Health'], ARRAY['FQHC', 'sliding scale'], 'FQHC Whatcom Community Health Ferndale', 48.8511, -122.5906),
  ('Jefferson Community Health Center - Chimacum', 'FQHC', 'Community health center serving East Jefferson County.', '335 Chimacum Rd', 'Chimacum', 'Jefferson', '98325', '(360) 732-0300', 'https://jeffersonhealthcare.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Dental'], ARRAY['FQHC', 'sliding scale'], 'FQHC Jefferson Community Health Chimacum', 47.9984, -122.8735),
  ('San Juan Community Health Center - Friday Harbor', 'FQHC', 'Community health center serving San Juan Islands.', '445 Spring St', 'Friday Harbor', 'San Juan', '98250', '(360) 378-1333', 'https://sanjuanhealth.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm", "saturday": "closed", "sunday": "closed"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Telehealth'], ARRAY['FQHC', 'sliding scale', 'islands'], 'FQHC San Juan Community Health Friday Harbor', 48.5345, -123.0192)
) AS data(
  name, subcategory, description, address, city, county, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
);
