-- Add vision, dialysis, hospice, and additional rural services
INSERT INTO resources (
  name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours,
  accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth,
  cost_free, languages, services, tags, search_text, lat, lng
)
SELECT
  data.name,
  data.category_id,
  data.subcategory,
  data.description,
  data.address,
  data.city,
  data.county,
  'WA',
  data.zip_code,
  data.phone,
  data.website,
  data.hours,
  data.accepts_uninsured,
  data.sliding_scale,
  data.medicaid,
  data.medicare,
  data.private_insurance,
  data.walk_ins_welcome,
  data.appointments,
  data.telehealth,
  data.cost_free,
  data.languages,
  data.services,
  data.tags,
  data.search_text,
  data.lat,
  data.lng
FROM (VALUES
  -- Vision Services
  ('Vision USA - Washington', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Vision', 'Free eye exams and glasses for low-income individuals. Must qualify through application.', 'PO Box 15246', 'Seattle', 'King', '98115', '(206) 527-5566', 'https://www.visionusa.org', '{"monday": "9am-4pm", "tuesday": "9am-4pm", "wednesday": "9am-4pm", "thursday": "9am-4pm", "friday": "9am-4pm"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English', 'Spanish'], ARRAY['Eye Exams', 'Eyeglasses', 'Vision Care'], ARRAY['vision', 'eye exam', 'glasses', 'free', 'low income', 'Seattle'], 'Vision USA Washington free eye exam glasses low income Seattle', 47.6819, -122.3186),
  ('Lions Club Vision Program - Washington', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Vision', 'Free vision screening and assistance with glasses for those in need.', 'Various Locations', 'Seattle', 'King', '98101', '(206) 623-5646', 'https://lionsclubs.org', '{"monday": "varies", "tuesday": "varies", "wednesday": "varies", "thursday": "varies", "friday": "varies"}'::jsonb, true, true, false, false, false, false, true, false, true, ARRAY['English'], ARRAY['Vision Screening', 'Eyeglasses Assistance'], ARRAY['vision', 'eye screening', 'glasses', 'free', 'Lions Club', 'Seattle'], 'Lions Club Vision Program free vision screening glasses Seattle', 47.6062, -122.3321),
  ('Puget Sound Lions Eye Bank', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Vision', 'Corneal tissue for transplant surgeries. Works with eye donors.', '750 Harvard Ave E', 'Seattle', 'King', '98102', '(206) 598-5500', 'https://www.psleb.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, false, false, false, true, true, false, true, false, false, ARRAY['English'], ARRAY['Corneal Transplant', 'Eye Donation', 'Tissue Banking'], ARRAY['cornea transplant', 'eye bank', 'tissue donation', 'Seattle'], 'Puget Sound Lions Eye Bank corneal transplant tissue donation Seattle', 47.6245, -122.3198),
  ('Sight Connection', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Vision', 'Vision rehabilitation services for people with low vision or blindness.', '4452 Corson Ave S', 'Seattle', 'King', '98108', '(206) 325-1610', 'https://www.sightconnection.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English', 'Spanish', 'Chinese'], ARRAY['Vision Rehabilitation', 'Low Vision Services', 'Independent Living'], ARRAY['low vision', 'blindness', 'vision rehabilitation', 'Seattle', 'adaptive technology'], 'Sight Connection vision rehabilitation low vision blindness Seattle', 47.5506, -122.3144),
  ('Bainbridge Vision Source', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Vision', 'Comprehensive eye care and eyewear boutique.', '256 Madisen Lane', 'Bainbridge Island', 'Kitsap', '98110', '(206) 842-4575', 'https://www.bainbridgevisionsource.com', '{"monday": "9am-5pm", "tuesday": "9am-5pm", "wednesday": "9am-5pm", "thursday": "9am-5pm", "friday": "9am-5pm", "saturday": "9am-1pm"}'::jsonb, false, false, false, true, true, false, true, false, false, ARRAY['English'], ARRAY['Eye Exams', 'Contact Lenses', 'Eyeglasses'], ARRAY['vision', 'eye exam', 'Bainbridge Island', 'optometry'], 'Bainbridge Vision Source eye exam eyeglasses Bainbridge Island', 47.6265, -122.5198),
  -- Dialysis Centers
  ('DaVita Seattle Dialysis', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Outpatient hemodialysis services for kidney disease patients.', '7500 MLK Jr Way S', 'Seattle', 'King', '98118', '(206) 723-3700', 'https://www.davita.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm", "saturday": "6am-12pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Seattle', 'DaVita'], 'DaVita Seattle Dialysis hemodialysis kidney disease Seattle', 47.5304, -122.2700),
  ('DaVita Tacoma Dialysis', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Outpatient dialysis center serving Tacoma and Pierce County.', '1901 S Union Ave Suite 103', 'Tacoma', 'Pierce', '98405', '(253) 473-3320', 'https://www.davita.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Tacoma', 'DaVita'], 'DaVita Tacoma Dialysis hemodialysis kidney disease Tacoma', 47.2554, -122.4706),
  ('DaVita Spokane Dialysis Center', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Comprehensive dialysis services for Spokane area.', '2003 E Holland Ave', 'Spokane', 'Spokane', '99218', '(509) 487-2111', 'https://www.davita.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Spokane', 'DaVita'], 'DaVita Spokane Dialysis Center hemodialysis kidney disease Spokane', 47.7006, -117.3762),
  ('Fresenius Kidney Care Vancouver', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Outpatient dialysis center serving Clark County.', '6101 NE 63rd St', 'Vancouver', 'Clark', '98661', '(360) 696-8823', 'https://www.freseniuskidneycare.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Vancouver', 'Fresenius'], 'Fresenius Kidney Care Vancouver dialysis hemodialysis Clark County', 45.6512, -122.5818),
  ('Fresenius Kidney Care Everett', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Dialysis services for Snohomish County patients.', '1020 128th St SW Suite B', 'Everett', 'Snohomish', '98208', '(425) 355-3805', 'https://www.freseniuskidneycare.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Everett', 'Fresenius'], 'Fresenius Kidney Care Everett dialysis hemodialysis Snohomish County', 47.8834, -122.2230),
  ('DaVita Tri-Cities Dialysis', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Dialysis center serving Kennewick, Pasco, Richland area.', '4315 W 24th Ave', 'Kennewick', 'Benton', '99337', '(509) 783-1700', 'https://www.davita.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Tri-Cities', 'Kennewick', 'DaVita'], 'DaVita Tri Cities Dialysis hemodialysis kidney disease Kennewick', 46.1969, -119.1538),
  ('Fresenius Kidney Care Yakima', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Dialysis', 'Outpatient dialysis services for Yakima Valley.', '806 S 44th Ave', 'Yakima', 'Yakima', '98908', '(509) 965-3610', 'https://www.freseniuskidneycare.com', '{"monday": "6am-6pm", "tuesday": "6am-6pm", "wednesday": "6am-6pm", "thursday": "6am-6pm", "friday": "6am-6pm"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hemodialysis', 'Kidney Care', 'Dialysis'], ARRAY['dialysis', 'kidney disease', 'hemodialysis', 'Yakima', 'Fresenius'], 'Fresenius Kidney Care Yakima dialysis hemodialysis Yakima Valley', 46.5896, -120.5488),
  -- Hospice and Palliative Care
  ('Providence Hospice of Seattle', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Hospice', 'Compassionate end-of-life care for patients and families.', '1801 S Woodruff Way', 'Spokane', 'Spokane', '99203', '(509) 474-4050', 'https://www.providence.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Hospice Care', 'Palliative Care', 'Bereavement Support'], ARRAY['hospice', 'end of life care', 'palliative', 'Spokane', 'Providence'], 'Providence Hospice of Seattle end of life care palliative hospice', 47.6470, -117.3939),
  ('PeaceHealth Hospice - Whatcom County', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Hospice', 'Hospice and palliative care services for Whatcom County.', '2925 Squalicum Pkwy', 'Bellingham', 'Whatcom', '98225', '(360) 788-3675', 'https://www.peacehealth.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Hospice Care', 'Palliative Care', 'Bereavement Support'], ARRAY['hospice', 'end of life care', 'palliative', 'Bellingham', 'PeaceHealth'], 'PeaceHealth Hospice Whatcom County end of life care palliative hospice', 48.7564, -122.4743),
  ('MultiCare Hospice - Tacoma', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Hospice', 'Hospice care providing comfort and support for patients and families.', '3024 14th St S', 'Tacoma', 'Pierce', '98405', '(253) 301-2067', 'https://www.multicare.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hospice Care', 'Palliative Care', 'Bereavement Support'], ARRAY['hospice', 'end of life care', 'palliative', 'Tacoma', 'MultiCare'], 'MultiCare Hospice Tacoma end of life care palliative hospice', 47.2566, -122.4643),
  ('Franciscan Hospice House - University Place', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Hospice', 'Inpatient and home hospice services.', '1315 54th Ave E', 'University Place', 'Pierce', '98466', '(253) 534-7444', 'https://www.chifranciscanhealth.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Hospice Care', 'Inpatient Hospice', 'Bereavement Support'], ARRAY['hospice', 'end of life care', 'inpatient hospice', 'University Place', 'Franciscan'], 'Franciscan Hospice House University Place end of life care inpatient hospice', 47.2040, -122.5278),
  ('Virginia Mason Hospice - Seattle', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Hospice', 'Comprehensive hospice services including home care and bereavement.', '904 7th Ave', 'Seattle', 'King', '98104', '(206) 386-6360', 'https://www.virginiamason.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Hospice Care', 'Palliative Care', 'Bereavement Support'], ARRAY['hospice', 'end of life care', 'palliative', 'Seattle', 'Virginia Mason'], 'Virginia Mason Hospice Seattle end of life care palliative hospice', 47.6076, -122.3202),
  ('EvergreenHealth Hospice - Kirkland', (SELECT id FROM resource_categories WHERE slug = 'specialty'), 'Hospice', 'Hospice care with inpatient unit and home-based services.', '12822 Totem Lake Blvd NE', 'Kirkland', 'King', '98034', '(425) 899-1555', 'https://www.evergreenhealth.com', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, false, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Hospice Care', 'Palliative Care', 'Bereavement Support'], ARRAY['hospice', 'end of life care', 'palliative', 'Kirkland', 'EvergreenHealth'], 'EvergreenHealth Hospice Kirkland end of life care palliative hospice', 47.6957, -122.1895),
  -- Additional Rural County Healthcare
  ('Othello Community Hospital', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Critical Access', 'Critical access hospital serving Adams County and surrounding area.', '715 S 7th Ave', 'Othello', 'Adams', '99344', '(509) 488-2500', 'https://www.othellohospital.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English', 'Spanish'], ARRAY['Emergency Care', 'Inpatient Care', 'Primary Care'], ARRAY['critical access', 'hospital', 'rural', 'Othello', 'Adams County'], 'Othello Community Hospital critical access rural Adams County emergency', 46.8242, -119.1763),
  ('Whitman Hospital and Medical Center', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Critical Access', 'Critical access hospital serving Whitman County.', '1200 W Main St', 'Colfax', 'Whitman', '99111', '(509) 397-3438', 'https://www.whitmanhospital.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, false, false, ARRAY['English'], ARRAY['Emergency Care', 'Inpatient Care', 'Primary Care', 'Swing Bed'], ARRAY['critical access', 'hospital', 'rural', 'Colfax', 'Whitman County'], 'Whitman Hospital Medical Center critical access rural Whitman County Colfax', 46.8792, -117.3662),
  ('Odessa Memorial Healthcare Center', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Critical Access', 'Critical access hospital serving Lincoln County.', '220 W 4th Ave', 'Odessa', 'Lincoln', '99159', '(509) 982-2641', 'https://www.odessamemorial.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Emergency Care', 'Physical Therapy'], ARRAY['critical access', 'hospital', 'rural', 'Odessa', 'Lincoln County'], 'Odessa Memorial Healthcare Center critical access rural Lincoln County Odessa', 47.0701, -118.5800),
  ('Coulee Medical Center', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Critical Access', 'Critical access hospital serving the Grand Coulee area.', '417 Main St', 'Grand Coulee', 'Grant', '99133', '(509) 633-1100', 'https://www.couleemedical.org', '{"monday": "8am-5pm", "tuesday": "8am-5pm", "wednesday": "8am-5pm", "thursday": "8am-5pm", "friday": "8am-5pm"}'::jsonb, true, true, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Primary Care', 'Emergency Care', 'Physical Therapy'], ARRAY['critical access', 'hospital', 'rural', 'Grand Coulee', 'Grant County'], 'Coulee Medical Center critical access rural Grand Coulee Grant County', 47.9743, -119.0712),
  ('Kittitas Valley Healthcare - Ellensburg', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Community Hospital', 'Community hospital serving Kittitas County with full medical services.', '603 S Main St', 'Ellensburg', 'Kittitas', '98926', '(509) 962-9800', 'https://www.kvhealth.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English', 'Spanish'], ARRAY['Emergency Care', 'Surgery', 'Primary Care', 'Cardiac Care'], ARRAY['community hospital', 'Ellensburg', 'Kittitas County', 'emergency surgery'], 'Kittitas Valley Healthcare Ellensburg hospital Kittitas County emergency', 46.9970, -120.5462),
  ('Jefferson Healthcare Hospital', (SELECT id FROM resource_categories WHERE slug = 'hospitals'), 'Community Hospital', 'Full service community hospital serving East Jefferson County.', '834 Sheridan St', 'Port Townsend', 'Jefferson', '98368', '(360) 385-2200', 'https://www.jeffersonhealth.org', '{"monday": "24/7", "tuesday": "24/7", "wednesday": "24/7", "thursday": "24/7", "friday": "24/7"}'::jsonb, true, false, true, true, true, false, true, true, false, ARRAY['English'], ARRAY['Emergency Care', 'Surgery', 'Primary Care', 'Cardiac Rehab'], ARRAY['community hospital', 'Port Townsend', 'Jefferson County', 'Olympic Peninsula'], 'Jefferson Healthcare Hospital Port Townsend Jefferson County Olympic Peninsula', 48.1216, -122.7556)
) AS data(name, category_id, subcategory, description, address, city, county, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, languages, services, tags, search_text, lat, lng);
