/*
# Add Northwest Justice Project Regional Offices

1. Data Insert
- Adds NJP regional offices in Spokane, Wenatchee, Bellingham, and Vancouver
  (Seattle and Yakima already exist).
2. Source
- Verified via NW Justice Project office-locations page (nwjustice.org).
3. Notes
- Free civil legal aid; cost_free=true.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Northwest Justice Project - Spokane', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'NJP Spokane regional office providing free civil legal assistance to low-income residents of Spokane, Whitman, Lincoln, Ferry, Pend Oreille and Stevens Counties in areas including housing, family safety, income security, health care, and education.', '157 S Howard St, Ste 405', 'Spokane', 'Spokane', 'WA', '99201', '509-324-9128', 'https://nwjustice.org/office-locations', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, true, true, 0, 0, '{English,Spanish,Russian,Marshallese}', '{wheelchair,"ADA parking","interpreter services"}', '{Civil Legal Aid,Housing,Family Law,Public Benefits,Health Care Access}', '{Civil Legal Aid}', '{Low-Income Individuals,Families,Seniors}', 4.0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Northwest Justice Project - Wenatchee', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'NJP Wenatchee regional office providing free civil legal assistance to low-income residents of Chelan, Douglas, Grant, and Okanogan Counties.', '300 Okanogan Ave, Ste 3A', 'Wenatchee', 'Chelan', 'WA', '98801', '509-664-5101', 'https://nwjustice.org/office-locations', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Civil Legal Aid,Housing,Family Law,Public Benefits,Health Care Access}', '{Civil Legal Aid}', '{Low-Income Individuals,Families}', 4.0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Northwest Justice Project - Bellingham', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'NJP Bellingham regional office providing free civil legal assistance to low-income residents of Whatcom, San Juan, Skagit, and Island Counties.', '1814 Cornwall Ave', 'Bellingham', 'Whatcom', 'WA', '98225', '360-734-8680', 'https://nwjustice.org/office-locations', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, true, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{Civil Legal Aid,Housing,Family Law,Public Benefits,Health Care Access}', '{Civil Legal Aid}', '{Low-Income Individuals,Families}', 4.0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Northwest Justice Project - Vancouver', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'NJP Vancouver regional office providing free civil legal assistance to low-income residents of Clark, Klickitat, and Skamania Counties.', '1104 Main St, Ste 500', 'Vancouver', 'Clark', 'WA', '98660', '360-693-6130', 'https://nwjustice.org/office-locations', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, true, true, 0, 0, '{English,Spanish,Russian}', '{wheelchair,"ADA parking","interpreter services"}', '{Civil Legal Aid,Housing,Family Law,Public Benefits,Health Care Access}', '{Civil Legal Aid}', '{Low-Income Individuals,Families}', 4.0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Northwest Justice Project - Aberdeen', (SELECT id FROM resource_categories WHERE slug='legal-aid'), '', 'NJP Aberdeen regional office providing free civil legal assistance to low-income residents of Grays Harbor, Pacific, Mason, and Wahkiakum Counties.', '218 N Broadway, Ste 1', 'Aberdeen', 'Grays Harbor', 'WA', '98520', '360-533-2282', 'https://nwjustice.org/office-locations', '{"mon":"9:00-17:00","tue":"9:00-17:00","wed":"9:00-17:00","thu":"9:00-17:00","fri":"9:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, false, false, false, false, false, true, true, true, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking","interpreter services"}', '{Civil Legal Aid,Housing,Family Law,Public Benefits,Health Care Access}', '{Civil Legal Aid}', '{Low-Income Individuals,Families}', 4.0, 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;