/*
# Add Washington Tribal Health Clinics

1. Data Insert
- Adds tribally operated and IHS health clinics across Washington State.
- Includes Suquamish Healing House, Tulalip, Swinomish, Jamestown S'Klallam,
  Makah, Quileute, Colville/Lake Roosevelt (Inchelium + Keller), Chehalis.
2. Source
- Verified via tribe/IHS websites and HelpMeGrowWA listings.
3. Notes
- Tribal clinics often serve tribal members and descendants; some serve the
  broader community (e.g., Jamestown Family Health Clinic is a Tribal FQHC open
  to non-tribal community members).
- medicaid=true, sliding_scale=true for these clinics.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('Suquamish Healing House Primary Care', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Suquamish Tribe primary care clinic offering medical, acupuncture, behavioral health and healthcare navigation services for tribal members and Medicaid patients.', '18490 Suquamish Way NE', 'Suquamish', 'Kitsap', 'WA', '98392', '360-598-4381', 'https://suquamish.nsn.us/health-division/healing-house', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Acupuncture,Behavioral Health,Healthcare Navigation}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans,Families}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Swinomish Medical Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Swinomish Indian Tribal Community health clinic providing full-spectrum medical, dental, behavioral health, pharmacy and social services for all ages.', '17400 Reservation Rd', 'La Conner', 'Skagit', 'WA', '98257', '360-466-3167', 'https://www.swinomish-nsn.gov/health-and-wellness/page/medical-clinic', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental,Behavioral Health,Pharmacy,Social Services}', '{Tribal Health,Family Medicine}', '{Native Americans,Tribal Members,Families}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Tulalip Health Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Tulalip Tribes health clinic offering medical, dental, behavioral health, substance use disorder treatment, pharmacy and child/youth/family mental wellness services serving Native Americans in Snohomish County.', '7520 Totem Beach Rd', 'Tulalip', 'Snohomish', 'WA', '98271', '360-716-4511', 'https://www.tulaliphealthsystem.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"8:00-16:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental,Behavioral Health,Substance Use,Pharmacy,Eye Care}', '{Tribal Health,Family Medicine,Pediatrics}', '{Native Americans,Tribal Members,Families,Youth}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Jamestown Family Health Clinic', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Jamestown S Klallam Tribe Tribal FQHC providing team-based primary medical care to both tribal citizens and non-tribal community members in Sequim. Includes medical, dental and substance use disorder services.', '808 N 5th Ave', 'Sequim', 'Clallam', 'WA', '98382', '360-683-5900', 'https://jamestownhealth.org', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"10:00-15:00","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental,Substance Use}', '{Tribal Health,Family Medicine}', '{General Public,Tribal Members,Families}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Sophie Trettevick Indian Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Makah Tribe Indian Health Service clinic providing medical, dental, pharmacy, lab, behavioral health, substance use treatment (MAT), naturopathy and acupuncture for the Makah Nation and Neah Bay community.', '250 Fort St', 'Neah Bay', 'Clallam', 'WA', '98357', '360-645-2233', 'https://www.stihc.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, true, false, 0, 0, '{English,Makah}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental,Pharmacy,Lab,Behavioral Health,Substance Use,MAT,Naturopathy,Acupuncture}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans,Community}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Quileute Health Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Quileute Tribe health clinic providing outpatient medical, dental, behavioral health, WIC and substance use services on the Quileute Indian Reservation.', '560 Quileute Heights Loop', 'La Push', 'Clallam', 'WA', '98350', '360-374-9035', 'https://quileutetribe.com', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English,Quileute}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental,Behavioral Health,WIC,Substance Use}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lake Roosevelt Community Health Center - Inchelium', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Colville Tribes IHS clinic in Inchelium providing medical and dental care on the Colville Indian Reservation.', '39 Shortcut Rd', 'Inchelium', 'Ferry', 'WA', '99138', '509-722-7006', 'https://www.lrchc.com', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"10:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Lake Roosevelt Community Health Center - Keller', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Colville Tribes IHS clinic in Keller providing medical and dental services on the Colville Indian Reservation.', '11665 S Hwy 21', 'Keller', 'Ferry', 'WA', '99148', '509-634-7300', 'https://www.lrchc.com', '{"mon":"8:00-16:00","tue":"8:00-16:00","wed":"8:00-16:00","thu":"8:00-16:00","fri":"8:00-16:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Dental}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans}', 4.0, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Chehalis Tribal Wellness Center', (SELECT id FROM resource_categories WHERE slug='fqhc'), 'Tribal Health', 'Chehalis Tribe full-service family practice clinic providing ambulatory care, dental, urgent care and pharmacy services for federally recognized tribal members.', '420 Howanut Rd', 'Oakville', 'Grays Harbor', 'WA', '98568', '360-273-5504', 'https://www.chehalistribe.org/departments/wellness-center', '{"mon":"8:00-17:00","tue":"8:00-17:00","wed":"8:00-17:00","thu":"8:00-17:00","fri":"8:00-17:00","sat":"Closed","sun":"Closed"}'::jsonb, true, true, true, true, true, true, true, false, false, 0, 0, '{English}', '{wheelchair,"ADA parking"}', '{Primary Care,Urgent Care,Dental,Pharmacy}', '{Tribal Health,Family Medicine}', '{Tribal Members,Native Americans}', 4.5, 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;