/*
# Add VA Community-Based Outpatient Clinics (CBOCs) in Washington

1. Data Insert
- Adds VA CBOCs across WA: Mount Vernon, Port Angeles, Bremerton (Puget Sound
  system), Wenatchee (Mann-Grandstaff system), Richland & Yakima Valley (Walla
  Walla system), and Walla Walla VA Medical Center main campus.
2. Source
- Verified via VA.gov locations pages and VA Puget Sound/Spokane/Walla Walla HCS.
3. Notes
- Veterans category. VA care = enrolled veterans primarily.
*/

INSERT INTO resources (name, category_id, subcategory, description, address, city, county, state, zip_code, phone, website, hours, accepts_uninsured, sliding_scale, medicaid, medicare, private_insurance, walk_ins_welcome, appointments, telehealth, cost_free, cost_estimate_min, cost_estimate_max, languages, accessibility, services, specialties, audiences, rating, photo_url, source) VALUES
('VA Puget Sound - Mount Vernon Community Clinic', (SELECT id FROM resource_categories WHERE slug='veterans'), 'CBOC', 'VA community-based outpatient clinic in Mount Vernon providing primary care, mental health, social work, lab and prescription services to enrolled Veterans in Skagit County.', '307 S 13th St, Ste 200', 'Mount Vernon', 'Skagit', 'WA', '98274', '360-848-7000', 'https://www.va.gov/puget-sound-health-care/locations', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Mental Health,Social Work,Lab,Pharmacy}', '{Veterans Health,Primary Care}', '{Veterans}', 4.5, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('VA Puget Sound - Port Angeles CBOC', (SELECT id FROM resource_categories WHERE slug='veterans'), 'CBOC', 'VA community-based outpatient clinic in Port Angeles providing primary care, mental health, telehealth specialty services and pharmacy services to enrolled Veterans on the Olympic Peninsula.', '435 S Lincoln St', 'Port Angeles', 'Clallam', 'WA', '98362', '360-417-7000', 'https://www.va.gov/puget-sound-health-care/locations', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Mental Health,Telehealth,Pharmacy}', '{Veterans Health,Primary Care}', '{Veterans}', 4.0, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('VA Puget Sound - Bremerton (Silverdale) CBOC', (SELECT id FROM resource_categories WHERE slug='veterans'), 'CBOC', 'VA community-based outpatient clinic in Silverdale serving Kitsap County Veterans with primary care, mental health, laboratory and pharmacy services.', '925 Silverdale Way', 'Silverdale', 'Kitsap', 'WA', '98383', '360-775-4000', 'https://www.va.gov/puget-sound-health-care/locations', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Mental Health,Lab,Pharmacy}', '{Veterans Health,Primary Care}', '{Veterans}', 4.5, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('VA Spokane - Wenatchee CBOC', (SELECT id FROM resource_categories WHERE slug='veterans'), 'CBOC', 'Mann-Grandstaff VA Medical Center community-based outpatient clinic in Wenatchee providing primary care and related services to enrolled Veterans in the Wenatchee Valley.', '609 Okanogan St, Ste 250', 'Wenatchee', 'Chelan', 'WA', '98801', '509-663-7615', 'https://www.va.gov/spokane-health-care/locations', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Mental Health,Telemental Health,Lab}', '{Veterans Health,Primary Care}', '{Veterans}', 4.5, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('VA Walla Walla - Richland VA Clinic', (SELECT id FROM resource_categories WHERE slug='veterans'), 'CBOC', 'VA community-based outpatient clinic in Richland providing primary care (family/internal medicine), toxic exposure screening, mental health, and pharmacy services to enrolled Veterans in the Tri-Cities.', '825 Jadwin Ave, Ste 250', 'Richland', 'Benton', 'WA', '99352', '509-539-5300', 'https://www.va.gov/walla-walla-health-care/locations/richland-va-clinic', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Toxic Exposure Screening,Mental Health,Pharmacy,Telehealth}', '{Veterans Health,Primary Care}', '{Veterans}', 4.5, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('VA Walla Walla - Yakima Valley VA Clinic', (SELECT id FROM resource_categories WHERE slug='veterans'), 'CBOC', 'VA community-based outpatient clinic in Union Gap serving Yakima Valley Veterans with primary care, mental health, telehealth specialty care, and pharmacy services.', '1211 Ahtanum Ridge Dr', 'Union Gap', 'Yakima', 'WA', '98903', '509-575-5500', 'https://www.va.gov/walla-walla-health-care/locations', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Mental Health,Telehealth,Pharmacy}', '{Veterans Health,Primary Care}', '{Veterans}', 4.5, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified'),
('Walla Walla VA Medical Center', (SELECT id FROM resource_categories WHERE slug='veterans'), 'Medical Center', 'Jonathan M. Wainwright Memorial VA Medical Center in Walla Walla providing comprehensive primary care, specialty care, mental health, rehabilitation, and pharmacy services to enrolled Veterans.', '77 Wainwright Dr', 'Walla Walla', 'Walla Walla', 'WA', '99362', '509-525-5200', 'https://www.va.gov/walla-walla-health-care', '{"mon":"8:00-16:30","tue":"8:00-16:30","wed":"8:00-16:30","thu":"8:00-16:30","fri":"8:00-16:30","sat":"Closed","sun":"Closed"}'::jsonb, false, false, true, true, false, false, true, true, false, 0, 0, '{English,Spanish}', '{wheelchair,"ADA parking"}', '{Primary Care,Specialty Care,Mental Health,Rehabilitation,Pharmacy,Radiology}', '{Veterans Health}', '{Veterans}', 4.5, 'https://images.pexels.com/photos/6678075/pexels-photo-6678075.jpeg?auto=compress&cs=tinysrgb=w=800', 'verified')
ON CONFLICT DO NOTHING;